import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("1.5.32 keeps first-weekend-FX-open copy control without taking Shift+F10", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="copy-first-weekend-fx-open"/);
  assert.match(html, /Copy first weekend-FX-open hour/);
  assert.match(html, /id="first-weekend-fx-open-copy-fallback"/);
  assert.match(html, /id="copy-last-weekend-fx-closed"[^>]*aria-keyshortcuts="F7"/);
  assert.match(html, /id="copy-last-weekday-fx-closed"[^>]*aria-keyshortcuts="F10"/);
  assert.doesNotMatch(html, /id="copy-first-weekend-fx-open"[^>]*aria-keyshortcuts="Shift\+F10"/);
  assert.match(app, /function copyFirstWeekendFxOpenHourMarkdown/);
  assert.match(app, /firstWeekendFxOpenHourToMarkdown\(scenario\)/);
  assert.match(app, /function copyLastWeekendFxClosedHourMarkdown/);
  assert.match(app, /event\.key === "F10" && event\.shiftKey/);
  assert.match(app, /copyLastWeekendFxClosedHourMarkdown\(\)/);
  assert.match(app, /event\.key === "F10"/);
  assert.match(app, /copyLastWeekdayFxClosedHourMarkdown\(\)/);
  assert.match(app, /if \(event\.defaultPrevented\) return/);
  assert.match(app, /event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key/);
  assert.notEqual(app.match(/function copyFirstWeekendFxOpenHourMarkdown/)?.[0], app.match(/function copyLastWeekendFxClosedHourMarkdown/)?.[0]);
  assert.notEqual(app.match(/function copyFirstWeekendFxOpenHourMarkdown/)?.[0], app.match(/function copyLastWeekdayFxClosedHourMarkdown/)?.[0]);
  const handler = app.slice(app.indexOf('document.addEventListener("keydown"'));
  const shiftF10 = handler.indexOf('event.key === "F10" && event.shiftKey');
  const unshiftedF10 = handler.lastIndexOf('event.key === "F10"');
  assert.ok(shiftF10 !== -1);
  assert.ok(unshiftedF10 !== -1);
  assert.ok(shiftF10 < unshiftedF10);
  const shiftSlice = handler.slice(shiftF10, shiftF10 + 180);
  assert.match(shiftSlice, /copyLastWeekendFxOpenHourMarkdown\(\)/);
  assert.doesNotMatch(shiftSlice, /copyFirstWeekendFxOpenHourMarkdown/);
  assert.doesNotMatch(shiftSlice, /copyFirstWeekendFxClosedHourMarkdown/);
  assert.doesNotMatch(shiftSlice, /copyLastWeekdayFxClosedHourMarkdown/);
  const unshiftedSlice = handler.slice(unshiftedF10, unshiftedF10 + 180);
  assert.match(unshiftedSlice, /copyLastWeekdayFxClosedHourMarkdown\(\)/);
});
