import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("keyboard F9 is wired to the hide-weekday-FX-closed Gantt filter", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="gantt-hide-weekday-fx-closed"/);
  assert.match(html, /id="gantt-title"/);
  assert.match(html, /<kbd>F9<\/kbd>/);
  assert.match(html, /Jump to the hide-weekday-FX-closed Gantt filter/);
  assert.match(html, /id="gantt-hide-weekday-fx-closed"[^>]*aria-keyshortcuts="F9 Shift\+F12"/);
  assert.match(app, /function jumpToHideWeekdayFxClosedFilter/);
  assert.match(app, /#gantt-hide-weekday-fx-closed/);
  assert.match(app, /event\.key === "F9"/);
  assert.match(app, /event\.key === "Backspace"/);
  assert.match(app, /event\.key === "ArrowRight"/);
  assert.match(app, /function jumpToHideWeekendFxClosedFilter/);
  assert.match(app, /function jumpToHideFxClosedFilter/);
  assert.match(app, /function jumpToGantt/);
  assert.notEqual(app.match(/function jumpToHideWeekdayFxClosedFilter/)?.[0], app.match(/function jumpToHideWeekendFxClosedFilter/)?.[0]);
  assert.notEqual(app.match(/function jumpToHideWeekdayFxClosedFilter/)?.[0], app.match(/function jumpToHideFxClosedFilter/)?.[0]);
  assert.notEqual(app.match(/function jumpToHideWeekdayFxClosedFilter/)?.[0], app.match(/function jumpToHideWeekendFxOpenFilter/)?.[0]);
  assert.notEqual(app.match(/function jumpToHideWeekdayFxClosedFilter/)?.[0], app.match(/function jumpToGantt/)?.[0]);
  const f9Fn = app.slice(app.indexOf("function jumpToHideWeekdayFxClosedFilter"), app.indexOf("document.querySelector(\"#jump-monday\")"));
  assert.match(f9Fn, /jumpToGantt\(\)/);
  assert.doesNotMatch(f9Fn, /copyLastWeekendFxClosedHourMarkdown/);
  assert.doesNotMatch(f9Fn, /copyLastClosedPayoutHourMarkdown/);
  const handler = app.slice(app.indexOf('document.addEventListener("keydown"'));
  assert.ok(handler.indexOf('event.key === "F9"') !== handler.indexOf('event.key === "Backspace"'));
  assert.ok(handler.indexOf('event.key === "F9"') !== handler.indexOf('event.key === "ArrowRight"'));
  const f9Slice = handler.slice(handler.indexOf('event.key === "F9"'), handler.indexOf('event.key === "F9"') + 180);
  assert.doesNotMatch(f9Slice, /copyLastWeekendFxClosedHourMarkdown/);
  assert.doesNotMatch(f9Slice, /copyLastClosedPayoutHourMarkdown/);
});
