import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("keyboard Shift+F12 is wired to the hide-weekday-FX-open Gantt filter before unshifted F12", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="gantt-hide-weekday-fx-open"/);
  assert.match(html, /id="gantt-hide-weekday-fx-closed"/);
  assert.match(html, /id="gantt-title"/);
  assert.match(html, /<kbd>Shift\+F12<\/kbd>/);
  assert.match(html, /Jump to the hide-weekday-FX-open Gantt filter/);
  assert.match(html, /id="gantt-hide-weekday-fx-open"[^>]*aria-keyshortcuts="Shift\+F12"/);
  assert.doesNotMatch(html, /id="gantt-hide-weekday-fx-closed"[^>]*aria-keyshortcuts="Shift\+F12"/);
  assert.match(html, /id="gantt-hide-weekday-fx-closed"[^>]*aria-keyshortcuts="F9"/);
  assert.match(html, /id="gantt-hide-weekend-fx-open"[^>]*aria-keyshortcuts="ArrowLeft F12"/);
  assert.match(html, /id="gantt-hide-weekend-fx-closed"[^>]*aria-keyshortcuts="Backspace"/);
  assert.match(app, /function jumpToHideWeekdayFxOpenFilter/);
  assert.match(app, /#gantt-hide-weekday-fx-open/);
  assert.match(app, /event\.key === "F12" && event\.shiftKey/);
  assert.match(app, /event\.key === "F12"/);
  assert.match(app, /event\.key === "F9"/);
  assert.match(app, /function jumpToHideWeekdayFxClosedFilter/);
  assert.match(app, /function jumpToHideWeekendFxOpenFilter/);
  assert.match(app, /function jumpToGantt/);
  assert.match(app, /if \(event\.defaultPrevented\) return/);
  assert.notEqual(app.match(/function jumpToHideWeekdayFxOpenFilter/)?.[0], app.match(/function jumpToHideWeekdayFxClosedFilter/)?.[0]);
  assert.notEqual(app.match(/function jumpToHideWeekdayFxOpenFilter/)?.[0], app.match(/function jumpToHideWeekendFxOpenFilter/)?.[0]);
  assert.notEqual(app.match(/function jumpToHideWeekdayFxOpenFilter/)?.[0], app.match(/function jumpToGantt/)?.[0]);
  const handler = app.slice(app.indexOf('document.addEventListener("keydown"'));
  const shiftF12 = handler.indexOf('event.key === "F12" && event.shiftKey');
  const unshiftedF12 = handler.lastIndexOf('event.key === "F12"');
  assert.ok(shiftF12 !== -1);
  assert.ok(unshiftedF12 !== -1);
  assert.ok(shiftF12 < unshiftedF12);
  const shiftSlice = handler.slice(shiftF12, shiftF12 + 180);
  assert.match(shiftSlice, /jumpToHideWeekdayFxOpenFilter\(\)/);
  assert.doesNotMatch(shiftSlice, /jumpToHideWeekdayFxClosedFilter/);
  assert.doesNotMatch(shiftSlice, /jumpToHideWeekendFxOpenFilter/);
  const unshiftedSlice = handler.slice(unshiftedF12, unshiftedF12 + 180);
  assert.match(unshiftedSlice, /jumpToHideWeekendFxOpenFilter\(\)/);
  assert.doesNotMatch(unshiftedSlice, /jumpToHideWeekdayFxOpenFilter/);
  const f9Slice = handler.slice(handler.indexOf('event.key === "F9"'), handler.indexOf('event.key === "F9"') + 180);
  assert.match(f9Slice, /jumpToHideWeekdayFxClosedFilter\(\)/);
});
