import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("keyboard F8 is wired to the last-weekend-FX-closed-hour copy control", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="copy-last-weekend-fx-closed"/);
  assert.match(html, /id="gantt-title"/);
  assert.match(html, /<kbd>F8<\/kbd>/);
  assert.match(html, /Jump to the last-weekend-FX-closed-hour copy control/);
  assert.match(app, /function jumpToLastWeekendFxClosedCopy/);
  assert.match(app, /#copy-last-weekend-fx-closed/);
  assert.ok(app.includes('event.key === "F8"'));
  assert.ok(app.includes('event.key === "F4"'));
  assert.ok(app.includes('event.key === "F2"'));
  assert.match(app, /function jumpToLastClosedPayoutCopy/);
  assert.match(app, /function jumpToLastClosedFxCopy/);
  assert.match(app, /function jumpToGantt/);
  assert.notEqual(app.match(/function jumpToLastWeekendFxClosedCopy/)?.[0], app.match(/function jumpToLastClosedPayoutCopy/)?.[0]);
  assert.notEqual(app.match(/function jumpToLastWeekendFxClosedCopy/)?.[0], app.match(/function jumpToLastClosedFxCopy/)?.[0]);
  assert.notEqual(app.match(/function jumpToLastWeekendFxClosedCopy/)?.[0], app.match(/function jumpToHideWeekendFxClosedFilter/)?.[0]);
  assert.notEqual(app.match(/function jumpToLastWeekendFxClosedCopy/)?.[0], app.match(/function jumpToGantt/)?.[0]);
  const f8Fn = app.slice(app.indexOf("function jumpToLastWeekendFxClosedCopy"), app.indexOf("function jumpToHideWeekdayFxClosedFilter"));
  assert.match(f8Fn, /jumpToGantt\(\)/);
  assert.doesNotMatch(f8Fn, /copyLastWeekendFxClosedHourMarkdown/);
  assert.doesNotMatch(f8Fn, /copyLastClosedPayoutHourMarkdown/);
  assert.doesNotMatch(f8Fn, /copyLastClosedFxHourMarkdown/);
  const handler = app.slice(app.indexOf('document.addEventListener("keydown"'));
  assert.ok(handler.indexOf('event.key === "F8"') !== handler.indexOf('event.key === "F4"'));
  assert.ok(handler.indexOf('event.key === "F8"') !== handler.indexOf('event.key === "F2"'));
  assert.match(handler, /jumpToLastWeekendFxClosedCopy\(\)/);
  assert.doesNotMatch(handler.slice(handler.indexOf('event.key === "F8"'), handler.indexOf('event.key === "F8"') + 180), /copyLastWeekendFxClosedHourMarkdown/);
  assert.doesNotMatch(handler.slice(handler.indexOf('event.key === "F8"'), handler.indexOf('event.key === "F8"') + 180), /copyLastClosedPayoutHourMarkdown/);
});
