import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("1.5.29 keeps last-weekday-FX-open jump without taking unshifted F11", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="copy-last-weekday-fx-open"/);
  assert.match(html, /id="copy-first-weekend-fx-open"/);
  assert.match(html, /id="gantt-title"/);
  assert.match(html, /<kbd>Shift\+F11<\/kbd>/);
  assert.match(html, /Jump to the first-weekend-FX-open-hour copy control/);
  assert.match(app, /function jumpToLastWeekdayFxOpenCopy/);
  assert.match(app, /function jumpToFirstWeekendFxOpenCopy/);
  assert.match(app, /#copy-last-weekday-fx-open/);
  assert.match(app, /#copy-first-weekend-fx-open/);
  assert.match(app, /event\.key === "F11" && event\.shiftKey/);
  assert.ok(app.includes('event.key === "F11"'));
  assert.match(app, /function jumpToLastWeekdayFxClosedCopy/);
  assert.match(app, /function jumpToGantt/);
  assert.match(app, /if \(event\.defaultPrevented\) return/);
  assert.notEqual(app.match(/function jumpToLastWeekdayFxOpenCopy/)?.[0], app.match(/function jumpToFirstWeekendFxOpenCopy/)?.[0]);
  assert.notEqual(app.match(/function jumpToLastWeekdayFxOpenCopy/)?.[0], app.match(/function jumpToLastWeekdayFxClosedCopy/)?.[0]);
  const lastFn = app.slice(app.indexOf("function jumpToLastWeekdayFxOpenCopy"), app.indexOf("function jumpToFirstWeekdayFxOpenCopy"));
  assert.match(lastFn, /jumpToGantt\(\)/);
  assert.doesNotMatch(lastFn, /copyLastWeekdayFxOpenHourMarkdown/);
  const handler = app.slice(app.indexOf('document.addEventListener("keydown"'));
  const shiftF11 = handler.indexOf('event.key === "F11" && event.shiftKey');
  const unshiftedF11 = handler.lastIndexOf('event.key === "F11"');
  assert.ok(shiftF11 !== -1);
  assert.ok(unshiftedF11 !== -1);
  assert.ok(shiftF11 < unshiftedF11);
  const shiftSlice = handler.slice(shiftF11, shiftF11 + 180);
  assert.match(shiftSlice, /jumpToFirstWeekendFxOpenCopy\(\)/);
  assert.doesNotMatch(shiftSlice, /jumpToLastWeekdayFxOpenCopy/);
  assert.doesNotMatch(shiftSlice, /jumpToLastWeekdayFxClosedCopy/);
  const unshiftedSlice = handler.slice(unshiftedF11, unshiftedF11 + 180);
  assert.match(unshiftedSlice, /jumpToLastWeekdayFxClosedCopy\(\)/);
});
