import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("1.5.29 keeps last-weekend-FX-open copy control without taking unshifted F10", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="copy-last-weekend-fx-open"/);
  assert.match(html, /Copy last weekend-FX-open hour/);
  assert.match(html, /id="last-weekend-fx-open-copy-fallback"/);
  assert.match(html, /id="copy-first-weekday-fx-closed"[^>]*aria-keyshortcuts="Shift\+F10"/);
  assert.match(html, /id="copy-last-weekday-fx-closed"[^>]*aria-keyshortcuts="F10"/);
  assert.match(app, /function copyLastWeekendFxOpenHourMarkdown/);
  assert.match(app, /lastWeekendFxOpenHourToMarkdown\(scenario\)/);
  assert.match(app, /function copyFirstWeekdayFxClosedHourMarkdown/);
  assert.match(app, /event\.key === "F10" && event\.shiftKey/);
  assert.match(app, /copyFirstWeekdayFxClosedHourMarkdown\(\)/);
  assert.match(app, /event\.key === "F10"/);
  assert.match(app, /copyLastWeekdayFxClosedHourMarkdown\(\)/);
  assert.match(app, /if \(event\.defaultPrevented\) return/);
  assert.notEqual(app.match(/function copyLastWeekendFxOpenHourMarkdown/)?.[0], app.match(/function copyFirstWeekdayFxClosedHourMarkdown/)?.[0]);
  assert.notEqual(app.match(/function copyLastWeekendFxOpenHourMarkdown/)?.[0], app.match(/function copyLastWeekdayFxClosedHourMarkdown/)?.[0]);
  const handler = app.slice(app.indexOf('document.addEventListener("keydown"'));
  const shiftF10 = handler.indexOf('event.key === "F10" && event.shiftKey');
  const unshiftedF10 = handler.lastIndexOf('event.key === "F10"');
  assert.ok(shiftF10 !== -1);
  assert.ok(unshiftedF10 !== -1);
  assert.ok(shiftF10 < unshiftedF10);
  const shiftSlice = handler.slice(shiftF10, shiftF10 + 180);
  assert.match(shiftSlice, /copyFirstWeekdayFxClosedHourMarkdown\(\)/);
  assert.doesNotMatch(shiftSlice, /copyLastWeekendFxOpenHourMarkdown/);
  assert.doesNotMatch(shiftSlice, /copyLastWeekdayFxClosedHourMarkdown/);
});
