import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import {
  DEFAULT_SCENARIO,
  PRESETS,
  dayAndHourAt,
  formatTime,
  getOperationalStatus,
  runSimulation,
  sanitizeScenario
} from "../src/model.js";

function firstSundayBreakfastFxOpenHour(scenario) {
  for (let hour = 0; hour < 72; hour += 1) {
    const { dayIndex, localHour } = dayAndHourAt(hour);
    if (dayIndex === 0 && localHour >= 7 && localHour < 9 && getOperationalStatus(scenario, hour).fxWeekday) {
      const ordinary = getOperationalStatus({
        ...scenario,
        sundayBreakfastFxOpen: false
      }, hour).fxWeekday;
      if (!ordinary) return hour;
    }
  }
  return null;
}

test("Sunday breakfast FX open keeps the Normal Friday calendar with a Sunday breakfast FX window", () => {
  const preset = PRESETS.sundayBreakfastFxOpen;
  assert.match(preset.name, /synthetic/i);
  assert.match(preset.name, /Sunday breakfast FX open/i);
  assert.equal(preset.sundayBreakfastFxOpen, true);
  assert.equal(DEFAULT_SCENARIO.sundayBreakfastFxOpen, false);
  assert.equal(preset.sundayDawnFxOpen, false);
  assert.equal(preset.sundaySunriseFxOpen, false);
  assert.equal(preset.sundayDaybreakFxOpen, false);
  assert.equal(preset.sundayPredawnFxOpen, false);
  assert.equal(preset.saturdayLateNightFxOpen, false);
  assert.equal(preset.saturdayNightFxOpen, false);
  assert.equal(preset.sundayLateNightFxOpen, false);
  assert.equal(preset.sundayNightFxOpen, false);
  assert.equal(preset.sundayEveningFxOpen, false);
  assert.equal(preset.saturdayEveningFxOpen, false);
  assert.equal(preset.sundayMorningFxOpen, false);
  assert.equal(preset.sundayAfternoonFxOpen, false);
  assert.equal(preset.sundayMiddayFxOpen, false);
  assert.equal(preset.saturdayAfternoonFxOpen, false);
  assert.equal(preset.saturdayMiddayFxOpen, false);
  assert.equal(preset.saturdayEarlyFxOpen, false);
  assert.equal(preset.saturdayLateFxOpen, false);
  assert.equal(preset.sundayEarlyFxOpen, false);
  assert.equal(preset.sundayLateFxOpen, false);
  assert.equal(preset.fridayEarlyFxOpen, false);
  assert.equal(preset.fridayLateFxOpen, false);
  assert.equal(preset.saturdayLatePayoutOpen, false);
  assert.equal(preset.demandProfile, DEFAULT_SCENARIO.demandProfile);
  assert.notDeepEqual(preset, PRESETS.normal);
  assert.notDeepEqual(preset, PRESETS.sundayDawnFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundaySunriseFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayDaybreakFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayPredawnFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayLateNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayLateNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayEveningFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayEveningFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayMorningFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayAfternoonFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayAfternoonFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayLateFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayMiddayFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayEarlyFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayLateFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayEarlyFxOpen);
  const breakfast = runSimulation(preset);
  const normal = runSimulation(DEFAULT_SCENARIO);
  const sunrise = runSimulation(PRESETS.sundaySunriseFxOpen);
  const daybreak = runSimulation(PRESETS.sundayDaybreakFxOpen);
  const dawn = runSimulation(PRESETS.sundayDawnFxOpen);
  const predawn = runSimulation(PRESETS.sundayPredawnFxOpen);
  const saturdayLateNight = runSimulation(PRESETS.saturdayLateNightFxOpen);
  const saturdayNight = runSimulation(PRESETS.saturdayNightFxOpen);
  const sundayLateNight = runSimulation(PRESETS.sundayLateNightFxOpen);
  const sundayNight = runSimulation(PRESETS.sundayNightFxOpen);
  const sundayEvening = runSimulation(PRESETS.sundayEveningFxOpen);
  const saturdayEvening = runSimulation(PRESETS.saturdayEveningFxOpen);
  const sundayMorning = runSimulation(PRESETS.sundayMorningFxOpen);
  const sundayAfternoon = runSimulation(PRESETS.sundayAfternoonFxOpen);
  const saturdayAfternoon = runSimulation(PRESETS.saturdayAfternoonFxOpen);
  const saturdayLate = runSimulation(PRESETS.saturdayLateFxOpen);
  const saturdayMidday = runSimulation(PRESETS.saturdayMiddayFxOpen);
  const saturdayEarly = runSimulation(PRESETS.saturdayEarlyFxOpen);
  const sundayMidday = runSimulation(PRESETS.sundayMiddayFxOpen);
  const sundayLate = runSimulation(PRESETS.sundayLateFxOpen);
  const sundayEarly = runSimulation(PRESETS.sundayEarlyFxOpen);
  assert.equal(formatTime(33), "Sun 00:00");
  assert.equal(formatTime(34), "Sun 01:00");
  assert.equal(formatTime(35), "Sun 02:00");
  assert.equal(formatTime(36), "Sun 03:00");
  assert.equal(formatTime(37), "Sun 04:00");
  assert.equal(formatTime(38), "Sun 05:00");
  assert.equal(formatTime(39), "Sun 06:00");
  assert.equal(formatTime(40), "Sun 07:00");
  assert.equal(formatTime(41), "Sun 08:00");
  assert.equal(formatTime(42), "Sun 09:00");
  assert.equal(formatTime(31), "Sat 22:00");
  assert.equal(formatTime(32), "Sat 23:00");
  assert.equal(breakfast.timeline[40].timeLabel, "Sun 07:00");
  assert.equal(breakfast.timeline[40].weekend, true);
  assert.equal(breakfast.timeline[40].fxWeekday, true);
  assert.equal(normal.timeline[40].fxWeekday, false);
  assert.equal(dawn.timeline[40].fxWeekday, false);
  assert.equal(predawn.timeline[40].fxWeekday, false);
  assert.equal(saturdayLateNight.timeline[40].fxWeekday, false);
  assert.equal(saturdayNight.timeline[40].fxWeekday, false);
  assert.equal(sundayLateNight.timeline[40].fxWeekday, false);
  assert.equal(breakfast.timeline[41].timeLabel, "Sun 08:00");
  assert.equal(breakfast.timeline[41].weekend, true);
  assert.equal(breakfast.timeline[41].fxWeekday, true);
  assert.equal(normal.timeline[41].fxWeekday, false);
  assert.equal(dawn.timeline[41].fxWeekday, false);
  assert.equal(predawn.timeline[41].fxWeekday, false);
  assert.equal(saturdayLateNight.timeline[41].fxWeekday, false);
  assert.equal(breakfast.timeline[39].timeLabel, "Sun 06:00");
  assert.equal(breakfast.timeline[39].fxWeekday, false);
  assert.equal(sunrise.timeline[39].fxWeekday, true);
  assert.equal(breakfast.timeline[39].fxWeekday, false);
  assert.equal(daybreak.timeline[37].fxWeekday, true);
  assert.equal(breakfast.timeline[37].fxWeekday, false);
  assert.equal(dawn.timeline[35].fxWeekday, true);
  assert.equal(breakfast.timeline[35].fxWeekday, false);
  assert.equal(dawn.timeline[36].fxWeekday, true);
  assert.equal(predawn.timeline[33].fxWeekday, true);
  assert.equal(breakfast.timeline[33].fxWeekday, false);
  assert.equal(predawn.timeline[34].fxWeekday, true);
  assert.equal(saturdayLateNight.timeline[31].fxWeekday, true);
  assert.equal(breakfast.timeline[31].fxWeekday, false);
  assert.equal(saturdayLateNight.timeline[32].fxWeekday, true);
  assert.equal(breakfast.timeline[32].fxWeekday, false);
  assert.equal(saturdayNight.timeline[29].fxWeekday, true);
  assert.equal(breakfast.timeline[29].fxWeekday, false);
  assert.equal(saturdayEvening.timeline[27].fxWeekday, true);
  assert.equal(breakfast.timeline[27].fxWeekday, false);
  assert.equal(sundayLateNight.timeline[55].fxWeekday, true);
  assert.equal(breakfast.timeline[55].fxWeekday, false);
  assert.equal(sundayLateNight.timeline[56].fxWeekday, true);
  assert.equal(breakfast.timeline[56].fxWeekday, false);
  assert.equal(sundayNight.timeline[53].fxWeekday, true);
  assert.equal(breakfast.timeline[53].fxWeekday, false);
  assert.equal(sundayEvening.timeline[51].fxWeekday, true);
  assert.equal(breakfast.timeline[51].fxWeekday, false);
  assert.equal(sundayLate.timeline[49].fxWeekday, true);
  assert.equal(breakfast.timeline[49].fxWeekday, false);
  assert.equal(sundayAfternoon.timeline[47].fxWeekday, true);
  assert.equal(breakfast.timeline[47].fxWeekday, false);
  assert.equal(sundayMidday.timeline[45].fxWeekday, true);
  assert.equal(breakfast.timeline[45].fxWeekday, false);
  assert.equal(sundayMorning.timeline[43].fxWeekday, true);
  assert.equal(breakfast.timeline[43].fxWeekday, false);
  assert.equal(sundayEarly.timeline[41].fxWeekday, true);
  assert.equal(breakfast.timeline[41].fxWeekday, true);
  assert.equal(sundayEarly.timeline[42].fxWeekday, true);
  assert.equal(breakfast.timeline[42].fxWeekday, false);
  assert.equal(sunrise.timeline[41].fxWeekday, false);
  assert.equal(saturdayLate.timeline[25].fxWeekday, true);
  assert.equal(breakfast.timeline[25].fxWeekday, false);
  assert.equal(saturdayAfternoon.timeline[23].fxWeekday, true);
  assert.equal(breakfast.timeline[23].fxWeekday, false);
  assert.equal(saturdayMidday.timeline[21].fxWeekday, true);
  assert.equal(breakfast.timeline[21].fxWeekday, false);
  assert.equal(saturdayEarly.timeline[15].fxWeekday, true);
  assert.equal(breakfast.timeline[15].fxWeekday, false);
  assert.equal(breakfast.timeline[40].issuerOpen, false);
  assert.equal(breakfast.timeline[40].bankOpen, false);
  assert.equal(breakfast.timeline[40].payoutOpen, false);
  assert.equal(getOperationalStatus(preset, 40).fxWeekday, true);
  assert.equal(getOperationalStatus(DEFAULT_SCENARIO, 40).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundaySunriseFxOpen, 39).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 39).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayDawnFxOpen, 35).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 35).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayPredawnFxOpen, 33).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 33).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.saturdayLateNightFxOpen, 31).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 31).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.saturdayNightFxOpen, 29).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 29).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayLateNightFxOpen, 55).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 55).fxWeekday, false);
  const breakfastOpen = firstSundayBreakfastFxOpenHour(preset);
  assert.equal(breakfastOpen, 40);
  assert.equal(firstSundayBreakfastFxOpenHour(DEFAULT_SCENARIO), null);
  assert.equal(firstSundayBreakfastFxOpenHour(PRESETS.sundaySunriseFxOpen), null);
  assert.equal(firstSundayBreakfastFxOpenHour(PRESETS.sundayDaybreakFxOpen), null);
  assert.equal(firstSundayBreakfastFxOpenHour(PRESETS.sundayDawnFxOpen), null);
  assert.equal(firstSundayBreakfastFxOpenHour(PRESETS.sundayPredawnFxOpen), null);
  assert.equal(firstSundayBreakfastFxOpenHour(PRESETS.saturdayLateNightFxOpen), null);
  assert.equal(firstSundayBreakfastFxOpenHour(PRESETS.saturdayNightFxOpen), null);
  assert.equal(firstSundayBreakfastFxOpenHour(PRESETS.sundayLateNightFxOpen), null);
  assert.equal(firstSundayBreakfastFxOpenHour(PRESETS.sundayEveningFxOpen), null);
  assert.equal(firstSundayBreakfastFxOpenHour(PRESETS.saturdayEveningFxOpen), null);
  assert.equal(firstSundayBreakfastFxOpenHour(PRESETS.sundayNightFxOpen), null);
  assert.ok(breakfastOpen > 39);
  assert.ok(breakfastOpen < 42);
  const sundayBreakfast = dayAndHourAt(40);
  const sundayCloseHour = dayAndHourAt(42);
  const sundaySunriseHour = dayAndHourAt(39);
  const sundayDawnHour = dayAndHourAt(35);
  const sundayPredawnHour = dayAndHourAt(33);
  const saturdayLateNightHour = dayAndHourAt(31);
  const saturdayNightHour = dayAndHourAt(29);
  const sundayLateNightHour = dayAndHourAt(55);
  const sundayEarlyHour = dayAndHourAt(41);
  assert.equal(sundayBreakfast.dayIndex, 0);
  assert.equal(sundayBreakfast.localHour, 7);
  assert.equal(sundayCloseHour.dayIndex, 0);
  assert.equal(sundayCloseHour.localHour, 9);
  assert.equal(sundayDawnHour.dayIndex, 0);
  assert.equal(sundayDawnHour.localHour, 2);
  assert.equal(sundayPredawnHour.dayIndex, 0);
  assert.equal(sundayPredawnHour.localHour, 0);
  assert.equal(saturdayLateNightHour.dayIndex, 6);
  assert.equal(saturdayLateNightHour.localHour, 22);
  assert.equal(saturdayNightHour.dayIndex, 6);
  assert.equal(saturdayNightHour.localHour, 20);
  assert.equal(sundayLateNightHour.dayIndex, 0);
  assert.equal(sundayLateNightHour.localHour, 22);
  assert.equal(sundayEarlyHour.dayIndex, 0);
  assert.equal(sundayEarlyHour.localHour, 8);
  assert.equal(sundaySunriseHour.localHour, 6);
  assert.notEqual(sundayBreakfast.localHour, sundaySunriseHour.localHour);
  assert.notEqual(sundayBreakfast.localHour, sundayDawnHour.localHour);
  assert.notEqual(sundayBreakfast.localHour, sundayPredawnHour.localHour);
  assert.notEqual(sundayBreakfast.localHour, saturdayLateNightHour.localHour);
  assert.notEqual(sundayBreakfast.localHour, saturdayNightHour.localHour);
  assert.notEqual(sundayBreakfast.localHour, sundayLateNightHour.localHour);
  assert.notEqual(sundayBreakfast.localHour, sundayEarlyHour.localHour);
  assert.notEqual(sundayBreakfast.dayIndex, saturdayLateNightHour.dayIndex);
});

test("Sunday breakfast FX open ORs into fxWeekday through isSundayBreakfastFxOpenHour after sundaySunriseFxOpen", async () => {
  const model = await readFile(new URL("../src/model.js", import.meta.url), "utf8");
  const helperStart = model.indexOf("function isSundayBreakfastFxOpenHour");
  const helperNext = model.indexOf("\nexport function getOperationalStatus", helperStart);
  const commentStart = model.lastIndexOf("/** Sunday 07:00-09:00", helperStart);
  const helper = model.slice(commentStart === -1 ? helperStart : commentStart, helperNext === -1 ? undefined : helperNext);
  assert.match(helper, /scenario\.sundayBreakfastFxOpen !== true/);
  assert.match(helper, /localHour >= 7 && localHour < 9/);
  assert.match(helper, /dayIndex === 0/);
  assert.match(helper, /sundaySunriseFxOpen/);
  assert.match(helper, /sundayDaybreakFxOpen/);
  assert.match(helper, /sundayDawnFxOpen/);
  assert.match(helper, /sundayPredawnFxOpen/);
  assert.match(helper, /saturdayLateNightFxOpen/);
  assert.match(helper, /saturdayNightFxOpen/);
  assert.match(helper, /sundayLateNightFxOpen/);
  assert.match(helper, /sundayNightFxOpen/);
  assert.match(helper, /saturdayEveningFxOpen/);
  assert.match(helper, /sundayEveningFxOpen/);
  assert.match(helper, /sundayLateFxOpen/);
  assert.match(helper, /sundayAfternoonFxOpen/);
  assert.match(helper, /sundayMiddayFxOpen/);
  assert.match(helper, /sundayMorningFxOpen/);
  assert.match(helper, /sundayEarlyFxOpen/);
  assert.match(helper, /saturdayLateFxOpen/);
  assert.match(helper, /saturdayAfternoonFxOpen/);
  assert.match(helper, /saturdayMiddayFxOpen/);
  assert.match(helper, /saturdayEarlyFxOpen/);
  assert.match(helper, /saturdayLatePayoutOpen/);
  assert.doesNotMatch(helper, /isSundaySunriseFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayDawnFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayPredawnFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayLateNightFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayNightFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayLateNightFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayEveningFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayNightFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayEveningFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayLateFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayAfternoonFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayMiddayFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayMorningFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayEarlyFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayLateFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayAfternoonFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayMiddayFxOpenHour/);
  assert.match(model, /isSundayBreakfastFxOpenHour\(hourOffset, scenario\)/);
  const sundaySunriseStart = model.indexOf("function isSundaySunriseFxOpenHour");
  const sundayBreakfastStart = model.indexOf("function isSundayBreakfastFxOpenHour");
  const statusStart = model.indexOf("export function getOperationalStatus");
  assert.ok(sundaySunriseStart !== -1 && sundayBreakfastStart > sundaySunriseStart);
  assert.ok(sundayBreakfastStart !== -1 && statusStart > sundayBreakfastStart);
  const statusNext = model.indexOf("\nexport function ", statusStart + 1);
  const status = model.slice(statusStart, statusNext === -1 ? undefined : statusNext);
  assert.match(status, /isSundaySunriseFxOpenHour\(hourOffset, scenario\)/);
  assert.match(status, /isSundayBreakfastFxOpenHour\(hourOffset, scenario\)/);
  const sundaySunriseCall = status.indexOf("isSundaySunriseFxOpenHour(hourOffset, scenario)");
  const sundayBreakfastCall = status.indexOf("isSundayBreakfastFxOpenHour(hourOffset, scenario)");
  assert.ok(sundaySunriseCall !== -1 && sundayBreakfastCall > sundaySunriseCall);
  assert.doesNotMatch(model, /Date\.now/);
});

test("older scenario JSON without sundayBreakfastFxOpen keeps Sunday breakfast on ordinary weekend FX depth", () => {
  assert.equal(sanitizeScenario({}).scenario.sundayBreakfastFxOpen, false);
  assert.equal(sanitizeScenario({ sundayBreakfastFxOpen: "true" }).scenario.sundayBreakfastFxOpen, false);
  assert.ok(sanitizeScenario({ sundayBreakfastFxOpen: "true" }).errors.some((error) => error.includes("sundayBreakfastFxOpen")));
});

test("Sunday breakfast FX open is available as a preset button and is not an FX feed", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const sundaySunrisePreset = html.indexOf('data-preset="sundaySunriseFxOpen"');
  const sundayBreakfastPreset = html.indexOf('data-preset="sundayBreakfastFxOpen"');
  assert.ok(sundaySunrisePreset !== -1 && sundayBreakfastPreset > sundaySunrisePreset);
  assert.match(html, /Sunday breakfast FX open \(synthetic\)/);
  assert.match(html, /id="sundayBreakfastFxOpen"/);
  assert.match(html, /Keep Sunday FX open 07:00 to 09:00/);
  assert.match(html, /Keep Sunday FX open 06:00 to 08:00/);
  assert.match(html, /Keep Sunday FX open 04:00 to 06:00/);
  assert.match(html, /Keep Sunday FX open 02:00 to 04:00/);
  assert.match(html, /not an FX feed/i);
  assert.doesNotMatch(html, /live queue/i);
  assert.doesNotMatch(html, /hosted API/i);
});
