import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import {
  DEFAULT_SCENARIO,
  PRESETS,
  dayAndHourAt,
  formatTime,
  getOperationalStatus,
  runSimulation,
  sanitizeScenario
} from "../src/model.js";

function firstSundayLunchFxOpenHour(scenario) {
  for (let hour = 0; hour < 72; hour += 1) {
    const { dayIndex, localHour } = dayAndHourAt(hour);
    if (dayIndex === 0 && localHour >= 10 && localHour < 12 && getOperationalStatus(scenario, hour).fxWeekday) {
      const ordinary = getOperationalStatus({
        ...scenario,
        sundayLunchFxOpen: false
      }, hour).fxWeekday;
      if (!ordinary) return hour;
    }
  }
  return null;
}

test("Sunday lunch FX open keeps the Normal Friday calendar with a Sunday lunch FX window", () => {
  const preset = PRESETS.sundayLunchFxOpen;
  assert.match(preset.name, /synthetic/i);
  assert.match(preset.name, /Sunday lunch FX open/i);
  assert.equal(preset.sundayLunchFxOpen, true);
  assert.equal(DEFAULT_SCENARIO.sundayLunchFxOpen, false);
  assert.equal(preset.sundayBrunchFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.sundayBrunchFxOpen, false);
  assert.equal(preset.sundayBreakfastFxOpen, false);
  assert.equal(preset.sundayDawnFxOpen, false);
  assert.equal(preset.sundaySunriseFxOpen, false);
  assert.equal(preset.sundayDaybreakFxOpen, false);
  assert.equal(preset.sundayPredawnFxOpen, false);
  assert.equal(preset.saturdayLateNightFxOpen, false);
  assert.equal(preset.saturdayNightFxOpen, false);
  assert.equal(preset.sundayLateNightFxOpen, false);
  assert.equal(preset.sundayNightFxOpen, false);
  assert.equal(preset.sundayEveningFxOpen, false);
  assert.equal(preset.saturdayEveningFxOpen, false);
  assert.equal(preset.sundayMorningFxOpen, false);
  assert.equal(preset.sundayAfternoonFxOpen, false);
  assert.equal(preset.sundayMiddayFxOpen, false);
  assert.equal(preset.saturdayAfternoonFxOpen, false);
  assert.equal(preset.saturdayMiddayFxOpen, false);
  assert.equal(preset.saturdayEarlyFxOpen, false);
  assert.equal(preset.saturdayLateFxOpen, false);
  assert.equal(preset.sundayEarlyFxOpen, false);
  assert.equal(preset.sundayLateFxOpen, false);
  assert.equal(preset.fridayEarlyFxOpen, false);
  assert.equal(preset.fridayLateFxOpen, false);
  assert.equal(preset.saturdayLatePayoutOpen, false);
  assert.equal(preset.demandProfile, DEFAULT_SCENARIO.demandProfile);
  assert.notDeepEqual(preset, PRESETS.normal);
  assert.notDeepEqual(preset, PRESETS.sundayBrunchFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayBreakfastFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayDawnFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundaySunriseFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayDaybreakFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayPredawnFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayLateNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayLateNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayEveningFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayEveningFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayMorningFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayAfternoonFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayAfternoonFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayLateFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayMiddayFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayEarlyFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayLateFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayEarlyFxOpen);
  const lunch = runSimulation(preset);
  const brunch = runSimulation(PRESETS.sundayBrunchFxOpen);
  const normal = runSimulation(DEFAULT_SCENARIO);
  const breakfast = runSimulation(PRESETS.sundayBreakfastFxOpen);
  const sunrise = runSimulation(PRESETS.sundaySunriseFxOpen);
  const daybreak = runSimulation(PRESETS.sundayDaybreakFxOpen);
  const dawn = runSimulation(PRESETS.sundayDawnFxOpen);
  const predawn = runSimulation(PRESETS.sundayPredawnFxOpen);
  const saturdayLateNight = runSimulation(PRESETS.saturdayLateNightFxOpen);
  const saturdayNight = runSimulation(PRESETS.saturdayNightFxOpen);
  const sundayLateNight = runSimulation(PRESETS.sundayLateNightFxOpen);
  const sundayNight = runSimulation(PRESETS.sundayNightFxOpen);
  const sundayEvening = runSimulation(PRESETS.sundayEveningFxOpen);
  const saturdayEvening = runSimulation(PRESETS.saturdayEveningFxOpen);
  const sundayMorning = runSimulation(PRESETS.sundayMorningFxOpen);
  const sundayAfternoon = runSimulation(PRESETS.sundayAfternoonFxOpen);
  const saturdayAfternoon = runSimulation(PRESETS.saturdayAfternoonFxOpen);
  const saturdayLate = runSimulation(PRESETS.saturdayLateFxOpen);
  const saturdayMidday = runSimulation(PRESETS.saturdayMiddayFxOpen);
  const saturdayEarly = runSimulation(PRESETS.saturdayEarlyFxOpen);
  const sundayMidday = runSimulation(PRESETS.sundayMiddayFxOpen);
  const sundayLate = runSimulation(PRESETS.sundayLateFxOpen);
  const sundayEarly = runSimulation(PRESETS.sundayEarlyFxOpen);
  assert.equal(formatTime(33), "Sun 00:00");
  assert.equal(formatTime(40), "Sun 07:00");
  assert.equal(formatTime(41), "Sun 08:00");
  assert.equal(formatTime(42), "Sun 09:00");
  assert.equal(formatTime(43), "Sun 10:00");
  assert.equal(formatTime(44), "Sun 11:00");
  assert.equal(formatTime(45), "Sun 12:00");
  assert.equal(lunch.timeline[42].timeLabel, "Sun 09:00");
  assert.equal(lunch.timeline[42].weekend, true);
  assert.equal(lunch.timeline[42].fxWeekday, false);
  assert.equal(brunch.timeline[42].fxWeekday, true);
  assert.equal(normal.timeline[42].fxWeekday, false);
  assert.equal(breakfast.timeline[42].fxWeekday, false);
  assert.equal(dawn.timeline[42].fxWeekday, false);
  assert.equal(predawn.timeline[42].fxWeekday, false);
  assert.equal(saturdayLateNight.timeline[42].fxWeekday, false);
  assert.equal(saturdayNight.timeline[42].fxWeekday, false);
  assert.equal(sundayLateNight.timeline[42].fxWeekday, false);
  assert.equal(lunch.timeline[43].timeLabel, "Sun 10:00");
  assert.equal(lunch.timeline[43].weekend, true);
  assert.equal(lunch.timeline[43].fxWeekday, true);
  assert.equal(brunch.timeline[43].fxWeekday, true);
  assert.equal(normal.timeline[43].fxWeekday, false);
  assert.equal(breakfast.timeline[43].fxWeekday, false);
  assert.equal(dawn.timeline[43].fxWeekday, false);
  assert.equal(predawn.timeline[43].fxWeekday, false);
  assert.equal(saturdayLateNight.timeline[43].fxWeekday, false);
  assert.equal(lunch.timeline[41].timeLabel, "Sun 08:00");
  assert.equal(lunch.timeline[41].fxWeekday, false);
  assert.equal(breakfast.timeline[41].fxWeekday, true);
  assert.equal(lunch.timeline[40].fxWeekday, false);
  assert.equal(breakfast.timeline[40].fxWeekday, true);
  assert.equal(sunrise.timeline[39].fxWeekday, true);
  assert.equal(lunch.timeline[39].fxWeekday, false);
  assert.equal(daybreak.timeline[37].fxWeekday, true);
  assert.equal(lunch.timeline[37].fxWeekday, false);
  assert.equal(dawn.timeline[35].fxWeekday, true);
  assert.equal(lunch.timeline[35].fxWeekday, false);
  assert.equal(dawn.timeline[36].fxWeekday, true);
  assert.equal(predawn.timeline[33].fxWeekday, true);
  assert.equal(lunch.timeline[33].fxWeekday, false);
  assert.equal(predawn.timeline[34].fxWeekday, true);
  assert.equal(saturdayLateNight.timeline[31].fxWeekday, true);
  assert.equal(lunch.timeline[31].fxWeekday, false);
  assert.equal(saturdayLateNight.timeline[32].fxWeekday, true);
  assert.equal(lunch.timeline[32].fxWeekday, false);
  assert.equal(saturdayNight.timeline[29].fxWeekday, true);
  assert.equal(lunch.timeline[29].fxWeekday, false);
  assert.equal(saturdayEvening.timeline[27].fxWeekday, true);
  assert.equal(lunch.timeline[27].fxWeekday, false);
  assert.equal(sundayLateNight.timeline[55].fxWeekday, true);
  assert.equal(lunch.timeline[55].fxWeekday, false);
  assert.equal(sundayLateNight.timeline[56].fxWeekday, true);
  assert.equal(lunch.timeline[56].fxWeekday, false);
  assert.equal(sundayNight.timeline[53].fxWeekday, true);
  assert.equal(lunch.timeline[53].fxWeekday, false);
  assert.equal(sundayEvening.timeline[51].fxWeekday, true);
  assert.equal(lunch.timeline[51].fxWeekday, false);
  assert.equal(sundayLate.timeline[49].fxWeekday, true);
  assert.equal(lunch.timeline[49].fxWeekday, false);
  assert.equal(sundayAfternoon.timeline[47].fxWeekday, true);
  assert.equal(lunch.timeline[47].fxWeekday, false);
  assert.equal(sundayMidday.timeline[45].fxWeekday, true);
  assert.equal(lunch.timeline[45].fxWeekday, false);
  assert.equal(lunch.timeline[44].timeLabel, "Sun 11:00");
  assert.equal(lunch.timeline[44].fxWeekday, true);
  assert.equal(brunch.timeline[44].fxWeekday, false);
  assert.equal(sundayMorning.timeline[43].fxWeekday, true);
  assert.equal(lunch.timeline[43].fxWeekday, true);
  assert.equal(sundayMorning.timeline[44].fxWeekday, true);
  assert.equal(sundayMorning.timeline[42].fxWeekday, false);
  assert.equal(sundayEarly.timeline[41].fxWeekday, true);
  assert.equal(lunch.timeline[41].fxWeekday, false);
  assert.equal(sundayEarly.timeline[42].fxWeekday, true);
  assert.equal(lunch.timeline[42].fxWeekday, false);
  assert.equal(sundayEarly.timeline[43].fxWeekday, false);
  assert.equal(sunrise.timeline[41].fxWeekday, false);
  assert.equal(saturdayLate.timeline[25].fxWeekday, true);
  assert.equal(lunch.timeline[25].fxWeekday, false);
  assert.equal(saturdayAfternoon.timeline[23].fxWeekday, true);
  assert.equal(lunch.timeline[23].fxWeekday, false);
  assert.equal(saturdayMidday.timeline[21].fxWeekday, true);
  assert.equal(lunch.timeline[21].fxWeekday, false);
  assert.equal(saturdayEarly.timeline[15].fxWeekday, true);
  assert.equal(lunch.timeline[15].fxWeekday, false);
  assert.equal(lunch.timeline[42].issuerOpen, false);
  assert.equal(lunch.timeline[42].bankOpen, false);
  assert.equal(lunch.timeline[42].payoutOpen, false);
  assert.equal(getOperationalStatus(preset, 42).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayBrunchFxOpen, 42).fxWeekday, true);
  assert.equal(getOperationalStatus(DEFAULT_SCENARIO, 42).fxWeekday, false);
  assert.equal(getOperationalStatus(preset, 43).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 44).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 45).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayBreakfastFxOpen, 40).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 40).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayBreakfastFxOpen, 41).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 41).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundaySunriseFxOpen, 39).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 39).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayDawnFxOpen, 35).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 35).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayPredawnFxOpen, 33).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 33).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.saturdayLateNightFxOpen, 31).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 31).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.saturdayNightFxOpen, 29).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 29).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayLateNightFxOpen, 55).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 55).fxWeekday, false);
  const lunchOpen = firstSundayLunchFxOpenHour(preset);
  assert.equal(lunchOpen, 43);
  assert.equal(firstSundayLunchFxOpenHour(DEFAULT_SCENARIO), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundayBrunchFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundayBreakfastFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundaySunriseFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundayDaybreakFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundayDawnFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundayPredawnFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.saturdayLateNightFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.saturdayNightFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundayLateNightFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundayEveningFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.saturdayEveningFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundayNightFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundayEarlyFxOpen), null);
  assert.equal(firstSundayLunchFxOpenHour(PRESETS.sundayMorningFxOpen), null);
  assert.ok(lunchOpen > 42);
  assert.ok(lunchOpen < 45);
  const sundayLunch = dayAndHourAt(43);
  const sundayCloseHour = dayAndHourAt(45);
  const sundayBrunchHour = dayAndHourAt(42);
  const sundayBreakfastHour = dayAndHourAt(40);
  const sundaySunriseHour = dayAndHourAt(39);
  const sundayDawnHour = dayAndHourAt(35);
  const sundayPredawnHour = dayAndHourAt(33);
  const saturdayLateNightHour = dayAndHourAt(31);
  const saturdayNightHour = dayAndHourAt(29);
  const sundayLateNightHour = dayAndHourAt(55);
  const sundayEarlyHour = dayAndHourAt(41);
  const sundayMorningHour = dayAndHourAt(43);
  assert.equal(sundayLunch.dayIndex, 0);
  assert.equal(sundayLunch.localHour, 10);
  assert.equal(sundayCloseHour.dayIndex, 0);
  assert.equal(sundayCloseHour.localHour, 12);
  assert.equal(sundayBrunchHour.dayIndex, 0);
  assert.equal(sundayBrunchHour.localHour, 9);
  assert.equal(sundayBreakfastHour.dayIndex, 0);
  assert.equal(sundayBreakfastHour.localHour, 7);
  assert.equal(sundayDawnHour.dayIndex, 0);
  assert.equal(sundayDawnHour.localHour, 2);
  assert.equal(sundayPredawnHour.dayIndex, 0);
  assert.equal(sundayPredawnHour.localHour, 0);
  assert.equal(saturdayLateNightHour.dayIndex, 6);
  assert.equal(saturdayLateNightHour.localHour, 22);
  assert.equal(saturdayNightHour.dayIndex, 6);
  assert.equal(saturdayNightHour.localHour, 20);
  assert.equal(sundayLateNightHour.dayIndex, 0);
  assert.equal(sundayLateNightHour.localHour, 22);
  assert.equal(sundayEarlyHour.dayIndex, 0);
  assert.equal(sundayEarlyHour.localHour, 8);
  assert.equal(sundayMorningHour.dayIndex, 0);
  assert.equal(sundayMorningHour.localHour, 10);
  assert.equal(sundaySunriseHour.localHour, 6);
  assert.notEqual(sundayLunch.localHour, sundayBreakfastHour.localHour);
  assert.notEqual(sundayLunch.localHour, sundaySunriseHour.localHour);
  assert.notEqual(sundayLunch.localHour, sundayDawnHour.localHour);
  assert.notEqual(sundayLunch.localHour, sundayPredawnHour.localHour);
  assert.notEqual(sundayLunch.localHour, saturdayLateNightHour.localHour);
  assert.notEqual(sundayLunch.localHour, saturdayNightHour.localHour);
  assert.notEqual(sundayLunch.localHour, sundayLateNightHour.localHour);
  assert.notEqual(sundayLunch.localHour, sundayEarlyHour.localHour);
  assert.equal(sundayLunch.localHour, sundayMorningHour.localHour);
  assert.notEqual(sundayLunch.localHour, sundayBrunchHour.localHour);
  assert.notEqual(sundayLunch.dayIndex, saturdayLateNightHour.dayIndex);
});

test("Sunday lunch FX open ORs into fxWeekday through isSundayLunchFxOpenHour after sundayBrunchFxOpen", async () => {
  const model = await readFile(new URL("../src/model.js", import.meta.url), "utf8");
  const helperStart = model.indexOf("function isSundayLunchFxOpenHour");
  const helperNext = model.indexOf("\nexport function getOperationalStatus", helperStart);
  const commentStart = model.lastIndexOf("/** Sunday 10:00-12:00", helperStart);
  const helper = model.slice(commentStart === -1 ? helperStart : commentStart, helperNext === -1 ? undefined : helperNext);
  assert.match(helper, /scenario\.sundayLunchFxOpen !== true/);
  assert.match(helper, /localHour >= 10 && localHour < 12/);
  assert.match(helper, /dayIndex === 0/);
  assert.match(helper, /sundayBrunchFxOpen/);
  assert.match(helper, /sundayBreakfastFxOpen/);
  assert.match(helper, /sundaySunriseFxOpen/);
  assert.match(helper, /sundayDaybreakFxOpen/);
  assert.match(helper, /sundayDawnFxOpen/);
  assert.match(helper, /sundayPredawnFxOpen/);
  assert.match(helper, /saturdayLateNightFxOpen/);
  assert.match(helper, /saturdayNightFxOpen/);
  assert.match(helper, /sundayLateNightFxOpen/);
  assert.match(helper, /sundayNightFxOpen/);
  assert.match(helper, /saturdayEveningFxOpen/);
  assert.match(helper, /sundayEveningFxOpen/);
  assert.match(helper, /sundayLateFxOpen/);
  assert.match(helper, /sundayAfternoonFxOpen/);
  assert.match(helper, /sundayMiddayFxOpen/);
  assert.match(helper, /sundayMorningFxOpen/);
  assert.match(helper, /sundayEarlyFxOpen/);
  assert.match(helper, /saturdayLateFxOpen/);
  assert.match(helper, /saturdayAfternoonFxOpen/);
  assert.match(helper, /saturdayMiddayFxOpen/);
  assert.match(helper, /saturdayEarlyFxOpen/);
  assert.match(helper, /saturdayLatePayoutOpen/);
  assert.doesNotMatch(helper, /isSundayBrunchFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayBreakfastFxOpenHour/);
  assert.doesNotMatch(helper, /isSundaySunriseFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayDawnFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayPredawnFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayLateNightFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayNightFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayLateNightFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayEveningFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayNightFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayEveningFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayLateFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayAfternoonFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayMiddayFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayMorningFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayEarlyFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayLateFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayAfternoonFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayMiddayFxOpenHour/);
  assert.match(model, /isSundayLunchFxOpenHour\(hourOffset, scenario\)/);
  const sundayBreakfastStart = model.indexOf("function isSundayBreakfastFxOpenHour");
  const sundayBrunchStart = model.indexOf("function isSundayBrunchFxOpenHour");
  const sundayLunchStart = model.indexOf("function isSundayLunchFxOpenHour");
  const statusStart = model.indexOf("export function getOperationalStatus");
  assert.ok(sundayBreakfastStart !== -1 && sundayBrunchStart > sundayBreakfastStart);
  assert.ok(sundayBrunchStart !== -1 && sundayLunchStart > sundayBrunchStart);
  assert.ok(sundayLunchStart !== -1 && statusStart > sundayLunchStart);
  const statusNext = model.indexOf("\nexport function ", statusStart + 1);
  const status = model.slice(statusStart, statusNext === -1 ? undefined : statusNext);
  assert.match(status, /isSundayBreakfastFxOpenHour\(hourOffset, scenario\)/);
  assert.match(status, /isSundayBrunchFxOpenHour\(hourOffset, scenario\)/);
  assert.match(status, /isSundayLunchFxOpenHour\(hourOffset, scenario\)/);
  const sundayBreakfastCall = status.indexOf("isSundayBreakfastFxOpenHour(hourOffset, scenario)");
  const sundayBrunchCall = status.indexOf("isSundayBrunchFxOpenHour(hourOffset, scenario)");
  const sundayLunchCall = status.indexOf("isSundayLunchFxOpenHour(hourOffset, scenario)");
  assert.ok(sundayBreakfastCall !== -1 && sundayBrunchCall > sundayBreakfastCall);
  assert.ok(sundayBrunchCall !== -1 && sundayLunchCall > sundayBrunchCall);
  assert.doesNotMatch(model, /Date\.now/);
});

test("older scenario JSON without sundayLunchFxOpen keeps Sunday lunch on ordinary weekend FX depth", () => {
  assert.equal(sanitizeScenario({}).scenario.sundayLunchFxOpen, false);
  assert.equal(sanitizeScenario({ sundayLunchFxOpen: "true" }).scenario.sundayLunchFxOpen, false);
  assert.ok(sanitizeScenario({ sundayLunchFxOpen: "true" }).errors.some((error) => error.includes("sundayLunchFxOpen")));
});

test("Sunday lunch FX open is available as a preset button and is not an FX feed", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const sundayBreakfastPreset = html.indexOf('data-preset="sundayBreakfastFxOpen"');
  const sundayBrunchPreset = html.indexOf('data-preset="sundayBrunchFxOpen"');
  const sundayLunchPreset = html.indexOf('data-preset="sundayLunchFxOpen"');
  assert.ok(sundayBreakfastPreset !== -1 && sundayBrunchPreset > sundayBreakfastPreset);
  assert.ok(sundayLunchPreset > sundayBrunchPreset);
  assert.match(html, /Sunday lunch FX open \(synthetic\)/);
  assert.match(html, /id="sundayLunchFxOpen"/);
  assert.match(html, /Keep Sunday FX open 10:00 to 12:00/);
  assert.match(html, /Keep Sunday FX open 09:00 to 11:00/);
  assert.match(html, /Keep Sunday FX open 07:00 to 09:00/);
  assert.match(html, /Keep Sunday FX open 06:00 to 08:00/);
  assert.match(html, /Keep Sunday FX open 04:00 to 06:00/);
  assert.match(html, /not an FX feed/i);
  assert.doesNotMatch(html, /live queue/i);
  assert.doesNotMatch(html, /hosted API/i);
});
