import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import {
  DEFAULT_SCENARIO,
  PRESETS,
  dayAndHourAt,
  formatTime,
  getOperationalStatus,
  runSimulation,
  sanitizeScenario
} from "../src/model.js";

function firstSaturdayNightFxOpenHour(scenario) {
  for (let hour = 0; hour < 72; hour += 1) {
    const { dayIndex, localHour } = dayAndHourAt(hour);
    if (dayIndex === 6 && localHour >= 20 && localHour < 22 && getOperationalStatus(scenario, hour).fxWeekday) {
      const ordinary = getOperationalStatus({
        ...scenario,
        saturdayNightFxOpen: false
      }, hour).fxWeekday;
      if (!ordinary) return hour;
    }
  }
  return null;
}

test("Saturday night FX open keeps the Normal Friday calendar with a Saturday night FX window", () => {
  const preset = PRESETS.saturdayNightFxOpen;
  assert.match(preset.name, /synthetic/i);
  assert.match(preset.name, /Saturday night FX open/i);
  assert.equal(preset.saturdayNightFxOpen, true);
  assert.equal(DEFAULT_SCENARIO.saturdayNightFxOpen, false);
  assert.equal(preset.sundayLateNightFxOpen, false);
  assert.equal(preset.saturdayLateNightFxOpen, false);
  assert.equal(preset.sundayPredawnFxOpen, false);
  assert.equal(preset.sundayDawnFxOpen, false);
  assert.equal(preset.sundayDaybreakFxOpen, false);
  assert.equal(preset.sundaySunriseFxOpen, false);
  assert.equal(preset.sundayBreakfastFxOpen, false);
  assert.equal(preset.sundayBrunchFxOpen, false);
  assert.equal(preset.sundayLunchFxOpen, false);
  assert.equal(preset.sundayNightFxOpen, false);
  assert.equal(preset.sundayEveningFxOpen, false);
  assert.equal(preset.saturdayEveningFxOpen, false);
  assert.equal(preset.sundayMorningFxOpen, false);
  assert.equal(preset.sundayAfternoonFxOpen, false);
  assert.equal(preset.sundayMiddayFxOpen, false);
  assert.equal(preset.saturdayAfternoonFxOpen, false);
  assert.equal(preset.saturdayMiddayFxOpen, false);
  assert.equal(preset.saturdayEarlyFxOpen, false);
  assert.equal(preset.saturdayLateFxOpen, false);
  assert.equal(preset.sundayEarlyFxOpen, false);
  assert.equal(preset.sundayLateFxOpen, false);
  assert.equal(preset.fridayEarlyFxOpen, false);
  assert.equal(preset.fridayLateFxOpen, false);
  assert.equal(preset.saturdayLatePayoutOpen, false);
  assert.equal(preset.demandProfile, DEFAULT_SCENARIO.demandProfile);
  assert.notDeepEqual(preset, PRESETS.normal);
  assert.notDeepEqual(preset, PRESETS.sundayLateNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayLateNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayPredawnFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayDawnFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayDaybreakFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundaySunriseFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayBreakfastFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayBrunchFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayLunchFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayNightFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayEveningFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayEveningFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayMorningFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayAfternoonFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayAfternoonFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayLateFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayMiddayFxOpen);
  assert.notDeepEqual(preset, PRESETS.saturdayEarlyFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayLateFxOpen);
  assert.notDeepEqual(preset, PRESETS.sundayEarlyFxOpen);
  const night = runSimulation(preset);
  const normal = runSimulation(DEFAULT_SCENARIO);
  const sundayLateNight = runSimulation(PRESETS.sundayLateNightFxOpen);
  const sundayNight = runSimulation(PRESETS.sundayNightFxOpen);
  const sundayEvening = runSimulation(PRESETS.sundayEveningFxOpen);
  const saturdayEvening = runSimulation(PRESETS.saturdayEveningFxOpen);
  const sundayMorning = runSimulation(PRESETS.sundayMorningFxOpen);
  const sundayAfternoon = runSimulation(PRESETS.sundayAfternoonFxOpen);
  const saturdayAfternoon = runSimulation(PRESETS.saturdayAfternoonFxOpen);
  const saturdayLate = runSimulation(PRESETS.saturdayLateFxOpen);
  const saturdayMidday = runSimulation(PRESETS.saturdayMiddayFxOpen);
  const saturdayEarly = runSimulation(PRESETS.saturdayEarlyFxOpen);
  const sundayMidday = runSimulation(PRESETS.sundayMiddayFxOpen);
  const sundayLate = runSimulation(PRESETS.sundayLateFxOpen);
  const sundayEarly = runSimulation(PRESETS.sundayEarlyFxOpen);
  assert.equal(formatTime(27), "Sat 18:00");
  assert.equal(formatTime(28), "Sat 19:00");
  assert.equal(formatTime(29), "Sat 20:00");
  assert.equal(formatTime(30), "Sat 21:00");
  assert.equal(formatTime(31), "Sat 22:00");
  assert.equal(formatTime(55), "Sun 22:00");
  assert.equal(formatTime(56), "Sun 23:00");
  assert.equal(formatTime(53), "Sun 20:00");
  assert.equal(formatTime(51), "Sun 18:00");
  assert.equal(formatTime(25), "Sat 16:00");
  assert.equal(formatTime(23), "Sat 14:00");
  assert.equal(formatTime(21), "Sat 12:00");
  assert.equal(formatTime(15), "Sat 06:00");
  assert.equal(formatTime(49), "Sun 16:00");
  assert.equal(formatTime(47), "Sun 14:00");
  assert.equal(formatTime(45), "Sun 12:00");
  assert.equal(formatTime(43), "Sun 10:00");
  assert.equal(night.timeline[29].timeLabel, "Sat 20:00");
  assert.equal(night.timeline[29].weekend, true);
  assert.equal(night.timeline[29].fxWeekday, true);
  assert.equal(normal.timeline[29].fxWeekday, false);
  assert.equal(sundayLateNight.timeline[29].fxWeekday, false);
  assert.equal(saturdayEvening.timeline[29].fxWeekday, false);
  assert.equal(sundayNight.timeline[29].fxWeekday, false);
  assert.equal(night.timeline[30].timeLabel, "Sat 21:00");
  assert.equal(night.timeline[30].fxWeekday, true);
  assert.equal(night.timeline[31].timeLabel, "Sat 22:00");
  assert.equal(night.timeline[31].weekend, true);
  assert.equal(night.timeline[31].fxWeekday, false);
  assert.equal(normal.timeline[31].fxWeekday, false);
  assert.equal(night.timeline[27].fxWeekday, false);
  assert.equal(night.timeline[28].fxWeekday, false);
  assert.equal(saturdayEvening.timeline[27].fxWeekday, true);
  assert.equal(saturdayEvening.timeline[28].fxWeekday, true);
  assert.equal(saturdayEvening.timeline[29].fxWeekday, false);
  assert.equal(sundayLateNight.timeline[55].fxWeekday, true);
  assert.equal(night.timeline[55].fxWeekday, false);
  assert.equal(sundayLateNight.timeline[56].fxWeekday, true);
  assert.equal(night.timeline[56].fxWeekday, false);
  assert.equal(sundayNight.timeline[53].fxWeekday, true);
  assert.equal(night.timeline[53].fxWeekday, false);
  assert.equal(sundayNight.timeline[54].fxWeekday, true);
  assert.equal(night.timeline[54].fxWeekday, false);
  assert.equal(sundayEvening.timeline[51].fxWeekday, true);
  assert.equal(night.timeline[51].fxWeekday, false);
  assert.equal(sundayEvening.timeline[52].fxWeekday, true);
  assert.equal(night.timeline[52].fxWeekday, false);
  assert.equal(sundayLate.timeline[49].fxWeekday, true);
  assert.equal(night.timeline[49].fxWeekday, false);
  assert.equal(sundayLate.timeline[50].fxWeekday, true);
  assert.equal(night.timeline[50].fxWeekday, false);
  assert.equal(sundayAfternoon.timeline[47].fxWeekday, true);
  assert.equal(night.timeline[47].fxWeekday, false);
  assert.equal(sundayMidday.timeline[45].fxWeekday, true);
  assert.equal(night.timeline[45].fxWeekday, false);
  assert.equal(sundayMorning.timeline[43].fxWeekday, true);
  assert.equal(night.timeline[43].fxWeekday, false);
  assert.equal(saturdayLate.timeline[25].fxWeekday, true);
  assert.equal(night.timeline[25].fxWeekday, false);
  assert.equal(saturdayAfternoon.timeline[23].fxWeekday, true);
  assert.equal(night.timeline[23].fxWeekday, false);
  assert.equal(saturdayMidday.timeline[21].fxWeekday, true);
  assert.equal(night.timeline[21].fxWeekday, false);
  assert.equal(saturdayEarly.timeline[15].fxWeekday, true);
  assert.equal(night.timeline[15].fxWeekday, false);
  assert.equal(sundayEarly.timeline[41].fxWeekday, true);
  assert.equal(night.timeline[41].fxWeekday, false);
  assert.equal(night.timeline[29].issuerOpen, false);
  assert.equal(night.timeline[29].bankOpen, false);
  assert.equal(night.timeline[29].payoutOpen, false);
  assert.equal(getOperationalStatus(preset, 29).fxWeekday, true);
  assert.equal(getOperationalStatus(DEFAULT_SCENARIO, 29).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayLateNightFxOpen, 55).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 55).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.saturdayEveningFxOpen, 27).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 27).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayNightFxOpen, 53).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 53).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayEveningFxOpen, 51).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 51).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayLateFxOpen, 49).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 49).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayAfternoonFxOpen, 47).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 47).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayMiddayFxOpen, 45).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 45).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.sundayMorningFxOpen, 43).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 43).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.saturdayLateFxOpen, 25).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 25).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.saturdayAfternoonFxOpen, 23).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 23).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.saturdayMiddayFxOpen, 21).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 21).fxWeekday, false);
  assert.equal(getOperationalStatus(PRESETS.saturdayEarlyFxOpen, 15).fxWeekday, true);
  assert.equal(getOperationalStatus(preset, 15).fxWeekday, false);
  const nightOpen = firstSaturdayNightFxOpenHour(preset);
  assert.equal(nightOpen, 29);
  assert.equal(firstSaturdayNightFxOpenHour(DEFAULT_SCENARIO), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.sundayLateNightFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.sundayEveningFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.saturdayEveningFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.sundayMorningFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.sundayAfternoonFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.saturdayAfternoonFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.saturdayLateFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.saturdayMiddayFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.saturdayEarlyFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.sundayMiddayFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.sundayLateFxOpen), null);
  assert.equal(firstSaturdayNightFxOpenHour(PRESETS.sundayNightFxOpen), null);
  assert.ok(nightOpen > 28);
  assert.ok(nightOpen < 31);
  const saturdayNight = dayAndHourAt(29);
  const saturdayCloseHour = dayAndHourAt(31);
  const saturdayEveningHour = dayAndHourAt(27);
  const saturdayLateHour = dayAndHourAt(25);
  const saturdayAfternoonHour = dayAndHourAt(23);
  const saturdayMiddayHour = dayAndHourAt(21);
  const saturdayEarlyHour = dayAndHourAt(15);
  const sundayLateNightHour = dayAndHourAt(55);
  const sundayNightHour = dayAndHourAt(53);
  const sundayEveningHour = dayAndHourAt(51);
  const sundayLateHour = dayAndHourAt(49);
  const sundayAfternoonHour = dayAndHourAt(47);
  const sundayNoon = dayAndHourAt(45);
  const sundayMorningHour = dayAndHourAt(43);
  assert.equal(saturdayNight.dayIndex, 6);
  assert.equal(saturdayNight.localHour, 20);
  assert.equal(saturdayCloseHour.dayIndex, 6);
  assert.equal(saturdayCloseHour.localHour, 22);
  assert.equal(saturdayEveningHour.dayIndex, 6);
  assert.equal(saturdayEveningHour.localHour, 18);
  assert.equal(saturdayLateHour.dayIndex, 6);
  assert.equal(saturdayLateHour.localHour, 16);
  assert.equal(saturdayAfternoonHour.dayIndex, 6);
  assert.equal(saturdayAfternoonHour.localHour, 14);
  assert.equal(saturdayMiddayHour.dayIndex, 6);
  assert.equal(saturdayMiddayHour.localHour, 12);
  assert.equal(saturdayEarlyHour.dayIndex, 6);
  assert.equal(saturdayEarlyHour.localHour, 6);
  assert.equal(sundayLateNightHour.dayIndex, 0);
  assert.equal(sundayLateNightHour.localHour, 22);
  assert.equal(sundayNightHour.dayIndex, 0);
  assert.equal(sundayNightHour.localHour, 20);
  assert.equal(sundayEveningHour.dayIndex, 0);
  assert.equal(sundayEveningHour.localHour, 18);
  assert.equal(sundayLateHour.dayIndex, 0);
  assert.equal(sundayLateHour.localHour, 16);
  assert.equal(sundayAfternoonHour.dayIndex, 0);
  assert.equal(sundayAfternoonHour.localHour, 14);
  assert.equal(sundayNoon.dayIndex, 0);
  assert.equal(sundayNoon.localHour, 12);
  assert.equal(sundayMorningHour.dayIndex, 0);
  assert.equal(sundayMorningHour.localHour, 10);
  assert.notEqual(saturdayNight.localHour, saturdayEveningHour.localHour);
  assert.notEqual(saturdayNight.localHour, saturdayLateHour.localHour);
  assert.notEqual(saturdayNight.localHour, saturdayAfternoonHour.localHour);
  assert.notEqual(saturdayNight.localHour, saturdayMiddayHour.localHour);
  assert.notEqual(saturdayNight.dayIndex, sundayLateNightHour.dayIndex);
  assert.notEqual(saturdayNight.dayIndex, sundayNightHour.dayIndex);
  assert.notEqual(saturdayNight.localHour, sundayEveningHour.localHour);
});

test("Saturday night FX open ORs into fxWeekday through isSaturdayNightFxOpenHour after sundayLateNightFxOpen", async () => {
  const model = await readFile(new URL("../src/model.js", import.meta.url), "utf8");
  const helperStart = model.indexOf("function isSaturdayNightFxOpenHour");
  const helperNext = model.indexOf("function isSaturdayLateNightFxOpenHour", helperStart);
  const commentStart = model.lastIndexOf("/** Saturday 20:00-22:00", helperStart);
  const helper = model.slice(commentStart === -1 ? helperStart : commentStart, helperNext === -1 ? undefined : helperNext);
  assert.match(helper, /scenario\.saturdayNightFxOpen !== true/);
  assert.match(helper, /localHour >= 20 && localHour < 22/);
  assert.match(helper, /dayIndex === 6/);
  assert.match(helper, /sundayLateNightFxOpen/);
  assert.match(helper, /sundayNightFxOpen/);
  assert.match(helper, /saturdayEveningFxOpen/);
  assert.match(helper, /sundayEveningFxOpen/);
  assert.match(helper, /sundayLateFxOpen/);
  assert.match(helper, /sundayAfternoonFxOpen/);
  assert.match(helper, /sundayMiddayFxOpen/);
  assert.match(helper, /sundayMorningFxOpen/);
  assert.match(helper, /sundayEarlyFxOpen/);
  assert.match(helper, /saturdayLateFxOpen/);
  assert.match(helper, /saturdayAfternoonFxOpen/);
  assert.match(helper, /saturdayMiddayFxOpen/);
  assert.match(helper, /saturdayEarlyFxOpen/);
  assert.match(helper, /saturdayLatePayoutOpen/);
  assert.doesNotMatch(helper, /isSaturdayEveningFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayNightFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayLateNightFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayEveningFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayLateFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayAfternoonFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayMiddayFxOpenHour/);
  assert.doesNotMatch(helper, /isSundayMorningFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayLateFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayAfternoonFxOpenHour/);
  assert.doesNotMatch(helper, /isSaturdayMiddayFxOpenHour/);
  assert.match(model, /isSaturdayNightFxOpenHour\(hourOffset, scenario\)/);
  const sundayLateNightStart = model.indexOf("function isSundayLateNightFxOpenHour");
  const saturdayNightStart = model.indexOf("function isSaturdayNightFxOpenHour");
  const statusStart = model.indexOf("export function getOperationalStatus");
  assert.ok(sundayLateNightStart !== -1 && saturdayNightStart > sundayLateNightStart);
  assert.ok(saturdayNightStart !== -1 && statusStart > saturdayNightStart);
  const statusNext = model.indexOf("\nexport function ", statusStart + 1);
  const status = model.slice(statusStart, statusNext === -1 ? undefined : statusNext);
  assert.match(status, /isSundayLateNightFxOpenHour\(hourOffset, scenario\)/);
  assert.match(status, /isSaturdayNightFxOpenHour\(hourOffset, scenario\)/);
  const sundayLateNightCall = status.indexOf("isSundayLateNightFxOpenHour(hourOffset, scenario)");
  const saturdayNightCall = status.indexOf("isSaturdayNightFxOpenHour(hourOffset, scenario)");
  assert.ok(sundayLateNightCall !== -1 && saturdayNightCall > sundayLateNightCall);
  assert.doesNotMatch(model, /Date\.now/);
});

test("older scenario JSON without saturdayNightFxOpen keeps Saturday night on ordinary weekend FX depth", () => {
  assert.equal(sanitizeScenario({}).scenario.saturdayNightFxOpen, false);
  assert.equal(sanitizeScenario({ saturdayNightFxOpen: "true" }).scenario.saturdayNightFxOpen, false);
  assert.ok(sanitizeScenario({ saturdayNightFxOpen: "true" }).errors.some((error) => error.includes("saturdayNightFxOpen")));
});

test("Saturday night FX open is available as a preset button and is not an FX feed", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const sundayLateNightPreset = html.indexOf('data-preset="sundayLateNightFxOpen"');
  const saturdayNightPreset = html.indexOf('data-preset="saturdayNightFxOpen"');
  assert.ok(sundayLateNightPreset !== -1 && saturdayNightPreset > sundayLateNightPreset);
  assert.match(html, /Saturday night FX open \(synthetic\)/);
  assert.match(html, /id="saturdayNightFxOpen"/);
  assert.match(html, /Keep Saturday FX open 20:00 to 22:00/);
  assert.match(html, /Keep Sunday FX open 22:00 to 24:00/);
  assert.match(html, /not an FX feed/i);
  assert.doesNotMatch(html, /live queue/i);
  assert.doesNotMatch(html, /hosted API/i);
});
