import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { DEFAULT_SCENARIO, PRESETS } from "../src/model.js";

test("1.5.26 keeps F7 F8 F9 last-weekend-FX-closed controls and F3 F4 Backspace", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="copy-last-closed-payout"[^>]*aria-keyshortcuts="F3"/);
  assert.match(html, /<kbd>F3<\/kbd>/);
  assert.match(html, /<kbd>F4<\/kbd>/);
  assert.match(html, /<kbd>Backspace<\/kbd>/);
  assert.match(html, /id="gantt-hide-weekend-fx-closed"[^>]*aria-keyshortcuts="Backspace"/);
  assert.match(html, /id="copy-last-closed-fx"[^>]*aria-keyshortcuts="Delete"/);
  assert.match(html, /id="gantt-hide-weekend-payout-closed"[^>]*aria-keyshortcuts="ArrowRight"/);
  assert.match(html, /id="copy-last-weekend-fx-closed"[^>]*aria-keyshortcuts="F7"/);
  assert.match(html, /id="gantt-hide-weekday-fx-closed"[^>]*aria-keyshortcuts="F9"/);
  assert.match(html, /id="copy-last-weekday-fx-closed"[^>]*aria-keyshortcuts="F10"/);
  assert.match(html, /id="gantt-hide-weekend-fx-open"[^>]*aria-keyshortcuts="ArrowLeft F12"/);
  assert.match(html, /data-preset="fridayLateFxOpen"/);
  assert.match(html, /data-preset="saturdayLateFxOpen"/);
  assert.match(html, /data-preset="sundayLateFxOpen"/);
  assert.match(app, /event\.key === "F3"/);
  assert.match(app, /copyLastClosedPayoutHourMarkdown\(\)/);
  assert.match(app, /event\.key === "F4"/);
  assert.match(app, /jumpToLastClosedPayoutCopy\(\)/);
  assert.match(app, /event\.key === "Backspace"/);
  assert.match(app, /jumpToHideWeekendFxClosedFilter\(\)/);
  assert.match(app, /event\.key === "Delete"/);
  assert.match(app, /copyLastClosedFxHourMarkdown\(\)/);
  assert.match(app, /event\.key === "F2"/);
  assert.match(app, /jumpToLastClosedFxCopy\(\)/);
  assert.match(app, /event\.key === "ArrowRight"/);
  assert.match(app, /jumpToHideWeekendPayoutClosedFilter\(\)/);
  assert.match(app, /event\.key === "F7"/);
  assert.match(app, /copyLastWeekendFxClosedHourMarkdown\(\)/);
  assert.match(app, /event\.key === "F8"/);
  assert.match(app, /jumpToLastWeekendFxClosedCopy\(\)/);
  assert.match(app, /event\.key === "F9"/);
  assert.match(app, /jumpToHideWeekdayFxClosedFilter\(\)/);
  assert.match(app, /event\.key === "F10"/);
  assert.match(app, /copyLastWeekdayFxClosedHourMarkdown\(\)/);
  assert.match(app, /event\.key === "F11"/);
  assert.match(app, /jumpToLastWeekdayFxClosedCopy\(\)/);
  assert.match(app, /event\.key === "F12"/);
  assert.match(app, /jumpToHideWeekendFxOpenFilter\(\)/);
  assert.match(app, /if \(event\.defaultPrevented\) return/);
  assert.equal(PRESETS.fridayLateFxOpen.fridayLateFxOpen, true);
  assert.equal(PRESETS.saturdayLateFxOpen.saturdayLateFxOpen, true);
  assert.equal(PRESETS.sundayLateFxOpen.sundayLateFxOpen, true);
  assert.equal(PRESETS.saturdayLateFxOpen.fridayLateFxOpen, false);
  assert.equal(PRESETS.saturdayLateFxOpen.saturdayLateBankOpen, false);
  assert.equal(PRESETS.saturdayLateFxOpen.saturdayLatePayoutOpen, false);
  assert.equal(PRESETS.saturdayLateFxOpen.saturdayEarlyFxOpen, false);
  assert.equal(PRESETS.sundayLateFxOpen.saturdayLateFxOpen, false);
  assert.equal(PRESETS.sundayLateFxOpen.fridayLateFxOpen, false);
  assert.equal(PRESETS.sundayLateFxOpen.sundayLateIssuerClose, false);
  assert.equal(PRESETS.sundayLateFxOpen.sundayLatePayoutClose, false);
  assert.equal(PRESETS.sundayLateFxOpen.sundayLateBankClose, false);
  assert.notDeepEqual(PRESETS.saturdayLateFxOpen, PRESETS.fridayLateFxOpen);
  assert.notDeepEqual(PRESETS.saturdayLateFxOpen, PRESETS.saturdayLateBankOpen);
  assert.notDeepEqual(PRESETS.sundayLateFxOpen, PRESETS.saturdayLateFxOpen);
  assert.equal(DEFAULT_SCENARIO.saturdayLateFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.fridayLateFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.sundayLateFxOpen, false);
  const handler = app.slice(app.indexOf('document.addEventListener("keydown"'));
  assert.ok(handler.indexOf('event.key === "F7"') !== handler.indexOf('event.key === "F3"'));
  assert.ok(handler.indexOf('event.key === "F8"') !== handler.indexOf('event.key === "F4"'));
  assert.ok(handler.indexOf('event.key === "F9"') !== handler.indexOf('event.key === "Backspace"'));
  assert.ok(handler.indexOf('event.key === "F10"') !== handler.indexOf('event.key === "F7"'));
  assert.ok(handler.indexOf('event.key === "F11"') !== handler.indexOf('event.key === "F8"'));
  assert.ok(handler.indexOf('event.key === "F12"') !== handler.indexOf('event.key === "F9"'));
  const f9Slice = handler.slice(handler.indexOf('event.key === "F9"'), handler.indexOf('event.key === "F9"') + 180);
  assert.doesNotMatch(f9Slice, /copyLastWeekendFxClosedHourMarkdown/);
  assert.doesNotMatch(f9Slice, /copyLastClosedPayoutHourMarkdown/);
  const f12Slice = handler.slice(handler.lastIndexOf('event.key === "F12"'), handler.lastIndexOf('event.key === "F12"') + 180);
  assert.match(f12Slice, /jumpToHideWeekendFxOpenFilter/);
  assert.doesNotMatch(f12Slice, /jumpToHideWeekdayFxClosedFilter/);
});
