import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { DEFAULT_SCENARIO, PRESETS } from "../src/model.js";

test("1.5.18 keeps 5 6 7 last-open-issuer controls and Sunday issuer presets", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="copy-last-open-issuer"[^>]*aria-keyshortcuts="5"/);
  assert.match(html, /<kbd>5<\/kbd>/);
  assert.match(html, /<kbd>6<\/kbd>/);
  assert.match(html, /<kbd>7<\/kbd>/);
  assert.match(html, /id="gantt-hide-weekend-issuer-open"[^>]*aria-keyshortcuts="7"/);
  assert.match(html, /data-preset="sundayEarlyIssuerOpen"/);
  assert.match(html, /data-preset="sundayLateIssuerClose"/);
  assert.match(html, /id="copy-last-closed-issuer"[^>]*aria-keyshortcuts="8"/);
  assert.match(html, /id="gantt-hide-weekend-issuer-closed"[^>]*aria-keyshortcuts="0"/);
  assert.match(app, /event\.key === "5"/);
  assert.match(app, /copyLastOpenIssuerHourMarkdown\(\)/);
  assert.match(app, /event\.key === "6"/);
  assert.match(app, /jumpToLastOpenIssuerCopy\(\)/);
  assert.match(app, /event\.key === "7"/);
  assert.match(app, /jumpToHideWeekendIssuerOpenFilter\(\)/);
  assert.match(app, /event\.key === "\$"/);
  assert.match(app, /copyFirstOpenIssuerHourMarkdown\(\)/);
  assert.match(app, /event\.key === "\^"/);
  assert.match(app, /jumpToFirstOpenIssuerCopy\(\)/);
  assert.match(app, /event\.key === "`"/);
  assert.match(app, /jumpToHideIssuerOpenFilter\(\)/);
  assert.equal(PRESETS.sundayEarlyIssuerOpen.sundayEarlyIssuerOpen, true);
  assert.equal(PRESETS.sundayLateIssuerClose.sundayLateIssuerClose, true);
  assert.equal(PRESETS.saturdayEarlyIssuerOpen.saturdayEarlyIssuerOpen, true);
  assert.equal(PRESETS.fridayEarlyIssuerOpen.fridayEarlyIssuerOpen, true);
  assert.equal(PRESETS.fridayEarlyIssuerOpen.saturdayEarlyIssuerOpen, false);
  assert.equal(PRESETS.saturdayEarlyBankOpen.saturdayEarlyBankOpen, true);
  assert.equal(PRESETS.saturdayEarlyBankOpen.saturdayEarlyIssuerOpen, false);
  assert.equal(PRESETS.saturdayEarlyIssuerOpen.sundayEarlyIssuerOpen, false);
  assert.equal(PRESETS.saturdayEarlyIssuerOpen.sundayLateIssuerClose, false);
  assert.equal(DEFAULT_SCENARIO.sundayEarlyIssuerOpen, false);
  assert.equal(DEFAULT_SCENARIO.sundayLateIssuerClose, false);
  assert.equal(DEFAULT_SCENARIO.saturdayEarlyIssuerOpen, false);
  assert.equal(DEFAULT_SCENARIO.fridayEarlyIssuerOpen, false);
  assert.equal(DEFAULT_SCENARIO.saturdayEarlyBankOpen, false);
  assert.equal(DEFAULT_SCENARIO.fridayEarlyBankOpen, false);
  assert.equal(DEFAULT_SCENARIO.saturdayLateBankOpen, false);
  const handler = app.slice(app.indexOf('document.addEventListener("keydown"'));
  assert.ok(handler.indexOf('event.key === "5"') !== handler.indexOf('event.key === "8"'));
  assert.ok(handler.indexOf('event.key === "6"') !== handler.indexOf('event.key === "9"'));
  assert.ok(handler.indexOf('event.key === "7"') !== handler.indexOf('event.key === "0"'));
  assert.ok(handler.indexOf('event.key === "7"') !== handler.indexOf('event.key === "`"'));
});
