import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { DEFAULT_SCENARIO, PRESETS } from "../src/model.js";

test("1.5.26 retains closed payout and weekend FX controls plus late FX presets", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="copy-last-closed-payout"/);
  assert.match(html, /id="gantt-hide-weekend-fx-closed"/);
  assert.match(html, /id="copy-last-closed-fx"/);
  assert.match(html, /id="gantt-hide-weekend-payout-closed"/);
  assert.match(html, /id="copy-last-weekend-fx-closed"/);
  assert.match(html, /id="gantt-hide-weekday-fx-closed"/);
  assert.match(html, /id="copy-last-weekday-fx-closed"/);
  assert.match(html, /id="gantt-hide-weekend-fx-open"/);
  assert.match(html, /data-preset="fridayLateFxOpen"/);
  assert.match(html, /data-preset="saturdayLateFxOpen"/);
  assert.match(html, /data-preset="sundayLateFxOpen"/);
  assert.match(app, /copyLastClosedPayoutHourMarkdown\(\)/);
  assert.match(app, /jumpToLastClosedPayoutCopy\(\)/);
  assert.match(app, /jumpToHideWeekendFxClosedFilter\(\)/);
  assert.match(app, /copyLastClosedFxHourMarkdown\(\)/);
  assert.match(app, /jumpToLastClosedFxCopy\(\)/);
  assert.match(app, /jumpToHideWeekendPayoutClosedFilter\(\)/);
  assert.match(app, /copyLastWeekendFxClosedHourMarkdown\(\)/);
  assert.match(app, /jumpToLastWeekendFxClosedCopy\(\)/);
  assert.match(app, /jumpToHideWeekdayFxClosedFilter\(\)/);
  assert.match(app, /copyLastWeekdayFxClosedHourMarkdown\(\)/);
  assert.match(app, /jumpToLastWeekdayFxClosedCopy\(\)/);
  assert.match(app, /jumpToHideWeekendFxOpenFilter\(\)/);
  assert.match(app, /if \(event\.defaultPrevented\) return/);
  assert.equal(PRESETS.fridayLateFxOpen.fridayLateFxOpen, true);
  assert.equal(PRESETS.saturdayLateFxOpen.saturdayLateFxOpen, true);
  assert.equal(PRESETS.sundayLateFxOpen.sundayLateFxOpen, true);
  assert.equal(PRESETS.saturdayLateFxOpen.fridayLateFxOpen, false);
  assert.equal(PRESETS.saturdayLateFxOpen.saturdayLateBankOpen, false);
  assert.equal(PRESETS.saturdayLateFxOpen.saturdayLatePayoutOpen, false);
  assert.equal(PRESETS.saturdayLateFxOpen.saturdayEarlyFxOpen, false);
  assert.equal(PRESETS.sundayLateFxOpen.saturdayLateFxOpen, false);
  assert.equal(PRESETS.sundayLateFxOpen.fridayLateFxOpen, false);
  assert.equal(PRESETS.sundayLateFxOpen.sundayLateIssuerClose, false);
  assert.equal(PRESETS.sundayLateFxOpen.sundayLatePayoutClose, false);
  assert.equal(PRESETS.sundayLateFxOpen.sundayLateBankClose, false);
  assert.notDeepEqual(PRESETS.saturdayLateFxOpen, PRESETS.fridayLateFxOpen);
  assert.notDeepEqual(PRESETS.saturdayLateFxOpen, PRESETS.saturdayLateBankOpen);
  assert.notDeepEqual(PRESETS.sundayLateFxOpen, PRESETS.saturdayLateFxOpen);
  assert.equal(DEFAULT_SCENARIO.saturdayLateFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.fridayLateFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.sundayLateFxOpen, false);
});
