import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { DEFAULT_SCENARIO, PRESETS } from "../src/model.js";

test("1.5.24 keeps Delete F2 ArrowRight last-closed-FX controls and Insert ArrowDown ArrowLeft", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="copy-last-closed-fx"[^>]*aria-keyshortcuts="Delete"/);
  assert.match(html, /<kbd>Delete<\/kbd>/);
  assert.match(html, /<kbd>F2<\/kbd>/);
  assert.match(html, /<kbd>ArrowRight<\/kbd>/);
  assert.match(html, /id="gantt-hide-weekend-payout-closed"[^>]*aria-keyshortcuts="ArrowRight"/);
  assert.match(html, /id="copy-last-open-fx"[^>]*aria-keyshortcuts="Insert"/);
  assert.match(html, /id="gantt-hide-weekend-fx-open"[^>]*aria-keyshortcuts="ArrowLeft F12 Shift\+F12"/);
  assert.match(html, /id="copy-last-closed-payout"[^>]*aria-keyshortcuts="F3"/);
  assert.match(html, /id="gantt-hide-weekend-fx-closed"[^>]*aria-keyshortcuts="Backspace"/);
  assert.match(html, /data-preset="fridayLateBankOpen"/);
  assert.match(html, /data-preset="fridayLateFxOpen"/);
  assert.match(app, /event\.key === "Delete"/);
  assert.match(app, /copyLastClosedFxHourMarkdown\(\)/);
  assert.match(app, /event\.key === "F2"/);
  assert.match(app, /jumpToLastClosedFxCopy\(\)/);
  assert.match(app, /event\.key === "ArrowRight"/);
  assert.match(app, /jumpToHideWeekendPayoutClosedFilter\(\)/);
  assert.match(app, /event\.key === "Insert"/);
  assert.match(app, /copyLastOpenFxHourMarkdown\(\)/);
  assert.match(app, /event\.key === "ArrowDown"/);
  assert.match(app, /jumpToLastOpenFxCopy\(\)/);
  assert.match(app, /event\.key === "ArrowLeft"/);
  assert.match(app, /jumpToHideWeekendFxOpenFilter\(\)/);
  assert.match(app, /event\.key === "F3"/);
  assert.match(app, /copyLastClosedPayoutHourMarkdown\(\)/);
  assert.match(app, /event\.key === "F4"/);
  assert.match(app, /jumpToLastClosedPayoutCopy\(\)/);
  assert.match(app, /event\.key === "Backspace"/);
  assert.match(app, /jumpToHideWeekendFxClosedFilter\(\)/);
  assert.equal(PRESETS.fridayLateBankOpen.fridayLateBankOpen, true);
  assert.equal(PRESETS.fridayLateFxOpen.fridayLateFxOpen, true);
  assert.equal(PRESETS.fridayLateFxOpen.fridayLateBankOpen, false);
  assert.equal(PRESETS.fridayLateFxOpen.fridayFxLateClose, false);
  assert.equal(PRESETS.fridayLateFxOpen.saturdayEarlyFxOpen, false);
  assert.notDeepEqual(PRESETS.fridayLateFxOpen, PRESETS.fridayLateBankOpen);
  assert.notDeepEqual(PRESETS.fridayLateFxOpen, PRESETS.fridayLateFxClose);
  assert.notDeepEqual(PRESETS.fridayLateFxOpen, PRESETS.saturdayEarlyFxOpen);
  assert.equal(DEFAULT_SCENARIO.fridayLateFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.fridayLateBankOpen, false);
  const handler = app.slice(app.indexOf('document.addEventListener("keydown"'));
  assert.ok(handler.indexOf('event.key === "Delete"') !== handler.indexOf('event.key === "F3"'));
  assert.ok(handler.indexOf('event.key === "F2"') !== handler.indexOf('event.key === "F4"'));
  assert.ok(handler.indexOf('event.key === "ArrowRight"') !== handler.indexOf('event.key === "Backspace"'));
});
