import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { DEFAULT_SCENARIO, PRESETS } from "../src/model.js";

test("1.5.29 keeps F10 F11 F12 last-weekday-FX-closed controls, last-weekend-FX-open copy, and F7 F8 F9", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="copy-last-weekday-fx-closed"[^>]*aria-keyshortcuts="F10"/);
  assert.match(html, /<kbd>F10<\/kbd>/);
  assert.match(html, /<kbd>F11<\/kbd>/);
  assert.match(html, /<kbd>F12<\/kbd>/);
  assert.match(html, /id="gantt-hide-weekend-fx-open"[^>]*aria-keyshortcuts="ArrowLeft F12"/);
  assert.match(html, /id="copy-last-weekend-fx-closed"[^>]*aria-keyshortcuts="F7"/);
  assert.match(html, /id="gantt-hide-weekday-fx-closed"[^>]*aria-keyshortcuts="F9 Shift\+F12"/);
  assert.match(html, /id="copy-last-weekend-fx-open"/);
  assert.match(html, /id="copy-last-weekday-fx-open"/);
  assert.match(html, /data-preset="sundayLateFxOpen"/);
  assert.match(html, /data-preset="sundayEarlyFxOpen"/);
  assert.match(html, /data-preset="mondayEarlyFxOpen"/);
  assert.match(html, /data-preset="mondayLateFxOpen"/);
  assert.match(html, /data-preset="tuesdayEarlyFxOpen"/);
  assert.match(html, /data-preset="tuesdayLateFxOpen"/);
  assert.match(html, /data-preset="wednesdayEarlyFxOpen"/);
  assert.match(html, /data-preset="wednesdayLateFxOpen"/);
  assert.match(html, /data-preset="thursdayEarlyFxOpen"/);
  assert.match(html, /data-preset="thursdayLateFxOpen"/);
  assert.match(html, /data-preset="fridayEarlyFxOpen"/);
  assert.match(html, /data-preset="saturdayMiddayFxOpen"/);
  assert.match(html, /data-preset="sundayMiddayFxOpen"/);
  assert.match(html, /data-preset="saturdayAfternoonFxOpen"/);
  assert.match(html, /data-preset="sundayAfternoonFxOpen"/);
  assert.match(app, /event\.key === "F10"/);
  assert.match(app, /copyLastWeekdayFxClosedHourMarkdown\(\)/);
  assert.match(app, /event\.key === "F11"/);
  assert.match(app, /jumpToLastWeekdayFxClosedCopy\(\)/);
  assert.match(app, /event\.key === "F12"/);
  assert.match(app, /jumpToHideWeekendFxOpenFilter\(\)/);
  assert.match(app, /event\.key === "F7"/);
  assert.match(app, /copyLastWeekendFxClosedHourMarkdown\(\)/);
  assert.match(app, /function copyLastWeekendFxOpenHourMarkdown/);
  assert.match(app, /function copyLastWeekdayFxOpenHourMarkdown/);
  assert.match(app, /if \(event\.defaultPrevented\) return/);
  assert.equal(PRESETS.sundayLateFxOpen.sundayLateFxOpen, true);
  assert.equal(PRESETS.sundayEarlyFxOpen.sundayEarlyFxOpen, true);
  assert.equal(PRESETS.mondayEarlyFxOpen.mondayEarlyFxOpen, true);
  assert.equal(PRESETS.mondayLateFxOpen.mondayLateFxOpen, true);
  assert.equal(PRESETS.mondayLateFxOpen.mondayEarlyFxOpen, false);
  assert.equal(PRESETS.tuesdayEarlyFxOpen.tuesdayEarlyFxOpen, true);
  assert.equal(PRESETS.tuesdayEarlyFxOpen.mondayLateFxOpen, false);
  assert.equal(PRESETS.tuesdayLateFxOpen.tuesdayLateFxOpen, true);
  assert.equal(PRESETS.tuesdayLateFxOpen.tuesdayEarlyFxOpen, false);
  assert.equal(PRESETS.wednesdayEarlyFxOpen.wednesdayEarlyFxOpen, true);
  assert.equal(PRESETS.wednesdayEarlyFxOpen.tuesdayLateFxOpen, false);
  assert.equal(PRESETS.wednesdayLateFxOpen.wednesdayLateFxOpen, true);
  assert.equal(PRESETS.wednesdayLateFxOpen.wednesdayEarlyFxOpen, false);
  assert.equal(PRESETS.thursdayEarlyFxOpen.thursdayEarlyFxOpen, true);
  assert.equal(PRESETS.thursdayEarlyFxOpen.wednesdayLateFxOpen, false);
  assert.equal(PRESETS.thursdayLateFxOpen.thursdayLateFxOpen, true);
  assert.equal(PRESETS.thursdayLateFxOpen.thursdayEarlyFxOpen, false);
  assert.equal(PRESETS.fridayEarlyFxOpen.fridayEarlyFxOpen, true);
  assert.equal(PRESETS.fridayEarlyFxOpen.thursdayLateFxOpen, false);
  assert.equal(PRESETS.fridayEarlyFxOpen.fridayLateFxOpen, false);
  assert.equal(PRESETS.saturdayMiddayFxOpen.saturdayMiddayFxOpen, true);
  assert.equal(PRESETS.saturdayMiddayFxOpen.saturdayEarlyFxOpen, false);
  assert.equal(PRESETS.saturdayMiddayFxOpen.saturdayLateFxOpen, false);
  assert.equal(PRESETS.saturdayMiddayFxOpen.fridayEarlyFxOpen, false);
  assert.equal(PRESETS.saturdayMiddayFxOpen.sundayMiddayFxOpen, false);
  assert.equal(PRESETS.sundayMiddayFxOpen.sundayMiddayFxOpen, true);
  assert.equal(PRESETS.sundayMiddayFxOpen.saturdayMiddayFxOpen, false);
  assert.equal(PRESETS.sundayMiddayFxOpen.sundayEarlyFxOpen, false);
  assert.equal(PRESETS.sundayMiddayFxOpen.sundayLateFxOpen, false);
  assert.equal(PRESETS.sundayMiddayFxOpen.saturdayAfternoonFxOpen, false);
  assert.equal(PRESETS.saturdayAfternoonFxOpen.saturdayAfternoonFxOpen, true);
  assert.equal(PRESETS.saturdayAfternoonFxOpen.sundayMiddayFxOpen, false);
  assert.equal(PRESETS.saturdayAfternoonFxOpen.saturdayMiddayFxOpen, false);
  assert.equal(PRESETS.saturdayAfternoonFxOpen.saturdayLateFxOpen, false);
  assert.equal(PRESETS.mondayEarlyFxOpen.sundayEarlyFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.sundayEarlyFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.mondayEarlyFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.mondayLateFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.tuesdayEarlyFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.tuesdayLateFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.wednesdayEarlyFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.wednesdayLateFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.thursdayEarlyFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.thursdayLateFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.fridayEarlyFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.saturdayMiddayFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.sundayMiddayFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.saturdayAfternoonFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.sundayAfternoonFxOpen, false);
  assert.equal(PRESETS.sundayAfternoonFxOpen.sundayAfternoonFxOpen, true);
  assert.equal(PRESETS.sundayAfternoonFxOpen.saturdayAfternoonFxOpen, false);
  assert.equal(PRESETS.saturdayAfternoonFxOpen.sundayAfternoonFxOpen, false);
  const handler = app.slice(app.indexOf('document.addEventListener("keydown"'));
  const unshiftedF12 = handler.lastIndexOf('event.key === "F12"');
  const f12Slice = handler.slice(unshiftedF12, unshiftedF12 + 180);
  assert.match(f12Slice, /jumpToHideWeekendFxOpenFilter/);
  assert.doesNotMatch(f12Slice, /jumpToHideWeekdayFxOpenFilter/);
  assert.doesNotMatch(f12Slice, /jumpToHideWeekendFxClosedFilter/);
  assert.ok(handler.indexOf('event.key === "F10" && event.shiftKey') < handler.lastIndexOf('event.key === "F10"'));
});
