import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { DEFAULT_SCENARIO, PRESETS } from "../src/model.js";

test("1.5.24 retains last-closed-FX and related controls plus Friday FX presets", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="copy-last-closed-fx"/);
  assert.match(html, /id="gantt-hide-weekend-payout-closed"/);
  assert.match(html, /id="copy-last-open-fx"/);
  assert.match(html, /id="gantt-hide-weekend-fx-open"/);
  assert.match(html, /id="copy-last-closed-payout"/);
  assert.match(html, /id="gantt-hide-weekend-fx-closed"/);
  assert.match(html, /data-preset="fridayLateBankOpen"/);
  assert.match(html, /data-preset="fridayLateFxOpen"/);
  assert.match(app, /copyLastClosedFxHourMarkdown\(\)/);
  assert.match(app, /jumpToLastClosedFxCopy\(\)/);
  assert.match(app, /jumpToHideWeekendPayoutClosedFilter\(\)/);
  assert.match(app, /copyLastOpenFxHourMarkdown\(\)/);
  assert.match(app, /jumpToLastOpenFxCopy\(\)/);
  assert.match(app, /jumpToHideWeekendFxOpenFilter\(\)/);
  assert.match(app, /copyLastClosedPayoutHourMarkdown\(\)/);
  assert.match(app, /jumpToLastClosedPayoutCopy\(\)/);
  assert.match(app, /jumpToHideWeekendFxClosedFilter\(\)/);
  assert.equal(PRESETS.fridayLateBankOpen.fridayLateBankOpen, true);
  assert.equal(PRESETS.fridayLateFxOpen.fridayLateFxOpen, true);
  assert.equal(PRESETS.fridayLateFxOpen.fridayLateBankOpen, false);
  assert.equal(PRESETS.fridayLateFxOpen.fridayFxLateClose, false);
  assert.equal(PRESETS.fridayLateFxOpen.saturdayEarlyFxOpen, false);
  assert.notDeepEqual(PRESETS.fridayLateFxOpen, PRESETS.fridayLateBankOpen);
  assert.notDeepEqual(PRESETS.fridayLateFxOpen, PRESETS.fridayLateFxClose);
  assert.notDeepEqual(PRESETS.fridayLateFxOpen, PRESETS.saturdayEarlyFxOpen);
  assert.equal(DEFAULT_SCENARIO.fridayLateFxOpen, false);
  assert.equal(DEFAULT_SCENARIO.fridayLateBankOpen, false);
});
