import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { buildStandalone, isStandaloneCurrent, standaloneCsp } from "../scripts/build-standalone.mjs";

test("standalone build is self-contained, LF-only, and deterministic", async () => {
  const first = await buildStandalone();
  const second = await buildStandalone();
  assert.equal(first, second);
  assert.equal(isStandaloneCurrent(first, second), true);
  assert.equal(isStandaloneCurrent(first.replace(/\n/g, "\r\n"), second), true);
  assert.equal(isStandaloneCurrent("stale", second), false);
  assert.match(first, /data-weekend-gap-standalone="true"/);
  assert.match(first, /Sharing unavailable in standalone file/);
  assert.match(first, /A\$\$\{/);
  assert.match(first, new RegExp(`<meta http-equiv="Content-Security-Policy" content="${standaloneCsp}">`));
  assert.doesNotMatch(first, /(?:script|style)-src[^\"]*(?:'self'|https?:|data:|blob:)/);
  assert.doesNotMatch(first, /src="src\/app\.js"|href="styles\.css"|href="MODEL\.md"/);
  assert.doesNotMatch(first, /\r/);
});

test("release 1.5.31 ships Tuesday late FX open, first-weekend-FX-open copy and weekday-FX-closed hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.31/);
  assert.match(readme, /Tuesday late FX open, first-weekend-FX-open copy, and weekday-FX-closed hide in Weekend Gap 1\.5\.31/);
  assert.match(changelog, /1\.5\.31/);
  assert.match(changelog, /Tuesday late FX open, first-weekend-FX-open copy, and weekday-FX-closed hide in Weekend Gap 1\.5\.31/);
  assert.ok(html.includes('event.key === "F10" && event.shiftKey'));
  assert.match(html, /id="copy-first-weekend-fx-open"/);
  assert.ok(html.includes('event.key === "F11" && event.shiftKey'));
  assert.ok(html.includes('event.key === "F12" && event.shiftKey'));
  assert.match(html, /id="gantt-hide-weekday-fx-closed"/);
  assert.match(html, /data-preset="tuesdayLateFxOpen"/);
  assert.match(html, /hideWeekdayFxClosedGanttHours/);
  assert.match(html, /firstWeekendFxOpenHourToMarkdown/);
  assert.match(html, /isTuesdayLateFxOpenHour/);
  assert.match(html, /ganttHourWeekendFxOpen/);
  assert.match(html, /if \(event\.defaultPrevented\) return/);
  assert.match(html, /event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key/);
  assert.ok(html.includes('event.key === "F10"'));
  assert.ok(html.includes('event.key === "F11"'));
  assert.ok(html.includes('event.key === "F12"'));
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.30 ships Tuesday early FX open, first-weekday-FX-closed copy and weekday-FX-open hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.30/);
  assert.match(readme, /Tuesday early FX open, first-weekday-FX-closed copy, and weekday-FX-open hide in Weekend Gap 1\.5\.30/);
  assert.match(changelog, /1\.5\.30/);
  assert.match(changelog, /Tuesday early FX open, first-weekday-FX-closed copy, and weekday-FX-open hide in Weekend Gap 1\.5\.30/);
  assert.ok(html.includes('event.key === "F10" && event.shiftKey'));
  assert.match(html, /id="copy-first-weekday-fx-closed"/);
  assert.ok(html.includes('event.key === "F11" && event.shiftKey'));
  assert.ok(html.includes('event.key === "F12" && event.shiftKey'));
  assert.match(html, /id="gantt-hide-weekday-fx-open"/);
  assert.match(html, /data-preset="tuesdayEarlyFxOpen"/);
  assert.match(html, /hideWeekdayFxOpenGanttHours/);
  assert.match(html, /firstWeekdayFxClosedHourToMarkdown/);
  assert.match(html, /isTuesdayEarlyFxOpenHour/);
  assert.match(html, /ganttHourWeekdayFxClosed/);
  assert.match(html, /if \(event\.defaultPrevented\) return/);
  assert.match(html, /event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key/);
  assert.ok(html.includes('event.key === "F10"'));
  assert.ok(html.includes('event.key === "F11"'));
  assert.ok(html.includes('event.key === "F12"'));
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.29 ships Monday late FX open, first-weekday-FX-open copy and weekday-FX-closed hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.29/);
  assert.match(readme, /Monday late FX open, first-weekday-FX-open copy, and weekday-FX-closed hide in Weekend Gap 1\.5\.29/);
  assert.match(changelog, /1\.5\.29/);
  assert.match(changelog, /Monday late FX open, first-weekday-FX-open copy, and weekday-FX-closed hide in Weekend Gap 1\.5\.29/);
  assert.ok(html.includes('event.key === "F10" && event.shiftKey'));
  assert.match(html, /id="copy-first-weekday-fx-open"/);
  assert.ok(html.includes('event.key === "F11" && event.shiftKey'));
  assert.ok(html.includes('event.key === "F12" && event.shiftKey'));
  assert.match(html, /id="gantt-hide-weekday-fx-closed"/);
  assert.match(html, /data-preset="mondayLateFxOpen"/);
  assert.match(html, /hideWeekdayFxClosedGanttHours/);
  assert.match(html, /firstWeekdayFxOpenHourToMarkdown/);
  assert.match(html, /isMondayLateFxOpenHour/);
  assert.match(html, /ganttHourWeekdayFxOpen/);
  assert.match(html, /if \(event\.defaultPrevented\) return/);
  assert.match(html, /event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key/);
  assert.ok(html.includes('event.key === "F10"'));
  assert.ok(html.includes('event.key === "F11"'));
  assert.ok(html.includes('event.key === "F12"'));
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.28 ships Monday early FX open, last-weekday-FX-open copy and weekend-FX-closed hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.28/);
  assert.match(readme, /Monday early FX open, last-weekday-FX-open copy, and weekend-FX-closed hide in Weekend Gap 1\.5\.28/);
  assert.match(changelog, /1\.5\.28/);
  assert.match(changelog, /Monday early FX open, last-weekday-FX-open copy, and weekend-FX-closed hide in Weekend Gap 1\.5\.28/);
  assert.ok(html.includes('event.key === "F10" && event.shiftKey'));
  assert.match(html, /id="copy-last-weekday-fx-open"/);
  assert.ok(html.includes('event.key === "F11" && event.shiftKey'));
  assert.ok(html.includes('event.key === "F12" && event.shiftKey'));
  assert.match(html, /id="gantt-hide-weekend-fx-closed"/);
  assert.match(html, /data-preset="mondayEarlyFxOpen"/);
  assert.match(html, /hideWeekendFxClosedGanttHours/);
  assert.match(html, /lastWeekdayFxOpenHourToMarkdown/);
  assert.match(html, /isMondayEarlyFxOpenHour/);
  assert.match(html, /ganttHourWeekdayFxOpen/);
  assert.match(html, /if \(event\.defaultPrevented\) return/);
  assert.match(html, /event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key/);
  assert.ok(html.includes('event.key === "F10"'));
  assert.ok(html.includes('event.key === "F11"'));
  assert.ok(html.includes('event.key === "F12"'));
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.27 ships Sunday early FX open, last-weekend-FX-open copy and weekday-FX-open hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.27/);
  assert.match(changelog, /1\.5\.27/);
  assert.ok(html.includes('event.key === "F10" && event.shiftKey'));
  assert.match(html, /id="copy-last-weekend-fx-open"/);
  assert.ok(html.includes('event.key === "F11" && event.shiftKey'));
  assert.ok(html.includes('event.key === "F12" && event.shiftKey'));
  assert.match(html, /id="gantt-hide-weekday-fx-open"/);
  assert.match(html, /data-preset="sundayEarlyFxOpen"/);
  assert.match(html, /hideWeekdayFxOpenGanttHours/);
  assert.match(html, /lastWeekendFxOpenHourToMarkdown/);
  assert.match(html, /isSundayEarlyFxOpenHour/);
  assert.match(html, /ganttHourWeekdayFxOpen/);
  assert.match(html, /if \(event\.defaultPrevented\) return/);
  assert.ok(html.includes('event.key === "F10"'));
  assert.ok(html.includes('event.key === "F11"'));
  assert.ok(html.includes('event.key === "F12"'));
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.26 ships Sunday late FX open, last-weekday-FX-closed copy and weekend-FX-open hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.26/);
  assert.match(changelog, /1\.5\.26/);
  assert.ok(html.includes('event.key === "F10"'));
  assert.match(html, /id="copy-last-weekday-fx-closed"/);
  assert.ok(html.includes('event.key === "F11"'));
  assert.ok(html.includes('event.key === "F12"'));
  assert.match(html, /id="gantt-hide-weekend-fx-open"/);
  assert.match(html, /data-preset="sundayLateFxOpen"/);
  assert.match(html, /hideWeekendFxOpenGanttHours/);
  assert.match(html, /lastWeekdayFxClosedHourToMarkdown/);
  assert.match(html, /isSundayLateFxOpenHour/);
  assert.match(html, /if \(event\.defaultPrevented\) return/);
  assert.ok(html.includes('event.key === "F7"'));
  assert.ok(html.includes('event.key === "F8"'));
  assert.ok(html.includes('event.key === "F9"'));
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.25 ships Saturday late FX open, last-weekend-FX-closed copy and weekday-FX-closed Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.25/);
  assert.match(changelog, /1\.5\.25/);
  assert.ok(html.includes('event.key === "F7"'));
  assert.match(html, /id="copy-last-weekend-fx-closed"/);
  assert.ok(html.includes('event.key === "F8"'));
  assert.ok(html.includes('event.key === "F9"'));
  assert.match(html, /id="gantt-hide-weekday-fx-closed"/);
  assert.match(html, /data-preset="saturdayLateFxOpen"/);
  assert.match(html, /hideWeekdayFxClosedGanttHours/);
  assert.match(html, /lastWeekendFxClosedHourToMarkdown/);
  assert.match(html, /ganttHourWeekdayFxClosed/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.24 ships Friday late FX open, last-closed-payout copy and weekend-FX-closed Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.24/);
  assert.match(changelog, /1\.5\.24/);
  assert.ok(html.includes('event.key === "F3"'));
  assert.match(html, /id="copy-last-closed-payout"/);
  assert.ok(html.includes('event.key === "F4"'));
  assert.match(html, /event\.key === "Backspace"/);
  assert.match(html, /id="gantt-hide-weekend-fx-closed"/);
  assert.match(html, /data-preset="fridayLateFxOpen"/);
  assert.match(html, /hideWeekendFxClosedGanttHours/);
  assert.match(html, /lastClosedPayoutHourToMarkdown/);
  assert.match(html, /ganttHourWeekendFxClosed/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.23 ships Friday late bank open, last-closed-FX copy and weekend-payout-closed Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.23/);
  assert.match(changelog, /1\.5\.23/);
  assert.ok(html.includes('event.key === "Delete"'));
  assert.match(html, /id="copy-last-closed-fx"/);
  assert.ok(html.includes('event.key === "F2"'));
  assert.match(html, /event\.key === "ArrowRight"/);
  assert.match(html, /id="gantt-hide-weekend-payout-closed"/);
  assert.match(html, /data-preset="fridayLateBankOpen"/);
  assert.match(html, /hideWeekendPayoutClosedGanttHours/);
  assert.match(html, /lastClosedFxHourToMarkdown/);
  assert.match(html, /ganttHourWeekendPayoutClosed/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.22 ships Saturday late bank open, last-open-FX copy and weekend-FX-open Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.22/);
  assert.match(changelog, /1\.5\.22/);
  assert.ok(html.includes('event.key === "Insert"'));
  assert.match(html, /id="copy-last-open-fx"/);
  assert.ok(html.includes('event.key === "ArrowDown"'));
  assert.match(html, /event\.key === "ArrowLeft"/);
  assert.match(html, /id="gantt-hide-weekend-fx-open"/);
  assert.match(html, /data-preset="saturdayLateBankOpen"/);
  assert.match(html, /hideWeekendFxOpenGanttHours/);
  assert.match(html, /lastOpenFxHourToMarkdown/);
  assert.match(html, /ganttHourWeekendFxOpen/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.21 ships Friday early bank open, last-open-payout copy and weekend-payout-open Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.21/);
  assert.match(changelog, /1\.5\.21/);
  assert.ok(html.includes('event.key === "PageUp"'));
  assert.match(html, /id="copy-last-open-payout"/);
  assert.ok(html.includes('event.key === "PageDown"'));
  assert.match(html, /event\.key === "ArrowUp"/);
  assert.match(html, /id="gantt-hide-weekend-payout-open"/);
  assert.match(html, /data-preset="fridayEarlyBankOpen"/);
  assert.match(html, /hideWeekendPayoutOpenGanttHours/);
  assert.match(html, /lastOpenPayoutHourToMarkdown/);
  assert.match(html, /ganttHourWeekendPayoutOpen/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.20 ships Saturday early bank open, last-open-bank copy and weekend-bank-open Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.20/);
  assert.match(changelog, /1\.5\.20/);
  assert.ok(html.includes('event.key === "4"'));
  assert.match(html, /id="copy-last-open-bank"/);
  assert.ok(html.includes('event.key === "Home"'));
  assert.match(html, /event\.key === "End"/);
  assert.match(html, /id="gantt-hide-weekend-bank-open"/);
  assert.match(html, /data-preset="saturdayEarlyBankOpen"/);
  assert.match(html, /hideWeekendBankOpenGanttHours/);
  assert.match(html, /lastOpenBankHourToMarkdown/);
  assert.match(html, /ganttHourWeekendBankOpen/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.19 ships Friday early issuer open, last-closed-bank copy and weekend-bank-closed Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.19/);
  assert.match(changelog, /1\.5\.19/);
  assert.ok(html.includes('event.key === "1"'));
  assert.match(html, /id="copy-last-closed-bank"/);
  assert.ok(html.includes('event.key === "2"'));
  assert.match(html, /event\.key === "3"/);
  assert.match(html, /id="gantt-hide-weekend-bank-closed"/);
  assert.match(html, /data-preset="fridayEarlyIssuerOpen"/);
  assert.match(html, /hideWeekendBankClosedGanttHours/);
  assert.match(html, /lastClosedBankHourToMarkdown/);
  assert.match(html, /ganttHourWeekendBankClosed/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 ships Saturday early issuer open, last-closed-issuer copy and weekend-issuer-closed Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.18/);
  assert.match(changelog, /1\.5\.18/);
  assert.ok(html.includes('event.key === "8"'));
  assert.match(html, /id="copy-last-closed-issuer"/);
  assert.ok(html.includes('event.key === "9"'));
  assert.match(html, /event\.key === "0"/);
  assert.match(html, /id="gantt-hide-weekend-issuer-closed"/);
  assert.match(html, /data-preset="saturdayEarlyIssuerOpen"/);
  assert.match(html, /hideWeekendIssuerClosedGanttHours/);
  assert.match(html, /id="gantt-hide-weekend-issuer-closed"/);
  assert.match(html, /id="copy-last-closed-issuer"/);
  assert.match(html, /lastClosedIssuerHourToMarkdown/);
  assert.match(html, /ganttHourWeekendIssuerClosed/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 retains 1.5.17 Sunday early issuer open, last-open-issuer copy and weekend-issuer-open Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.17/);
  assert.match(changelog, /1\.5\.17/);
  assert.ok(html.includes('event.key === "5"'));
  assert.match(html, /id="copy-last-open-issuer"/);
  assert.ok(html.includes('event.key === "6"'));
  assert.match(html, /event\.key === "7"/);
  assert.match(html, /id="gantt-hide-weekend-issuer-open"/);
  assert.match(html, /data-preset="sundayEarlyIssuerOpen"/);
  assert.match(html, /hideWeekendIssuerOpenGanttHours/);
  assert.match(html, /id="gantt-hide-weekend-issuer-open"/);
  assert.match(html, /id="copy-last-open-issuer"/);
  assert.match(html, /lastOpenIssuerHourToMarkdown/);
  assert.match(html, /ganttHourWeekendIssuerOpen/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 retains 1.5.16 Sunday late issuer close, issuer-open copy and issuer-open Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.16/);
  assert.match(changelog, /1\.5\.16/);
  assert.ok(html.includes('event.key === "$"'));
  assert.match(html, /id="copy-first-open-issuer"/);
  assert.ok(html.includes('event.key === "^"'));
  assert.match(html, /event\.key === "`"/);
  assert.match(html, /id="gantt-hide-issuer-open"/);
  assert.match(html, /data-preset="sundayLateIssuerClose"/);
  assert.match(html, /hideIssuerOpenGanttHours/);
  assert.match(html, /id="gantt-hide-issuer-open"/);
  assert.match(html, /id="copy-first-open-issuer"/);
  assert.match(html, /firstOpenIssuerHourToMarkdown/);
  assert.match(html, /ganttHourIssuerOpen/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 retains 1.5.15 Sunday early payout, bank-open Gantt hide and first-open-issuer copy", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.15/);
  assert.match(changelog, /1\.5\.15/);
  assert.ok(html.includes('event.key === "*"'));
  assert.match(html, /id="copy-first-open-bank"/);
  assert.ok(html.includes('event.key === "&"'));
  assert.match(html, /event\.key === "%"/);
  assert.match(html, /id="gantt-hide-fx-open"/);
  assert.match(html, /data-preset="sundayEarlyPayoutOpen"/);
  assert.match(html, /hideBankOpenGanttHours/);
  assert.match(html, /id="gantt-hide-bank-open"/);
  assert.match(html, /id="first-open-bank-hour-line"/);
  assert.match(html, /id="copy-first-open-issuer"/);
  assert.match(html, /firstOpenIssuerHourToMarkdown/);
  assert.match(html, /the first open bank hour when one exists, with an honest empty when none/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 retains 1.5.14 Saturday late payout, FX-open Gantt hide and first-open-bank copy", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.14/);
  assert.match(changelog, /1\.5\.14/);
  assert.ok(html.includes('event.key === "("'));
  assert.match(html, /id="copy-first-open-fx"/);
  assert.ok(html.includes('event.key === ")"'));
  assert.match(html, /event\.key === "#"/);
  assert.match(html, /id="gantt-hide-payout-open"/);
  assert.match(html, /data-preset="saturdayLatePayoutOpen"/);
  assert.match(html, /hideFxOpenGanttHours/);
  assert.match(html, /id="gantt-hide-fx-open"/);
  assert.match(html, /id="first-open-fx-hour-line"/);
  assert.match(html, /id="copy-first-open-bank"/);
  assert.match(html, /firstOpenBankHourToMarkdown/);
  assert.match(html, /the first open FX hour when one exists, with an honest empty when none/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 retains 1.5.13 Friday early payout, payout-open Gantt hide and first-open-FX copy", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.13/);
  assert.match(changelog, /1\.5\.13/);
  assert.ok(html.includes('event.key === "~"'));
  assert.match(html, /id="copy-first-open-payout"/);
  assert.ok(html.includes('event.key === "!"'));
  assert.match(html, /event\.key === "@"/);
  assert.match(html, /id="gantt-hide-fx-closed"/);
  assert.match(html, /data-preset="fridayEarlyPayoutOpen"/);
  assert.match(html, /hidePayoutOpenGanttHours/);
  assert.match(html, /id="gantt-hide-payout-open"/);
  assert.match(html, /id="first-open-payout-hour-line"/);
  assert.match(html, /id="copy-first-open-fx"/);
  assert.match(html, /firstOpenFxHourToMarkdown/);
  assert.match(html, /the first open payout hour when one exists, with an honest empty when none/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 retains 1.5.12 Saturday early payout, FX-closed Gantt hide and first-open-payout copy", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.12/);
  assert.match(changelog, /1\.5\.12/);
  assert.ok(html.includes('event.key === "}"'));
  assert.match(html, /id="copy-first-closed-fx"/);
  assert.ok(html.includes('event.key === "+"'));
  assert.match(html, /event\.key === "\|"/);
  assert.match(html, /id="gantt-hide-payout-closed"/);
  assert.match(html, /data-preset="saturdayEarlyPayoutOpen"/);
  assert.match(html, /hideFxClosedGanttHours/);
  assert.match(html, /id="gantt-hide-fx-closed"/);
  assert.match(html, /id="first-closed-fx-hour-line"/);
  assert.match(html, /id="copy-first-open-payout"/);
  assert.match(html, /firstOpenPayoutHourToMarkdown/);
  assert.match(html, /the first closed FX hour when one exists, with an honest empty when none/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 retains 1.5.11 Sunday late payout, payout-closed Gantt hide and first-closed-payout print", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.11/);
  assert.match(changelog, /1\.5\.11/);
  assert.match(html, /event\.key === '"'/);
  assert.match(html, /id="copy-first-closed-payout"/);
  assert.ok(html.includes('event.key === "_"'));
  assert.match(html, /event\.key === "\{"/);
  assert.match(html, /id="gantt-hide-issuer-closed"/);
  assert.match(html, /data-preset="sundayLatePayoutClose"/);
  assert.match(html, /hidePayoutClosedGanttHours/);
  assert.match(html, /id="gantt-hide-payout-closed"/);
  assert.match(html, /id="first-closed-payout-hour-line"/);
  assert.match(html, /id="copy-first-closed-fx"/);
  assert.match(html, /firstClosedFxHourToMarkdown/);
  assert.match(html, /the first closed payout hour when one exists, with an honest empty when none/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 retains 1.5.10 Sunday late bank, issuer-closed Gantt hide and first-closed-issuer print", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.10/);
  assert.match(changelog, /1\.5\.10/);
  assert.match(html, /event\.key === ":"/);
  assert.match(html, /id="copy-first-closed-issuer"/);
  assert.ok(html.includes('event.key === "-"'));
  assert.match(html, /event\.key === "="/);
  assert.match(html, /id="gantt-hide-bank-closed"/);
  assert.match(html, /data-preset="sundayLateBankClose"/);
  assert.match(html, /hideIssuerClosedGanttHours/);
  assert.match(html, /id="gantt-hide-issuer-closed"/);
  assert.match(html, /id="first-closed-issuer-hour-line"/);
  assert.match(html, /id="copy-first-closed-payout"/);
  assert.match(html, /firstClosedPayoutHourToMarkdown/);
  assert.match(html, /the first closed issuer hour when one exists, with an honest empty when none/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 retains 1.5.9 Saturday early FX, bank-closed Gantt hide and first-closed-bank print", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.9/);
  assert.match(changelog, /1\.5\.9/);
  assert.match(html, /event\.key === "'"/);
  assert.match(html, /id="copy-first-closed-bank"/);
  assert.ok(html.includes('event.key === "<"'));
  assert.match(html, /event\.key === ">"/);
  assert.match(html, /id="gantt-hide-zero-queue"/);
  assert.match(html, /data-preset="saturdayEarlyFxOpen"/);
  assert.match(html, /hideBankClosedGanttHours/);
  assert.match(html, /id="gantt-hide-bank-closed"/);
  assert.match(html, /id="first-closed-bank-hour-line"/);
  assert.match(html, /id="copy-first-closed-issuer"/);
  assert.match(html, /firstClosedIssuerHourToMarkdown/);
  assert.match(html, /the first closed bank hour when one exists, with an honest empty when none/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
});

test("release 1.5.18 retains 1.5.8 Monday late issuer, hours-to-clear semicolon copy and zero-queue Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.8/);
  assert.match(changelog, /1\.5\.8/);
  assert.match(html, /event\.key === ";"/);
  assert.match(html, /id="copy-hours-to-clear"/);
  assert.match(html, /event\.key === "\["/);
  assert.match(html, /event\.key === "\]"/);
  assert.match(html, /id="print"/);
  assert.match(html, /id="print-heading"/);
  assert.match(html, /data-preset="mondayLateIssuerOpen"/);
  assert.match(html, /hideZeroQueueGanttHours/);
  assert.match(html, /id="gantt-hide-zero-queue"/);
  assert.match(html, /id="copy-first-closed-bank"/);
  assert.match(html, /firstClosedBankHourToMarkdown/);
  assert.match(html, /hours to clear the queue when a queue exists, with an honest empty when none/);
});

test("release 1.5.18 retains 1.5.7 Friday late FX close, settlement comma copy and closed Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.7/);
  assert.match(changelog, /1\.5\.7/);
  assert.match(html, /event\.key === ","/);
  assert.match(html, /id="copy-hours-to-first-settlement"/);
  assert.match(html, /event\.key === "\."/);
  assert.match(html, /id="copy-first-closed-fx"/);
  assert.match(html, /event\.key === "\/"/);
  assert.match(html, /id="copy-remaining-reserve"/);
  assert.match(html, /data-preset="fridayLateFxClose"/);
  assert.match(html, /hideClosedGanttHours/);
  assert.match(html, /id="gantt-hide-closed"/);
  assert.match(html, /id="first-closed-fx-hour-line"/);
  assert.match(html, /id="copy-hours-to-clear"/);
  assert.match(html, /The first closed FX hour label stays on the printed brief/);
});

test("release 1.5.18 retains 1.5.6 early Monday bank, settlement jump and weekend Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.6/);
  assert.match(changelog, /1\.5\.6/);
  assert.match(html, /event\.key === "y"/);
  assert.match(html, /id="hours-to-first-settlement-line"/);
  assert.match(html, /event\.key === "z"/);
  assert.match(html, /id="copy-remaining-reserve"/);
  assert.match(html, /data-preset="earlyMondayBankOpen"/);
  assert.match(html, /hideWeekendGanttHours/);
  assert.match(html, /id="gantt-hide-weekends"/);
  assert.match(html, /id="copy-first-closed-fx"/);
  assert.match(html, /firstClosedFxHourToMarkdown/);
  assert.match(html, /Hours to first settlement stay on the printed brief/);
});

test("release 1.5.18 retains 1.5.5 thin Saturday FX, settlement copy and issuer jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.5/);
  assert.match(changelog, /1\.5\.5/);
  assert.match(html, /event\.key === "i"/);
  assert.match(html, /id="gantt-issuer-row"/);
  assert.match(html, /event\.key === "l"/);
  assert.match(html, /id="copy-hours-to-first-settlement"/);
  assert.match(html, /event\.key === "o"/);
  assert.match(html, /id="gantt-payout-row"/);
  assert.match(html, /event\.key === "v"/);
  assert.match(html, /id="copy-selected-versus-peak"/);
  assert.match(html, /data-preset="thinSaturdayFx"/);
  assert.match(html, /hideOpenGanttHours/);
  assert.match(html, /id="gantt-hide-open"/);
  assert.match(html, /id="copy-next-payout"/);
  assert.match(html, /hoursToFirstSettlementToMarkdown/);
  assert.match(html, /selectedVersusPeakHourToMarkdown/);
  assert.match(html, /nextPayoutHourToMarkdown/);
  assert.match(html, /ganttHourOpenOnEveryGate/);
});

test("release 1.5.18 retains 1.5.4 Sunday stall close, reserve copy and weekend Gantt filter", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.4/);
  assert.match(changelog, /1\.5\.4/);
  assert.match(html, /event\.key === "k"/);
  assert.match(html, /id="hours-to-clear-line"/);
  assert.match(html, /event\.key === "n"/);
  assert.match(html, /id="gantt-first-payout-marker"/);
  assert.match(html, /event\.key === "a"/);
  assert.match(html, /id="analysis-export-controls"/);
  assert.match(html, /event\.key === "w"/);
  assert.match(html, /id="gantt-fx-row"/);
  assert.match(html, /id="copy-remaining-reserve"/);
  assert.match(html, /data-preset="sundayStallClose"/);
  assert.match(html, /hideWeekdayGanttHours/);
  assert.match(html, /id="gantt-hide-weekdays"/);
  assert.match(html, /id="selected-gantt-hour-line"/);
  assert.match(html, /id="copy-weekend-fx-counts"/);
});

test("release 1.5.18 retains 1.5.3 hours-to-clear copy, Saturday market and hour persist", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.3/);
  assert.match(readme, /Saturday market burst/);
  assert.match(html, /id="copy-hours-to-clear"/);
  assert.match(html, /event\.key === "h"/);
  assert.match(html, /data-preset="saturdayMarketBurst"/);
  assert.match(html, /event\.key === "x"/);
  assert.match(html, /ganttHourIndex/);
  assert.match(html, /event\.key === "b"/);
  assert.match(html, /id="copy-fx-hours"/);
  assert.match(html, /event\.key === "m"/);
  assert.match(html, /id="hours-to-clear-line"/);
  assert.match(html, /id="gantt-every-closed"/);
  assert.match(html, /ganttEveryGateClosed/);
});

test("release 1.5.18 retains 1.5.2 peak-hour copy, holiday Monday and gate filter", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.2/);
  assert.match(readme, /Public-holiday Monday/);
  assert.match(html, /id="copy-peak-hour"/);
  assert.match(html, /id="gantt-gate-filter"/);
  assert.match(html, /data-preset="publicHolidayMonday"/);
  assert.match(html, /id="copy-closed-hours"/);
  assert.match(html, /id="queue-backlog-only"/);
  assert.match(html, /event\.key === "c"/);
  assert.match(html, /event\.key === "t"/);
  assert.match(html, /id="copy-cohort-markdown"/);
  assert.match(html, /id="peak-queue-hour-value"/);
  assert.match(html, /queueBacklogOnly/);
});

test("release 1.5.18 retains 1.5.1 Gantt hour copy, payday burst, dashboard CSV and timing review", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const html = await buildStandalone();
    assert.equal(pkg.version, "1.5.31");
  assert.match(readme, /New in v1\.5\.1/);
  assert.match(readme, /New in v1\.5\.0/);
  assert.match(readme, /Payday Friday burst/);
  assert.match(html, /id="copy-gantt-hour"/);
  assert.match(html, /event\.key === "f"/);
  assert.match(html, /id="gantt-closed-only"/);
  assert.match(html, /id="compare-three-scenario-files"/);
  assert.match(html, /data-preset="paydayFridayBurst"/);
  assert.match(html, /event\.key === "s"/);
  assert.match(html, /id="export-dashboard-csv"/);
  assert.match(html, /ganttClosedOnly/);
  assert.match(html, /id="print-redacted"/);
  assert.match(html, /id="copy-bottleneck-markdown"/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /replayWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
  assert.match(html, /id="copy-dashboard-markdown"/);
  assert.match(html, /id="compare-scenario-files"/);
  assert.match(html, /data-preset="compressedFridayClose"/);
});
