import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { buildStandalone, isStandaloneCurrent, standaloneCsp } from "../scripts/build-standalone.mjs";

test("standalone build is self-contained, LF-only, and deterministic", async () => {
  const first = await buildStandalone();
  const second = await buildStandalone();
  assert.equal(first, second);
  assert.equal(isStandaloneCurrent(first, second), true);
  assert.equal(isStandaloneCurrent(first.replace(/\n/g, "\r\n"), second), true);
  assert.equal(isStandaloneCurrent("stale", second), false);
  assert.match(first, /data-weekend-gap-standalone="true"/);
  assert.match(first, /Sharing unavailable in standalone file/);
  assert.match(first, /A\$\$\{/);
  assert.match(first, new RegExp(`<meta http-equiv="Content-Security-Policy" content="${standaloneCsp}">`));
  assert.doesNotMatch(first, /(?:script|style)-src[^\"]*(?:'self'|https?:|data:|blob:)/);
  assert.doesNotMatch(first, /src="src\/app\.js"|href="styles\.css"|href="MODEL\.md"/);
  assert.doesNotMatch(first, /\r/);
});

test("release 1.5.7 ships Friday late FX close, settlement comma copy and closed Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.7");
  assert.match(readme, /New in v1\.5\.7/);
  assert.match(changelog, /1\.5\.7/);
  assert.match(html, /event\.key === ","/);
  assert.match(html, /id="copy-hours-to-first-settlement"/);
  assert.match(html, /event\.key === "\."/);
  assert.match(html, /id="copy-first-closed-fx"/);
  assert.match(html, /event\.key === "\/"/);
  assert.match(html, /id="copy-remaining-reserve"/);
  assert.match(html, /data-preset="fridayLateFxClose"/);
  assert.match(html, /hideClosedGanttHours/);
  assert.match(html, /id="gantt-hide-closed"/);
  assert.match(html, /id="first-closed-fx-hour-line"/);
  assert.match(html, /id="copy-hours-to-clear"/);
  assert.match(html, /The first closed FX hour label stays on the printed brief/);
});

test("release 1.5.7 retains 1.5.6 early Monday bank, settlement jump and weekend Gantt hide", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.7");
  assert.match(readme, /New in v1\.5\.6/);
  assert.match(changelog, /1\.5\.6/);
  assert.match(html, /event\.key === "y"/);
  assert.match(html, /id="hours-to-first-settlement-line"/);
  assert.match(html, /event\.key === "z"/);
  assert.match(html, /id="copy-remaining-reserve"/);
  assert.match(html, /data-preset="earlyMondayBankOpen"/);
  assert.match(html, /hideWeekendGanttHours/);
  assert.match(html, /id="gantt-hide-weekends"/);
  assert.match(html, /id="copy-first-closed-fx"/);
  assert.match(html, /firstClosedFxHourToMarkdown/);
  assert.match(html, /Hours to first settlement stay on the printed brief/);
});

test("release 1.5.7 retains 1.5.5 thin Saturday FX, settlement copy and issuer jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.7");
  assert.match(readme, /New in v1\.5\.5/);
  assert.match(changelog, /1\.5\.5/);
  assert.match(html, /event\.key === "i"/);
  assert.match(html, /id="gantt-issuer-row"/);
  assert.match(html, /event\.key === "l"/);
  assert.match(html, /id="copy-hours-to-first-settlement"/);
  assert.match(html, /event\.key === "o"/);
  assert.match(html, /id="gantt-payout-row"/);
  assert.match(html, /event\.key === "v"/);
  assert.match(html, /id="copy-selected-versus-peak"/);
  assert.match(html, /data-preset="thinSaturdayFx"/);
  assert.match(html, /hideOpenGanttHours/);
  assert.match(html, /id="gantt-hide-open"/);
  assert.match(html, /id="copy-next-payout"/);
  assert.match(html, /hoursToFirstSettlementToMarkdown/);
  assert.match(html, /selectedVersusPeakHourToMarkdown/);
  assert.match(html, /nextPayoutHourToMarkdown/);
  assert.match(html, /ganttHourOpenOnEveryGate/);
});

test("release 1.5.7 retains 1.5.4 Sunday stall close, reserve copy and weekend Gantt filter", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.7");
  assert.match(readme, /New in v1\.5\.4/);
  assert.match(changelog, /1\.5\.4/);
  assert.match(html, /event\.key === "k"/);
  assert.match(html, /id="hours-to-clear-line"/);
  assert.match(html, /event\.key === "n"/);
  assert.match(html, /id="gantt-first-payout-marker"/);
  assert.match(html, /event\.key === "a"/);
  assert.match(html, /id="analysis-export-controls"/);
  assert.match(html, /event\.key === "w"/);
  assert.match(html, /id="gantt-fx-row"/);
  assert.match(html, /id="copy-remaining-reserve"/);
  assert.match(html, /data-preset="sundayStallClose"/);
  assert.match(html, /hideWeekdayGanttHours/);
  assert.match(html, /id="gantt-hide-weekdays"/);
  assert.match(html, /id="selected-gantt-hour-line"/);
  assert.match(html, /id="copy-weekend-fx-counts"/);
});

test("release 1.5.7 retains 1.5.3 hours-to-clear copy, Saturday market and hour persist", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.7");
  assert.match(readme, /New in v1\.5\.3/);
  assert.match(readme, /Saturday market burst/);
  assert.match(html, /id="copy-hours-to-clear"/);
  assert.match(html, /event\.key === "h"/);
  assert.match(html, /data-preset="saturdayMarketBurst"/);
  assert.match(html, /event\.key === "x"/);
  assert.match(html, /ganttHourIndex/);
  assert.match(html, /event\.key === "b"/);
  assert.match(html, /id="copy-fx-hours"/);
  assert.match(html, /event\.key === "m"/);
  assert.match(html, /id="hours-to-clear-line"/);
  assert.match(html, /id="gantt-every-closed"/);
  assert.match(html, /ganttEveryGateClosed/);
});

test("release 1.5.7 retains 1.5.2 peak-hour copy, holiday Monday and gate filter", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.7");
  assert.match(readme, /New in v1\.5\.2/);
  assert.match(readme, /Public-holiday Monday/);
  assert.match(html, /id="copy-peak-hour"/);
  assert.match(html, /id="gantt-gate-filter"/);
  assert.match(html, /data-preset="publicHolidayMonday"/);
  assert.match(html, /id="copy-closed-hours"/);
  assert.match(html, /id="queue-backlog-only"/);
  assert.match(html, /event\.key === "c"/);
  assert.match(html, /event\.key === "t"/);
  assert.match(html, /id="copy-cohort-markdown"/);
  assert.match(html, /id="peak-queue-hour-value"/);
  assert.match(html, /queueBacklogOnly/);
});

test("release 1.5.7 retains 1.5.1 Gantt hour copy, payday burst, dashboard CSV and timing review", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const html = await buildStandalone();
  assert.equal(pkg.version, "1.5.7");
  assert.match(readme, /New in v1\.5\.1/);
  assert.match(readme, /New in v1\.5\.0/);
  assert.match(readme, /Payday Friday burst/);
  assert.match(html, /id="copy-gantt-hour"/);
  assert.match(html, /event\.key === "f"/);
  assert.match(html, /id="gantt-closed-only"/);
  assert.match(html, /id="compare-three-scenario-files"/);
  assert.match(html, /data-preset="paydayFridayBurst"/);
  assert.match(html, /event\.key === "s"/);
  assert.match(html, /id="export-dashboard-csv"/);
  assert.match(html, /ganttClosedOnly/);
  assert.match(html, /id="print-redacted"/);
  assert.match(html, /id="copy-bottleneck-markdown"/);
  assert.match(html, /id="weekend-review"/);
  assert.match(html, /createWeekendReviewPacket/);
  assert.match(html, /replayWeekendReviewPacket/);
  assert.match(html, /WEEKEND_REVIEW_TOOLS/);
  assert.match(html, /id="copy-dashboard-markdown"/);
  assert.match(html, /id="compare-scenario-files"/);
  assert.match(html, /data-preset="compressedFridayClose"/);
});
