import test from "node:test";
import assert from "node:assert/strict";
import { DEFAULT_SCENARIO, PRESETS, workspaceToJSON, workspaceFromJSON, scenarioFromJSON } from "../src/model.js";
test("workspace round trip preserves detached baseline, notes and analysis controls",()=>{
 const text=workspaceToJSON(PRESETS.marketStress,DEFAULT_SCENARIO,{notes:"<b>test</b>",selectedHour:65,targetPercent:75,deadlineHour:70,ganttDensity:"all"});
 const result=workspaceFromJSON(text);assert.deepEqual(result.errors,[]);assert.equal(result.workspace.baseline.name,"Normal Friday");
 assert.equal(result.workspace.current.name,"Market Stress");assert.equal(result.workspace.selectedHour,65);assert.equal(result.workspace.ganttHourIndex,65);assert.equal(result.workspace.notes,"<b>test</b>");
 assert.equal(result.workspace.ganttDensity,"all");
 assert.equal(result.workspace.selectedChart,"queue");
 assert.equal(result.workspace.ganttClosedOnly,false);
 assert.equal(result.workspace.ganttGateFilter,"all");
 assert.equal(result.workspace.queueBacklogOnly,false);
 assert.equal(result.workspace.ganttEveryGateClosed,false);
 assert.equal(result.workspace.hideWeekdayGanttHours,false);
 assert.equal(result.workspace.hideWeekendGanttHours,false);
 assert.equal(result.workspace.hideOpenGanttHours,false);
 assert.equal(scenarioFromJSON(text).scenario,null);assert.deepEqual(workspaceFromJSON("\uFEFF"+text),result);
});
test("workspace Gantt density defaults to snapshots and older files remain valid",()=>{
 const omitted=workspaceToJSON(DEFAULT_SCENARIO,DEFAULT_SCENARIO,{notes:"legacy"});
 const restored=workspaceFromJSON(omitted);
 assert.equal(restored.workspace.ganttDensity,"snapshots");
 const raw=JSON.parse(omitted);
 delete raw.ganttDensity;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.ganttDensity,"snapshots");
 assert.deepEqual(legacy.errors,[]);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,ganttDensity:"open"})).workspace.ganttDensity,"open");
});
test("older workspace files omit selectedHour and restore hour zero",()=>{
 const text=workspaceToJSON(PRESETS.weekendRush,DEFAULT_SCENARIO,{selectedHour:21,notes:"legacy hour"});
 const raw=JSON.parse(text);
 assert.equal(raw.selectedHour,21);
 delete raw.selectedHour;
 delete raw.ganttHourIndex;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.selectedHour,0);
 assert.equal(legacy.workspace.ganttHourIndex,0);
 assert.deepEqual(legacy.errors,[]);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,selectedHour:65})).workspace.selectedHour,65);
});
test("older workspace files omit selectedChart and restore the queue chart",()=>{
 const text=workspaceToJSON(DEFAULT_SCENARIO,DEFAULT_SCENARIO,{selectedChart:"gantt",notes:"legacy chart"});
 const raw=JSON.parse(text);
 assert.equal(raw.selectedChart,"gantt");
 delete raw.selectedChart;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.selectedChart,"queue");
 assert.deepEqual(legacy.errors,[]);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,selectedChart:"gantt"})).workspace.selectedChart,"gantt");
});
test("older workspace files omit ganttClosedOnly and restore all hours",()=>{
 const text=workspaceToJSON(DEFAULT_SCENARIO,DEFAULT_SCENARIO,{ganttClosedOnly:true,notes:"legacy filter"});
 const raw=JSON.parse(text);
 assert.equal(raw.ganttClosedOnly,true);
 delete raw.ganttClosedOnly;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.ganttClosedOnly,false);
 assert.deepEqual(legacy.errors,[]);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,ganttClosedOnly:true})).workspace.ganttClosedOnly,true);
});
test("older workspace files omit ganttGateFilter and restore all gates",()=>{
 const text=workspaceToJSON(DEFAULT_SCENARIO,DEFAULT_SCENARIO,{ganttGateFilter:"bank",notes:"legacy gate filter"});
 const raw=JSON.parse(text);
 assert.equal(raw.ganttGateFilter,"bank");
 delete raw.ganttGateFilter;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.ganttGateFilter,"all");
 assert.deepEqual(legacy.errors,[]);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,ganttGateFilter:"fx"})).workspace.ganttGateFilter,"fx");
});
test("older workspace files omit queueBacklogOnly and restore all hours",()=>{
 const text=workspaceToJSON(DEFAULT_SCENARIO,DEFAULT_SCENARIO,{queueBacklogOnly:true,notes:"legacy backlog filter"});
 const raw=JSON.parse(text);
 assert.equal(raw.queueBacklogOnly,true);
 delete raw.queueBacklogOnly;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.queueBacklogOnly,false);
 assert.deepEqual(legacy.errors,[]);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,queueBacklogOnly:true})).workspace.queueBacklogOnly,true);
});
test("older workspace files omit ganttHourIndex and restore the selected hour default",()=>{
 const text=workspaceToJSON(PRESETS.weekendRush,DEFAULT_SCENARIO,{selectedHour:21,ganttHourIndex:21,notes:"legacy gantt hour"});
 const raw=JSON.parse(text);
 assert.equal(raw.ganttHourIndex,21);
 delete raw.ganttHourIndex;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.ganttHourIndex,21);
 assert.equal(legacy.workspace.selectedHour,21);
 assert.deepEqual(legacy.errors,[]);
 const neither=JSON.parse(text);
 delete neither.ganttHourIndex;
 delete neither.selectedHour;
 assert.equal(workspaceFromJSON(JSON.stringify(neither)).workspace.ganttHourIndex,0);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,ganttHourIndex:65,selectedHour:65})).workspace.ganttHourIndex,65);
});
test("older workspace files omit ganttEveryGateClosed and restore all hours",()=>{
 const text=workspaceToJSON(DEFAULT_SCENARIO,DEFAULT_SCENARIO,{ganttEveryGateClosed:true,notes:"legacy every-closed filter"});
 const raw=JSON.parse(text);
 assert.equal(raw.ganttEveryGateClosed,true);
 delete raw.ganttEveryGateClosed;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.ganttEveryGateClosed,false);
 assert.deepEqual(legacy.errors,[]);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,ganttEveryGateClosed:true})).workspace.ganttEveryGateClosed,true);
});
test("older workspace files omit hideWeekdayGanttHours and restore all hours",()=>{
 const text=workspaceToJSON(DEFAULT_SCENARIO,DEFAULT_SCENARIO,{hideWeekdayGanttHours:true,notes:"legacy weekday filter"});
 const raw=JSON.parse(text);
 assert.equal(raw.hideWeekdayGanttHours,true);
 delete raw.hideWeekdayGanttHours;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.hideWeekdayGanttHours,false);
 assert.deepEqual(legacy.errors,[]);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,hideWeekdayGanttHours:true})).workspace.hideWeekdayGanttHours,true);
});
test("older workspace files omit hideWeekendGanttHours and restore all hours",()=>{
 const text=workspaceToJSON(DEFAULT_SCENARIO,DEFAULT_SCENARIO,{hideWeekendGanttHours:true,notes:"legacy weekend filter"});
 const raw=JSON.parse(text);
 assert.equal(raw.hideWeekendGanttHours,true);
 delete raw.hideWeekendGanttHours;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.hideWeekendGanttHours,false);
 assert.deepEqual(legacy.errors,[]);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,hideWeekendGanttHours:true})).workspace.hideWeekendGanttHours,true);
});
test("older workspace files omit hideOpenGanttHours and restore all hours",()=>{
 const text=workspaceToJSON(DEFAULT_SCENARIO,DEFAULT_SCENARIO,{hideOpenGanttHours:true,notes:"legacy open-hour filter"});
 const raw=JSON.parse(text);
 assert.equal(raw.hideOpenGanttHours,true);
 delete raw.hideOpenGanttHours;
 const legacy=workspaceFromJSON(JSON.stringify(raw));
 assert.ok(legacy.workspace);
 assert.equal(legacy.workspace.hideOpenGanttHours,false);
 assert.deepEqual(legacy.errors,[]);
 assert.equal(workspaceFromJSON(JSON.stringify({...raw,hideOpenGanttHours:true})).workspace.hideOpenGanttHours,true);
});
test("invalid workspace controls and format cannot replace an active workspace",()=>{
 const valid=JSON.parse(workspaceToJSON(DEFAULT_SCENARIO,DEFAULT_SCENARIO));
 for(const changed of [{version:2},{current:null},{baseline:[]},{targetPercent:-1},{deadlineHour:73},{selectedHour:1.5},{ganttHourIndex:1.5},{notes:"x".repeat(4001)},{ganttDensity:"wide"},{selectedChart:"canvas"},{ganttClosedOnly:"yes"},{ganttGateFilter:"issuer-only"},{queueBacklogOnly:"yes"},{ganttEveryGateClosed:"yes"},{hideWeekdayGanttHours:"yes"},{hideWeekendGanttHours:"yes"},{hideOpenGanttHours:"yes"},{extraField:true},{constructor:{}}]) assert.equal(workspaceFromJSON(JSON.stringify({...valid,...changed})).workspace,null);
 assert.equal(workspaceFromJSON("x".repeat(250001)).workspace,null);
});
