import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("bottle-hand cycling club hours keeps remaining 31 / 33 / 83 after domestique", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const bottleHandStart = app.indexOf('"bottle-hand-cycling-club-hours"');
  const bottleHandEnd = app.indexOf("let agreementReviewPacket", bottleHandStart);
  const bottleHand = app.slice(bottleHandStart, bottleHandEnd === -1 ? undefined : bottleHandEnd);
  const domestiqueStart = app.indexOf('"domestique-cycling-club-hours"');
  const domestique = app.slice(domestiqueStart, bottleHandStart);
  const soigneurStart = app.indexOf('"soigneur-cycling-club-hours"');
  const soigneur = app.slice(soigneurStart, domestiqueStart);
  assert.ok(bottleHandStart > domestiqueStart);
  assert.ok(domestiqueStart > soigneurStart);
  assert.match(bottleHand, /weight: 31/);
  assert.match(bottleHand, /weight: 33/);
  assert.match(bottleHand, /Car-window hours/);
  assert.match(bottleHand, /Crate-lock lock-up/);
  assert.match(bottleHand, /crate crew at the crate-lock shed/);
  assert.match(bottleHand, /12:10/);
  assert.match(bottleHand, /20:55/);
  assert.match(bottleHand, /16:05/);
  assert.doesNotMatch(bottleHand, /wheel-change/);
  assert.doesNotMatch(bottleHand, /Neutral-service hours/);
  assert.doesNotMatch(bottleHand, /Team-car lock-up/);
  assert.doesNotMatch(bottleHand, /team-car/);
  assert.doesNotMatch(bottleHand, /car crew/);
  assert.doesNotMatch(bottleHand, /soigneur-station/);
  assert.doesNotMatch(bottleHand, /cape-bag/);
  assert.doesNotMatch(bottleHand, /rice-cake/);
  assert.doesNotMatch(bottleHand, /cake crew/);
  assert.doesNotMatch(bottleHand, /train-line/);
  assert.doesNotMatch(bottleHand, /last-rider/);
  assert.doesNotMatch(bottleHand, /sprinter-launch/);
  assert.doesNotMatch(bottleHand, /launch crew/);
  assert.doesNotMatch(bottleHand, /musette-line/);
  assert.doesNotMatch(bottleHand, /sticky-bottle/);
  assert.doesNotMatch(bottleHand, /bottle-hand-up/);
  assert.doesNotMatch(bottleHand, /bottle crew/);
  assert.doesNotMatch(bottleHand, /treatment-tent/);
  assert.doesNotMatch(bottleHand, /ice-pack-rota/);
  assert.doesNotMatch(bottleHand, /triage-board/);
  assert.doesNotMatch(bottleHand, /ice-pack crew/);
  assert.doesNotMatch(bottleHand, /start-gate/);
  assert.doesNotMatch(bottleHand, /flying-relay/);
  assert.doesNotMatch(bottleHand, /trio-board/);
  assert.doesNotMatch(bottleHand, /relay crew/);
  assert.doesNotMatch(bottleHand, /team-pursuit-rota/);
  assert.doesNotMatch(bottleHand, /changeover-bell/);
  assert.doesNotMatch(bottleHand, /quartet-board/);
  assert.doesNotMatch(bottleHand, /changeover crew/);
  assert.doesNotMatch(bottleHand, /pursuit-line/);
  assert.doesNotMatch(bottleHand, /catch-bell/);
  assert.doesNotMatch(bottleHand, /pursuit-chip/);
  assert.doesNotMatch(bottleHand, /pursuit crew/);
  assert.doesNotMatch(bottleHand, /12:00/);
  assert.doesNotMatch(bottleHand, /20:45/);
  assert.doesNotMatch(bottleHand, /15:55/);
  assert.doesNotMatch(bottleHand, /11:50/);
  assert.doesNotMatch(bottleHand, /20:35/);
  assert.doesNotMatch(bottleHand, /15:45/);
  assert.match(domestique, /weight: 30/);
  assert.match(domestique, /weight: 32/);
  assert.match(domestique, /Neutral-service hours/);
  assert.match(domestique, /Team-car lock-up/);
  assert.doesNotMatch(domestique, /Bidon-pass/);
  assert.doesNotMatch(domestique, /Car-window hours/);
  assert.doesNotMatch(domestique, /Crate-lock lock-up/);
  assert.match(soigneur, /weight: 29/);
  assert.match(soigneur, /weight: 31/);
  assert.match(soigneur, /Cape-bag hours/);
  assert.doesNotMatch(soigneur, /Bidon-pass/);
  assert.doesNotMatch(soigneur, /Car-window hours/);
});
