import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("bottle-hand cycling club hours remaining 31 / 33 / 83 is distinct from domestique 30 / 32 / 81", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const bottleHandStart = app.indexOf('"bottle-hand-cycling-club-hours"');
  const bottleHandEnd = app.indexOf("let agreementReviewPacket", bottleHandStart);
  const bottleHand = app.slice(bottleHandStart, bottleHandEnd === -1 ? undefined : bottleHandEnd);
  const domestiqueStart = app.indexOf('"domestique-cycling-club-hours"');
  const domestique = app.slice(domestiqueStart, bottleHandStart);
  const soigneurStart = app.indexOf('"soigneur-cycling-club-hours"');
  const soigneur = app.slice(soigneurStart, domestiqueStart);
  const leadOutStart = app.indexOf('"lead-out-cycling-club-hours"');
  const leadOut = app.slice(leadOutStart, soigneurStart);
  const feedZoneStart = app.indexOf('"feed-zone-cycling-club-hours"');
  const feedZone = app.slice(feedZoneStart, leadOutStart);
  const firstAidStart = app.indexOf('"first-aid-cycling-club-hours"');
  const firstAid = app.slice(firstAidStart, feedZoneStart);
  const sprintStart = app.indexOf('"team-sprint-cycling-club-hours"');
  const sprint = app.slice(sprintStart, firstAidStart);
  const teamStart = app.indexOf('"team-pursuit-cycling-club-hours"');
  const team = app.slice(teamStart, sprintStart);
  const pursuitStart = app.indexOf('"individual-pursuit-cycling-club-hours"');
  const pursuit = app.slice(pursuitStart, teamStart);
  const scratchStart = app.indexOf('"scratch-cycling-club-hours"');
  const scratch = app.slice(scratchStart, pursuitStart);
  assert.ok(bottleHandStart > domestiqueStart);
  assert.ok(domestiqueStart > soigneurStart);
  assert.ok(soigneurStart > leadOutStart);
  assert.ok(leadOutStart > feedZoneStart);
  assert.ok(feedZoneStart > firstAidStart);
  assert.ok(firstAidStart > sprintStart);
  assert.ok(sprintStart > teamStart);
  assert.ok(teamStart > pursuitStart);
  assert.match(bottleHand, /weight: 31/);
  assert.match(bottleHand, /weight: 33/);
  assert.match(bottleHand, /crate crew at the crate-lock shed/);
  assert.match(domestique, /weight: 30/);
  assert.match(domestique, /weight: 32/);
  assert.match(domestique, /car crew at the team-car shed/);
  assert.match(soigneur, /weight: 29/);
  assert.match(soigneur, /weight: 31/);
  assert.match(soigneur, /cake crew at the rice-cake shed/);
  assert.match(leadOut, /weight: 28/);
  assert.match(leadOut, /weight: 30/);
  assert.match(leadOut, /launch crew at the sprinter-launch shed/);
  assert.match(feedZone, /weight: 27/);
  assert.match(feedZone, /weight: 29/);
  assert.match(feedZone, /bottle crew at the bottle-hand-up shed/);
  assert.match(firstAid, /weight: 26/);
  assert.match(firstAid, /weight: 28/);
  assert.match(firstAid, /ice-pack crew at the triage-board shed/);
  assert.match(sprint, /weight: 25/);
  assert.match(sprint, /weight: 27/);
  assert.match(sprint, /relay crew at the trio-board shed/);
  assert.match(team, /weight: 24/);
  assert.match(team, /weight: 26/);
  assert.match(team, /changeover crew at the quartet-board shed/);
  assert.match(pursuit, /weight: 23/);
  assert.match(pursuit, /weight: 25/);
  assert.match(scratch, /weight: 22/);
  assert.match(scratch, /weight: 24/);
  assert.notEqual(bottleHand.match(/weight: 31/)?.[0], domestique.match(/weight: 30/)?.[0]);
  assert.notEqual(bottleHand.match(/weight: 33/)?.[0], domestique.match(/weight: 32/)?.[0]);
  assert.doesNotMatch(bottleHand, /wheel-change/);
  assert.doesNotMatch(bottleHand, /Neutral-service hours/);
  assert.doesNotMatch(bottleHand, /Team-car lock-up/);
  assert.doesNotMatch(bottleHand, /team-car/);
  assert.doesNotMatch(bottleHand, /soigneur-station/);
  assert.doesNotMatch(bottleHand, /cape-bag/);
  assert.doesNotMatch(bottleHand, /rice-cake/);
  assert.doesNotMatch(bottleHand, /train-line/);
  assert.doesNotMatch(bottleHand, /last-rider/);
  assert.doesNotMatch(bottleHand, /sprinter-launch/);
  assert.doesNotMatch(bottleHand, /musette-line/);
  assert.doesNotMatch(bottleHand, /sticky-bottle/);
  assert.doesNotMatch(bottleHand, /bottle-hand-up/);
  assert.doesNotMatch(bottleHand, /treatment-tent/);
  assert.doesNotMatch(bottleHand, /ice-pack-rota/);
  assert.doesNotMatch(bottleHand, /triage-board/);
  assert.doesNotMatch(domestique, /Bidon-pass/);
  assert.doesNotMatch(domestique, /Car-window hours/);
  assert.doesNotMatch(domestique, /Crate-lock lock-up/);
  assert.doesNotMatch(soigneur, /Bidon-pass/);
  assert.doesNotMatch(soigneur, /Car-window hours/);
  assert.doesNotMatch(leadOut, /Bidon-pass/);
  assert.doesNotMatch(feedZone, /Bidon-pass/);
  assert.doesNotMatch(firstAid, /Bidon-pass/);
  assert.doesNotMatch(sprint, /Bidon-pass/);
  assert.doesNotMatch(team, /Bidon-pass/);
  assert.doesNotMatch(pursuit, /Bidon-pass/);
  assert.doesNotMatch(scratch, /Bidon-pass/);
});
