import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("domestique cycling club hours remaining 30 / 32 / 81 is distinct from soigneur 29 / 31 / 79", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const domestiqueStart = app.indexOf('"domestique-cycling-club-hours"');
  const bottleHandStart = app.indexOf('"bottle-hand-cycling-club-hours"');
  const domestiqueEnd = bottleHandStart;
  const domestique = app.slice(domestiqueStart, domestiqueEnd === -1 ? undefined : domestiqueEnd);
  const soigneurStart = app.indexOf('"soigneur-cycling-club-hours"');
  const soigneur = app.slice(soigneurStart, domestiqueStart);
  const leadOutStart = app.indexOf('"lead-out-cycling-club-hours"');
  const leadOut = app.slice(leadOutStart, soigneurStart);
  const feedZoneStart = app.indexOf('"feed-zone-cycling-club-hours"');
  const feedZone = app.slice(feedZoneStart, leadOutStart);
  const firstAidStart = app.indexOf('"first-aid-cycling-club-hours"');
  const firstAid = app.slice(firstAidStart, feedZoneStart);
  const sprintStart = app.indexOf('"team-sprint-cycling-club-hours"');
  const sprint = app.slice(sprintStart, firstAidStart);
  const teamStart = app.indexOf('"team-pursuit-cycling-club-hours"');
  const team = app.slice(teamStart, sprintStart);
  const pursuitStart = app.indexOf('"individual-pursuit-cycling-club-hours"');
  const pursuit = app.slice(pursuitStart, teamStart);
  const scratchStart = app.indexOf('"scratch-cycling-club-hours"');
  const scratch = app.slice(scratchStart, pursuitStart);
  assert.ok(bottleHandStart > domestiqueStart);
  assert.ok(domestiqueStart > soigneurStart);
  assert.ok(soigneurStart > leadOutStart);
  assert.ok(leadOutStart > feedZoneStart);
  assert.ok(feedZoneStart > firstAidStart);
  assert.ok(firstAidStart > sprintStart);
  assert.ok(sprintStart > teamStart);
  assert.ok(teamStart > pursuitStart);
  assert.match(domestique, /weight: 30/);
  assert.match(domestique, /weight: 32/);
  assert.match(domestique, /car crew at the team-car shed/);
  assert.match(soigneur, /weight: 29/);
  assert.match(soigneur, /weight: 31/);
  assert.match(soigneur, /cake crew at the rice-cake shed/);
  assert.match(leadOut, /weight: 28/);
  assert.match(leadOut, /weight: 30/);
  assert.match(leadOut, /launch crew at the sprinter-launch shed/);
  assert.match(feedZone, /weight: 27/);
  assert.match(feedZone, /weight: 29/);
  assert.match(feedZone, /bottle crew at the bottle-hand-up shed/);
  assert.match(firstAid, /weight: 26/);
  assert.match(firstAid, /weight: 28/);
  assert.match(firstAid, /ice-pack crew at the triage-board shed/);
  assert.match(sprint, /weight: 25/);
  assert.match(sprint, /weight: 27/);
  assert.match(sprint, /relay crew at the trio-board shed/);
  assert.match(team, /weight: 24/);
  assert.match(team, /weight: 26/);
  assert.match(team, /changeover crew at the quartet-board shed/);
  assert.match(pursuit, /weight: 23/);
  assert.match(pursuit, /weight: 25/);
  assert.match(scratch, /weight: 22/);
  assert.match(scratch, /weight: 24/);
  assert.notEqual(domestique.match(/weight: 30/)?.[0], soigneur.match(/weight: 29/)?.[0]);
  assert.notEqual(domestique.match(/weight: 32/)?.[0], soigneur.match(/weight: 31/)?.[0]);
  assert.doesNotMatch(domestique, /soigneur-station/);
  assert.doesNotMatch(domestique, /cape-bag/);
  assert.doesNotMatch(domestique, /rice-cake/);
  assert.doesNotMatch(domestique, /train-line/);
  assert.doesNotMatch(domestique, /last-rider/);
  assert.doesNotMatch(domestique, /sprinter-launch/);
  assert.doesNotMatch(domestique, /musette-line/);
  assert.doesNotMatch(domestique, /sticky-bottle/);
  assert.doesNotMatch(domestique, /bottle-hand-up/);
  assert.doesNotMatch(domestique, /bidon-pass/);
  assert.doesNotMatch(domestique, /Car-window hours/);
  assert.doesNotMatch(domestique, /Crate-lock lock-up/);
  assert.doesNotMatch(domestique, /treatment-tent/);
  assert.doesNotMatch(domestique, /ice-pack-rota/);
  assert.doesNotMatch(domestique, /triage-board/);
  assert.doesNotMatch(soigneur, /Neutral-service hours/);
  assert.doesNotMatch(soigneur, /Team-car lock-up/);
  assert.doesNotMatch(leadOut, /Neutral-service hours/);
  assert.doesNotMatch(leadOut, /Team-car lock-up/);
  assert.doesNotMatch(feedZone, /Neutral-service hours/);
  assert.doesNotMatch(firstAid, /Neutral-service hours/);
  assert.doesNotMatch(sprint, /Neutral-service hours/);
  assert.doesNotMatch(team, /Neutral-service hours/);
  assert.doesNotMatch(pursuit, /Neutral-service hours/);
  assert.doesNotMatch(scratch, /Neutral-service hours/);
});
