import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("domestique cycling club hours keeps remaining 30 / 32 / 81 after soigneur", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const domestiqueStart = app.indexOf('"domestique-cycling-club-hours"');
  const bottleHandStart = app.indexOf('"bottle-hand-cycling-club-hours"');
  const domestiqueEnd = bottleHandStart;
  const domestique = app.slice(domestiqueStart, domestiqueEnd === -1 ? undefined : domestiqueEnd);
  const soigneurStart = app.indexOf('"soigneur-cycling-club-hours"');
  const soigneur = app.slice(soigneurStart, domestiqueStart);
  assert.ok(bottleHandStart > domestiqueStart);
  assert.ok(domestiqueStart > soigneurStart);
  assert.match(domestique, /weight: 30/);
  assert.match(domestique, /weight: 32/);
  assert.match(domestique, /Neutral-service hours/);
  assert.match(domestique, /Team-car lock-up/);
  assert.match(domestique, /car crew at the team-car shed/);
  assert.match(domestique, /12:00/);
  assert.match(domestique, /20:45/);
  assert.match(domestique, /15:55/);
  assert.doesNotMatch(domestique, /soigneur-station/);
  assert.doesNotMatch(domestique, /cape-bag/);
  assert.doesNotMatch(domestique, /rice-cake/);
  assert.doesNotMatch(domestique, /cake crew/);
  assert.doesNotMatch(domestique, /train-line/);
  assert.doesNotMatch(domestique, /last-rider/);
  assert.doesNotMatch(domestique, /sprinter-launch/);
  assert.doesNotMatch(domestique, /launch crew/);
  assert.doesNotMatch(domestique, /musette-line/);
  assert.doesNotMatch(domestique, /sticky-bottle/);
  assert.doesNotMatch(domestique, /bottle-hand-up/);
  assert.doesNotMatch(domestique, /bidon-pass/);
  assert.doesNotMatch(domestique, /Car-window hours/);
  assert.doesNotMatch(domestique, /Crate-lock lock-up/);
  assert.doesNotMatch(domestique, /bottle crew/);
  assert.doesNotMatch(domestique, /treatment-tent/);
  assert.doesNotMatch(domestique, /ice-pack-rota/);
  assert.doesNotMatch(domestique, /triage-board/);
  assert.doesNotMatch(domestique, /ice-pack crew/);
  assert.doesNotMatch(domestique, /start-gate/);
  assert.doesNotMatch(domestique, /flying-relay/);
  assert.doesNotMatch(domestique, /trio-board/);
  assert.doesNotMatch(domestique, /relay crew/);
  assert.doesNotMatch(domestique, /team-pursuit-rota/);
  assert.doesNotMatch(domestique, /changeover-bell/);
  assert.doesNotMatch(domestique, /quartet-board/);
  assert.doesNotMatch(domestique, /changeover crew/);
  assert.doesNotMatch(domestique, /start-ramp/);
  assert.doesNotMatch(domestique, /time-check/);
  assert.doesNotMatch(domestique, /timing-hut/);
  assert.doesNotMatch(domestique, /pit-lane/);
  assert.doesNotMatch(domestique, /sealed-road/);
  assert.doesNotMatch(domestique, /circuit/);
  assert.doesNotMatch(domestique, /banked-boards/);
  assert.doesNotMatch(domestique, /summit-marshal/);
  assert.doesNotMatch(domestique, /hairpin/);
  assert.doesNotMatch(domestique, /climb-chip/);
  assert.doesNotMatch(domestique, /derny-pacer/);
  assert.doesNotMatch(domestique, /keirin-chip/);
  assert.doesNotMatch(domestique, /keirin-gate/);
  assert.doesNotMatch(domestique, /madison-pair/);
  assert.doesNotMatch(domestique, /handsling/);
  assert.doesNotMatch(domestique, /pairing crew/);
  assert.doesNotMatch(domestique, /flying-200/);
  assert.doesNotMatch(domestique, /tempo-board/);
  assert.doesNotMatch(domestique, /omnium-board/);
  assert.doesNotMatch(domestique, /elimination-heat/);
  assert.doesNotMatch(domestique, /tempo-lap/);
  assert.doesNotMatch(domestique, /tempo crew/);
  assert.doesNotMatch(domestique, /points-race/);
  assert.doesNotMatch(domestique, /points-sprint/);
  assert.doesNotMatch(domestique, /bell-lap/);
  assert.doesNotMatch(domestique, /prime-board/);
  assert.doesNotMatch(domestique, /bell crew/);
  assert.doesNotMatch(domestique, /scratch-bunch/);
  assert.doesNotMatch(domestique, /bunch-finish/);
  assert.doesNotMatch(domestique, /scratch-chip/);
  assert.doesNotMatch(domestique, /bunch crew/);
  assert.doesNotMatch(domestique, /pursuit-line/);
  assert.doesNotMatch(domestique, /catch-bell/);
  assert.doesNotMatch(domestique, /pursuit-chip/);
  assert.doesNotMatch(domestique, /pursuit crew/);
  assert.doesNotMatch(domestique, /11:50/);
  assert.doesNotMatch(domestique, /20:35/);
  assert.doesNotMatch(domestique, /15:45/);
  assert.match(soigneur, /weight: 29/);
  assert.match(soigneur, /weight: 31/);
  assert.match(soigneur, /Cape-bag hours/);
  assert.doesNotMatch(soigneur, /Neutral-service hours/);
  assert.doesNotMatch(soigneur, /Team-car lock-up/);
});
