import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("feed-zone cycling club hours keeps remaining 27 / 29 / 75 after first-aid", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const feedZoneStart = app.indexOf('"feed-zone-cycling-club-hours"');
  const feedZoneEnd = app.indexOf("let agreementReviewPacket", feedZoneStart);
  const feedZone = app.slice(feedZoneStart, feedZoneEnd === -1 ? undefined : feedZoneEnd);
  const firstAidStart = app.indexOf('"first-aid-cycling-club-hours"');
  const firstAid = app.slice(firstAidStart, feedZoneStart);
  assert.ok(feedZoneStart > firstAidStart);
  assert.match(feedZone, /weight: 27/);
  assert.match(feedZone, /weight: 29/);
  assert.match(feedZone, /Sticky-bottle hours/);
  assert.match(feedZone, /Bottle-hand-up lock-up/);
  assert.match(feedZone, /bottle crew at the bottle-hand-up shed/);
  assert.match(feedZone, /11:30/);
  assert.match(feedZone, /20:15/);
  assert.match(feedZone, /15:25/);
  assert.doesNotMatch(feedZone, /treatment-tent/);
  assert.doesNotMatch(feedZone, /ice-pack-rota/);
  assert.doesNotMatch(feedZone, /triage-board/);
  assert.doesNotMatch(feedZone, /ice-pack crew/);
  assert.doesNotMatch(feedZone, /start-gate/);
  assert.doesNotMatch(feedZone, /flying-relay/);
  assert.doesNotMatch(feedZone, /trio-board/);
  assert.doesNotMatch(feedZone, /relay crew/);
  assert.doesNotMatch(feedZone, /team-pursuit-rota/);
  assert.doesNotMatch(feedZone, /changeover-bell/);
  assert.doesNotMatch(feedZone, /quartet-board/);
  assert.doesNotMatch(feedZone, /changeover crew/);
  assert.doesNotMatch(feedZone, /start-ramp/);
  assert.doesNotMatch(feedZone, /time-check/);
  assert.doesNotMatch(feedZone, /timing-hut/);
  assert.doesNotMatch(feedZone, /pit-lane/);
  assert.doesNotMatch(feedZone, /sealed-road/);
  assert.doesNotMatch(feedZone, /circuit/);
  assert.doesNotMatch(feedZone, /banked-boards/);
  assert.doesNotMatch(feedZone, /summit-marshal/);
  assert.doesNotMatch(feedZone, /hairpin/);
  assert.doesNotMatch(feedZone, /climb-chip/);
  assert.doesNotMatch(feedZone, /derny-pacer/);
  assert.doesNotMatch(feedZone, /keirin-chip/);
  assert.doesNotMatch(feedZone, /keirin-gate/);
  assert.doesNotMatch(feedZone, /madison-pair/);
  assert.doesNotMatch(feedZone, /handsling/);
  assert.doesNotMatch(feedZone, /pairing crew/);
  assert.doesNotMatch(feedZone, /flying-200/);
  assert.doesNotMatch(feedZone, /tempo-board/);
  assert.doesNotMatch(feedZone, /omnium-board/);
  assert.doesNotMatch(feedZone, /elimination-heat/);
  assert.doesNotMatch(feedZone, /tempo-lap/);
  assert.doesNotMatch(feedZone, /tempo crew/);
  assert.doesNotMatch(feedZone, /points-race/);
  assert.doesNotMatch(feedZone, /points-sprint/);
  assert.doesNotMatch(feedZone, /bell-lap/);
  assert.doesNotMatch(feedZone, /prime-board/);
  assert.doesNotMatch(feedZone, /bell crew/);
  assert.doesNotMatch(feedZone, /scratch-bunch/);
  assert.doesNotMatch(feedZone, /bunch-finish/);
  assert.doesNotMatch(feedZone, /scratch-chip/);
  assert.doesNotMatch(feedZone, /bunch crew/);
  assert.doesNotMatch(feedZone, /pursuit-line/);
  assert.doesNotMatch(feedZone, /catch-bell/);
  assert.doesNotMatch(feedZone, /pursuit-chip/);
  assert.doesNotMatch(feedZone, /pursuit crew/);
  assert.doesNotMatch(feedZone, /11:20/);
  assert.doesNotMatch(feedZone, /20:05/);
  assert.doesNotMatch(feedZone, /15:15/);
  assert.match(firstAid, /weight: 26/);
  assert.match(firstAid, /weight: 28/);
  assert.match(firstAid, /Ice-pack-rota hours/);
  assert.doesNotMatch(firstAid, /Sticky-bottle hours/);
  assert.doesNotMatch(firstAid, /Bottle-hand-up lock-up/);
  assert.equal(app.includes('} else if (event.shiftKey && key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.equal(app.includes('} else if (key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.match(html, /<kbd>Shift\+F9<\/kbd> Jump to the hide-last-group-without-floor control, or the groups heading/);
});
