import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("first-aid cycling club hours remaining 26 / 28 / 73 is distinct from team-sprint 25 / 27 / 71", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const firstAidStart = app.indexOf('"first-aid-cycling-club-hours"');
  const feedZoneStart = app.indexOf('"feed-zone-cycling-club-hours"');
  const firstAidEnd = feedZoneStart === -1 ? app.indexOf("let agreementReviewPacket", firstAidStart) : feedZoneStart;
  const firstAid = app.slice(firstAidStart, firstAidEnd === -1 ? undefined : firstAidEnd);
  const sprintStart = app.indexOf('"team-sprint-cycling-club-hours"');
  const sprint = app.slice(sprintStart, firstAidStart);
  const teamStart = app.indexOf('"team-pursuit-cycling-club-hours"');
  const team = app.slice(teamStart, sprintStart);
  const pursuitStart = app.indexOf('"individual-pursuit-cycling-club-hours"');
  const pursuit = app.slice(pursuitStart, teamStart);
  const scratchStart = app.indexOf('"scratch-cycling-club-hours"');
  const scratch = app.slice(scratchStart, pursuitStart);
  assert.ok(firstAidStart > sprintStart);
  assert.ok(sprintStart > teamStart);
  assert.ok(teamStart > pursuitStart);
  assert.match(firstAid, /weight: 26/);
  assert.match(firstAid, /weight: 28/);
  assert.match(firstAid, /ice-pack crew at the triage-board shed/);
  assert.match(sprint, /weight: 25/);
  assert.match(sprint, /weight: 27/);
  assert.match(sprint, /relay crew at the trio-board shed/);
  assert.match(team, /weight: 24/);
  assert.match(team, /weight: 26/);
  assert.match(team, /changeover crew at the quartet-board shed/);
  assert.match(pursuit, /weight: 23/);
  assert.match(pursuit, /weight: 25/);
  assert.match(scratch, /weight: 22/);
  assert.match(scratch, /weight: 24/);
  assert.notEqual(firstAid.match(/weight: 26/)?.[0], sprint.match(/weight: 25/)?.[0]);
  assert.notEqual(firstAid.match(/weight: 28/)?.[0], sprint.match(/weight: 27/)?.[0]);
  assert.doesNotMatch(firstAid, /start-gate/);
  assert.doesNotMatch(firstAid, /flying-relay/);
  assert.doesNotMatch(firstAid, /trio-board/);
  assert.doesNotMatch(sprint, /Ice-pack-rota hours/);
  assert.doesNotMatch(sprint, /Triage-board lock-up/);
  assert.doesNotMatch(team, /Ice-pack-rota hours/);
  assert.doesNotMatch(pursuit, /Ice-pack-rota hours/);
  assert.doesNotMatch(scratch, /Ice-pack-rota hours/);
});
