import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("first-aid cycling club hours keeps remaining 26 / 28 / 73 after team-sprint", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const firstAidStart = app.indexOf('"first-aid-cycling-club-hours"');
  const feedZoneStart = app.indexOf('"feed-zone-cycling-club-hours"');
  const firstAidEnd = feedZoneStart === -1 ? app.indexOf("let agreementReviewPacket", firstAidStart) : feedZoneStart;
  const firstAid = app.slice(firstAidStart, firstAidEnd === -1 ? undefined : firstAidEnd);
  const sprintStart = app.indexOf('"team-sprint-cycling-club-hours"');
  const sprint = app.slice(sprintStart, firstAidStart);
  assert.ok(firstAidStart > sprintStart);
  assert.match(firstAid, /weight: 26/);
  assert.match(firstAid, /weight: 28/);
  assert.match(firstAid, /Ice-pack-rota hours/);
  assert.match(firstAid, /Triage-board lock-up/);
  assert.match(firstAid, /ice-pack crew at the triage-board shed/);
  assert.match(firstAid, /11:20/);
  assert.match(firstAid, /20:05/);
  assert.match(firstAid, /15:15/);
  assert.doesNotMatch(firstAid, /start-gate/);
  assert.doesNotMatch(firstAid, /flying-relay/);
  assert.doesNotMatch(firstAid, /trio-board/);
  assert.doesNotMatch(firstAid, /relay crew/);
  assert.doesNotMatch(firstAid, /team-pursuit-rota/);
  assert.doesNotMatch(firstAid, /changeover-bell/);
  assert.doesNotMatch(firstAid, /quartet-board/);
  assert.doesNotMatch(firstAid, /changeover crew/);
  assert.doesNotMatch(firstAid, /start-ramp/);
  assert.doesNotMatch(firstAid, /time-check/);
  assert.doesNotMatch(firstAid, /timing-hut/);
  assert.doesNotMatch(firstAid, /pit-lane/);
  assert.doesNotMatch(firstAid, /sealed-road/);
  assert.doesNotMatch(firstAid, /circuit/);
  assert.doesNotMatch(firstAid, /feed-zone/);
  assert.doesNotMatch(firstAid, /banked-boards/);
  assert.doesNotMatch(firstAid, /summit-marshal/);
  assert.doesNotMatch(firstAid, /hairpin/);
  assert.doesNotMatch(firstAid, /climb-chip/);
  assert.doesNotMatch(firstAid, /derny-pacer/);
  assert.doesNotMatch(firstAid, /keirin-chip/);
  assert.doesNotMatch(firstAid, /keirin-gate/);
  assert.doesNotMatch(firstAid, /madison-pair/);
  assert.doesNotMatch(firstAid, /handsling/);
  assert.doesNotMatch(firstAid, /pairing crew/);
  assert.doesNotMatch(firstAid, /flying-200/);
  assert.doesNotMatch(firstAid, /tempo-board/);
  assert.doesNotMatch(firstAid, /omnium-board/);
  assert.doesNotMatch(firstAid, /elimination-heat/);
  assert.doesNotMatch(firstAid, /tempo-lap/);
  assert.doesNotMatch(firstAid, /tempo crew/);
  assert.doesNotMatch(firstAid, /points-race/);
  assert.doesNotMatch(firstAid, /points-sprint/);
  assert.doesNotMatch(firstAid, /bell-lap/);
  assert.doesNotMatch(firstAid, /prime-board/);
  assert.doesNotMatch(firstAid, /bell crew/);
  assert.doesNotMatch(firstAid, /scratch-bunch/);
  assert.doesNotMatch(firstAid, /bunch-finish/);
  assert.doesNotMatch(firstAid, /scratch-chip/);
  assert.doesNotMatch(firstAid, /bunch crew/);
  assert.doesNotMatch(firstAid, /pursuit-line/);
  assert.doesNotMatch(firstAid, /catch-bell/);
  assert.doesNotMatch(firstAid, /pursuit-chip/);
  assert.doesNotMatch(firstAid, /pursuit crew/);
  assert.doesNotMatch(firstAid, /11:10/);
  assert.doesNotMatch(firstAid, /19:55/);
  assert.doesNotMatch(firstAid, /15:05/);
  assert.match(sprint, /weight: 25/);
  assert.match(sprint, /weight: 27/);
  assert.match(sprint, /Flying-relay hours/);
  assert.doesNotMatch(sprint, /Ice-pack-rota hours/);
  assert.doesNotMatch(sprint, /Triage-board lock-up/);
  assert.equal(app.includes('} else if (event.shiftKey && key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.equal(app.includes('} else if (key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.match(html, /<kbd>Shift\+F9<\/kbd> Jump to the hide-last-group-without-floor control, or the groups heading/);
});
