import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("individual-pursuit cycling club hours keeps remaining 23 / 25 / 67 after scratch", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const pursuitStart = app.indexOf('"individual-pursuit-cycling-club-hours"');
  const teamStart = app.indexOf('"team-pursuit-cycling-club-hours"');
  const pursuitEnd = teamStart === -1 ? app.indexOf("let agreementReviewPacket", pursuitStart) : teamStart;
  const pursuit = app.slice(pursuitStart, pursuitEnd === -1 ? undefined : pursuitEnd);
  const scratchStart = app.indexOf('"scratch-cycling-club-hours"');
  const scratch = app.slice(scratchStart, pursuitStart);
  assert.ok(pursuitStart > scratchStart);
  assert.match(pursuit, /weight: 23/);
  assert.match(pursuit, /weight: 25/);
  assert.match(pursuit, /Catch-bell hours/);
  assert.match(pursuit, /Pursuit-chip lock-up/);
  assert.match(pursuit, /pursuit crew at the pursuit-chip shed/);
  assert.match(pursuit, /10:50/);
  assert.match(pursuit, /19:35/);
  assert.match(pursuit, /14:45/);
  assert.doesNotMatch(pursuit, /start-ramp/);
  assert.doesNotMatch(pursuit, /time-check/);
  assert.doesNotMatch(pursuit, /timing-hut/);
  assert.doesNotMatch(pursuit, /pit-lane/);
  assert.doesNotMatch(pursuit, /sealed-road/);
  assert.doesNotMatch(pursuit, /circuit/);
  assert.doesNotMatch(pursuit, /feed-zone/);
  assert.doesNotMatch(pursuit, /banked-boards/);
  assert.doesNotMatch(pursuit, /summit-marshal/);
  assert.doesNotMatch(pursuit, /hairpin/);
  assert.doesNotMatch(pursuit, /climb-chip/);
  assert.doesNotMatch(pursuit, /derny-pacer/);
  assert.doesNotMatch(pursuit, /keirin-chip/);
  assert.doesNotMatch(pursuit, /keirin-gate/);
  assert.doesNotMatch(pursuit, /madison-pair/);
  assert.doesNotMatch(pursuit, /handsling/);
  assert.doesNotMatch(pursuit, /pairing crew/);
  assert.doesNotMatch(pursuit, /pacer crew/);
  assert.doesNotMatch(pursuit, /flying-200/);
  assert.doesNotMatch(pursuit, /tempo-board/);
  assert.doesNotMatch(pursuit, /omnium-board/);
  assert.doesNotMatch(pursuit, /elimination-heat/);
  assert.doesNotMatch(pursuit, /tempo-lap/);
  assert.doesNotMatch(pursuit, /tempo crew/);
  assert.doesNotMatch(pursuit, /points-race/);
  assert.doesNotMatch(pursuit, /points-sprint/);
  assert.doesNotMatch(pursuit, /bell-lap/);
  assert.doesNotMatch(pursuit, /prime-board/);
  assert.doesNotMatch(pursuit, /bell crew/);
  assert.doesNotMatch(pursuit, /scratch-bunch/);
  assert.doesNotMatch(pursuit, /bunch-finish/);
  assert.doesNotMatch(pursuit, /scratch-chip/);
  assert.doesNotMatch(pursuit, /bunch crew/);
  assert.doesNotMatch(pursuit, /changeover-bell/);
  assert.doesNotMatch(pursuit, /quartet-board/);
  assert.doesNotMatch(pursuit, /team-pursuit-rota/);
  assert.doesNotMatch(pursuit, /changeover crew/);
  assert.doesNotMatch(pursuit, /10:40/);
  assert.doesNotMatch(pursuit, /19:25/);
  assert.doesNotMatch(pursuit, /14:35/);
  assert.match(scratch, /weight: 22/);
  assert.match(scratch, /weight: 24/);
  assert.match(scratch, /Bunch-finish hours/);
  assert.doesNotMatch(scratch, /Catch-bell hours/);
  assert.doesNotMatch(scratch, /Pursuit-chip lock-up/);
  assert.equal(app.includes('} else if (event.shiftKey && key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.equal(app.includes('} else if (key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.match(html, /<kbd>Shift\+F9<\/kbd> Jump to the hide-last-group-without-floor control, or the groups heading/);
});
