import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("keirin cycling club hours keeps remaining 18 / 20 / 53 after hill-climb", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const keirinStart = app.indexOf('"keirin-cycling-club-hours"');
  const madisonStart = app.indexOf('"madison-cycling-club-hours"');
  const keirinEnd = madisonStart === -1 ? app.indexOf("let agreementReviewPacket", keirinStart) : madisonStart;
  const keirin = app.slice(keirinStart, keirinEnd === -1 ? undefined : keirinEnd);
  const hillClimbStart = app.indexOf('"hill-climb-cycling-club-hours"');
  const hillClimb = app.slice(hillClimbStart, keirinStart);
  assert.ok(keirinStart > hillClimbStart);
  assert.match(keirin, /weight: 18/);
  assert.match(keirin, /weight: 20/);
  assert.match(keirin, /Derny-pacer hours/);
  assert.match(keirin, /Keirin-chip lock-up/);
  assert.match(keirin, /pacer crew at the derny-pacer shed/);
  assert.match(keirin, /09:50/);
  assert.match(keirin, /18:35/);
  assert.match(keirin, /13:45/);
  assert.doesNotMatch(keirin, /start-ramp/);
  assert.doesNotMatch(keirin, /time-check/);
  assert.doesNotMatch(keirin, /timing-hut/);
  assert.doesNotMatch(keirin, /pit-lane/);
  assert.doesNotMatch(keirin, /sealed-road/);
  assert.doesNotMatch(keirin, /circuit/);
  assert.doesNotMatch(keirin, /feed-zone/);
  assert.doesNotMatch(keirin, /banked-boards/);
  assert.doesNotMatch(keirin, /summit-marshal/);
  assert.doesNotMatch(keirin, /hairpin/);
  assert.doesNotMatch(keirin, /climb-chip/);
  assert.match(hillClimb, /weight: 17/);
  assert.match(hillClimb, /weight: 19/);
  assert.match(hillClimb, /Summit-marshal hours/);
  assert.doesNotMatch(hillClimb, /Derny-pacer hours/);
  assert.doesNotMatch(hillClimb, /Keirin-chip lock-up/);
  assert.equal(app.includes('} else if (event.shiftKey && key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.equal(app.includes('} else if (key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.match(html, /<kbd>Shift\+F9<\/kbd> Jump to the hide-last-group-without-floor control, or the groups heading/);
});
