import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("lead-out cycling club hours keeps remaining 28 / 30 / 77 after feed-zone", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const leadOutStart = app.indexOf('"lead-out-cycling-club-hours"');
  const leadOutEnd = app.indexOf("let agreementReviewPacket", leadOutStart);
  const leadOut = app.slice(leadOutStart, leadOutEnd === -1 ? undefined : leadOutEnd);
  const feedZoneStart = app.indexOf('"feed-zone-cycling-club-hours"');
  const feedZone = app.slice(feedZoneStart, leadOutStart);
  assert.ok(leadOutStart > feedZoneStart);
  assert.match(leadOut, /weight: 28/);
  assert.match(leadOut, /weight: 30/);
  assert.match(leadOut, /Last-rider hours/);
  assert.match(leadOut, /Sprinter-launch lock-up/);
  assert.match(leadOut, /launch crew at the sprinter-launch shed/);
  assert.match(leadOut, /11:40/);
  assert.match(leadOut, /20:25/);
  assert.match(leadOut, /15:35/);
  assert.doesNotMatch(leadOut, /musette-line/);
  assert.doesNotMatch(leadOut, /sticky-bottle/);
  assert.doesNotMatch(leadOut, /bottle-hand-up/);
  assert.doesNotMatch(leadOut, /bottle crew/);
  assert.doesNotMatch(leadOut, /treatment-tent/);
  assert.doesNotMatch(leadOut, /ice-pack-rota/);
  assert.doesNotMatch(leadOut, /triage-board/);
  assert.doesNotMatch(leadOut, /ice-pack crew/);
  assert.doesNotMatch(leadOut, /start-gate/);
  assert.doesNotMatch(leadOut, /flying-relay/);
  assert.doesNotMatch(leadOut, /trio-board/);
  assert.doesNotMatch(leadOut, /relay crew/);
  assert.doesNotMatch(leadOut, /team-pursuit-rota/);
  assert.doesNotMatch(leadOut, /changeover-bell/);
  assert.doesNotMatch(leadOut, /quartet-board/);
  assert.doesNotMatch(leadOut, /changeover crew/);
  assert.doesNotMatch(leadOut, /start-ramp/);
  assert.doesNotMatch(leadOut, /time-check/);
  assert.doesNotMatch(leadOut, /timing-hut/);
  assert.doesNotMatch(leadOut, /pit-lane/);
  assert.doesNotMatch(leadOut, /sealed-road/);
  assert.doesNotMatch(leadOut, /circuit/);
  assert.doesNotMatch(leadOut, /banked-boards/);
  assert.doesNotMatch(leadOut, /summit-marshal/);
  assert.doesNotMatch(leadOut, /hairpin/);
  assert.doesNotMatch(leadOut, /climb-chip/);
  assert.doesNotMatch(leadOut, /derny-pacer/);
  assert.doesNotMatch(leadOut, /keirin-chip/);
  assert.doesNotMatch(leadOut, /keirin-gate/);
  assert.doesNotMatch(leadOut, /madison-pair/);
  assert.doesNotMatch(leadOut, /handsling/);
  assert.doesNotMatch(leadOut, /pairing crew/);
  assert.doesNotMatch(leadOut, /flying-200/);
  assert.doesNotMatch(leadOut, /tempo-board/);
  assert.doesNotMatch(leadOut, /omnium-board/);
  assert.doesNotMatch(leadOut, /elimination-heat/);
  assert.doesNotMatch(leadOut, /tempo-lap/);
  assert.doesNotMatch(leadOut, /tempo crew/);
  assert.doesNotMatch(leadOut, /points-race/);
  assert.doesNotMatch(leadOut, /points-sprint/);
  assert.doesNotMatch(leadOut, /bell-lap/);
  assert.doesNotMatch(leadOut, /prime-board/);
  assert.doesNotMatch(leadOut, /bell crew/);
  assert.doesNotMatch(leadOut, /scratch-bunch/);
  assert.doesNotMatch(leadOut, /bunch-finish/);
  assert.doesNotMatch(leadOut, /scratch-chip/);
  assert.doesNotMatch(leadOut, /bunch crew/);
  assert.doesNotMatch(leadOut, /pursuit-line/);
  assert.doesNotMatch(leadOut, /catch-bell/);
  assert.doesNotMatch(leadOut, /pursuit-chip/);
  assert.doesNotMatch(leadOut, /pursuit crew/);
  assert.doesNotMatch(leadOut, /11:30/);
  assert.doesNotMatch(leadOut, /20:15/);
  assert.doesNotMatch(leadOut, /15:25/);
  assert.match(feedZone, /weight: 27/);
  assert.match(feedZone, /weight: 29/);
  assert.match(feedZone, /Sticky-bottle hours/);
  assert.doesNotMatch(feedZone, /Last-rider hours/);
  assert.doesNotMatch(feedZone, /Sprinter-launch lock-up/);
});
