import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("lead-out cycling club hours remaining 28 / 30 / 77 is distinct from feed-zone 27 / 29 / 75", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const leadOutStart = app.indexOf('"lead-out-cycling-club-hours"');
  const leadOutEnd = app.indexOf("let agreementReviewPacket", leadOutStart);
  const leadOut = app.slice(leadOutStart, leadOutEnd === -1 ? undefined : leadOutEnd);
  const feedZoneStart = app.indexOf('"feed-zone-cycling-club-hours"');
  const feedZone = app.slice(feedZoneStart, leadOutStart);
  const firstAidStart = app.indexOf('"first-aid-cycling-club-hours"');
  const firstAid = app.slice(firstAidStart, feedZoneStart);
  const sprintStart = app.indexOf('"team-sprint-cycling-club-hours"');
  const sprint = app.slice(sprintStart, firstAidStart);
  const teamStart = app.indexOf('"team-pursuit-cycling-club-hours"');
  const team = app.slice(teamStart, sprintStart);
  const pursuitStart = app.indexOf('"individual-pursuit-cycling-club-hours"');
  const pursuit = app.slice(pursuitStart, teamStart);
  const scratchStart = app.indexOf('"scratch-cycling-club-hours"');
  const scratch = app.slice(scratchStart, pursuitStart);
  assert.ok(leadOutStart > feedZoneStart);
  assert.ok(feedZoneStart > firstAidStart);
  assert.ok(firstAidStart > sprintStart);
  assert.ok(sprintStart > teamStart);
  assert.ok(teamStart > pursuitStart);
  assert.match(leadOut, /weight: 28/);
  assert.match(leadOut, /weight: 30/);
  assert.match(leadOut, /launch crew at the sprinter-launch shed/);
  assert.match(feedZone, /weight: 27/);
  assert.match(feedZone, /weight: 29/);
  assert.match(feedZone, /bottle crew at the bottle-hand-up shed/);
  assert.match(firstAid, /weight: 26/);
  assert.match(firstAid, /weight: 28/);
  assert.match(firstAid, /ice-pack crew at the triage-board shed/);
  assert.match(sprint, /weight: 25/);
  assert.match(sprint, /weight: 27/);
  assert.match(sprint, /relay crew at the trio-board shed/);
  assert.match(team, /weight: 24/);
  assert.match(team, /weight: 26/);
  assert.match(team, /changeover crew at the quartet-board shed/);
  assert.match(pursuit, /weight: 23/);
  assert.match(pursuit, /weight: 25/);
  assert.match(scratch, /weight: 22/);
  assert.match(scratch, /weight: 24/);
  assert.notEqual(leadOut.match(/weight: 28/)?.[0], feedZone.match(/weight: 27/)?.[0]);
  assert.notEqual(leadOut.match(/weight: 30/)?.[0], feedZone.match(/weight: 29/)?.[0]);
  assert.doesNotMatch(leadOut, /musette-line/);
  assert.doesNotMatch(leadOut, /sticky-bottle/);
  assert.doesNotMatch(leadOut, /bottle-hand-up/);
  assert.doesNotMatch(leadOut, /treatment-tent/);
  assert.doesNotMatch(leadOut, /ice-pack-rota/);
  assert.doesNotMatch(leadOut, /triage-board/);
  assert.doesNotMatch(feedZone, /Last-rider hours/);
  assert.doesNotMatch(feedZone, /Sprinter-launch lock-up/);
  assert.doesNotMatch(firstAid, /Last-rider hours/);
  assert.doesNotMatch(sprint, /Last-rider hours/);
  assert.doesNotMatch(team, /Last-rider hours/);
  assert.doesNotMatch(pursuit, /Last-rider hours/);
  assert.doesNotMatch(scratch, /Last-rider hours/);
});
