import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("madison cycling club hours keeps remaining 19 / 21 / 56 after keirin", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const madisonStart = app.indexOf('"madison-cycling-club-hours"');
  const madisonEnd = app.indexOf("let agreementReviewPacket", madisonStart);
  const madison = app.slice(madisonStart, madisonEnd === -1 ? undefined : madisonEnd);
  const keirinStart = app.indexOf('"keirin-cycling-club-hours"');
  const keirin = app.slice(keirinStart, madisonStart);
  assert.ok(madisonStart > keirinStart);
  assert.match(madison, /weight: 19/);
  assert.match(madison, /weight: 21/);
  assert.match(madison, /Handsling hours/);
  assert.match(madison, /Pairing-board lock-up/);
  assert.match(madison, /pairing crew at the handsling shed/);
  assert.match(madison, /10:05/);
  assert.match(madison, /18:50/);
  assert.match(madison, /14:00/);
  assert.doesNotMatch(madison, /start-ramp/);
  assert.doesNotMatch(madison, /time-check/);
  assert.doesNotMatch(madison, /timing-hut/);
  assert.doesNotMatch(madison, /pit-lane/);
  assert.doesNotMatch(madison, /sealed-road/);
  assert.doesNotMatch(madison, /circuit/);
  assert.doesNotMatch(madison, /feed-zone/);
  assert.doesNotMatch(madison, /banked-boards/);
  assert.doesNotMatch(madison, /summit-marshal/);
  assert.doesNotMatch(madison, /hairpin/);
  assert.doesNotMatch(madison, /climb-chip/);
  assert.doesNotMatch(madison, /derny-pacer/);
  assert.doesNotMatch(madison, /keirin-chip/);
  assert.doesNotMatch(madison, /keirin-gate/);
  assert.match(keirin, /weight: 18/);
  assert.match(keirin, /weight: 20/);
  assert.match(keirin, /Derny-pacer hours/);
  assert.doesNotMatch(keirin, /Handsling hours/);
  assert.doesNotMatch(keirin, /Pairing-board lock-up/);
  assert.equal(app.includes('} else if (event.shiftKey && key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.equal(app.includes('} else if (key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.match(html, /<kbd>Shift\+F9<\/kbd> Jump to the hide-last-group-without-floor control, or the groups heading/);
});
