import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("omnium cycling club hours keeps remaining 20 / 22 / 59 after madison", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const omniumStart = app.indexOf('"omnium-cycling-club-hours"');
  const omniumEnd = app.indexOf("let agreementReviewPacket", omniumStart);
  const omnium = app.slice(omniumStart, omniumEnd === -1 ? undefined : omniumEnd);
  const madisonStart = app.indexOf('"madison-cycling-club-hours"');
  const madison = app.slice(madisonStart, omniumStart);
  assert.ok(omniumStart > madisonStart);
  assert.match(omnium, /weight: 20/);
  assert.match(omnium, /weight: 22/);
  assert.match(omnium, /Flying-200 hours/);
  assert.match(omnium, /Tempo-board lock-up/);
  assert.match(omnium, /tempo crew at the flying-200 shed/);
  assert.match(omnium, /10:20/);
  assert.match(omnium, /19:05/);
  assert.match(omnium, /14:15/);
  assert.doesNotMatch(omnium, /start-ramp/);
  assert.doesNotMatch(omnium, /time-check/);
  assert.doesNotMatch(omnium, /timing-hut/);
  assert.doesNotMatch(omnium, /pit-lane/);
  assert.doesNotMatch(omnium, /sealed-road/);
  assert.doesNotMatch(omnium, /circuit/);
  assert.doesNotMatch(omnium, /feed-zone/);
  assert.doesNotMatch(omnium, /banked-boards/);
  assert.doesNotMatch(omnium, /summit-marshal/);
  assert.doesNotMatch(omnium, /hairpin/);
  assert.doesNotMatch(omnium, /climb-chip/);
  assert.doesNotMatch(omnium, /derny-pacer/);
  assert.doesNotMatch(omnium, /keirin-chip/);
  assert.doesNotMatch(omnium, /keirin-gate/);
  assert.doesNotMatch(omnium, /madison-pair/);
  assert.doesNotMatch(omnium, /handsling/);
  assert.doesNotMatch(omnium, /pairing crew/);
  assert.doesNotMatch(omnium, /pacer crew/);
  assert.match(madison, /weight: 19/);
  assert.match(madison, /weight: 21/);
  assert.match(madison, /Handsling hours/);
  assert.doesNotMatch(madison, /Flying-200 hours/);
  assert.doesNotMatch(madison, /Tempo-board lock-up/);
  assert.equal(app.includes('} else if (event.shiftKey && key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.equal(app.includes('} else if (key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.match(html, /<kbd>Shift\+F9<\/kbd> Jump to the hide-last-group-without-floor control, or the groups heading/);
});
