import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("points-race cycling club hours keeps remaining 21 / 23 / 62 after omnium", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const pointsRaceStart = app.indexOf('"points-race-cycling-club-hours"');
  const pointsRaceEnd = app.indexOf("let agreementReviewPacket", pointsRaceStart);
  const pointsRace = app.slice(pointsRaceStart, pointsRaceEnd === -1 ? undefined : pointsRaceEnd);
  const omniumStart = app.indexOf('"omnium-cycling-club-hours"');
  const omnium = app.slice(omniumStart, pointsRaceStart);
  assert.ok(pointsRaceStart > omniumStart);
  assert.match(pointsRace, /weight: 21/);
  assert.match(pointsRace, /weight: 23/);
  assert.match(pointsRace, /Bell-lap hours/);
  assert.match(pointsRace, /Prime-board lock-up/);
  assert.match(pointsRace, /bell crew at the bell-lap shed/);
  assert.match(pointsRace, /10:30/);
  assert.match(pointsRace, /19:15/);
  assert.match(pointsRace, /14:25/);
  assert.doesNotMatch(pointsRace, /start-ramp/);
  assert.doesNotMatch(pointsRace, /time-check/);
  assert.doesNotMatch(pointsRace, /timing-hut/);
  assert.doesNotMatch(pointsRace, /pit-lane/);
  assert.doesNotMatch(pointsRace, /sealed-road/);
  assert.doesNotMatch(pointsRace, /circuit/);
  assert.doesNotMatch(pointsRace, /feed-zone/);
  assert.doesNotMatch(pointsRace, /banked-boards/);
  assert.doesNotMatch(pointsRace, /summit-marshal/);
  assert.doesNotMatch(pointsRace, /hairpin/);
  assert.doesNotMatch(pointsRace, /climb-chip/);
  assert.doesNotMatch(pointsRace, /derny-pacer/);
  assert.doesNotMatch(pointsRace, /keirin-chip/);
  assert.doesNotMatch(pointsRace, /keirin-gate/);
  assert.doesNotMatch(pointsRace, /madison-pair/);
  assert.doesNotMatch(pointsRace, /handsling/);
  assert.doesNotMatch(pointsRace, /pairing crew/);
  assert.doesNotMatch(pointsRace, /pacer crew/);
  assert.doesNotMatch(pointsRace, /flying-200/);
  assert.doesNotMatch(pointsRace, /tempo-board/);
  assert.doesNotMatch(pointsRace, /omnium-board/);
  assert.doesNotMatch(pointsRace, /elimination-heat/);
  assert.doesNotMatch(pointsRace, /tempo-lap/);
  assert.doesNotMatch(pointsRace, /tempo crew/);
  assert.match(omnium, /weight: 20/);
  assert.match(omnium, /weight: 22/);
  assert.match(omnium, /Flying-200 hours/);
  assert.doesNotMatch(omnium, /Bell-lap hours/);
  assert.doesNotMatch(omnium, /Prime-board lock-up/);
  assert.equal(app.includes('} else if (event.shiftKey && key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.equal(app.includes('} else if (key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.match(html, /<kbd>Shift\+F9<\/kbd> Jump to the hide-last-group-without-floor control, or the groups heading/);
});
