import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("scratch cycling club hours keeps remaining 22 / 24 / 65 after points-race", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const scratchStart = app.indexOf('"scratch-cycling-club-hours"');
  const scratchEnd = app.indexOf("let agreementReviewPacket", scratchStart);
  const scratch = app.slice(scratchStart, scratchEnd === -1 ? undefined : scratchEnd);
  const pointsRaceStart = app.indexOf('"points-race-cycling-club-hours"');
  const pointsRace = app.slice(pointsRaceStart, scratchStart);
  assert.ok(scratchStart > pointsRaceStart);
  assert.match(scratch, /weight: 22/);
  assert.match(scratch, /weight: 24/);
  assert.match(scratch, /Bunch-finish hours/);
  assert.match(scratch, /Scratch-chip lock-up/);
  assert.match(scratch, /bunch crew at the scratch-chip shed/);
  assert.match(scratch, /10:40/);
  assert.match(scratch, /19:25/);
  assert.match(scratch, /14:35/);
  assert.doesNotMatch(scratch, /start-ramp/);
  assert.doesNotMatch(scratch, /time-check/);
  assert.doesNotMatch(scratch, /timing-hut/);
  assert.doesNotMatch(scratch, /pit-lane/);
  assert.doesNotMatch(scratch, /sealed-road/);
  assert.doesNotMatch(scratch, /circuit/);
  assert.doesNotMatch(scratch, /feed-zone/);
  assert.doesNotMatch(scratch, /banked-boards/);
  assert.doesNotMatch(scratch, /summit-marshal/);
  assert.doesNotMatch(scratch, /hairpin/);
  assert.doesNotMatch(scratch, /climb-chip/);
  assert.doesNotMatch(scratch, /derny-pacer/);
  assert.doesNotMatch(scratch, /keirin-chip/);
  assert.doesNotMatch(scratch, /keirin-gate/);
  assert.doesNotMatch(scratch, /madison-pair/);
  assert.doesNotMatch(scratch, /handsling/);
  assert.doesNotMatch(scratch, /pairing crew/);
  assert.doesNotMatch(scratch, /pacer crew/);
  assert.doesNotMatch(scratch, /flying-200/);
  assert.doesNotMatch(scratch, /tempo-board/);
  assert.doesNotMatch(scratch, /omnium-board/);
  assert.doesNotMatch(scratch, /elimination-heat/);
  assert.doesNotMatch(scratch, /tempo-lap/);
  assert.doesNotMatch(scratch, /tempo crew/);
  assert.doesNotMatch(scratch, /points-race/);
  assert.doesNotMatch(scratch, /points-sprint/);
  assert.doesNotMatch(scratch, /bell-lap/);
  assert.doesNotMatch(scratch, /prime-board/);
  assert.doesNotMatch(scratch, /bell crew/);
  assert.match(pointsRace, /weight: 21/);
  assert.match(pointsRace, /weight: 23/);
  assert.match(pointsRace, /Bell-lap hours/);
  assert.doesNotMatch(pointsRace, /Bunch-finish hours/);
  assert.doesNotMatch(pointsRace, /Scratch-chip lock-up/);
  assert.equal(app.includes('} else if (event.shiftKey && key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.equal(app.includes('} else if (key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.match(html, /<kbd>Shift\+F9<\/kbd> Jump to the hide-last-group-without-floor control, or the groups heading/);
});
