import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("soigneur cycling club hours keeps remaining 29 / 31 / 79 after lead-out", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const soigneurStart = app.indexOf('"soigneur-cycling-club-hours"');
  const soigneurEnd = app.indexOf('"domestique-cycling-club-hours"', soigneurStart);
  const soigneur = app.slice(soigneurStart, soigneurEnd === -1 ? undefined : soigneurEnd);
  const leadOutStart = app.indexOf('"lead-out-cycling-club-hours"');
  const leadOut = app.slice(leadOutStart, soigneurStart);
  assert.ok(soigneurStart > leadOutStart);
  assert.match(soigneur, /weight: 29/);
  assert.match(soigneur, /weight: 31/);
  assert.match(soigneur, /Cape-bag hours/);
  assert.match(soigneur, /Rice-cake lock-up/);
  assert.match(soigneur, /cake crew at the rice-cake shed/);
  assert.match(soigneur, /11:50/);
  assert.match(soigneur, /20:35/);
  assert.match(soigneur, /15:45/);
  assert.doesNotMatch(soigneur, /train-line/);
  assert.doesNotMatch(soigneur, /last-rider/);
  assert.doesNotMatch(soigneur, /sprinter-launch/);
  assert.doesNotMatch(soigneur, /launch crew/);
  assert.doesNotMatch(soigneur, /musette-line/);
  assert.doesNotMatch(soigneur, /sticky-bottle/);
  assert.doesNotMatch(soigneur, /bottle-hand-up/);
  assert.doesNotMatch(soigneur, /bottle crew/);
  assert.doesNotMatch(soigneur, /treatment-tent/);
  assert.doesNotMatch(soigneur, /ice-pack-rota/);
  assert.doesNotMatch(soigneur, /triage-board/);
  assert.doesNotMatch(soigneur, /ice-pack crew/);
  assert.doesNotMatch(soigneur, /start-gate/);
  assert.doesNotMatch(soigneur, /flying-relay/);
  assert.doesNotMatch(soigneur, /trio-board/);
  assert.doesNotMatch(soigneur, /relay crew/);
  assert.doesNotMatch(soigneur, /team-pursuit-rota/);
  assert.doesNotMatch(soigneur, /changeover-bell/);
  assert.doesNotMatch(soigneur, /quartet-board/);
  assert.doesNotMatch(soigneur, /changeover crew/);
  assert.doesNotMatch(soigneur, /start-ramp/);
  assert.doesNotMatch(soigneur, /time-check/);
  assert.doesNotMatch(soigneur, /timing-hut/);
  assert.doesNotMatch(soigneur, /pit-lane/);
  assert.doesNotMatch(soigneur, /sealed-road/);
  assert.doesNotMatch(soigneur, /circuit/);
  assert.doesNotMatch(soigneur, /banked-boards/);
  assert.doesNotMatch(soigneur, /summit-marshal/);
  assert.doesNotMatch(soigneur, /hairpin/);
  assert.doesNotMatch(soigneur, /climb-chip/);
  assert.doesNotMatch(soigneur, /derny-pacer/);
  assert.doesNotMatch(soigneur, /keirin-chip/);
  assert.doesNotMatch(soigneur, /keirin-gate/);
  assert.doesNotMatch(soigneur, /madison-pair/);
  assert.doesNotMatch(soigneur, /handsling/);
  assert.doesNotMatch(soigneur, /pairing crew/);
  assert.doesNotMatch(soigneur, /flying-200/);
  assert.doesNotMatch(soigneur, /tempo-board/);
  assert.doesNotMatch(soigneur, /omnium-board/);
  assert.doesNotMatch(soigneur, /elimination-heat/);
  assert.doesNotMatch(soigneur, /tempo-lap/);
  assert.doesNotMatch(soigneur, /tempo crew/);
  assert.doesNotMatch(soigneur, /points-race/);
  assert.doesNotMatch(soigneur, /points-sprint/);
  assert.doesNotMatch(soigneur, /bell-lap/);
  assert.doesNotMatch(soigneur, /prime-board/);
  assert.doesNotMatch(soigneur, /bell crew/);
  assert.doesNotMatch(soigneur, /scratch-bunch/);
  assert.doesNotMatch(soigneur, /bunch-finish/);
  assert.doesNotMatch(soigneur, /scratch-chip/);
  assert.doesNotMatch(soigneur, /bunch crew/);
  assert.doesNotMatch(soigneur, /pursuit-line/);
  assert.doesNotMatch(soigneur, /catch-bell/);
  assert.doesNotMatch(soigneur, /pursuit-chip/);
  assert.doesNotMatch(soigneur, /pursuit crew/);
  assert.doesNotMatch(soigneur, /11:40/);
  assert.doesNotMatch(soigneur, /20:25/);
  assert.doesNotMatch(soigneur, /15:35/);
  assert.match(leadOut, /weight: 28/);
  assert.match(leadOut, /weight: 30/);
  assert.match(leadOut, /Last-rider hours/);
  assert.doesNotMatch(leadOut, /Cape-bag hours/);
  assert.doesNotMatch(leadOut, /Rice-cake lock-up/);
  assert.equal(app.includes('} else if (event.shiftKey && key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.equal(app.includes('} else if (key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.match(html, /<kbd>Shift\+F9<\/kbd> Jump to the hide-last-group-without-floor control, or the groups heading/);
});
