import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("soigneur cycling club hours remaining 29 / 31 / 79 is distinct from lead-out 28 / 30 / 77", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const soigneurStart = app.indexOf('"soigneur-cycling-club-hours"');
  const soigneurEnd = app.indexOf("let agreementReviewPacket", soigneurStart);
  const soigneur = app.slice(soigneurStart, soigneurEnd === -1 ? undefined : soigneurEnd);
  const leadOutStart = app.indexOf('"lead-out-cycling-club-hours"');
  const leadOut = app.slice(leadOutStart, soigneurStart);
  const feedZoneStart = app.indexOf('"feed-zone-cycling-club-hours"');
  const feedZone = app.slice(feedZoneStart, leadOutStart);
  const firstAidStart = app.indexOf('"first-aid-cycling-club-hours"');
  const firstAid = app.slice(firstAidStart, feedZoneStart);
  const sprintStart = app.indexOf('"team-sprint-cycling-club-hours"');
  const sprint = app.slice(sprintStart, firstAidStart);
  const teamStart = app.indexOf('"team-pursuit-cycling-club-hours"');
  const team = app.slice(teamStart, sprintStart);
  const pursuitStart = app.indexOf('"individual-pursuit-cycling-club-hours"');
  const pursuit = app.slice(pursuitStart, teamStart);
  const scratchStart = app.indexOf('"scratch-cycling-club-hours"');
  const scratch = app.slice(scratchStart, pursuitStart);
  assert.ok(soigneurStart > leadOutStart);
  assert.ok(leadOutStart > feedZoneStart);
  assert.ok(feedZoneStart > firstAidStart);
  assert.ok(firstAidStart > sprintStart);
  assert.ok(sprintStart > teamStart);
  assert.ok(teamStart > pursuitStart);
  assert.match(soigneur, /weight: 29/);
  assert.match(soigneur, /weight: 31/);
  assert.match(soigneur, /cake crew at the rice-cake shed/);
  assert.match(leadOut, /weight: 28/);
  assert.match(leadOut, /weight: 30/);
  assert.match(leadOut, /launch crew at the sprinter-launch shed/);
  assert.match(feedZone, /weight: 27/);
  assert.match(feedZone, /weight: 29/);
  assert.match(feedZone, /bottle crew at the bottle-hand-up shed/);
  assert.match(firstAid, /weight: 26/);
  assert.match(firstAid, /weight: 28/);
  assert.match(firstAid, /ice-pack crew at the triage-board shed/);
  assert.match(sprint, /weight: 25/);
  assert.match(sprint, /weight: 27/);
  assert.match(sprint, /relay crew at the trio-board shed/);
  assert.match(team, /weight: 24/);
  assert.match(team, /weight: 26/);
  assert.match(team, /changeover crew at the quartet-board shed/);
  assert.match(pursuit, /weight: 23/);
  assert.match(pursuit, /weight: 25/);
  assert.match(scratch, /weight: 22/);
  assert.match(scratch, /weight: 24/);
  assert.notEqual(soigneur.match(/weight: 29/)?.[0], leadOut.match(/weight: 28/)?.[0]);
  assert.notEqual(soigneur.match(/weight: 31/)?.[0], leadOut.match(/weight: 30/)?.[0]);
  assert.doesNotMatch(soigneur, /train-line/);
  assert.doesNotMatch(soigneur, /last-rider/);
  assert.doesNotMatch(soigneur, /sprinter-launch/);
  assert.doesNotMatch(soigneur, /musette-line/);
  assert.doesNotMatch(soigneur, /sticky-bottle/);
  assert.doesNotMatch(soigneur, /bottle-hand-up/);
  assert.doesNotMatch(soigneur, /treatment-tent/);
  assert.doesNotMatch(soigneur, /ice-pack-rota/);
  assert.doesNotMatch(soigneur, /triage-board/);
  assert.doesNotMatch(leadOut, /Cape-bag hours/);
  assert.doesNotMatch(leadOut, /Rice-cake lock-up/);
  assert.doesNotMatch(feedZone, /Cape-bag hours/);
  assert.doesNotMatch(firstAid, /Cape-bag hours/);
  assert.doesNotMatch(sprint, /Cape-bag hours/);
  assert.doesNotMatch(team, /Cape-bag hours/);
  assert.doesNotMatch(pursuit, /Cape-bag hours/);
  assert.doesNotMatch(scratch, /Cape-bag hours/);
});
