import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("team-sprint cycling club hours keeps remaining 25 / 27 / 71 after team-pursuit", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const sprintStart = app.indexOf('"team-sprint-cycling-club-hours"');
  const firstAidStart = app.indexOf('"first-aid-cycling-club-hours"');
  const sprintEnd = firstAidStart === -1 ? app.indexOf("let agreementReviewPacket", sprintStart) : firstAidStart;
  const sprint = app.slice(sprintStart, sprintEnd === -1 ? undefined : sprintEnd);
  const teamStart = app.indexOf('"team-pursuit-cycling-club-hours"');
  const team = app.slice(teamStart, sprintStart);
  assert.ok(sprintStart > teamStart);
  assert.match(sprint, /weight: 25/);
  assert.match(sprint, /weight: 27/);
  assert.match(sprint, /Flying-relay hours/);
  assert.match(sprint, /Trio-board lock-up/);
  assert.match(sprint, /relay crew at the trio-board shed/);
  assert.match(sprint, /11:10/);
  assert.match(sprint, /19:55/);
  assert.match(sprint, /15:05/);
  assert.doesNotMatch(sprint, /team-pursuit-rota/);
  assert.doesNotMatch(sprint, /changeover-bell/);
  assert.doesNotMatch(sprint, /quartet-board/);
  assert.doesNotMatch(sprint, /changeover crew/);
  assert.doesNotMatch(sprint, /start-ramp/);
  assert.doesNotMatch(sprint, /time-check/);
  assert.doesNotMatch(sprint, /timing-hut/);
  assert.doesNotMatch(sprint, /pit-lane/);
  assert.doesNotMatch(sprint, /sealed-road/);
  assert.doesNotMatch(sprint, /circuit/);
  assert.doesNotMatch(sprint, /feed-zone/);
  assert.doesNotMatch(sprint, /banked-boards/);
  assert.doesNotMatch(sprint, /summit-marshal/);
  assert.doesNotMatch(sprint, /hairpin/);
  assert.doesNotMatch(sprint, /climb-chip/);
  assert.doesNotMatch(sprint, /derny-pacer/);
  assert.doesNotMatch(sprint, /keirin-chip/);
  assert.doesNotMatch(sprint, /keirin-gate/);
  assert.doesNotMatch(sprint, /madison-pair/);
  assert.doesNotMatch(sprint, /handsling/);
  assert.doesNotMatch(sprint, /pairing crew/);
  assert.doesNotMatch(sprint, /pacer crew/);
  assert.doesNotMatch(sprint, /flying-200/);
  assert.doesNotMatch(sprint, /tempo-board/);
  assert.doesNotMatch(sprint, /omnium-board/);
  assert.doesNotMatch(sprint, /elimination-heat/);
  assert.doesNotMatch(sprint, /tempo-lap/);
  assert.doesNotMatch(sprint, /tempo crew/);
  assert.doesNotMatch(sprint, /points-race/);
  assert.doesNotMatch(sprint, /points-sprint/);
  assert.doesNotMatch(sprint, /bell-lap/);
  assert.doesNotMatch(sprint, /prime-board/);
  assert.doesNotMatch(sprint, /bell crew/);
  assert.doesNotMatch(sprint, /scratch-bunch/);
  assert.doesNotMatch(sprint, /bunch-finish/);
  assert.doesNotMatch(sprint, /scratch-chip/);
  assert.doesNotMatch(sprint, /bunch crew/);
  assert.doesNotMatch(sprint, /pursuit-line/);
  assert.doesNotMatch(sprint, /catch-bell/);
  assert.doesNotMatch(sprint, /pursuit-chip/);
  assert.doesNotMatch(sprint, /pursuit crew/);
  assert.doesNotMatch(sprint, /11:00/);
  assert.doesNotMatch(sprint, /19:45/);
  assert.doesNotMatch(sprint, /14:55/);
  assert.match(team, /weight: 24/);
  assert.match(team, /weight: 26/);
  assert.match(team, /Changeover-bell hours/);
  assert.doesNotMatch(team, /Flying-relay hours/);
  assert.doesNotMatch(team, /Trio-board lock-up/);
});
