import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("team-pursuit cycling club hours keeps remaining 24 / 26 / 69 after individual-pursuit", async () => {
  const app = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const html = (await readFile(new URL("../index.html", import.meta.url), "utf8")).replaceAll("\r\n", "\n");
  const teamStart = app.indexOf('"team-pursuit-cycling-club-hours"');
  const sprintStart = app.indexOf('"team-sprint-cycling-club-hours"');
  const teamEnd = sprintStart === -1 ? app.indexOf("let agreementReviewPacket", teamStart) : sprintStart;
  const team = app.slice(teamStart, teamEnd === -1 ? undefined : teamEnd);
  const pursuitStart = app.indexOf('"individual-pursuit-cycling-club-hours"');
  const pursuit = app.slice(pursuitStart, teamStart);
  assert.ok(teamStart > pursuitStart);
  assert.match(team, /weight: 24/);
  assert.match(team, /weight: 26/);
  assert.match(team, /Changeover-bell hours/);
  assert.match(team, /Quartet-board lock-up/);
  assert.match(team, /changeover crew at the quartet-board shed/);
  assert.match(team, /11:00/);
  assert.match(team, /19:45/);
  assert.match(team, /14:55/);
  assert.doesNotMatch(team, /start-ramp/);
  assert.doesNotMatch(team, /time-check/);
  assert.doesNotMatch(team, /timing-hut/);
  assert.doesNotMatch(team, /pit-lane/);
  assert.doesNotMatch(team, /sealed-road/);
  assert.doesNotMatch(team, /circuit/);
  assert.doesNotMatch(team, /feed-zone/);
  assert.doesNotMatch(team, /banked-boards/);
  assert.doesNotMatch(team, /summit-marshal/);
  assert.doesNotMatch(team, /hairpin/);
  assert.doesNotMatch(team, /climb-chip/);
  assert.doesNotMatch(team, /derny-pacer/);
  assert.doesNotMatch(team, /keirin-chip/);
  assert.doesNotMatch(team, /keirin-gate/);
  assert.doesNotMatch(team, /madison-pair/);
  assert.doesNotMatch(team, /handsling/);
  assert.doesNotMatch(team, /pairing crew/);
  assert.doesNotMatch(team, /pacer crew/);
  assert.doesNotMatch(team, /flying-200/);
  assert.doesNotMatch(team, /tempo-board/);
  assert.doesNotMatch(team, /omnium-board/);
  assert.doesNotMatch(team, /elimination-heat/);
  assert.doesNotMatch(team, /tempo-lap/);
  assert.doesNotMatch(team, /tempo crew/);
  assert.doesNotMatch(team, /points-race/);
  assert.doesNotMatch(team, /points-sprint/);
  assert.doesNotMatch(team, /bell-lap/);
  assert.doesNotMatch(team, /prime-board/);
  assert.doesNotMatch(team, /bell crew/);
  assert.doesNotMatch(team, /scratch-bunch/);
  assert.doesNotMatch(team, /bunch-finish/);
  assert.doesNotMatch(team, /scratch-chip/);
  assert.doesNotMatch(team, /bunch crew/);
  assert.doesNotMatch(team, /pursuit-line/);
  assert.doesNotMatch(team, /catch-bell/);
  assert.doesNotMatch(team, /pursuit-chip/);
  assert.doesNotMatch(team, /pursuit crew/);
  assert.doesNotMatch(team, /10:50/);
  assert.doesNotMatch(team, /19:35/);
  assert.doesNotMatch(team, /14:45/);
  assert.match(pursuit, /weight: 23/);
  assert.match(pursuit, /weight: 25/);
  assert.match(pursuit, /Catch-bell hours/);
  assert.doesNotMatch(pursuit, /Changeover-bell hours/);
  assert.doesNotMatch(pursuit, /Quartet-board lock-up/);
  assert.equal(app.includes('} else if (event.shiftKey && key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.equal(app.includes('} else if (key === "F9") {\n    event.preventDefault();\n    jumpToHideLastGroupWithoutFloor();'), true);
  assert.match(html, /<kbd>Shift\+F9<\/kbd> Jump to the hide-last-group-without-floor control, or the groups heading/);
});
