import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { catalogVersionLine, notFoundPage, catalogJobs, catalogLastWhatsNewHeading, catalogFirstWhatsNewHeading, catalogFirstWorkbenchHeading, catalogLastWorkbenchHeading, catalogLastReviewPath, catalogFirstReviewPath, catalogFirstOpenHref, catalogLastOpenHref, catalogFirstSkipHref, catalogLastSkipHref, catalogFirstSkipText, catalogLastSkipText, catalogFirstSkipTargetText, catalogLastSkipTargetText, catalogFirstLabelledSkipTargetText, catalogLastLabelledSkipTargetText, catalogFirstLabelledSkipHref, catalogLastLabelledSkipHref, catalogLastLabelledSkipText, catalogFirstLabelledSkipText, catalogLastUnlabelledSkipText, catalogFirstUnlabelledSkipText, catalogFirstUnlabelledSkipHref, catalogLastUnlabelledSkipHref, catalogFirstUnlabelledSkipTargetText, catalogLastUnlabelledSkipTargetText, catalogFirstUnlabelledSkipTargetId, catalogLastUnlabelledSkipTargetId, catalogFirstLabelledSkipTargetId, catalogLastLabelledSkipTargetId, catalogLastLabelledSkipLabelledbyId } from '../scripts/serve.mjs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const readme = readFileSync(new URL('../README.md', import.meta.url), 'utf8');
const apps = [
  ['partnership-breakpoint', 'Partnership Breakpoint'],
  ['common-cart', 'Common Cart'],
  ['smallest-agreement', 'The Smallest Agreement'],
  ['weekend-gap', 'Weekend Gap'],
];

test('catalog version list and cards match each app package.json', () => {
  assert.match(html, /id="workbench-versions"/);
  const versionLine = html.match(/class="version-line">([^<]+)</)?.[1] ?? '';
  for (const [id, label] of apps) {
    const version = JSON.parse(readFileSync(new URL(`../apps/${id}/package.json`, import.meta.url), 'utf8')).version;
    const escaped = version.replaceAll('.', '\\.');
    assert.match(html, new RegExp(`data-app="${id}">\\s*${escaped}\\s*<`));
    assert.match(html, new RegExp(`data-app-version="${id}">\\s*${escaped}\\s*<`));
    assert.equal(versionLine.includes(`${label} ${version}`), true, `${label} ${version} missing from version line`);
    assert.equal(
      readme.includes(`[${label}](apps/${id}/) | ${version} |`),
      true,
      `${label} ${version} missing from README table`,
    );
  }
});

test('404 catalog version line matches each app package.json', () => {
  const line = catalogVersionLine();
  for (const [id, label] of apps) {
    const version = JSON.parse(readFileSync(new URL(`../apps/${id}/package.json`, import.meta.url), 'utf8')).version;
    assert.equal(line.includes(`${label} ${version}`), true, `${label} ${version} missing from 404 version line`);
  }
  const page = notFoundPage();
  assert.match(page, /Current catalog:/);
  assert.equal(page.includes(line), true, '404 page should include the catalog version line');
  assert.match(page, /id="copy-versions"/);
  assert.match(page, />Copy versions</);
  assert.match(page, /id="copy-version-line"/);
  assert.match(page, />Copy version line</);
  assert.match(page, /querySelector\('\.version-line'\)/);
  assert.match(page, /versionLineMarkdown/);
  assert.match(page, /id="copy-trust"/);
  assert.match(page, />Copy Trust and limits</);
  assert.match(page, /id="trust"/);
  assert.match(page, /Not a live policy feed/);
  assert.match(page, /id="copy-how"/);
  assert.match(page, />Copy How it works</);
  assert.match(page, /id="how-it-works"/);
  assert.match(page, /id="copy-jobs"/);
  assert.match(page, />Copy jobs</);
  assert.match(page, /id="catalog-jobs"/);
  assert.match(page, /Not a live product feed/);
  assert.match(page, /id="copy-lede"/);
  assert.match(page, />Copy catalog intro</);
  assert.doesNotMatch(page, /\bfetch\s*\(/);
  assert.doesNotMatch(page, /XMLHttpRequest/);
  assert.match(page, /id="copy-first-trust"/);
  assert.match(page, />Copy first Trust item</);
  assert.match(page, /firstTrustMarkdown/);
  assert.match(page, /id="copy-first-how"/);
  assert.match(page, />Copy first How it works item</);
  assert.match(page, /firstHowMarkdown/);
  assert.match(page, /id="copy-last-how"/);
  assert.match(page, />Copy last How it works item</);
  assert.match(page, /lastHowMarkdown/);
  assert.match(page, /id="copy-last-job"/);
  assert.match(page, />Copy last job</);
  assert.match(page, /lastJobMarkdown/);
  assert.match(page, /id="copy-last-whats-new"/);
  assert.match(page, />Copy last What's new heading</);
  assert.match(page, /lastWhatsNewMarkdown/);
  assert.match(page, /id="copy-first-whats-new"/);
  assert.match(page, />Copy first What's new heading</);
  assert.match(page, /firstWhatsNewMarkdown/);
  assert.match(page, /id="copy-first-workbench"/);
  assert.match(page, />Copy first workbench heading</);
  assert.match(page, /firstWorkbenchMarkdown/);
  assert.match(page, /id="copy-last-workbench"/);
  assert.match(page, />Copy last workbench heading</);
  assert.match(page, /lastWorkbenchMarkdown/);
  assert.match(page, /id="copy-last-review"/);
  assert.match(page, />Copy last review path</);
  assert.match(page, /lastReviewMarkdown/);
  assert.match(page, /id="copy-first-review"/);
  assert.match(page, />Copy first review path</);
  assert.match(page, /firstReviewMarkdown/);
  assert.match(page, /id="copy-first-open"/);
  assert.match(page, />Copy first Open href</);
  assert.match(page, /firstOpenMarkdown/);
  assert.match(page, /id="copy-last-open"/);
  assert.match(page, />Copy last Open href</);
  assert.match(page, /lastOpenMarkdown/);
});

test('404 catalog jobs match the four catalog cards', () => {
  const jobs = catalogJobs();
  assert.equal(jobs.length, 4);
  assert.equal(jobs[0].name, 'Partnership Breakpoint');
  assert.equal(jobs[1].name, 'Common Cart');
  assert.equal(jobs[2].name, 'The Smallest Agreement');
  assert.equal(jobs[3].name, 'Weekend Gap');
  for (const { name, job } of jobs) {
    assert.match(job, /\S/);
    assert.equal(html.includes(`<h3>${name}</h3>`), true, `${name} heading missing from catalog`);
    assert.equal(html.includes(`<p class="job">${job}</p>`), true, `${name} job missing from catalog`);
  }
  const page = notFoundPage();
  for (const { name, job } of jobs) {
    assert.equal(page.includes(`${name}: ${job}`), true, `${name} job missing from 404 page`);
  }
});

test('404 last What\'s new heading matches the last catalog What\'s new heading', () => {
  const heading = catalogLastWhatsNewHeading();
  assert.match(heading, /\S/);
  assert.equal(html.includes(`>${heading}</h3>`), true, 'last What\'s new heading missing from catalog');
  const page = notFoundPage();
  assert.equal(page.includes(heading), true, 'last What\'s new heading missing from 404 page');
  assert.match(page, /id="copy-last-whats-new"/);
  assert.match(page, />Copy last What's new heading</);
});

test('404 first What\'s new heading matches the first catalog What\'s new heading', () => {
  const heading = catalogFirstWhatsNewHeading();
  assert.match(heading, /\S/);
  assert.equal(html.includes(`>${heading}</h3>`), true, 'first What\'s new heading missing from catalog');
  const page = notFoundPage();
  assert.equal(page.includes(heading), true, 'first What\'s new heading missing from 404 page');
  assert.match(page, /id="copy-first-whats-new"/);
  assert.match(page, />Copy first What's new heading</);
  assert.match(page, /id="copy-last-whats-new"/);
  assert.match(page, />Copy last What's new heading</);
});

test('404 first workbench heading matches the first catalog workbench card heading', () => {
  const heading = catalogFirstWorkbenchHeading();
  assert.equal(heading, 'Partnership Breakpoint');
  assert.equal(html.includes(`<h3>${heading}</h3>`), true, 'first workbench heading missing from catalog');
  const page = notFoundPage();
  assert.equal(page.includes(heading), true, 'first workbench heading missing from 404 page');
  assert.match(page, /id="copy-first-workbench"/);
  assert.match(page, />Copy first workbench heading</);
  assert.match(page, /querySelector\('#workbenches article\.workbench h3'\)/);
  assert.match(page, /id="workbenches"/);
});


test('404 last workbench heading matches the last catalog workbench card heading', () => {
  const heading = catalogLastWorkbenchHeading();
  assert.equal(heading, 'Weekend Gap');
  assert.equal(html.includes(`<h3>${heading}</h3>`), true, 'last workbench heading missing from catalog');
  const first = catalogFirstWorkbenchHeading();
  assert.equal(first, 'Partnership Breakpoint');
  assert.notEqual(heading, first);
  const page = notFoundPage();
  assert.equal(page.includes(heading), true, 'last workbench heading missing from 404 page');
  assert.equal(page.includes(first), true, 'first workbench heading missing from 404 page');
  assert.match(page, /id="copy-last-workbench"/);
  assert.match(page, />Copy last workbench heading</);
  assert.match(page, /querySelectorAll\('#workbenches article\.workbench h3'\)/);
  assert.match(page, /id="workbenches"/);
  assert.match(page, /id="copy-first-workbench"/);
  assert.match(page, />Copy first workbench heading</);
});

test('404 last Open href matches the last catalog Open workbench href', () => {
  const href = catalogLastOpenHref();
  assert.equal(href, 'apps/weekend-gap/standalone.html');
  assert.equal(html.includes(`href="${href}"`), true, 'last Open href missing from catalog');
  assert.notEqual(href, catalogFirstOpenHref());
  assert.notEqual(href, catalogLastReviewPath());
  assert.notEqual(href, catalogLastWorkbenchHeading());
  const page = notFoundPage();
  assert.equal(page.includes(href), true, 'last Open href missing from 404 page');
  assert.match(page, /id="copy-last-open"/);
  assert.match(page, />Copy last Open href</);
  assert.match(page, /querySelectorAll\('#workbenches a\.open'\)/);
  assert.match(page, /id="workbenches"/);
  assert.match(page, /id="copy-first-open"/);
  assert.match(page, />Copy first Open href</);
});

test('404 first skip href matches the first catalog skip-link href', () => {
  const href = catalogFirstSkipHref();
  assert.equal(href, '#whats-new');
  assert.equal(html.includes(`href="${href}"`), true, 'first skip href missing from catalog');
  assert.notEqual(href, catalogFirstOpenHref());
  assert.notEqual(href, catalogLastOpenHref());
  const page = notFoundPage();
  assert.equal(page.includes(href), true, 'first skip href missing from 404 page');
  assert.match(page, /id="copy-first-skip"/);
  assert.match(page, />Copy first skip href</);
  assert.match(page, /querySelector\('#skips a\.skip'\)/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="copy-last-open"/);
  assert.match(page, />Copy last Open href</);
});

test('404 last skip href matches the last catalog skip-link href', () => {
  const href = catalogLastSkipHref();
  assert.equal(href, '#version-line');
  assert.equal(html.includes(`href="${href}"`), true, 'last skip href missing from catalog');
  assert.notEqual(href, catalogFirstSkipHref());
  assert.notEqual(href, catalogFirstOpenHref());
  assert.notEqual(href, catalogLastOpenHref());
  const page = notFoundPage();
  assert.equal(page.includes(href), true, 'last skip href missing from 404 page');
  assert.match(page, /id="copy-last-skip"/);
  assert.match(page, />Copy last skip href</);
  assert.match(page, /querySelectorAll\('#skips a\.skip'\)/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="copy-first-skip"/);
  assert.match(page, />Copy first skip href</);
});

test('404 first skip text matches the first catalog skip-link text', () => {
  const text = catalogFirstSkipText();
  assert.equal(text, "Skip to what's new");
  assert.equal(html.includes(text), true, 'first skip text missing from catalog');
  assert.notEqual(text, catalogFirstSkipHref());
  assert.notEqual(text, catalogLastSkipHref());
  assert.notEqual(text, catalogFirstOpenHref());
  const page = notFoundPage();
  assert.equal(page.includes(text), true, 'first skip text missing from 404 page');
  assert.match(page, /id="copy-first-skip-text"/);
  assert.match(page, />Copy first skip text</);
  assert.match(page, /querySelector\('#skips a\.skip'\)/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="copy-last-skip"/);
  assert.match(page, />Copy last skip href</);
});

test('404 last skip text matches the last catalog skip-link text', () => {
  const text = catalogLastSkipText();
  assert.equal(text, 'Skip to catalog versions');
  assert.equal(html.includes(text), true, 'last skip text missing from catalog');
  assert.notEqual(text, catalogLastSkipHref());
  assert.notEqual(text, catalogFirstSkipText());
  assert.notEqual(text, catalogFirstSkipHref());
  const page = notFoundPage();
  assert.equal(page.includes(text), true, 'last skip text missing from 404 page');
  assert.match(page, /id="copy-last-skip-text"/);
  assert.match(page, />Copy last skip text</);
  assert.match(page, /querySelectorAll\('#skips a\.skip'\)/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="copy-first-skip-text"/);
  assert.match(page, />Copy first skip text</);
});

test('404 first skip target text matches the labelled heading of the first skip href', () => {
  const text = catalogFirstSkipTargetText();
  assert.equal(text, "What's new");
  assert.equal(html.includes(`>${text}</h2>`), true, 'first skip target text missing from catalog');
  assert.notEqual(text, catalogFirstSkipText());
  assert.notEqual(text, catalogFirstSkipHref());
  assert.notEqual(text, catalogLastSkipText());
  assert.notEqual(text, catalogFirstWhatsNewHeading());
  const page = notFoundPage();
  assert.equal(page.includes(text), true, 'first skip target text missing from 404 page');
  assert.match(page, /id="copy-first-skip-target-text"/);
  assert.match(page, />Copy first skip target text</);
  assert.match(page, /firstSkipTargetTextMarkdown/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="whats-new"/);
  assert.match(page, /aria-labelledby="whats-new-title"/);
  assert.match(page, /id="copy-last-skip-text"/);
  assert.match(page, />Copy last skip text</);
});

test('404 last skip target text matches the labelled heading of the last skip href that has one', () => {
  const text = catalogLastSkipTargetText();
  assert.equal(text, 'Trust and limits');
  assert.equal(html.includes(`>${text}</h2>`), true, 'last skip target text missing from catalog');
  assert.notEqual(text, catalogLastSkipText());
  assert.notEqual(text, catalogLastSkipHref());
  assert.notEqual(text, catalogFirstSkipTargetText());
  assert.notEqual(text, catalogFirstSkipText());
  const page = notFoundPage();
  assert.equal(page.includes(text), true, 'last skip target text missing from 404 page');
  assert.match(page, /id="copy-last-skip-target-text"/);
  assert.match(page, />Copy last skip target text</);
  assert.match(page, /lastSkipTargetTextMarkdown/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="trust"/);
  assert.match(page, /aria-labelledby="trust-title"/);
  assert.match(page, /id="copy-first-skip-target-text"/);
  assert.match(page, />Copy first skip target text</);
});

test('404 first labelled skip target text matches the label of the first skip href that has aria-labelledby', () => {
  const text = catalogFirstLabelledSkipTargetText();
  assert.equal(text, "What's new");
  assert.equal(html.includes(`>${text}</h2>`), true, 'first labelled skip target text missing from catalog');
  assert.notEqual(text, catalogFirstSkipText());
  assert.notEqual(text, catalogFirstSkipHref());
  assert.notEqual(text, catalogLastSkipTargetText());
  assert.notEqual(text, catalogFirstWhatsNewHeading());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogFirstLabelledSkipTargetText');
  const end = serve.indexOf('export function catalogLastSkipTargetText');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /catalogSkipTargetText\(/);
  assert.doesNotMatch(body, /\^<h\[1-6\]/);
  const page = notFoundPage();
  assert.equal(page.includes(text), true, 'first labelled skip target text missing from 404 page');
  assert.match(page, /id="copy-first-labelled-skip-target-text"/);
  assert.match(page, />Copy first labelled skip target text</);
  assert.match(page, /firstLabelledSkipTargetTextMarkdown/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="whats-new"/);
  assert.match(page, /aria-labelledby="whats-new-title"/);
  assert.match(page, /id="copy-first-skip-target-text"/);
  assert.match(page, />Copy first skip target text</);
  assert.match(page, /id="copy-last-skip-target-text"/);
  assert.match(page, />Copy last skip target text</);
});

test('404 last labelled skip target text matches the label of the last skip href that has aria-labelledby', () => {
  const text = catalogLastLabelledSkipTargetText();
  assert.equal(text, 'Trust and limits');
  assert.equal(html.includes(`>${text}</h2>`), true, 'last labelled skip target text missing from catalog');
  assert.notEqual(text, catalogLastSkipText());
  assert.notEqual(text, catalogLastSkipHref());
  assert.notEqual(text, catalogFirstLabelledSkipTargetText());
  assert.notEqual(text, catalogFirstSkipTargetText());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogLastLabelledSkipTargetText');
  const end = serve.indexOf('export function notFoundPage');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /catalogMarkupText/);
  assert.match(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogSkipTargetText\(/);
  assert.doesNotMatch(body, /\^<h\[1-6\]/);
  const page = notFoundPage();
  assert.equal(page.includes(text), true, 'last labelled skip target text missing from 404 page');
  assert.match(page, /id="copy-last-labelled-skip-target-text"/);
  assert.match(page, />Copy last labelled skip target text</);
  assert.match(page, /lastLabelledSkipTargetTextMarkdown/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="trust"/);
  assert.match(page, /aria-labelledby="trust-title"/);
  assert.match(page, /id="copy-first-labelled-skip-target-text"/);
  assert.match(page, />Copy first labelled skip target text</);
  assert.match(page, /id="copy-last-skip-target-text"/);
  assert.match(page, />Copy last skip target text</);
});

test('404 first labelled skip href matches the first skip href whose target has aria-labelledby', () => {
  const href = catalogFirstLabelledSkipHref();
  assert.equal(href, '#whats-new');
  assert.equal(html.includes(`href="${href}"`), true, 'first labelled skip href missing from catalog');
  assert.equal(href, catalogFirstSkipHref());
  assert.notEqual(href, catalogLastSkipHref());
  assert.notEqual(href, catalogFirstLabelledSkipTargetText());
  assert.notEqual(href, catalogFirstSkipText());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogFirstLabelledSkipHref');
  const end = serve.indexOf('export function catalogFirstLabelledSkipText');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /return href/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /catalogSkipTargetText\(/);
  assert.doesNotMatch(body, /\^<h\[1-6\]/);
  const page = notFoundPage();
  assert.equal(page.includes(href), true, 'first labelled skip href missing from 404 page');
  assert.match(page, /id="copy-first-labelled-skip-href"/);
  assert.match(page, />Copy first labelled skip href</);
  assert.match(page, /firstLabelledSkipHrefMarkdown/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="whats-new"/);
  assert.match(page, /aria-labelledby="whats-new-title"/);
  assert.match(page, /id="copy-first-skip"/);
  assert.match(page, />Copy first skip href</);
  assert.match(page, /id="copy-last-skip"/);
  assert.match(page, />Copy last skip href</);
  assert.match(page, /id="copy-first-labelled-skip-target-text"/);
  assert.match(page, />Copy first labelled skip target text</);
});

test('404 last labelled skip href matches the last skip href whose target has aria-labelledby', () => {
  const href = catalogLastLabelledSkipHref();
  assert.equal(href, '#trust');
  assert.equal(html.includes(`href="${href}"`), true, 'last labelled skip href missing from catalog');
  assert.notEqual(href, catalogLastLabelledSkipTargetText());
  assert.notEqual(href, catalogLastSkipText());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogLastLabelledSkipHref');
  const end = serve.indexOf('export function catalogLastLabelledSkipText');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /return href/);
  assert.match(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /catalogSkipTargetText\(/);
  assert.doesNotMatch(body, /\^<h\[1-6\]/);
  const page = notFoundPage();
  assert.equal(page.includes(href), true, 'last labelled skip href missing from 404 page');
  assert.match(page, /id="copy-last-labelled-skip-href"/);
  assert.match(page, />Copy last labelled skip href</);
  assert.match(page, /lastLabelledSkipHrefMarkdown/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="trust"/);
  assert.match(page, /aria-labelledby="trust-title"/);
  assert.match(page, /id="copy-last-skip"/);
  assert.match(page, />Copy last skip href</);
  assert.match(page, /id="copy-first-labelled-skip-href"/);
  assert.match(page, />Copy first labelled skip href</);
  assert.match(page, /id="copy-last-labelled-skip-target-text"/);
  assert.match(page, />Copy last labelled skip target text</);
});

test('404 last labelled skip text matches the last skip text whose target has aria-labelledby', () => {
  const text = catalogLastLabelledSkipText();
  assert.equal(text, 'Skip to Trust and limits');
  assert.equal(html.includes(text), true, 'last labelled skip text missing from catalog');
  assert.notEqual(text, catalogLastLabelledSkipHref());
  assert.notEqual(text, catalogLastLabelledSkipTargetText());
  assert.notEqual(text, catalogLastSkipText());
  assert.notEqual(text, catalogFirstSkipText());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogLastLabelledSkipText');
  const end = serve.indexOf('export function catalogLastLabelledSkipTargetText');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /links\.length - 1/);
  assert.match(body, /return links\[i\]\.text/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /catalogSkipTargetText\(/);
  assert.doesNotMatch(body, /return href/);
  const page = notFoundPage();
  assert.equal(page.includes(text), true, 'last labelled skip text missing from 404 page');
  assert.match(page, /id="copy-last-labelled-skip-text"/);
  assert.match(page, />Copy last labelled skip text</);
  assert.match(page, /lastLabelledSkipTextMarkdown/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="trust"/);
  assert.match(page, /aria-labelledby="trust-title"/);
  assert.match(page, /id="copy-last-skip-text"/);
  assert.match(page, />Copy last skip text</);
  assert.match(page, /id="copy-last-labelled-skip-href"/);
  assert.match(page, />Copy last labelled skip href</);
  assert.match(page, /id="copy-last-labelled-skip-target-text"/);
  assert.match(page, />Copy last labelled skip target text</);
});

test('404 first labelled skip text matches the first skip text whose target has aria-labelledby', () => {
  const text = catalogFirstLabelledSkipText();
  assert.equal(text, "Skip to what's new");
  assert.equal(html.includes(text), true, 'first labelled skip text missing from catalog');
  assert.notEqual(text, catalogFirstLabelledSkipHref());
  assert.notEqual(text, catalogFirstLabelledSkipTargetText());
  assert.notEqual(text, catalogLastLabelledSkipText());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogFirstLabelledSkipText');
  const end = serve.indexOf('export function catalogLastLabelledSkipHref');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /return link\.text/);
  assert.doesNotMatch(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /catalogSkipTargetText\(/);
  assert.doesNotMatch(body, /return href/);
  const page = notFoundPage();
  assert.equal(page.includes(text), true, 'first labelled skip text missing from 404 page');
  assert.match(page, /id="copy-first-labelled-skip-text"/);
  assert.match(page, />Copy first labelled skip text</);
  assert.match(page, /firstLabelledSkipTextMarkdown/);
  assert.match(page, /firstLabelledSkipLink/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="whats-new"/);
  assert.match(page, /aria-labelledby="whats-new-title"/);
  assert.match(page, /id="copy-first-skip-text"/);
  assert.match(page, />Copy first skip text</);
  assert.match(page, /id="copy-first-labelled-skip-href"/);
  assert.match(page, />Copy first labelled skip href</);
  assert.match(page, /id="copy-last-labelled-skip-text"/);
  assert.match(page, />Copy last labelled skip text</);
});

test('404 first unlabelled skip text matches the first skip text whose target has no aria-labelledby', () => {
  const text = catalogFirstUnlabelledSkipText();
  assert.equal(text, 'Skip to catalog versions');
  assert.equal(html.includes(text), true, 'first unlabelled skip text missing from catalog');
  assert.equal(text, catalogLastSkipText());
  assert.notEqual(text, catalogFirstLabelledSkipText());
  assert.notEqual(text, catalogFirstSkipText());
  assert.notEqual(text, catalogFirstLabelledSkipHref());
  assert.notEqual(text, catalogFirstSkipTargetText());
  assert.notEqual(text, catalogFirstLabelledSkipTargetText());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogFirstUnlabelledSkipText');
  const end = serve.indexOf('export function catalogFirstUnlabelledSkipTargetText');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /return link\.text/);
  assert.doesNotMatch(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogLastSkipText/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /return href/);
  const page = notFoundPage();
  assert.equal(page.includes(text), true, 'first unlabelled skip text missing from 404 page');
  assert.match(page, /id="copy-first-unlabelled-skip-text"/);
  assert.match(page, />Copy first unlabelled skip text</);
  assert.match(page, /firstUnlabelledSkipTextMarkdown/);
  assert.match(page, /id="copy-first-labelled-skip-text"/);
  assert.match(page, />Copy first labelled skip text</);
  assert.match(page, /id="version-line"/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="whats-new"/);
  assert.match(page, /aria-labelledby="whats-new-title"/);
  assert.match(page, /id="workbenches"/);
  assert.match(page, /aria-labelledby="workbenches-title"/);
  assert.match(page, /id="how-it-works"/);
  assert.match(page, /aria-labelledby="how-title"/);
  assert.match(page, /id="copy-first-skip-text"/);
  assert.match(page, />Copy first skip text</);
});

test('404 last unlabelled skip text matches the last skip text whose target has no aria-labelledby', () => {
  const text = catalogLastUnlabelledSkipText();
  assert.equal(text, 'Skip to catalog versions');
  assert.equal(html.includes(text), true, 'last unlabelled skip text missing from catalog');
  assert.equal(text, catalogLastSkipText());
  assert.equal(text, catalogFirstUnlabelledSkipText());
  assert.notEqual(text, catalogFirstLabelledSkipText());
  assert.notEqual(text, catalogLastLabelledSkipText());
  assert.notEqual(text, catalogFirstSkipText());
  assert.notEqual(text, catalogLastLabelledSkipHref());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogLastUnlabelledSkipText');
  const end = serve.indexOf('export function catalogFirstUnlabelledSkipText');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /links\.length - 1/);
  assert.match(body, /return links\[i\]\.text/);
  assert.doesNotMatch(body, /catalogLastSkipText/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /return href/);
  const page = notFoundPage();
  assert.equal(page.includes(text), true, 'last unlabelled skip text missing from 404 page');
  assert.match(page, /id="copy-last-unlabelled-skip-text"/);
  assert.match(page, />Copy last unlabelled skip text</);
  assert.match(page, /lastUnlabelledSkipTextMarkdown/);
  assert.match(page, /id="copy-first-unlabelled-skip-text"/);
  assert.match(page, />Copy first unlabelled skip text</);
  assert.match(page, /id="copy-last-labelled-skip-text"/);
  assert.match(page, />Copy last labelled skip text</);
  assert.match(page, /id="version-line"/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="whats-new"/);
  assert.match(page, /aria-labelledby="whats-new-title"/);
  assert.match(page, /id="copy-last-skip-text"/);
  assert.match(page, />Copy last skip text</);
});

test('404 first unlabelled skip href matches the first skip href whose target has no aria-labelledby', () => {
  const href = catalogFirstUnlabelledSkipHref();
  assert.equal(href, '#version-line');
  assert.equal(html.includes(`href="${href}"`), true, 'first unlabelled skip href missing from catalog');
  assert.equal(href, catalogLastSkipHref());
  assert.notEqual(href, catalogFirstLabelledSkipHref());
  assert.notEqual(href, catalogFirstSkipHref());
  assert.notEqual(href, catalogFirstUnlabelledSkipText());
  assert.notEqual(href, catalogFirstLabelledSkipTargetText());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogFirstUnlabelledSkipHref');
  const end = serve.indexOf('export function catalogLastUnlabelledSkipHref');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /return href/);
  assert.doesNotMatch(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogLastSkipHref/);
  assert.doesNotMatch(body, /return link\.text/);
  const page = notFoundPage();
  assert.equal(page.includes(href), true, 'first unlabelled skip href missing from 404 page');
  assert.match(page, /id="copy-first-unlabelled-skip-href"/);
  assert.match(page, />Copy first unlabelled skip href</);
  assert.match(page, /firstUnlabelledSkipHrefMarkdown/);
  assert.match(page, /id="copy-first-unlabelled-skip-text"/);
  assert.match(page, />Copy first unlabelled skip text</);
  assert.match(page, /id="copy-first-labelled-skip-href"/);
  assert.match(page, />Copy first labelled skip href</);
  assert.match(page, /id="copy-first-skip"/);
  assert.match(page, />Copy first skip href</);
  assert.match(page, /id="version-line"/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="whats-new"/);
  assert.match(page, /aria-labelledby="whats-new-title"/);
});

test('404 last unlabelled skip href matches the last skip href whose target has no aria-labelledby', () => {
  const href = catalogLastUnlabelledSkipHref();
  assert.equal(href, '#version-line');
  assert.equal(html.includes(`href="${href}"`), true, 'last unlabelled skip href missing from catalog');
  assert.equal(href, catalogFirstUnlabelledSkipHref());
  assert.equal(href, catalogLastSkipHref());
  assert.notEqual(href, catalogFirstLabelledSkipHref());
  assert.notEqual(href, catalogLastLabelledSkipHref());
  assert.notEqual(href, catalogFirstSkipHref());
  assert.notEqual(href, catalogLastUnlabelledSkipText());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogLastUnlabelledSkipHref');
  const end = serve.indexOf('export function catalogLastUnlabelledSkipText');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /links\.length - 1/);
  assert.match(body, /return href/);
  assert.doesNotMatch(body, /catalogLastSkipHref/);
  assert.doesNotMatch(body, /return link\.text/);
  assert.doesNotMatch(body, /return links\[i\]\.text/);
  const page = notFoundPage();
  assert.equal(page.includes(href), true, 'last unlabelled skip href missing from 404 page');
  assert.match(page, /id="copy-last-unlabelled-skip-href"/);
  assert.match(page, />Copy last unlabelled skip href</);
  assert.match(page, /lastUnlabelledSkipHrefMarkdown/);
  assert.match(page, /id="copy-first-unlabelled-skip-href"/);
  assert.match(page, />Copy first unlabelled skip href</);
  assert.match(page, /id="copy-last-labelled-skip-href"/);
  assert.match(page, />Copy last labelled skip href</);
  assert.match(page, /id="copy-last-skip"/);
  assert.match(page, />Copy last skip href</);
  assert.match(page, /id="version-line"/);
  assert.match(page, /id="skips"/);
  assert.match(page, /id="whats-new"/);
  assert.match(page, /aria-labelledby="whats-new-title"/);
  assert.equal(page.indexOf('id="copy-first-unlabelled-skip-href"') < page.indexOf('id="copy-last-unlabelled-skip-href"'), true);
});


test('404 first unlabelled skip target text matches the first skip target that has no aria-labelledby', () => {
  const text = catalogFirstUnlabelledSkipTargetText();
  assert.match(text, /Each workbench versions itself/);
  assert.equal(text.includes(catalogVersionLine()), true);
  assert.notEqual(text, catalogVersionLine());
  assert.equal(html.includes(text), true, 'first unlabelled skip target text missing from catalog');
  assert.notEqual(text, catalogFirstUnlabelledSkipHref());
  assert.notEqual(text, catalogFirstUnlabelledSkipText());
  assert.notEqual(text, catalogFirstSkipTargetText());
  assert.notEqual(text, catalogFirstLabelledSkipTargetText());
  assert.notEqual(text, catalogLastSkipTargetText());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogFirstUnlabelledSkipTargetText');
  const end = serve.indexOf('export function catalogLastUnlabelledSkipTargetText');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /catalogMarkupText/);
  assert.match(body, /return catalogMarkupText/);
  assert.doesNotMatch(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogFirstSkipTargetText/);
  assert.doesNotMatch(body, /return href/);
  assert.doesNotMatch(body, /return link\.text/);
  const page = notFoundPage();
  assert.match(page, /id="copy-first-unlabelled-skip-target-text"/);
  assert.match(page, />Copy first unlabelled skip target text</);
  assert.match(page, /firstUnlabelledSkipTargetTextMarkdown/);
  assert.match(page, /id="copy-first-unlabelled-skip-href"/);
  assert.match(page, />Copy first unlabelled skip href</);
  assert.match(page, /id="copy-first-skip-target-text"/);
  assert.match(page, />Copy first skip target text</);
  assert.match(page, /id="copy-first-labelled-skip-target-text"/);
  assert.match(page, />Copy first labelled skip target text</);
  assert.match(page, /id="version-line"/);
  assert.match(page, /id="skips"/);
  assert.equal(page.indexOf('id="copy-last-unlabelled-skip-href"') < page.indexOf('id="copy-first-unlabelled-skip-target-text"'), true);
  assert.equal(page.indexOf('id="copy-first-unlabelled-skip-target-text"') < page.indexOf('id="copy-last-unlabelled-skip-target-text"'), true);
});

test('404 last unlabelled skip target text matches the last skip target that has no aria-labelledby', () => {
  const text = catalogLastUnlabelledSkipTargetText();
  assert.match(text, /Each workbench versions itself/);
  assert.equal(text.includes(catalogVersionLine()), true);
  assert.notEqual(text, catalogVersionLine());
  assert.equal(html.includes(text), true, 'last unlabelled skip target text missing from catalog');
  assert.equal(text, catalogFirstUnlabelledSkipTargetText());
  assert.notEqual(text, catalogLastUnlabelledSkipHref());
  assert.notEqual(text, catalogLastUnlabelledSkipText());
  assert.notEqual(text, catalogLastSkipTargetText());
  assert.notEqual(text, catalogLastLabelledSkipTargetText());
  const serve = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serve.indexOf('export function catalogLastUnlabelledSkipTargetText');
  const end = serve.indexOf('export function catalogFirstUnlabelledSkipTargetId');
  const body = serve.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /catalogMarkupText/);
  assert.match(body, /return catalogMarkupText/);
  assert.match(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogLastSkipTargetText/);
  assert.doesNotMatch(body, /return href/);
  assert.doesNotMatch(body, /return links\[i\]\.text/);
  const page = notFoundPage();
  assert.match(page, /id="copy-last-unlabelled-skip-target-text"/);
  assert.match(page, />Copy last unlabelled skip target text</);
  assert.match(page, /lastUnlabelledSkipTargetTextMarkdown/);
  assert.match(page, /id="copy-first-unlabelled-skip-target-text"/);
  assert.match(page, />Copy first unlabelled skip target text</);
  assert.match(page, /id="copy-last-unlabelled-skip-href"/);
  assert.match(page, />Copy last unlabelled skip href</);
  assert.match(page, /id="copy-last-skip-target-text"/);
  assert.match(page, />Copy last skip target text</);
  assert.match(page, /id="copy-last-labelled-skip-target-text"/);
  assert.match(page, />Copy last labelled skip target text</);
  assert.match(page, /id="copy-last-unlabelled-skip-text"/);
  assert.match(page, />Copy last unlabelled skip text</);
  assert.match(page, /id="version-line"/);
  assert.match(page, /id="skips"/);
  assert.equal(page.indexOf('id="copy-first-unlabelled-skip-target-text"') < page.indexOf('id="copy-last-unlabelled-skip-target-text"'), true);
});

test('404 first unlabelled skip target id matches the first skip target that has no aria-labelledby', () => {
  const id = catalogFirstUnlabelledSkipTargetId();
  assert.equal(id, 'version-line');
  assert.equal(html.includes(`id="${id}"`), true, 'first unlabelled skip target id missing from catalog');
  assert.notEqual(id, catalogFirstUnlabelledSkipHref());
  assert.notEqual(id, catalogFirstUnlabelledSkipTargetText());
  assert.notEqual(id, catalogFirstUnlabelledSkipText());
  assert.notEqual(id, catalogFirstSkipTargetText());
  assert.notEqual(id, catalogLastUnlabelledSkipTargetText());
  const serveSrc = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serveSrc.indexOf('export function catalogFirstUnlabelledSkipTargetId');
  const end = serveSrc.indexOf('export function catalogLastUnlabelledSkipTargetId');
  const body = serveSrc.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /return href\.slice\(1\)/);
  assert.doesNotMatch(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /return link\.text/);
  const page = notFoundPage();
  assert.match(page, /id="copy-first-unlabelled-skip-target-id"/);
  assert.match(page, />Copy first unlabelled skip target id</);
  assert.match(page, /firstUnlabelledSkipTargetIdMarkdown/);
  assert.match(page, /id="copy-first-unlabelled-skip-target-text"/);
  assert.match(page, />Copy first unlabelled skip target text</);
  assert.match(page, /id="copy-first-unlabelled-skip-href"/);
  assert.match(page, />Copy first unlabelled skip href</);
  assert.match(page, /id="version-line"/);
  assert.match(page, /id="skips"/);
  assert.equal(page.indexOf('id="copy-last-unlabelled-skip-target-text"') < page.indexOf('id="copy-first-unlabelled-skip-target-id"'), true);
});

test('404 last unlabelled skip target id matches the last skip target that has no aria-labelledby', () => {
  const id = catalogLastUnlabelledSkipTargetId();
  assert.equal(id, 'version-line');
  assert.equal(html.includes(`id="${id}"`), true, 'last unlabelled skip target id missing from catalog');
  assert.equal(id, catalogFirstUnlabelledSkipTargetId());
  assert.notEqual(id, catalogLastUnlabelledSkipHref());
  assert.notEqual(id, catalogLastUnlabelledSkipTargetText());
  assert.notEqual(id, catalogLastUnlabelledSkipText());
  assert.notEqual(id, catalogLastSkipTargetText());
  const serveSrc = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serveSrc.indexOf('export function catalogLastUnlabelledSkipTargetId');
  const end = serveSrc.indexOf('export function catalogFirstLabelledSkipTargetId');
  const body = serveSrc.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /return href\.slice\(1\)/);
  assert.match(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /return link\.text/);
  const page = notFoundPage();
  assert.match(page, /id="copy-last-unlabelled-skip-target-id"/);
  assert.match(page, />Copy last unlabelled skip target id</);
  assert.match(page, /lastUnlabelledSkipTargetIdMarkdown/);
  assert.match(page, /id="copy-first-unlabelled-skip-target-id"/);
  assert.match(page, />Copy first unlabelled skip target id</);
  assert.match(page, /id="copy-last-unlabelled-skip-target-text"/);
  assert.match(page, />Copy last unlabelled skip target text</);
  assert.match(page, /id="copy-last-unlabelled-skip-href"/);
  assert.match(page, />Copy last unlabelled skip href</);
  assert.match(page, /id="version-line"/);
  assert.match(page, /id="skips"/);
  assert.equal(page.indexOf('id="copy-first-unlabelled-skip-target-id"') < page.indexOf('id="copy-last-unlabelled-skip-target-id"'), true);
});


test('404 first labelled skip target id matches the first skip target that has aria-labelledby', () => {
  const id = catalogFirstLabelledSkipTargetId();
  assert.equal(id, 'whats-new');
  assert.equal(html.includes(`id="${id}"`), true, 'first labelled skip target id missing from catalog');
  assert.notEqual(id, catalogFirstLabelledSkipHref());
  assert.notEqual(id, catalogFirstLabelledSkipTargetText());
  assert.notEqual(id, catalogFirstLabelledSkipText());
  assert.notEqual(id, catalogFirstUnlabelledSkipTargetId());
  assert.notEqual(id, catalogFirstSkipTargetText());
  const serveSrc = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serveSrc.indexOf('export function catalogFirstLabelledSkipTargetId');
  const end = serveSrc.indexOf('export function catalogLastLabelledSkipTargetId');
  const body = serveSrc.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /return href\.slice\(1\)/);
  assert.match(body, /if \(!found\.tag\.match/);
  assert.doesNotMatch(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /return link\.text/);
  const page = notFoundPage();
  assert.match(page, /id="copy-first-labelled-skip-target-id"/);
  assert.match(page, />Copy first labelled skip target id</);
  assert.match(page, /firstLabelledSkipTargetIdMarkdown/);
  assert.match(page, /id="copy-last-unlabelled-skip-target-id"/);
  assert.match(page, />Copy last unlabelled skip target id</);
  assert.match(page, /id="copy-first-labelled-skip-href"/);
  assert.match(page, />Copy first labelled skip href</);
  assert.match(page, /id="whats-new"/);
  assert.match(page, /id="skips"/);
  assert.equal(page.indexOf('id="copy-last-unlabelled-skip-target-id"') < page.indexOf('id="copy-first-labelled-skip-target-id"'), true);
});

test('404 last labelled skip target id matches the last skip target that has aria-labelledby', () => {
  const id = catalogLastLabelledSkipTargetId();
  assert.equal(id, 'trust');
  assert.equal(html.includes(`id="${id}"`), true, 'last labelled skip target id missing from catalog');
  assert.notEqual(id, catalogFirstLabelledSkipTargetId());
  assert.notEqual(id, catalogLastUnlabelledSkipTargetId());
  assert.notEqual(id, catalogLastLabelledSkipHref());
  assert.notEqual(id, catalogLastLabelledSkipTargetText());
  assert.notEqual(id, catalogLastLabelledSkipText());
  const serveSrc = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serveSrc.indexOf('export function catalogLastLabelledSkipTargetId');
  const end = serveSrc.indexOf('export function catalogLastLabelledSkipLabelledbyId');
  const body = serveSrc.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /return href\.slice\(1\)/);
  assert.match(body, /links\.length - 1/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /return link\.text/);
  assert.doesNotMatch(body, /return match\[1\]/);
  const page = notFoundPage();
  assert.match(page, /id="copy-last-labelled-skip-target-id"/);
  assert.match(page, />Copy last labelled skip target id</);
  assert.match(page, /lastLabelledSkipTargetIdMarkdown/);
  assert.match(page, /id="copy-first-labelled-skip-target-id"/);
  assert.match(page, />Copy first labelled skip target id</);
  assert.match(page, /id="copy-last-unlabelled-skip-target-id"/);
  assert.match(page, />Copy last unlabelled skip target id</);
  assert.match(page, /id="trust"/);
  assert.match(page, /id="skips"/);
  assert.equal(page.indexOf('id="copy-first-labelled-skip-target-id"') < page.indexOf('id="copy-last-labelled-skip-target-id"'), true);
});


test('404 last labelled skip labelledby id matches the aria-labelledby id of the last skip target that has aria-labelledby', () => {
  const id = catalogLastLabelledSkipLabelledbyId();
  assert.equal(id, 'trust-title');
  assert.equal(html.includes(`id="${id}"`), true, 'last labelled skip labelledby id missing from catalog');
  assert.notEqual(id, 'trust');
  assert.notEqual(id, catalogLastLabelledSkipTargetId());
  assert.notEqual(id, catalogFirstLabelledSkipTargetId());
  assert.notEqual(id, catalogLastUnlabelledSkipTargetId());
  assert.notEqual(id, catalogLastLabelledSkipHref());
  assert.notEqual(id, catalogLastLabelledSkipTargetText());
  assert.notEqual(id, catalogLastLabelledSkipText());
  const serveSrc = readFileSync(new URL('../scripts/serve.mjs', import.meta.url), 'utf8');
  const start = serveSrc.indexOf('export function catalogLastLabelledSkipLabelledbyId');
  const end = serveSrc.indexOf('export function notFoundPage');
  const body = serveSrc.slice(start, end);
  assert.match(body, /aria-labelledby/);
  assert.match(body, /continue/);
  assert.match(body, /links\.length - 1/);
  assert.match(body, /return match\[1\]/);
  assert.doesNotMatch(body, /return href\.slice\(1\)/);
  assert.doesNotMatch(body, /catalogMarkupText/);
  assert.doesNotMatch(body, /return link\.text/);
  const page = notFoundPage();
  assert.match(page, /id="copy-last-labelled-skip-labelledby-id"/);
  assert.match(page, />Copy last labelled skip labelledby id</);
  assert.match(page, /lastLabelledSkipLabelledbyIdMarkdown/);
  assert.match(page, /id="copy-last-labelled-skip-target-id"/);
  assert.match(page, />Copy last labelled skip target id</);
  assert.match(page, /id="copy-first-labelled-skip-target-id"/);
  assert.match(page, />Copy first labelled skip target id</);
  assert.match(page, /id="copy-last-unlabelled-skip-target-id"/);
  assert.match(page, />Copy last unlabelled skip target id</);
  assert.match(page, /id="trust"/);
  assert.match(page, /id="trust-title"/);
  assert.match(page, /id="skips"/);
  assert.equal(page.indexOf('id="copy-last-labelled-skip-target-id"') < page.indexOf('id="copy-last-labelled-skip-labelledby-id"'), true);
});
test('404 first Open href matches the first catalog Open workbench href', () => {
  const href = catalogFirstOpenHref();
  assert.equal(href, 'apps/partnership-breakpoint/standalone.html');
  assert.equal(html.includes(`href="${href}"`), true, 'first Open href missing from catalog');
  assert.notEqual(href, catalogFirstReviewPath());
  assert.notEqual(href, catalogFirstWorkbenchHeading());
  const page = notFoundPage();
  assert.equal(page.includes(href), true, 'first Open href missing from 404 page');
  assert.match(page, /id="copy-first-open"/);
  assert.match(page, />Copy first Open href</);
  assert.match(page, /querySelector\('#workbenches a\.open'\)/);
  assert.match(page, /id="workbenches"/);
  assert.match(page, /id="copy-first-review"/);
  assert.match(page, />Copy first review path</);
});

test('404 first review path matches the first catalog workbench review path', () => {
  const path = catalogFirstReviewPath();
  assert.match(path, /Review constraints and negotiation room/);
  assert.equal(html.includes('Review constraints and negotiation room'), true, 'first review path missing from catalog');
  assert.notEqual(path, catalogFirstWorkbenchHeading());
  assert.notEqual(path, catalogLastReviewPath());
  const page = notFoundPage();
  assert.equal(page.includes(path), true, 'first review path missing from 404 page');
  assert.match(page, /id="copy-first-review"/);
  assert.match(page, />Copy first review path</);
  assert.match(page, /querySelector\('#workbenches article\.workbench \.review-path'\)/);
  assert.match(page, /id="workbenches"/);
  assert.match(page, /id="copy-last-review"/);
  assert.match(page, />Copy last review path</);
});

test('404 last review path matches the last catalog workbench review path', () => {
  const path = catalogLastReviewPath();
  assert.match(path, /Review the timing behind the queue/);
  assert.equal(html.includes('Review the timing behind the queue'), true, 'last review path missing from catalog');
  assert.notEqual(path, catalogLastWorkbenchHeading());
  const page = notFoundPage();
  assert.equal(page.includes(path), true, 'last review path missing from 404 page');
  assert.match(page, /id="copy-last-review"/);
  assert.match(page, />Copy last review path</);
  assert.match(page, /querySelectorAll\('#workbenches article\.workbench \.review-path'\)/);
  assert.match(page, /id="workbenches"/);
  assert.match(page, /id="copy-last-workbench"/);
  assert.match(page, />Copy last workbench heading</);
});


test('catalog versions stay Partnership Breakpoint 1.5.42, Common Cart 1.4.42, The Smallest Agreement 1.5.42, Weekend Gap 1.5.41', () => {
  assert.match(html, /data-app="partnership-breakpoint">\s*1\.5\.42\s*</);
  assert.match(html, /data-app="common-cart">\s*1\.4\.42\s*</);
  assert.match(html, /data-app="smallest-agreement">\s*1\.5\.42\s*</);
  assert.match(html, /data-app="weekend-gap">\s*1\.5\.41\s*</);
  assert.match(html, /data-app-version="partnership-breakpoint">\s*1\.5\.42\s*</);
  assert.match(html, /data-app-version="common-cart">\s*1\.4\.42\s*</);
  assert.match(html, /data-app-version="smallest-agreement">\s*1\.5\.42\s*</);
  assert.match(html, /data-app-version="weekend-gap">\s*1\.5\.41\s*</);
  assert.match(html, /Partnership Breakpoint 1\.5\.42, Common Cart 1\.4\.42, The Smallest Agreement 1\.5\.42, Weekend Gap 1.5\.41/);
  assert.match(readme, /\[Partnership Breakpoint\]\(apps\/partnership-breakpoint\/\) \| 1\.5\.42 \|/);
  assert.match(readme, /\[Common Cart\]\(apps\/common-cart\/\) \| 1\.4\.42 \|/);
  assert.match(readme, /\[The Smallest Agreement\]\(apps\/smallest-agreement\/\) \| 1\.5\.42 \|/);
  assert.match(readme, /\[Weekend Gap\]\(apps\/weekend-gap\/\) \| 1\.5\.41 \|/);
});
