import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { isStandaloneCurrent, renderStandalone, buildStandalone } from '../scripts/build-standalone.mjs';

const html = '<html><head><title>Partnership Breakpoint</title><link rel="stylesheet" href="styles.css" /></head><body><a href="MODEL.md">Read the full model</a><script type="module" src="src/app.js"></script></body></html>';
const appImport = `import {
  createPartnershipReviewPacket,
  replayPartnershipReviewPacket,
  PARTNERSHIP_REVIEW_TOOLS,
  analyzePartnershipReview,
  PRESETS,
  DEFAULT_STRESS,
  MAX_PARTICIPANTS,
  ValidationError,
  applyStressProposal,
  calculatePartnership,
  calculateFeeRequirements,
  clonePreset,
  compareImportedCase,
  compareThreeSnapshots,
  duplicateDisplayNames,
  duplicateParticipant,
  dropAndReallocate,
  evaluateStressGrid,
  exportDownloadName,
  makeParticipant,
  materializeStressCase,
  moveParticipant,
  swapAdjacentParticipants,
  participantsFromCsv,
  participantsFromRosterText,
  participantsToCsv,
  redactConfiguration,
  solveFeeForAllHold,
  solveMinimumShareToHold,
  solveMinimumVolumeToHold,
  stressGridCsv,
  uniqueCopyName,
  validateConfiguration,
} from './model.js';

`;

test('release 1.5.54 ships bottle-hand cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.54/);
  assert.match(readme, /Decision workflow \(v1\.5\.54\)/);
  assert.match(readme, /Bottle-hand cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.54/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Bottle-hand cycling carnival starting point is loaded/);
  const firstHeading = changelog.match(/^## .+$/m)?.[0];
  assert.equal(firstHeading, '## 1.5.54');
  assert.match(changelog, /Bottle-hand cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.54/);
  assert.match(html, /bottleHandCyclingCarnivalSplit/);
  assert.match(html, /Bottle-hand cycling carnival split/);
  assert.match(html, /domestiqueCyclingCarnivalSplit/);
  const bottleHandPresetAt = html.indexOf('bottleHandCyclingCarnivalSplit:');
  const domestiquePresetAt = html.indexOf('domestiqueCyclingCarnivalSplit:');
  const soigneurPresetAt = html.indexOf('soigneurCyclingCarnivalSplit:');
  assert.notEqual(bottleHandPresetAt, -1);
  assert.notEqual(domestiquePresetAt, -1);
  assert.notEqual(soigneurPresetAt, -1);
  assert.ok(domestiquePresetAt < bottleHandPresetAt);
  assert.ok(soigneurPresetAt < domestiquePresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.18/);
  assert.match(html, /id: 'bottle-hand-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.18/);
  assert.match(html, /id: 'domestique-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.20/);
  assert.match(html, /id: 'soigneur-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.22/);
  assert.match(html, /id: 'lead-out-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.24/);
  assert.match(html, /id: 'feed-zone-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.26/);
  assert.match(html, /id: 'first-aid-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.28/);
  assert.match(html, /id: 'team-sprint-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.30/);
  assert.match(html, /id: 'team-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.32/);
  assert.match(html, /id: 'individual-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.34/);
  assert.match(html, /id: 'scratch-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});
test('release 1.5.53 ships domestique cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.53/);
  assert.match(readme, /Domestique cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.53/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Domestique cycling carnival starting point is loaded/);
  assert.match(changelog, /Domestique cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.53/);
  assert.match(html, /domestiqueCyclingCarnivalSplit/);
  assert.match(html, /Domestique cycling carnival split/);
  assert.match(html, /soigneurCyclingCarnivalSplit/);
  const domestiquePresetAt = html.indexOf('domestiqueCyclingCarnivalSplit:');
  const soigneurPresetAt = html.indexOf('soigneurCyclingCarnivalSplit:');
  const leadOutPresetAt = html.indexOf('leadOutCyclingCarnivalSplit:');
  assert.notEqual(domestiquePresetAt, -1);
  assert.notEqual(soigneurPresetAt, -1);
  assert.notEqual(leadOutPresetAt, -1);
  assert.ok(soigneurPresetAt < domestiquePresetAt);
  assert.ok(leadOutPresetAt < soigneurPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.20/);
  assert.match(html, /id: 'domestique-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.20/);
  assert.match(html, /id: 'soigneur-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.22/);
  assert.match(html, /id: 'lead-out-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.24/);
  assert.match(html, /id: 'feed-zone-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.26/);
  assert.match(html, /id: 'first-aid-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.28/);
  assert.match(html, /id: 'team-sprint-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.30/);
  assert.match(html, /id: 'team-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.32/);
  assert.match(html, /id: 'individual-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.34/);
  assert.match(html, /id: 'scratch-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});
test('release 1.5.52 ships soigneur cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.52/);
  assert.match(readme, /Soigneur cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.52/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Soigneur cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.52/);
  assert.match(changelog, /Soigneur cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.52/);
  assert.match(html, /soigneurCyclingCarnivalSplit/);
  assert.match(html, /Soigneur cycling carnival split/);
  assert.match(html, /leadOutCyclingCarnivalSplit/);
  const soigneurPresetAt = html.indexOf('soigneurCyclingCarnivalSplit:');
  const leadOutPresetAt = html.indexOf('leadOutCyclingCarnivalSplit:');
  const feedZonePresetAt = html.indexOf('feedZoneCyclingCarnivalSplit:');
  assert.notEqual(soigneurPresetAt, -1);
  assert.notEqual(leadOutPresetAt, -1);
  assert.notEqual(feedZonePresetAt, -1);
  assert.ok(leadOutPresetAt < soigneurPresetAt);
  assert.ok(feedZonePresetAt < leadOutPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.22/);
  assert.match(html, /id: 'soigneur-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.22/);
  assert.match(html, /id: 'lead-out-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.24/);
  assert.match(html, /id: 'feed-zone-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.26/);
  assert.match(html, /id: 'first-aid-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.28/);
  assert.match(html, /id: 'team-sprint-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.30/);
  assert.match(html, /id: 'team-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.32/);
  assert.match(html, /id: 'individual-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.34/);
  assert.match(html, /id: 'scratch-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});
test('release 1.5.51 ships lead-out cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.51/);
  assert.match(readme, /Lead-out cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.51/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Lead-out cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.51/);
  assert.match(changelog, /Lead-out cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.51/);
  assert.match(html, /leadOutCyclingCarnivalSplit/);
  assert.match(html, /Lead-out cycling carnival split/);
  assert.match(html, /feedZoneCyclingCarnivalSplit/);
  const leadOutPresetAt = html.indexOf('leadOutCyclingCarnivalSplit:');
  const feedZonePresetAt = html.indexOf('feedZoneCyclingCarnivalSplit:');
  const firstAidPresetAt = html.indexOf('firstAidCyclingCarnivalSplit:');
  assert.notEqual(leadOutPresetAt, -1);
  assert.notEqual(feedZonePresetAt, -1);
  assert.notEqual(firstAidPresetAt, -1);
  assert.ok(feedZonePresetAt < leadOutPresetAt);
  assert.ok(firstAidPresetAt < feedZonePresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.24/);
  assert.match(html, /id: 'lead-out-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.24/);
  assert.match(html, /id: 'feed-zone-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.26/);
  assert.match(html, /id: 'first-aid-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.28/);
  assert.match(html, /id: 'team-sprint-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.30/);
  assert.match(html, /id: 'team-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.32/);
  assert.match(html, /id: 'individual-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.34/);
  assert.match(html, /id: 'scratch-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});
test('release 1.5.50 ships feed-zone cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.50/);
  assert.match(readme, /Feed-zone cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.50/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Feed-zone cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.50/);
  assert.match(changelog, /Feed-zone cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.50/);
  assert.match(html, /feedZoneCyclingCarnivalSplit/);
  assert.match(html, /Feed-zone cycling carnival split/);
  assert.match(html, /firstAidCyclingCarnivalSplit/);
  const feedZonePresetAt = html.indexOf('feedZoneCyclingCarnivalSplit:');
  const firstAidPresetAt = html.indexOf('firstAidCyclingCarnivalSplit:');
  const sprintPresetAt49 = html.indexOf('teamSprintCyclingCarnivalSplit:');
  assert.notEqual(feedZonePresetAt, -1);
  assert.notEqual(firstAidPresetAt, -1);
  assert.notEqual(sprintPresetAt49, -1);
  assert.ok(firstAidPresetAt < feedZonePresetAt);
  assert.ok(sprintPresetAt49 < firstAidPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.26/);
  assert.match(html, /id: 'feed-zone-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.26/);
  assert.match(html, /id: 'first-aid-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.28/);
  assert.match(html, /id: 'team-sprint-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.30/);
  assert.match(html, /id: 'team-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.32/);
  assert.match(html, /id: 'individual-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.34/);
  assert.match(html, /id: 'scratch-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});
test('release 1.5.49 ships first-aid cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.49/);
  assert.match(readme, /First-aid cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.49/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the First-aid cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.49/);
  assert.match(changelog, /First-aid cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.49/);
  assert.match(html, /firstAidCyclingCarnivalSplit/);
  assert.match(html, /First-aid cycling carnival split/);
  assert.match(html, /teamSprintCyclingCarnivalSplit/);
  const firstAidPresetAt = html.indexOf('firstAidCyclingCarnivalSplit:');
  const sprintPresetAt49 = html.indexOf('teamSprintCyclingCarnivalSplit:');
  assert.notEqual(firstAidPresetAt, -1);
  assert.notEqual(sprintPresetAt49, -1);
  assert.ok(sprintPresetAt49 < firstAidPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.28/);
  assert.match(html, /id: 'first-aid-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.28/);
  assert.match(html, /id: 'team-sprint-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.30/);
  assert.match(html, /id: 'team-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.32/);
  assert.match(html, /id: 'individual-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.34/);
  assert.match(html, /id: 'scratch-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.48 ships team-sprint cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.48/);
  assert.match(readme, /Team-sprint cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.48/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Team-sprint cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.48/);
  assert.match(changelog, /Team-sprint cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.48/);
  assert.match(html, /teamSprintCyclingCarnivalSplit/);
  assert.match(html, /Team-sprint cycling carnival split/);
  assert.match(html, /teamPursuitCyclingCarnivalSplit/);
  const sprintPresetAt = html.indexOf('teamSprintCyclingCarnivalSplit:');
  const teamPresetAt48 = html.indexOf('teamPursuitCyclingCarnivalSplit:');
  assert.notEqual(sprintPresetAt, -1);
  assert.notEqual(teamPresetAt48, -1);
  assert.ok(teamPresetAt48 < sprintPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.30/);
  assert.match(html, /id: 'team-sprint-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.30/);
  assert.match(html, /id: 'team-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.32/);
  assert.match(html, /id: 'individual-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.34/);
  assert.match(html, /id: 'scratch-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.47 ships team-pursuit cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.47/);
  assert.match(readme, /Team-pursuit cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.47/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Team-pursuit cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.47/);
  assert.match(changelog, /Team-pursuit cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.47/);
  assert.match(html, /teamPursuitCyclingCarnivalSplit/);
  assert.match(html, /Team-pursuit cycling carnival split/);
  assert.match(html, /individualPursuitCyclingCarnivalSplit/);
  const teamPresetAt = html.indexOf('teamPursuitCyclingCarnivalSplit:');
  const pursuitPresetAt47 = html.indexOf('individualPursuitCyclingCarnivalSplit:');
  assert.notEqual(teamPresetAt, -1);
  assert.notEqual(pursuitPresetAt47, -1);
  assert.ok(pursuitPresetAt47 < teamPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.32/);
  assert.match(html, /id: 'team-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.32/);
  assert.match(html, /id: 'individual-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.34/);
  assert.match(html, /id: 'scratch-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.46 ships individual-pursuit cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.46/);
  assert.match(readme, /Individual-pursuit cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.46/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Individual-pursuit cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.46/);
  assert.match(changelog, /Individual-pursuit cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.46/);
  assert.match(html, /individualPursuitCyclingCarnivalSplit/);
  assert.match(html, /Individual-pursuit cycling carnival split/);
  assert.match(html, /scratchCyclingCarnivalSplit/);
  const pursuitPresetAt = html.indexOf('individualPursuitCyclingCarnivalSplit:');
  const scratchPresetAt46 = html.indexOf('scratchCyclingCarnivalSplit:');
  assert.notEqual(pursuitPresetAt, -1);
  assert.notEqual(scratchPresetAt46, -1);
  assert.ok(scratchPresetAt46 < pursuitPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.34/);
  assert.match(html, /id: 'individual-pursuit-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.34/);
  assert.match(html, /id: 'scratch-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.45 ships scratch cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.45/);
  assert.match(readme, /Scratch cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.45/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Scratch cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.45/);
  assert.match(changelog, /Scratch cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.45/);
  assert.match(html, /scratchCyclingCarnivalSplit/);
  assert.match(html, /Scratch cycling carnival split/);
  assert.match(html, /pointsRaceCyclingCarnivalSplit/);
  const scratchPresetAt = html.indexOf('scratchCyclingCarnivalSplit:');
  const pointsRacePresetAt45 = html.indexOf('pointsRaceCyclingCarnivalSplit:');
  assert.notEqual(scratchPresetAt, -1);
  assert.notEqual(pointsRacePresetAt45, -1);
  assert.ok(pointsRacePresetAt45 < scratchPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'scratch-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.36/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.44 ships points-race cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.44/);
  assert.match(readme, /Points-race cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.44/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Points-race cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.44/);
  assert.match(changelog, /Points-race cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.44/);
  assert.match(html, /pointsRaceCyclingCarnivalSplit/);
  assert.match(html, /Points-race cycling carnival split/);
  assert.match(html, /omniumCyclingCarnivalSplit/);
  const pointsRacePresetAt = html.indexOf('pointsRaceCyclingCarnivalSplit:');
  const omniumPresetAt44 = html.indexOf('omniumCyclingCarnivalSplit:');
  assert.notEqual(pointsRacePresetAt, -1);
  assert.notEqual(omniumPresetAt44, -1);
  assert.ok(omniumPresetAt44 < pointsRacePresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'points-race-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.38/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.43 ships omnium cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.43/);
  assert.match(readme, /Omnium cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.43/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Omnium cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.43/);
  assert.match(changelog, /Omnium cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.43/);
  assert.match(html, /omniumCyclingCarnivalSplit/);
  assert.match(html, /Omnium cycling carnival split/);
  assert.match(html, /madisonCyclingCarnivalSplit/);
  const omniumPresetAt = html.indexOf('omniumCyclingCarnivalSplit:');
  const madisonPresetAt43 = html.indexOf('madisonCyclingCarnivalSplit:');
  assert.notEqual(omniumPresetAt, -1);
  assert.notEqual(madisonPresetAt43, -1);
  assert.ok(madisonPresetAt43 < omniumPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'omnium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.40/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.42 ships madison cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.42/);
  assert.match(readme, /Madison cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.42/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Madison cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.42/);
  assert.match(changelog, /Madison cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.42/);
  assert.match(html, /madisonCyclingCarnivalSplit/);
  assert.match(html, /Madison cycling carnival split/);
  assert.match(html, /keirinCyclingCarnivalSplit/);
  const madisonPresetAt = html.indexOf('madisonCyclingCarnivalSplit:');
  const keirinPresetAt42 = html.indexOf('keirinCyclingCarnivalSplit:');
  assert.notEqual(madisonPresetAt, -1);
  assert.notEqual(keirinPresetAt42, -1);
  assert.ok(keirinPresetAt42 < madisonPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'madison-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.42/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.41 ships keirin cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.41/);
  assert.match(readme, /Keirin cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.41/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Keirin cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.41/);
  assert.match(changelog, /Keirin cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.41/);
  assert.match(html, /keirinCyclingCarnivalSplit/);
  assert.match(html, /Keirin cycling carnival split/);
  assert.match(html, /hillClimbCyclingCarnivalSplit/);
  const keirinPresetAt = html.indexOf('keirinCyclingCarnivalSplit:');
  const hillClimbPresetAt41 = html.indexOf('hillClimbCyclingCarnivalSplit:');
  assert.notEqual(keirinPresetAt, -1);
  assert.notEqual(hillClimbPresetAt41, -1);
  assert.ok(hillClimbPresetAt41 < keirinPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'keirin-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.44/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.40 ships hill-climb cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.40/);
  assert.match(readme, /Hill-climb cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.40/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Hill-climb cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.40/);
  assert.match(changelog, /Hill-climb cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.40/);
  assert.match(html, /hillClimbCyclingCarnivalSplit/);
  assert.match(html, /Hill-climb cycling carnival split/);
  assert.match(html, /timeTrialCyclingCarnivalSplit/);
  assert.match(html, /Time-trial cycling carnival split/);
  const hillClimbPresetAt = html.indexOf('hillClimbCyclingCarnivalSplit:');
  const timeTrialPresetAt40 = html.indexOf('timeTrialCyclingCarnivalSplit:');
  assert.notEqual(hillClimbPresetAt, -1);
  assert.notEqual(timeTrialPresetAt40, -1);
  assert.ok(timeTrialPresetAt40 < hillClimbPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'hill-climb-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.46/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'criterium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.50/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.39 ships time-trial cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.39/);
  assert.match(readme, /Time-trial cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.39/);
  assert.match(readme, /Cyclo-cross first-aid stays variable cost 1\.56 after the Time-trial cycling carnival starting point is loaded/);
  assert.match(changelog, /## 1\.5\.39/);
  assert.match(changelog, /Time-trial cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.39/);
  assert.match(html, /timeTrialCyclingCarnivalSplit/);
  assert.match(html, /Time-trial cycling carnival split/);
  assert.match(html, /criteriumCyclingCarnivalSplit/);
  assert.match(html, /Criterium cycling carnival split/);
  assert.match(html, /roadCyclingCarnivalSplit/);
  assert.match(html, /Road cycling carnival split/);
  assert.match(html, /gravelCyclingCarnivalSplit/);
  assert.match(html, /Gravel cycling carnival split/);
  assert.match(html, /trackCyclingCarnivalSplit/);
  assert.match(html, /Track cycling carnival split/);
  assert.match(html, /cycloCrossCarnivalSplit/);
  assert.match(html, /Cyclo-cross carnival split/);
  const gravelPresetAt = html.indexOf('gravelCyclingCarnivalSplit:');
  const roadPresetAt = html.indexOf('roadCyclingCarnivalSplit:');
  const criteriumPresetAt = html.indexOf('criteriumCyclingCarnivalSplit:');
  const timeTrialPresetAt = html.indexOf('timeTrialCyclingCarnivalSplit:');
  const trackPresetAt = html.indexOf('trackCyclingCarnivalSplit:');
  assert.notEqual(trackPresetAt, -1);
  assert.notEqual(gravelPresetAt, -1);
  assert.notEqual(roadPresetAt, -1);
  assert.notEqual(criteriumPresetAt, -1);
  assert.notEqual(timeTrialPresetAt, -1);
  assert.ok(trackPresetAt < gravelPresetAt);
  assert.ok(gravelPresetAt < roadPresetAt);
  assert.ok(roadPresetAt < criteriumPresetAt);
  assert.ok(criteriumPresetAt < timeTrialPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.56/);
  assert.match(html, /variableCostPerTransaction: 1\.52/);
  assert.match(html, /variableCostPerTransaction: 1\.50/);
  assert.match(html, /variableCostPerTransaction: 1\.48/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id: 'road-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.52/);
  assert.match(html, /id: 'criterium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.50/);
  assert.match(html, /id: 'time-trial-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.48/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.38 ships criterium cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.38/);
  assert.match(readme, /Criterium cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.38/);
  assert.match(changelog, /## 1\.5\.38/);
  assert.match(changelog, /Criterium cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.38/);
  assert.match(html, /criteriumCyclingCarnivalSplit/);
  assert.match(html, /Criterium cycling carnival split/);
  assert.match(html, /roadCyclingCarnivalSplit/);
  assert.match(html, /Road cycling carnival split/);
  assert.match(html, /gravelCyclingCarnivalSplit/);
  assert.match(html, /Gravel cycling carnival split/);
  assert.match(html, /trackCyclingCarnivalSplit/);
  assert.match(html, /Track cycling carnival split/);
  assert.match(html, /cycloCrossCarnivalSplit/);
  assert.match(html, /Cyclo-cross carnival split/);
  const gravelPresetAt = html.indexOf('gravelCyclingCarnivalSplit:');
  const roadPresetAt = html.indexOf('roadCyclingCarnivalSplit:');
  const criteriumPresetAt = html.indexOf('criteriumCyclingCarnivalSplit:');
  const trackPresetAt = html.indexOf('trackCyclingCarnivalSplit:');
  assert.notEqual(trackPresetAt, -1);
  assert.notEqual(gravelPresetAt, -1);
  assert.notEqual(roadPresetAt, -1);
  assert.notEqual(criteriumPresetAt, -1);
  assert.ok(trackPresetAt < gravelPresetAt);
  assert.ok(gravelPresetAt < roadPresetAt);
  assert.ok(roadPresetAt < criteriumPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.56/);
  assert.match(html, /variableCostPerTransaction: 1\.52/);
  assert.match(html, /variableCostPerTransaction: 1\.50/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id: 'road-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.52/);
  assert.match(html, /id: 'criterium-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.50/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('release 1.5.37 ships road cycling carnival, last-over-capacity remaining copy and last-over-capacity hide jump', async () => {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  const changelog = await readFile(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
  const html = await buildStandalone();
  assert.equal(pkg.version, '1.5.54');
  assert.match(readme, /New in v1\.5\.37/);
  assert.match(readme, /Road cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.37/);
  assert.match(changelog, /## 1\.5\.37/);
  assert.match(changelog, /Road cycling carnival, last-over-capacity remaining listed capacity copy, and last-over-capacity hide jump in Partnership Breakpoint 1\.5\.37/);
  assert.match(html, /roadCyclingCarnivalSplit/);
  assert.match(html, /Road cycling carnival split/);
  assert.match(html, /gravelCyclingCarnivalSplit/);
  assert.match(html, /Gravel cycling carnival split/);
  assert.match(html, /trackCyclingCarnivalSplit/);
  assert.match(html, /Track cycling carnival split/);
  assert.match(html, /cycloCrossCarnivalSplit/);
  assert.match(html, /Cyclo-cross carnival split/);
  const gravelPresetAt = html.indexOf('gravelCyclingCarnivalSplit:');
  const roadPresetAt = html.indexOf('roadCyclingCarnivalSplit:');
  const trackPresetAt = html.indexOf('trackCyclingCarnivalSplit:');
  assert.notEqual(trackPresetAt, -1);
  assert.notEqual(gravelPresetAt, -1);
  assert.notEqual(roadPresetAt, -1);
  assert.ok(trackPresetAt < gravelPresetAt);
  assert.ok(gravelPresetAt < roadPresetAt);
  assert.match(html, /variableCostPerTransaction: 1\.56/);
  assert.match(html, /variableCostPerTransaction: 1\.52/);
  assert.match(html, /id: 'cyclo-cross-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.56/);
  assert.match(html, /id: 'road-cycling-first-aid', name: 'First-aid', revenueShare: 0\.25, variableCostPerTransaction: 1\.52/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /print-only print-keep"><h2>Last over-capacity remaining listed capacity/);
  assert.match(html, /print-only print-keep"><h2>First over-capacity volume-to-hold/);
});

test('standalone renderer inlines local assets with deterministic LF bytes', () => {
  const input = { html, css: 'body { color: black; }', model: 'export const value = 1;\n', app: `${appImport}console.log(value);\n` };
  const first = renderStandalone(input);
  const second = renderStandalone(input);
  assert.equal(first, second);
  assert.equal(isStandaloneCurrent(first.replace(/\n/g, '\r\n'), second), true);
  assert.equal(isStandaloneCurrent('stale', second), false);
  assert.match(first, /<style>\nbody \{ color: black; \}\n<\/style>/);
  assert.match(first, /http-equiv="Content-Security-Policy"/);
  assert.match(first, /default-src 'none'; base-uri 'none'; connect-src 'none'; form-action 'none'; img-src 'none'; media-src 'none'; object-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'/);
  assert.match(first, /const value = 1;/);
  assert.doesNotMatch(first, /src="src\/app\.js"|href="styles\.css"|href="MODEL\.md"/);
  assert.doesNotMatch(first, /\r/);
});

test('standalone renderer refuses missing markers and external CSS resources', () => {
  assert.throws(() => renderStandalone({ html: '<html></html>', css: '', model: '', app: appImport }), /marker/);
  assert.throws(() => renderStandalone({ html, css: 'body { background: url(image.png); }', model: '', app: appImport }), /URL resource/);
});

test('standalone retains 1.5.16 review tools and 1.5.17 copy controls', async () => {
  const html = await buildStandalone();
  assert.match(html, /createPartnershipReviewPacket/);
  assert.match(html, /replayPartnershipReviewPacket/);
  assert.match(html, /PARTNERSHIP_REVIEW_TOOLS/);
  assert.match(html, /analyzePartnershipReview/);
  assert.match(html, /data-action="copy-first-breakpoint-remaining"/);
  assert.match(html, /id="copy-first-breakpoint-remaining"/);
  assert.match(html, /data-action="copy-first-breakpoint-volume"/);
  assert.match(html, /aria-keyshortcuts=":"/);
  assert.match(html, /data-action="hide-spare-capacity-participants"/);
  assert.match(html, /data-action="hide-least-headroom-participants"/);
  assert.match(html, /data-action="hide-within-capacity-participants"/);
  assert.match(html, /id="hide-within-capacity-participants"/);
  assert.match(html, /data-action="hide-first-breakpoint-participant"/);
  assert.match(html, /id="hide-first-breakpoint-participant"/);
  assert.match(html, /id="hide-first-breakpoint-participant"[^>]*aria-keyshortcuts="\|"/);
  assert.match(html, /aria-keyshortcuts="\{"/);
  assert.match(html, /id="copy-over-capacity-count"/);
  assert.match(html, /id="copy-over-capacity-count"[^>]*aria-keyshortcuts='"'/);
  assert.match(html, /id="copy-first-over-capacity-label"/);
  assert.match(html, /id="copy-first-over-capacity-label"[^>]*aria-keyshortcuts="\}"/u);
  assert.match(html, /id="hide-first-over-capacity-participant"/);
  assert.match(html, /id="hide-first-over-capacity-participant"[^>]*aria-keyshortcuts="@"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"/);
  assert.match(html, /id="copy-first-over-capacity-remaining"[^>]*aria-keyshortcuts="~"/);
  assert.match(html, /id="copy-last-over-capacity-label"/);
  assert.match(html, /data-action="copy-last-over-capacity-label"/);
  assert.match(html, /id="copy-last-over-capacity-label"[^>]*aria-keyshortcuts="\("/);
  assert.match(html, /id="copy-last-over-capacity-remaining"/);
  assert.match(html, /data-action="copy-last-over-capacity-remaining"/);
  assert.match(html, /id="copy-last-over-capacity-remaining"[^>]*aria-keyshortcuts="\*"/);
  assert.match(html, /id="copy-last-over-capacity-volume"/);
  assert.match(html, /data-action="copy-last-over-capacity-volume"/);
  assert.match(html, /id="copy-first-over-capacity-volume"/);
  assert.match(html, /data-action="copy-first-over-capacity-volume"/);
  assert.match(html, /id="copy-first-within-capacity-remaining"/);
  assert.match(html, /data-action="copy-first-within-capacity-remaining"/);
  assert.match(html, /id="copy-first-within-capacity-remaining"[^>]*aria-keyshortcuts="\$"/);
  assert.match(html, /id="copy-last-within-capacity-remaining"/);
  assert.match(html, /data-action="copy-last-within-capacity-remaining"/);
  assert.match(html, /id="copy-last-within-capacity-remaining"[^>]*aria-keyshortcuts="5"/);
  assert.match(html, /id="hide-last-over-capacity-participant"[^>]*aria-keyshortcuts="#"/);
  assert.match(html, /id="hide-last-breakpoint-participant"/);
  assert.match(html, /data-action="hide-last-breakpoint-participant"/);
  assert.match(html, /id="copy-last-breakpoint-label"/);
  assert.match(html, /data-action="copy-last-breakpoint-label"/);
  assert.match(html, /id="hide-last-within-capacity-participant"/);
  assert.match(html, /data-action="hide-last-within-capacity-participant"/);
  assert.match(html, /id="hide-first-within-capacity-participant"/);
  assert.match(html, /data-action="hide-first-within-capacity-participant"/);
  assert.match(html, /id="hide-first-within-capacity-participant"[^>]*aria-keyshortcuts="\\`"/);
  assert.match(html, /id="hide-last-spare-capacity-participant"/);
  assert.match(html, /data-action="hide-last-spare-capacity-participant"/);
  assert.match(html, /id="hide-last-spare-capacity-participant"[^>]*aria-keyshortcuts="7"/);
  assert.match(html, /id="copy-last-spare-capacity-remaining"/);
  assert.match(html, /data-action="copy-last-spare-capacity-remaining"/);
  assert.match(html, /id="copy-last-spare-capacity-remaining"[^>]*aria-keyshortcuts="8"/);
  assert.match(html, /id="copy-first-spare-capacity-remaining"/);
  assert.match(html, /data-action="copy-first-spare-capacity-remaining"/);
  assert.match(html, /id="copy-first-spare-capacity-remaining"[^>]*aria-keyshortcuts="1"/);
  assert.match(html, /id="copy-last-unbounded-remaining"/);
  assert.match(html, /data-action="copy-last-unbounded-remaining"/);
  assert.match(html, /id="copy-last-unbounded-remaining"[^>]*aria-keyshortcuts="4"/);
  assert.match(html, /id="copy-first-unbounded-remaining"/);
  assert.match(html, /data-action="copy-first-unbounded-remaining"/);
  assert.match(html, /id="copy-last-at-hold-remaining"/);
  assert.match(html, /data-action="copy-last-at-hold-remaining"/);
  assert.match(html, /id="copy-first-at-hold-remaining"/);
  assert.match(html, /data-action="copy-first-at-hold-remaining"/);
  assert.match(html, /id="hide-first-zero-share-participant"/);
  assert.match(html, /data-action="hide-first-zero-share-participant"/);
  assert.match(html, /id="copy-first-zero-share-participant"/);
  assert.match(html, /data-action="copy-first-zero-share-participant"/);
  assert.match(html, /id="copy-last-zero-share-participant"/);
  assert.match(html, /data-action="copy-last-zero-share-participant"/);
  assert.match(html, /id="copy-last-zero-share-remaining"/);
  assert.match(html, /data-action="copy-last-zero-share-remaining"/);
  assert.match(html, /id="copy-last-zero-share-volume"/);
  assert.match(html, /data-action="copy-last-zero-share-volume"/);
  assert.match(html, /id="copy-first-zero-share-volume"/);
  assert.match(html, /data-action="copy-first-zero-share-volume"/);
  assert.match(html, /id="copy-first-zero-share-remaining"/);
  assert.match(html, /data-action="copy-first-zero-share-remaining"/);
  assert.match(html, /id="hide-zero-share-participants"/);
  assert.match(html, /data-action="hide-zero-share-participants"/);
  assert.match(html, /id="hide-last-zero-share-participant"/);
  assert.match(html, /data-action="hide-last-zero-share-participant"/);
  assert.match(html, /id="hide-first-spare-capacity-participant"/);
  assert.match(html, /id="hide-first-spare-capacity-participant"/);
  assert.match(html, /data-action="hide-first-spare-capacity-participant"/);
  assert.match(html, /id="hide-first-spare-capacity-participant"[^>]*aria-keyshortcuts="0"/);
  assert.match(html, /id="hide-last-without-capacity-participant"/);
  assert.match(html, /data-action="hide-last-without-capacity-participant"/);
  assert.match(html, /id="hide-last-without-capacity-participant"[^>]*aria-keyshortcuts="3"/);
  assert.match(html, /id="hide-first-without-capacity-participant"/);
  assert.match(html, /data-action="hide-first-without-capacity-participant"/);
  assert.match(html, /id="hide-last-at-hold-participant"/);
  assert.match(html, /data-action="hide-last-at-hold-participant"/);
  assert.match(html, /id="hide-first-at-hold-participant"/);
  assert.match(html, /data-action="hide-first-at-hold-participant"/);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/);
  assert.doesNotMatch(html, /if \(event\.key\.length !== 1\) return;/);
  assert.match(html, /key === 'u'/);
  assert.match(html, /School concert split/);
  assert.match(html, /Sports carnival split/);
  assert.match(html, /Netball carnival/);
  assert.match(html, /Swimming carnival split/);
  assert.match(html, /Athletics carnival split/);
  assert.match(html, /Cricket carnival split/);
  assert.match(html, /Tennis carnival split/);
  assert.match(html, /Basketball carnival split/);
  assert.match(html, /Volleyball carnival split/);
  assert.match(html, /Rugby carnival split/);
  assert.match(html, /Hockey carnival split/);
  assert.match(html, /Baseball carnival split/);
  assert.match(html, /Softball carnival split/);
  assert.match(html, /Lacrosse carnival split/);
  assert.match(html, /Water polo carnival split/);
  assert.match(html, /Rowing carnival split/);
  assert.match(html, /Sailing carnival split/);
  assert.match(html, /Canoeing carnival split/);
  assert.match(html, /Kayaking carnival split/);
  assert.match(html, /Dragon boat carnival split/);
  assert.match(html, /Surf carnival split/);
  assert.match(html, /Triathlon carnival split/);
  assert.match(html, /Cycling carnival split/);
  assert.match(html, /Mountain bike carnival split/);
  assert.match(html, /BMX carnival split/);
  assert.match(html, /Cyclo-cross carnival split/);
  assert.match(html, /Track cycling carnival split/);
  assert.match(html, /Gravel cycling carnival split/);
  assert.match(html, /Road cycling carnival split/);
  const surfAt = html.indexOf('Surf carnival split');
  const triathlonAt = html.indexOf('Triathlon carnival split');
  const cyclingAt = html.indexOf('Cycling carnival split');
  const mountainAt = html.indexOf('Mountain bike carnival split');
  const bmxAt = html.indexOf('BMX carnival split');
  const cycloAt = html.indexOf('Cyclo-cross carnival split');
  const trackAt = html.indexOf('Track cycling carnival split');
  const gravelAt = html.indexOf('Gravel cycling carnival split');
  const roadAt = html.indexOf('Road cycling carnival split');
  assert.notEqual(surfAt, -1);
  assert.notEqual(triathlonAt, -1);
  assert.notEqual(cyclingAt, -1);
  assert.notEqual(mountainAt, -1);
  assert.notEqual(bmxAt, -1);
  assert.notEqual(cycloAt, -1);
  assert.notEqual(trackAt, -1);
  assert.notEqual(gravelAt, -1);
  assert.notEqual(roadAt, -1);
  assert.ok(surfAt < triathlonAt);
  assert.ok(triathlonAt < cyclingAt);
  assert.ok(cyclingAt < mountainAt);
  assert.ok(mountainAt < bmxAt);
  assert.ok(bmxAt < cycloAt);
  assert.ok(cycloAt < trackAt);
  assert.ok(trackAt < gravelAt);
  assert.ok(gravelAt < roadAt);
  assert.match(html, /lastOverCapacityVolumeMarkdown/);
  assert.match(html, /copyLastOverCapacityVolume/);
  assert.match(html, /firstOverCapacityVolumeMarkdown/);
  assert.match(html, /copyFirstOverCapacityVolume/);
  assert.match(html, /lastOverCapacityRemainingMarkdown/);
  assert.match(html, /copyLastOverCapacityRemaining/);
  assert.match(html, /firstOverCapacityRemainingMarkdown/);
  assert.match(html, /copyFirstOverCapacityRemaining/);
  assert.match(html, /hideParticipantsAtLeastHeadroom/);
  assert.match(html, /hideParticipantsWithinCapacity/);
  assert.match(html, /hideFirstBreakpointParticipant/);
  assert.match(html, /hideFirstOverCapacityParticipant/);
  assert.match(html, /hideLastOverCapacityParticipant/);
  assert.match(html, /hideLastBreakpointParticipant/);
  assert.match(html, /hideLastWithinCapacityParticipant/);
  assert.match(html, /hideFirstWithinCapacityParticipant/);
  assert.match(html, /hideLastSpareCapacityParticipant/);
  assert.match(html, /hideFirstSpareCapacityParticipant/);
  assert.match(html, /hideLastParticipantWithoutCapacity/);
  assert.match(html, /hideFirstParticipantWithoutCapacity/);
  assert.match(html, /hideLastParticipantAtHold/);
  assert.match(html, /hideFirstParticipantAtHold/);
  assert.match(html, /hideFirstZeroShareParticipant/);
  assert.match(html, /hideLastZeroShareParticipant/);
  assert.match(html, /copyLastZeroShareRemaining/);
  assert.match(html, /lastZeroShareRemainingMarkdown/);
  assert.match(html, /copyLastZeroShareVolume/);
  assert.match(html, /lastZeroShareVolumeMarkdown/);
  assert.match(html, /copyFirstZeroShareVolume/);
  assert.match(html, /firstZeroShareVolumeMarkdown/);
  assert.match(html, /copyFirstZeroShareRemaining/);
  assert.match(html, /firstZeroShareRemainingMarkdown/);
  assert.match(html, /id="hide-last-over-capacity-participant"/);
});
