import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("bmx carnival lunch leftover fill is hall pickup and stays distinct from mountain bike carnival lunch", () => {
  const bmx = evaluateMarket(clonePreset("bmxCarnivalLunch"));
  const mountainBike = evaluateMarket(clonePreset("mountainBikeCarnivalLunch"));
  const cycling = evaluateMarket(clonePreset("cyclingCarnivalLunch"));
  const triathlon = evaluateMarket(clonePreset("triathlonCarnivalLunch"));
  const surf = evaluateMarket(clonePreset("surfCarnivalLunch"));
  const dragonBoat = evaluateMarket(clonePreset("dragonBoatCarnivalLunch"));
  const kayaking = evaluateMarket(clonePreset("kayakingCarnivalLunch"));
  const canoeing = evaluateMarket(clonePreset("canoeingCarnivalLunch"));
  const sailing = evaluateMarket(clonePreset("sailingCarnivalLunch"));
  const rowing = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(bmx.winner);
  assert.equal(bmx.winner.offer.merchant, "Court-side BMX Delivery");
  assert.equal(bmx.winner.offer.fulfillment, "shipping");
  assert.equal(bmx.winner.fulfilledUnits, 50);
  assert.deepEqual(bmx.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(bmx.scenario.title, "BMX carnival lunch");
  assert.notEqual(bmx.scenario.title, mountainBike.scenario.title);
  assert.notEqual(bmx.scenario.title, cycling.scenario.title);
  assert.notEqual(bmx.scenario.title, triathlon.scenario.title);
  assert.notEqual(bmx.scenario.title, surf.scenario.title);
  assert.notEqual(bmx.scenario.title, dragonBoat.scenario.title);
  assert.notEqual(bmx.scenario.title, kayaking.scenario.title);
  assert.notEqual(bmx.scenario.title, canoeing.scenario.title);
  assert.notEqual(bmx.scenario.title, sailing.scenario.title);
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("mountainBikeCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("cyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("triathlonCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("surfCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("dragonBoatCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("kayakingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("canoeingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("sailingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("rowingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("waterPoloCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("bmxCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(bmx.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall BMX Pickup");
  const leftoverOffer = bmx.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 26);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.minimumUnits);
  assert.equal(leftoverOffer.unitPrice, 21);
  assert.equal(bmx.scenario.buyers.find((buyer) => buyer.id === "B04").maxUnitPrice, 21);
  assert.equal(bmx.scenario.buyers.find((buyer) => buyer.id === "B04").quantity, 12);
  assert.equal(mountainBike.scenario.offers.find((offer) => offer.merchant === "Hall Mountain Bike Pickup").minimumUnits, 25);
  assert.equal(cycling.scenario.offers.find((offer) => offer.merchant === "Hall Cycling Pickup").minimumUnits, 24);
  assert.equal(triathlon.scenario.offers.find((offer) => offer.merchant === "Hall Triathlon Pickup").minimumUnits, 23);
  assert.equal(surf.scenario.offers.find((offer) => offer.merchant === "Hall Surf Pickup").minimumUnits, 22);
  assert.equal(dragonBoat.scenario.offers.find((offer) => offer.merchant === "Hall Dragon Boat Pickup").minimumUnits, 21);
  assert.equal(kayaking.scenario.offers.find((offer) => offer.merchant === "Hall Kayaking Pickup").minimumUnits, 20);
  assert.equal(canoeing.scenario.offers.find((offer) => offer.merchant === "Hall Canoeing Pickup").minimumUnits, 19);
  assert.equal(sailing.scenario.offers.find((offer) => offer.merchant === "Hall Sailing Pickup").minimumUnits, 18);
  assert.equal(rowing.scenario.offers.find((offer) => offer.merchant === "Hall Rowing Pickup").minimumUnits, 17);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(waterPolo.scenario.offers.find((offer) => offer.merchant === "Hall Water Polo Pickup").minimumUnits, 16);
  assert.equal(mountainBike.winner.offer.merchant, "Court-side Mountain Bike Delivery");
  assert.equal(cycling.winner.offer.merchant, "Court-side Cycling Delivery");
  assert.equal(triathlon.winner.offer.merchant, "Court-side Triathlon Delivery");
  assert.equal(surf.winner.offer.merchant, "Court-side Surf Delivery");
  assert.equal(dragonBoat.winner.offer.merchant, "Court-side Dragon Boat Delivery");
  assert.equal(kayaking.winner.offer.merchant, "Court-side Kayaking Delivery");
  assert.equal(sailing.winner.offer.merchant, "Court-side Sailing Delivery");
  assert.equal(canoeing.winner.offer.merchant, "Court-side Canoeing Delivery");
  assert.equal(rowing.winner.offer.merchant, "Court-side Rowing Delivery");
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(leftoverOffer.capacity, 52);
  assert.equal(leftoverFill.fulfilledUnits, 27);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 25);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.unitPrice);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.minimumUnits);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(bmx.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(bmx.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(bmx.results.some((result) => result.offer.merchant === "Court-side BMX Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("BMX pie")));
  assert.ok(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pump salad")));
  assert.ok(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pump water")));
  assert.equal(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail pie")), false);
  assert.equal(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail salad")), false);
  assert.equal(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail water")), false);
  assert.equal(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cycle pie")), false);
  assert.equal(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Velodrome salad")), false);
  assert.equal(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Velodrome water")), false);
  assert.equal(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tri pie")), false);
  assert.equal(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Surf pie")), false);
  assert.equal(bmx.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Dragon boat pie")), false);
  const first = evaluateMarket(clonePreset("bmxCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("bmxCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes bmx carnival lunch next to mountain bike carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="bmxCarnivalLunch"/u);
  assert.match(html, /BMX carnival/u);
  assert.match(html, /data-preset="mountainBikeCarnivalLunch"/u);
  assert.match(html, /data-preset="cycloCrossCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="mountainBikeCarnivalLunch"') < html.indexOf('data-preset="bmxCarnivalLunch"'));
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="bmxCarnivalLunch"') < html.indexOf('data-preset="cycloCrossCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="cycloCrossCarnivalLunch"') < html.indexOf('data-preset="trackCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
});
