import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("kayaking carnival lunch leftover fill is hall pickup and stays distinct from canoeing carnival lunch", () => {
  const kayaking = evaluateMarket(clonePreset("kayakingCarnivalLunch"));
  const canoeing = evaluateMarket(clonePreset("canoeingCarnivalLunch"));
  const sailing = evaluateMarket(clonePreset("sailingCarnivalLunch"));
  const rowing = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(kayaking.winner);
  assert.equal(kayaking.winner.offer.merchant, "Court-side Kayaking Delivery");
  assert.equal(kayaking.winner.offer.fulfillment, "shipping");
  assert.equal(kayaking.winner.fulfilledUnits, 50);
  assert.deepEqual(kayaking.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(kayaking.scenario.title, "Kayaking carnival lunch");
  assert.notEqual(kayaking.scenario.title, canoeing.scenario.title);
  assert.notEqual(kayaking.scenario.title, sailing.scenario.title);
  assert.notDeepEqual(clonePreset("kayakingCarnivalLunch"), clonePreset("canoeingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("kayakingCarnivalLunch"), clonePreset("sailingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("kayakingCarnivalLunch"), clonePreset("rowingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("kayakingCarnivalLunch"), clonePreset("waterPoloCarnivalLunch"));
  assert.notDeepEqual(clonePreset("kayakingCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("kayakingCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("kayakingCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("kayakingCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("kayakingCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(kayaking.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Kayaking Pickup");
  const leftoverOffer = kayaking.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 20);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.minimumUnits);
  assert.equal(leftoverOffer.unitPrice, 17);
  assert.equal(kayaking.scenario.buyers.find((buyer) => buyer.id === "B04").maxUnitPrice, 17);
  assert.equal(canoeing.scenario.offers.find((offer) => offer.merchant === "Hall Canoeing Pickup").minimumUnits, 19);
  assert.equal(sailing.scenario.offers.find((offer) => offer.merchant === "Hall Sailing Pickup").minimumUnits, 18);
  assert.equal(rowing.scenario.offers.find((offer) => offer.merchant === "Hall Rowing Pickup").minimumUnits, 17);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(waterPolo.scenario.offers.find((offer) => offer.merchant === "Hall Water Polo Pickup").minimumUnits, 16);
  assert.equal(sailing.winner.offer.merchant, "Court-side Sailing Delivery");
  assert.equal(canoeing.winner.offer.merchant, "Court-side Canoeing Delivery");
  assert.equal(rowing.winner.offer.merchant, "Court-side Rowing Delivery");
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(leftoverOffer.capacity, 44);
  assert.equal(leftoverFill.fulfilledUnits, 23);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 21);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(kayaking.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(kayaking.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(kayaking.results.some((result) => result.offer.merchant === "Court-side Kayaking Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(kayaking.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Kayaking pie")));
  assert.ok(kayaking.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Boathouse salad")));
  assert.ok(kayaking.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Boathouse water")));
  assert.equal(kayaking.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Canoeing pie")), false);
  assert.equal(kayaking.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Clubhouse water")), false);
  assert.equal(kayaking.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Clubhouse salad")), false);
  assert.equal(kayaking.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Sailing pie")), false);
  assert.equal(kayaking.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Marina water")), false);
  const first = evaluateMarket(clonePreset("kayakingCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("kayakingCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes kayaking carnival lunch next to canoeing carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="kayakingCarnivalLunch"/u);
  assert.match(html, /Kayaking carnival/u);
  assert.match(html, /data-preset="canoeingCarnivalLunch"/u);
});
