import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("keirin cycling carnival lunch leftover fill is hall pickup and stays distinct from time-trial cycling carnival lunch", () => {
  const keirinCycling = evaluateMarket(clonePreset("keirinCyclingCarnivalLunch"));
  const timeTrialCycling = evaluateMarket(clonePreset("timeTrialCyclingCarnivalLunch"));
  const criteriumCycling = evaluateMarket(clonePreset("criteriumCyclingCarnivalLunch"));
  const roadCycling = evaluateMarket(clonePreset("roadCyclingCarnivalLunch"));
  const gravelCycling = evaluateMarket(clonePreset("gravelCyclingCarnivalLunch"));
  const trackCycling = evaluateMarket(clonePreset("trackCyclingCarnivalLunch"));
  const cycloCross = evaluateMarket(clonePreset("cycloCrossCarnivalLunch"));
  const bmx = evaluateMarket(clonePreset("bmxCarnivalLunch"));
  const mountainBike = evaluateMarket(clonePreset("mountainBikeCarnivalLunch"));
  const cycling = evaluateMarket(clonePreset("cyclingCarnivalLunch"));
  const triathlon = evaluateMarket(clonePreset("triathlonCarnivalLunch"));
  const surf = evaluateMarket(clonePreset("surfCarnivalLunch"));
  const dragonBoat = evaluateMarket(clonePreset("dragonBoatCarnivalLunch"));
  const kayaking = evaluateMarket(clonePreset("kayakingCarnivalLunch"));
  const canoeing = evaluateMarket(clonePreset("canoeingCarnivalLunch"));
  const sailing = evaluateMarket(clonePreset("sailingCarnivalLunch"));
  const rowing = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(keirinCycling.winner);
  assert.equal(keirinCycling.winner.offer.merchant, "Court-side Keirin Delivery");
  assert.equal(keirinCycling.winner.offer.fulfillment, "shipping");
  assert.equal(keirinCycling.winner.fulfilledUnits, 50);
  assert.deepEqual(keirinCycling.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(keirinCycling.scenario.title, "Keirin cycling carnival lunch");
  assert.notEqual(keirinCycling.scenario.title, clonePreset("hillClimbCyclingCarnivalLunch").title);
  assert.notEqual(keirinCycling.scenario.title, timeTrialCycling.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, criteriumCycling.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, roadCycling.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, gravelCycling.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, trackCycling.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, cycloCross.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, bmx.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, mountainBike.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, cycling.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, triathlon.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, surf.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, dragonBoat.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, kayaking.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, canoeing.scenario.title);
  assert.notEqual(keirinCycling.scenario.title, sailing.scenario.title);
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("hillClimbCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("timeTrialCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("criteriumCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("roadCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("gravelCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("trackCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("cycloCrossCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("bmxCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("mountainBikeCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("cyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("triathlonCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("surfCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("dragonBoatCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("kayakingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("canoeingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("sailingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("rowingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("waterPoloCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("madisonCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("keirinCyclingCarnivalLunch"), clonePreset("omniumCyclingCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(keirinCycling.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Keirin Pickup");
  const leftoverOffer = keirinCycling.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 34);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.minimumUnits);
  assert.equal(leftoverOffer.unitPrice, 30);
  assert.equal(keirinCycling.scenario.buyers.find((buyer) => buyer.id === "B04").maxUnitPrice, 30);
  assert.equal(keirinCycling.scenario.buyers.find((buyer) => buyer.id === "B04").quantity, 20);
  assert.equal(criteriumCycling.scenario.offers.find((offer) => offer.merchant === "Hall Criterium Pickup").minimumUnits, 31);
  assert.equal(roadCycling.scenario.offers.find((offer) => offer.merchant === "Hall Road Cycling Pickup").minimumUnits, 30);
  assert.equal(gravelCycling.scenario.offers.find((offer) => offer.merchant === "Hall Gravel Cycling Pickup").minimumUnits, 29);
  assert.equal(trackCycling.scenario.offers.find((offer) => offer.merchant === "Hall Track Cycling Pickup").minimumUnits, 28);
  assert.equal(cycloCross.scenario.offers.find((offer) => offer.merchant === "Hall Cyclo-cross Pickup").minimumUnits, 27);
  assert.equal(bmx.scenario.offers.find((offer) => offer.merchant === "Hall BMX Pickup").minimumUnits, 26);
  assert.equal(mountainBike.scenario.offers.find((offer) => offer.merchant === "Hall Mountain Bike Pickup").minimumUnits, 25);
  assert.equal(cycling.scenario.offers.find((offer) => offer.merchant === "Hall Cycling Pickup").minimumUnits, 24);
  assert.equal(triathlon.scenario.offers.find((offer) => offer.merchant === "Hall Triathlon Pickup").minimumUnits, 23);
  assert.equal(surf.scenario.offers.find((offer) => offer.merchant === "Hall Surf Pickup").minimumUnits, 22);
  assert.equal(dragonBoat.scenario.offers.find((offer) => offer.merchant === "Hall Dragon Boat Pickup").minimumUnits, 21);
  assert.equal(kayaking.scenario.offers.find((offer) => offer.merchant === "Hall Kayaking Pickup").minimumUnits, 20);
  assert.equal(canoeing.scenario.offers.find((offer) => offer.merchant === "Hall Canoeing Pickup").minimumUnits, 19);
  assert.equal(sailing.scenario.offers.find((offer) => offer.merchant === "Hall Sailing Pickup").minimumUnits, 18);
  assert.equal(rowing.scenario.offers.find((offer) => offer.merchant === "Hall Rowing Pickup").minimumUnits, 17);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(waterPolo.scenario.offers.find((offer) => offer.merchant === "Hall Water Polo Pickup").minimumUnits, 16);
  assert.equal(criteriumCycling.winner.offer.merchant, "Court-side Criterium Delivery");
  assert.equal(roadCycling.winner.offer.merchant, "Court-side Road Cycling Delivery");
  assert.equal(gravelCycling.winner.offer.merchant, "Court-side Gravel Cycling Delivery");
  assert.equal(trackCycling.winner.offer.merchant, "Court-side Track Cycling Delivery");
  assert.equal(cycloCross.winner.offer.merchant, "Court-side Cyclo-cross Delivery");
  assert.equal(bmx.winner.offer.merchant, "Court-side BMX Delivery");
  assert.equal(mountainBike.winner.offer.merchant, "Court-side Mountain Bike Delivery");
  assert.equal(cycling.winner.offer.merchant, "Court-side Cycling Delivery");
  assert.equal(triathlon.winner.offer.merchant, "Court-side Triathlon Delivery");
  assert.equal(surf.winner.offer.merchant, "Court-side Surf Delivery");
  assert.equal(dragonBoat.winner.offer.merchant, "Court-side Dragon Boat Delivery");
  assert.equal(kayaking.winner.offer.merchant, "Court-side Kayaking Delivery");
  assert.equal(sailing.winner.offer.merchant, "Court-side Sailing Delivery");
  assert.equal(canoeing.winner.offer.merchant, "Court-side Canoeing Delivery");
  assert.equal(rowing.winner.offer.merchant, "Court-side Rowing Delivery");
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(leftoverOffer.capacity, 64);
  assert.equal(leftoverFill.fulfilledUnits, 35);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 29);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.unitPrice);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.minimumUnits);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverFill.fulfilledUnits, 34);
  assert.notEqual(leftoverFill.fulfilledUnits, 33);
  assert.notEqual(leftoverFill.fulfilledUnits, 32);
  assert.notEqual(leftoverFill.fulfilledUnits, 31);
  assert.notEqual(leftoverFill.fulfilledUnits, 30);
  assert.notEqual(leftoverFill.fulfilledUnits, 28);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(keirinCycling.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(keirinCycling.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(keirinCycling.results.some((result) => result.offer.merchant === "Court-side Keirin Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Keirin pie")));
  assert.ok(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Derny salad")));
  assert.ok(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Derny water")));
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Criterium pie")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Circuit salad")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Circuit water")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Road pie")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Peloton salad")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Bottle water")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Gravel pie")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Feed-zone salad")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Neutral water")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hill-climb pie")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hairpin salad")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hairpin water")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Sprint salad")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Keirin water")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cyclo-cross pie")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Barrier salad")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pit water")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("BMX pie")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pump salad")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pump water")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail pie")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail salad")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail water")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cycle pie")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Velodrome salad")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Velodrome water")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tri pie")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Surf pie")), false);
  assert.equal(keirinCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Dragon boat pie")), false);
  const payload = JSON.stringify(clonePreset("keirinCyclingCarnivalLunch"));
  assert.equal(payload.includes("start-ramp"), false);
  assert.equal(payload.includes("timing-hut"), false);
  assert.equal(payload.includes("time-check"), false);
  assert.equal(payload.includes("pit-lane"), false);
  assert.equal(payload.includes("circuit"), false);
  assert.equal(payload.includes("sealed-road"), false);
  assert.equal(payload.includes("feed-zone"), false);
  assert.equal(payload.includes("summit-marshal"), false);
  assert.equal(payload.includes("hairpin"), false);
  assert.equal(payload.includes("climb-chip"), false);
  assert.match(payload, /Derny crate/);
  assert.match(payload, /Keirin-gate bench/);
  assert.match(payload, /Pacer hamper/);
  const first = evaluateMarket(clonePreset("keirinCyclingCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("keirinCyclingCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes keirin cycling carnival lunch next to time-trial cycling carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="timeTrialCyclingCarnivalLunch"/u);
  assert.match(html, /Time-trial cycling carnival/u);
  assert.match(html, /data-preset="criteriumCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="roadCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="gravelCyclingCarnivalLunch"') < html.indexOf('data-preset="roadCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="roadCyclingCarnivalLunch"') < html.indexOf('data-preset="criteriumCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="criteriumCyclingCarnivalLunch"') < html.indexOf('data-preset="timeTrialCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="timeTrialCyclingCarnivalLunch"') < html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"') < html.indexOf('data-preset="keirinCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="keirinCyclingCarnivalLunch"') < html.indexOf('data-preset="madisonCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="madisonCyclingCarnivalLunch"') < html.indexOf('data-preset="omniumCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="omniumCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
});
