import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("print leftover one-pager includes leftover uncovered count when leftover uncovered minimum has a print line", async () => {
  const css = await readFile(new URL("../styles.css", import.meta.url), "utf8");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
  assert.match(html, /id="leftover-print-uncovered-count"/u);
  assert.match(html, /Leftover uncovered count: none/u);
  assert.match(html, /id="leftover-print-uncovered-minimum"/u);
  assert.match(html, /id="leftover-print-uncovered-maximum"/u);
  assert.match(html, /id="leftover-print-winner"/u);
  assert.match(html, /Winner merchant:/u);
  assert.match(css, /body\.print-leftover #leftover-print-uncovered-count/u);
  assert.match(css, /body\.print-leftover #leftover-print-uncovered-minimum/u);
  const leftover = html.slice(html.indexOf('id="leftover-print-uncovered-count"'), html.indexOf('id="copy-winning-merchant"'));
  assert.match(leftover, /print-leftover-keep/u);
  assert.equal(leftover.includes("maxUnitPrice"), false);
  assert.equal(leftover.includes("selectedBuyerIds"), false);
  assert.equal(leftover.includes("leftoverBuyerIds"), false);
  assert.match(app, /leftover-print-uncovered-count/u);
  assert.match(app, /Leftover uncovered count:/u);
  assert.match(app, /Leftover uncovered count: \$\{coverage\.unfilledBuyerCount\} buyers/u);
  assert.match(app, /coverage\.leftoverBuyerCount/u);
  assert.match(app, /Winner merchant:/u);
  const leftoverPrint = app.slice(app.indexOf("function printLeftoverOnePager"), app.indexOf("function focusVariantOverlap"));
  assert.doesNotMatch(leftoverPrint, /leftoverBuyerIds/u);
  const merchantPanel = html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"'));
  assert.equal(merchantPanel.includes("leftover-print-uncovered-count"), false);
});
