import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("madison cycling carnival lunch leftover fill is hall pickup and stays distinct from keirin cycling carnival lunch", () => {
  const madisonCycling = evaluateMarket(clonePreset("madisonCyclingCarnivalLunch"));
  const keirinCycling = evaluateMarket(clonePreset("keirinCyclingCarnivalLunch"));
  const hillClimbCycling = evaluateMarket(clonePreset("hillClimbCyclingCarnivalLunch"));
  const timeTrialCycling = evaluateMarket(clonePreset("timeTrialCyclingCarnivalLunch"));
  const criteriumCycling = evaluateMarket(clonePreset("criteriumCyclingCarnivalLunch"));
  const roadCycling = evaluateMarket(clonePreset("roadCyclingCarnivalLunch"));
  const gravelCycling = evaluateMarket(clonePreset("gravelCyclingCarnivalLunch"));
  const trackCycling = evaluateMarket(clonePreset("trackCyclingCarnivalLunch"));
  const cycloCross = evaluateMarket(clonePreset("cycloCrossCarnivalLunch"));
  const bmx = evaluateMarket(clonePreset("bmxCarnivalLunch"));
  const mountainBike = evaluateMarket(clonePreset("mountainBikeCarnivalLunch"));
  const cycling = evaluateMarket(clonePreset("cyclingCarnivalLunch"));
  const triathlon = evaluateMarket(clonePreset("triathlonCarnivalLunch"));
  const surf = evaluateMarket(clonePreset("surfCarnivalLunch"));
  const dragonBoat = evaluateMarket(clonePreset("dragonBoatCarnivalLunch"));
  const kayaking = evaluateMarket(clonePreset("kayakingCarnivalLunch"));
  const canoeing = evaluateMarket(clonePreset("canoeingCarnivalLunch"));
  const sailing = evaluateMarket(clonePreset("sailingCarnivalLunch"));
  const rowing = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(madisonCycling.winner);
  assert.equal(madisonCycling.winner.offer.merchant, "Court-side Madison Delivery");
  assert.equal(madisonCycling.winner.offer.fulfillment, "shipping");
  assert.equal(madisonCycling.winner.fulfilledUnits, 50);
  assert.deepEqual(madisonCycling.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(madisonCycling.scenario.title, "Madison cycling carnival lunch");
  assert.notEqual(madisonCycling.scenario.title, clonePreset("keirinCyclingCarnivalLunch").title);
  assert.notEqual(madisonCycling.scenario.title, hillClimbCycling.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, timeTrialCycling.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, criteriumCycling.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, roadCycling.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, gravelCycling.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, trackCycling.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, cycloCross.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, bmx.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, mountainBike.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, cycling.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, triathlon.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, surf.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, dragonBoat.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, kayaking.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, canoeing.scenario.title);
  assert.notEqual(madisonCycling.scenario.title, sailing.scenario.title);
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("keirinCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("hillClimbCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("timeTrialCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("criteriumCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("roadCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("gravelCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("trackCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("cycloCrossCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("bmxCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("mountainBikeCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("cyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("triathlonCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("surfCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("dragonBoatCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("kayakingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("canoeingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("sailingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("rowingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("waterPoloCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  assert.notDeepEqual(clonePreset("madisonCyclingCarnivalLunch"), clonePreset("omniumCyclingCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(madisonCycling.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Madison Pickup");
  const leftoverOffer = madisonCycling.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 35);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.minimumUnits);
  assert.equal(leftoverOffer.unitPrice, 31);
  assert.equal(madisonCycling.scenario.buyers.find((buyer) => buyer.id === "B04").maxUnitPrice, 31);
  assert.equal(madisonCycling.scenario.buyers.find((buyer) => buyer.id === "B04").quantity, 21);
  assert.equal(keirinCycling.scenario.offers.find((offer) => offer.merchant === "Hall Keirin Pickup").minimumUnits, 34);
  assert.equal(hillClimbCycling.scenario.offers.find((offer) => offer.merchant === "Hall Hill Climb Pickup").minimumUnits, 33);
  assert.equal(timeTrialCycling.scenario.offers.find((offer) => offer.merchant === "Hall Time Trial Pickup").minimumUnits, 32);
  assert.equal(criteriumCycling.scenario.offers.find((offer) => offer.merchant === "Hall Criterium Pickup").minimumUnits, 31);
  assert.equal(roadCycling.scenario.offers.find((offer) => offer.merchant === "Hall Road Cycling Pickup").minimumUnits, 30);
  assert.equal(gravelCycling.scenario.offers.find((offer) => offer.merchant === "Hall Gravel Cycling Pickup").minimumUnits, 29);
  assert.equal(trackCycling.scenario.offers.find((offer) => offer.merchant === "Hall Track Cycling Pickup").minimumUnits, 28);
  assert.equal(cycloCross.scenario.offers.find((offer) => offer.merchant === "Hall Cyclo-cross Pickup").minimumUnits, 27);
  assert.equal(bmx.scenario.offers.find((offer) => offer.merchant === "Hall BMX Pickup").minimumUnits, 26);
  assert.equal(mountainBike.scenario.offers.find((offer) => offer.merchant === "Hall Mountain Bike Pickup").minimumUnits, 25);
  assert.equal(cycling.scenario.offers.find((offer) => offer.merchant === "Hall Cycling Pickup").minimumUnits, 24);
  assert.equal(triathlon.scenario.offers.find((offer) => offer.merchant === "Hall Triathlon Pickup").minimumUnits, 23);
  assert.equal(surf.scenario.offers.find((offer) => offer.merchant === "Hall Surf Pickup").minimumUnits, 22);
  assert.equal(dragonBoat.scenario.offers.find((offer) => offer.merchant === "Hall Dragon Boat Pickup").minimumUnits, 21);
  assert.equal(kayaking.scenario.offers.find((offer) => offer.merchant === "Hall Kayaking Pickup").minimumUnits, 20);
  assert.equal(canoeing.scenario.offers.find((offer) => offer.merchant === "Hall Canoeing Pickup").minimumUnits, 19);
  assert.equal(sailing.scenario.offers.find((offer) => offer.merchant === "Hall Sailing Pickup").minimumUnits, 18);
  assert.equal(rowing.scenario.offers.find((offer) => offer.merchant === "Hall Rowing Pickup").minimumUnits, 17);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(waterPolo.scenario.offers.find((offer) => offer.merchant === "Hall Water Polo Pickup").minimumUnits, 16);
  assert.equal(criteriumCycling.winner.offer.merchant, "Court-side Criterium Delivery");
  assert.equal(keirinCycling.winner.offer.merchant, "Court-side Keirin Delivery");
  assert.equal(leftoverOffer.capacity, 64);
  assert.equal(leftoverFill.fulfilledUnits, 36);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 28);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.unitPrice);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.minimumUnits);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverFill.fulfilledUnits, 35);
  assert.notEqual(leftoverFill.fulfilledUnits, 34);
  assert.notEqual(leftoverFill.fulfilledUnits, 33);
  assert.notEqual(leftoverFill.fulfilledUnits, 32);
  assert.notEqual(leftoverFill.fulfilledUnits, 31);
  assert.notEqual(leftoverFill.fulfilledUnits, 30);
  assert.notEqual(leftoverFill.fulfilledUnits, 29);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(madisonCycling.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(madisonCycling.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(madisonCycling.results.some((result) => result.offer.merchant === "Court-side Madison Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Madison pie")));
  assert.ok(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Handsling salad")));
  assert.ok(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Handsling water")));
  assert.equal(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Keirin pie")), false);
  assert.equal(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Derny salad")), false);
  assert.equal(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Derny water")), false);
  assert.equal(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hill-climb pie")), false);
  assert.equal(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hairpin salad")), false);
  assert.equal(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hairpin water")), false);
  assert.equal(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Criterium pie")), false);
  assert.equal(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Circuit salad")), false);
  assert.equal(madisonCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Circuit water")), false);
  const payload = JSON.stringify(clonePreset("madisonCyclingCarnivalLunch"));
  assert.equal(payload.includes("start-ramp"), false);
  assert.equal(payload.includes("timing-hut"), false);
  assert.equal(payload.includes("time-check"), false);
  assert.equal(payload.includes("pit-lane"), false);
  assert.equal(payload.includes("circuit"), false);
  assert.equal(payload.includes("sealed-road"), false);
  assert.equal(payload.includes("feed-zone"), false);
  assert.equal(payload.includes("summit-marshal"), false);
  assert.equal(payload.includes("hairpin"), false);
  assert.equal(payload.includes("climb-chip"), false);
  assert.equal(payload.includes("derny-pacer"), false);
  assert.equal(payload.includes("keirin-chip"), false);
  assert.equal(payload.includes("keirin-gate"), false);
  assert.match(payload, /Madison-pair crate/);
  assert.match(payload, /Handsling bench/);
  assert.match(payload, /Pairing hamper/);
  const first = evaluateMarket(clonePreset("madisonCyclingCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("madisonCyclingCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes madison cycling carnival lunch next to keirin cycling carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="madisonCyclingCarnivalLunch"/u);
  assert.match(html, /Madison cycling carnival/u);
  assert.match(html, /data-preset="keirinCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="hillClimbCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"') < html.indexOf('data-preset="keirinCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="keirinCyclingCarnivalLunch"') < html.indexOf('data-preset="madisonCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="madisonCyclingCarnivalLunch"') < html.indexOf('data-preset="omniumCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="omniumCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
});
