import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("mountain bike carnival lunch leftover fill is hall pickup and stays distinct from cycling carnival lunch", () => {
  const mountainBike = evaluateMarket(clonePreset("mountainBikeCarnivalLunch"));
  const cycling = evaluateMarket(clonePreset("cyclingCarnivalLunch"));
  const triathlon = evaluateMarket(clonePreset("triathlonCarnivalLunch"));
  const surf = evaluateMarket(clonePreset("surfCarnivalLunch"));
  const dragonBoat = evaluateMarket(clonePreset("dragonBoatCarnivalLunch"));
  const kayaking = evaluateMarket(clonePreset("kayakingCarnivalLunch"));
  const canoeing = evaluateMarket(clonePreset("canoeingCarnivalLunch"));
  const sailing = evaluateMarket(clonePreset("sailingCarnivalLunch"));
  const rowing = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(mountainBike.winner);
  assert.equal(mountainBike.winner.offer.merchant, "Court-side Mountain Bike Delivery");
  assert.equal(mountainBike.winner.offer.fulfillment, "shipping");
  assert.equal(mountainBike.winner.fulfilledUnits, 50);
  assert.deepEqual(mountainBike.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(mountainBike.scenario.title, "Mountain bike carnival lunch");
  assert.notEqual(mountainBike.scenario.title, cycling.scenario.title);
  assert.notEqual(mountainBike.scenario.title, triathlon.scenario.title);
  assert.notEqual(mountainBike.scenario.title, surf.scenario.title);
  assert.notEqual(mountainBike.scenario.title, dragonBoat.scenario.title);
  assert.notEqual(mountainBike.scenario.title, kayaking.scenario.title);
  assert.notEqual(mountainBike.scenario.title, canoeing.scenario.title);
  assert.notEqual(mountainBike.scenario.title, sailing.scenario.title);
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("cyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("triathlonCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("surfCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("dragonBoatCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("kayakingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("canoeingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("sailingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("rowingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("waterPoloCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  assert.notDeepEqual(clonePreset("mountainBikeCarnivalLunch"), clonePreset("bmxCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(mountainBike.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Mountain Bike Pickup");
  const leftoverOffer = mountainBike.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 25);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.minimumUnits);
  assert.equal(leftoverOffer.unitPrice, 20);
  assert.equal(mountainBike.scenario.buyers.find((buyer) => buyer.id === "B04").maxUnitPrice, 20);
  assert.equal(mountainBike.scenario.buyers.find((buyer) => buyer.id === "B04").quantity, 11);
  assert.equal(cycling.scenario.offers.find((offer) => offer.merchant === "Hall Cycling Pickup").minimumUnits, 24);
  assert.equal(triathlon.scenario.offers.find((offer) => offer.merchant === "Hall Triathlon Pickup").minimumUnits, 23);
  assert.equal(surf.scenario.offers.find((offer) => offer.merchant === "Hall Surf Pickup").minimumUnits, 22);
  assert.equal(dragonBoat.scenario.offers.find((offer) => offer.merchant === "Hall Dragon Boat Pickup").minimumUnits, 21);
  assert.equal(kayaking.scenario.offers.find((offer) => offer.merchant === "Hall Kayaking Pickup").minimumUnits, 20);
  assert.equal(canoeing.scenario.offers.find((offer) => offer.merchant === "Hall Canoeing Pickup").minimumUnits, 19);
  assert.equal(sailing.scenario.offers.find((offer) => offer.merchant === "Hall Sailing Pickup").minimumUnits, 18);
  assert.equal(rowing.scenario.offers.find((offer) => offer.merchant === "Hall Rowing Pickup").minimumUnits, 17);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(waterPolo.scenario.offers.find((offer) => offer.merchant === "Hall Water Polo Pickup").minimumUnits, 16);
  assert.equal(cycling.winner.offer.merchant, "Court-side Cycling Delivery");
  assert.equal(triathlon.winner.offer.merchant, "Court-side Triathlon Delivery");
  assert.equal(surf.winner.offer.merchant, "Court-side Surf Delivery");
  assert.equal(dragonBoat.winner.offer.merchant, "Court-side Dragon Boat Delivery");
  assert.equal(kayaking.winner.offer.merchant, "Court-side Kayaking Delivery");
  assert.equal(sailing.winner.offer.merchant, "Court-side Sailing Delivery");
  assert.equal(canoeing.winner.offer.merchant, "Court-side Canoeing Delivery");
  assert.equal(rowing.winner.offer.merchant, "Court-side Rowing Delivery");
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(leftoverOffer.capacity, 50);
  assert.equal(leftoverFill.fulfilledUnits, 26);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 24);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.unitPrice);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.minimumUnits);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(mountainBike.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(mountainBike.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(mountainBike.results.some((result) => result.offer.merchant === "Court-side Mountain Bike Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(mountainBike.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail pie")));
  assert.ok(mountainBike.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail salad")));
  assert.ok(mountainBike.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail water")));
  assert.equal(mountainBike.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cycle pie")), false);
  assert.equal(mountainBike.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Velodrome salad")), false);
  assert.equal(mountainBike.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Velodrome water")), false);
  assert.equal(mountainBike.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tri pie")), false);
  assert.equal(mountainBike.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Surf pie")), false);
  assert.equal(mountainBike.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Dragon boat pie")), false);
  const first = evaluateMarket(clonePreset("mountainBikeCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("mountainBikeCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes mountain bike carnival lunch next to cycling carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="mountainBikeCarnivalLunch"/u);
  assert.match(html, /Mountain bike carnival/u);
  assert.match(html, /data-preset="cyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="bmxCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="cyclingCarnivalLunch"') < html.indexOf('data-preset="mountainBikeCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="mountainBikeCarnivalLunch"') < html.indexOf('data-preset="bmxCarnivalLunch"'));
});
