import test from "node:test";
import assert from "node:assert/strict";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("office pantry and hardware presets evaluate with distinct categories", () => {
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  assert.ok(office.winner);
  assert.ok(hardware.winner);
  assert.equal(office.categoryCount, 1);
  assert.equal(hardware.categoryCount, 1);
  assert.equal(office.scenario.buyers[0].category, "Office pantry crate");
  assert.equal(hardware.scenario.buyers[0].category, "Hand tool kit");
  assert.ok(office.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Sweet snack")));
  assert.ok(hardware.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Imperial")));
  assert.notEqual(office.winner.offer.category, hardware.winner.offer.category);
  assert.ok(hardware.results.some((result) => result.offer.fulfillment === "pickup"));
});

test("community garden bulk seed is distinct and includes a pickup offer", () => {
  const garden = evaluateMarket(clonePreset("garden"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  assert.ok(garden.winner);
  assert.equal(garden.scenario.title, "Community garden bulk seed");
  assert.equal(garden.scenario.buyers[0].category, "Garden seed pack");
  assert.notEqual(garden.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(garden.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(garden.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.ok(garden.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Heirloom tomato")));
  assert.ok(garden.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cover crop")));
  assert.ok(garden.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Potting soil")));
  assert.ok(garden.results.some((result) => result.offer.fulfillment === "pickup"));
  const quantities = garden.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("garden"));
  const second = evaluateMarket(validateScenario(clonePreset("garden")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("school fete catering is distinct synthetic bulk catering", () => {
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(fete.winner);
  assert.equal(fete.scenario.title, "School fete catering");
  assert.equal(fete.scenario.buyers[0].category, "Fete catering pack");
  assert.notEqual(fete.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(fete.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(fete.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(fete.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(fete.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(fete.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(fete.scenario.title, ladder.scenario.title);
  assert.ok(fete.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Sausage sizzle")));
  assert.ok(fete.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cake stall")));
  assert.ok(fete.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Drinks cooler")));
  assert.ok(fete.results.some((result) => result.offer.fulfillment === "pickup"));
  const quantities = fete.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("schoolFete"));
  const second = evaluateMarket(validateScenario(clonePreset("schoolFete")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("office fruit box is distinct synthetic weekly fruit for an office", () => {
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(fruit.winner);
  assert.equal(fruit.scenario.title, "Office fruit box");
  assert.equal(fruit.scenario.buyers[0].category, "Office fruit crate");
  assert.notEqual(fruit.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(fruit.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(fruit.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(fruit.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(fruit.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(fruit.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(fruit.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(fruit.scenario.title, ladder.scenario.title);
  assert.ok(fruit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Citrus mix")));
  assert.ok(fruit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Apple crate")));
  assert.ok(fruit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Mixed seasonal")));
  assert.ok(fruit.results.some((result) => result.offer.fulfillment === "pickup"));
  const quantities = fruit.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("officeFruit"));
  const second = evaluateMarket(validateScenario(clonePreset("officeFruit")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("new presets survive validation and keep a deterministic winner", () => {
  for (const name of ["officePantry", "hardware", "garden", "schoolFete", "officeFruit", "libraryPaper", "sportsKit", "surfFirstAid", "theatreWardrobe", "choirFolders", "scoutCamp", "schoolExcursionLunch", "netballCanteen", "swimmingCarnivalLunch", "athleticsCarnivalLunch", "cricketCarnivalLunch", "tennisCarnivalLunch", "basketballCarnivalLunch", "volleyballCarnivalLunch", "soccerCarnivalLunch", "rugbyCarnivalLunch", "hockeyCarnivalLunch", "baseballCarnivalLunch", "softballCarnivalLunch", "waterPoloCarnivalLunch", "rowingCarnivalLunch", "sailingCarnivalLunch", "canoeingCarnivalLunch", "kayakingCarnivalLunch", "dragonBoatCarnivalLunch", "surfCarnivalLunch", "triathlonCarnivalLunch", "cyclingCarnivalLunch", "mountainBikeCarnivalLunch", "bmxCarnivalLunch", "cycloCrossCarnivalLunch", "trackCyclingCarnivalLunch", "gravelCyclingCarnivalLunch", "roadCyclingCarnivalLunch", "criteriumCyclingCarnivalLunch", "timeTrialCyclingCarnivalLunch", "hillClimbCyclingCarnivalLunch"]) {
    const first = evaluateMarket(clonePreset(name));
    const second = evaluateMarket(validateScenario(clonePreset(name)));
    assert.equal(first.winner.offer.id, second.winner.offer.id);
    assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  }
});

test("the example bar includes school fete catering", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="schoolFete"/u);
  assert.match(html, /School fete/u);
});

test("the example bar includes the community garden bulk seed preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="garden"/u);
  assert.match(html, /Garden seed/u);
});

test("the example bar includes the office fruit box preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="officeFruit"/u);
  assert.match(html, /Office fruit/u);
});

test("library photocopy paper is distinct synthetic mixed-ream paper for a library", () => {
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(paper.winner);
  assert.equal(paper.scenario.title, "Library photocopy paper");
  assert.equal(paper.scenario.buyers[0].category, "Photocopy paper ream");
  assert.notEqual(paper.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(paper.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(paper.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(paper.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(paper.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(paper.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(paper.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(paper.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(paper.scenario.title, ladder.scenario.title);
  assert.ok(paper.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("A4 80gsm")));
  assert.ok(paper.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("A3 80gsm")));
  assert.ok(paper.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Recycled A4")));
  assert.ok(paper.results.some((result) => result.offer.merchant === "Desk Delivery Paper" && result.offer.fulfillment === "shipping"));
  assert.ok(paper.results.some((result) => result.offer.merchant === "Lobby Paper Pickup" && result.offer.fulfillment === "pickup"));
  const quantities = paper.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("libraryPaper"));
  const second = evaluateMarket(validateScenario(clonePreset("libraryPaper")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the library photocopy paper preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="libraryPaper"/u);
  assert.match(html, /Library paper/u);
});

test("sports club match-day kit is distinct synthetic mixed kit for a club", () => {
  const kit = evaluateMarket(clonePreset("sportsKit"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(kit.winner);
  assert.equal(kit.scenario.title, "Sports club match-day kit");
  assert.equal(kit.scenario.buyers[0].category, "Match-day kit pack");
  assert.notEqual(kit.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, paper.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.title, ladder.scenario.title);
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Club jersey")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Training shorts")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Water crate")));
  assert.ok(kit.results.some((result) => result.offer.merchant === "Field Kit Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(kit.results.some((result) => result.offer.merchant === "Clubhouse Kit Pickup" && result.offer.fulfillment === "pickup"));
  const quantities = kit.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("sportsKit"));
  const second = evaluateMarket(validateScenario(clonePreset("sportsKit")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the sports club match-day kit preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="sportsKit"/u);
  assert.match(html, /Sports kit/u);
});

test("surf club first-aid kit is distinct synthetic mixed first-aid for a club", () => {
  const kit = evaluateMarket(clonePreset("surfFirstAid"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const sports = evaluateMarket(clonePreset("sportsKit"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(kit.winner);
  assert.equal(kit.scenario.title, "Surf club first-aid kit");
  assert.equal(kit.scenario.buyers[0].category, "Surf first-aid kit");
  assert.notEqual(kit.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, paper.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, sports.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.title, ladder.scenario.title);
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Crepe bandage")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Ice pack")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Saline rinse")));
  assert.ok(kit.results.some((result) => result.offer.merchant === "Beach Kit Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(kit.results.some((result) => result.offer.merchant === "Clubhouse First-Aid Pickup" && result.offer.fulfillment === "pickup"));
  const quantities = kit.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("surfFirstAid"));
  const second = evaluateMarket(validateScenario(clonePreset("surfFirstAid")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the surf club first-aid kit preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="surfFirstAid"/u);
  assert.match(html, /Surf first-aid/u);
});

test("theatre wardrobe kit is distinct synthetic mixed costume wardrobe", () => {
  const kit = evaluateMarket(clonePreset("theatreWardrobe"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const sports = evaluateMarket(clonePreset("sportsKit"));
  const surf = evaluateMarket(clonePreset("surfFirstAid"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(kit.winner);
  assert.equal(kit.scenario.title, "Theatre wardrobe kit");
  assert.equal(kit.scenario.buyers[0].category, "Costume wardrobe pack");
  assert.notEqual(kit.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, paper.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, sports.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, surf.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.title, ladder.scenario.title);
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Period costume")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Rehearsal blacks")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Quick-change cloak")));
  assert.ok(kit.results.some((result) => result.offer.merchant === "Stage-door Costume Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(kit.results.some((result) => result.offer.merchant === "Green-room Wardrobe Pickup" && result.offer.fulfillment === "pickup"));
  const quantities = kit.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("theatreWardrobe"));
  const second = evaluateMarket(validateScenario(clonePreset("theatreWardrobe")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the theatre wardrobe kit preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="theatreWardrobe"/u);
  assert.match(html, /Theatre wardrobe/u);
});

test("community choir folders is distinct synthetic mixed SATB folders", () => {
  const kit = evaluateMarket(clonePreset("choirFolders"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const sports = evaluateMarket(clonePreset("sportsKit"));
  const surf = evaluateMarket(clonePreset("surfFirstAid"));
  const theatre = evaluateMarket(clonePreset("theatreWardrobe"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(kit.winner);
  assert.equal(kit.scenario.title, "Community choir folders");
  assert.equal(kit.scenario.buyers[0].category, "Choir folder pack");
  assert.notEqual(kit.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, paper.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, sports.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, surf.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, theatre.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.title, ladder.scenario.title);
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Soprano folder")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Alto folder")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tenor folder")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Bass folder")));
  assert.ok(kit.results.some((result) => result.offer.merchant === "Rehearsal-room Folder Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(kit.results.some((result) => result.offer.merchant === "Hall Folder Pickup" && result.offer.fulfillment === "pickup"));
  const quantities = kit.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("choirFolders"));
  const second = evaluateMarket(validateScenario(clonePreset("choirFolders")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the community choir folders preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="choirFolders"/u);
  assert.match(html, /Choir folders/u);
});

test("scout camp kit is distinct synthetic mixed camp kit", () => {
  const kit = evaluateMarket(clonePreset("scoutCamp"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const sports = evaluateMarket(clonePreset("sportsKit"));
  const surf = evaluateMarket(clonePreset("surfFirstAid"));
  const theatre = evaluateMarket(clonePreset("theatreWardrobe"));
  const choir = evaluateMarket(clonePreset("choirFolders"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(kit.winner);
  assert.equal(kit.scenario.title, "Scout camp kit");
  assert.equal(kit.scenario.buyers[0].category, "Scout camp pack");
  assert.notEqual(kit.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, paper.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, sports.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, surf.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, theatre.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.buyers[0].category, choir.scenario.buyers[0].category);
  assert.notEqual(kit.scenario.title, ladder.scenario.title);
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Synthetic compass")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Mess-tin")));
  assert.ok(kit.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Groundsheet")));
  assert.ok(kit.results.some((result) => result.offer.merchant === "Campsite Kit Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(kit.results.some((result) => result.offer.merchant === "Scout-hall Kit Pickup" && result.offer.fulfillment === "pickup"));
  const quantities = kit.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("scoutCamp"));
  const second = evaluateMarket(validateScenario(clonePreset("scoutCamp")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the scout camp kit preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="scoutCamp"/u);
  assert.match(html, /Scout camp/u);
});

test("school excursion lunch is distinct synthetic mixed lunch packs", () => {
  const lunch = evaluateMarket(clonePreset("schoolExcursionLunch"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const sports = evaluateMarket(clonePreset("sportsKit"));
  const surf = evaluateMarket(clonePreset("surfFirstAid"));
  const theatre = evaluateMarket(clonePreset("theatreWardrobe"));
  const choir = evaluateMarket(clonePreset("choirFolders"));
  const scout = evaluateMarket(clonePreset("scoutCamp"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(lunch.winner);
  assert.equal(lunch.scenario.title, "School excursion lunch");
  assert.equal(lunch.scenario.buyers[0].category, "Excursion lunch pack");
  assert.notEqual(lunch.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, paper.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, sports.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, surf.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, theatre.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, choir.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.buyers[0].category, scout.scenario.buyers[0].category);
  assert.notEqual(lunch.scenario.title, ladder.scenario.title);
  assert.notEqual(lunch.scenario.title, fete.scenario.title);
  assert.ok(lunch.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Mixed sandwich")));
  assert.ok(lunch.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Fruit cup")));
  assert.ok(lunch.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Water crate")));
  assert.ok(lunch.results.some((result) => result.offer.merchant === "Coach-stop Lunch Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(lunch.results.some((result) => result.offer.merchant === "Hall Lunch Pickup" && result.offer.fulfillment === "pickup"));
  const quantities = lunch.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("schoolExcursionLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("schoolExcursionLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the school excursion lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="schoolExcursionLunch"/u);
  assert.match(html, /School excursion/u);
});

test("netball canteen lunch is distinct synthetic mixed canteen lunch", () => {
  const canteen = evaluateMarket(clonePreset("netballCanteen"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const sports = evaluateMarket(clonePreset("sportsKit"));
  const surf = evaluateMarket(clonePreset("surfFirstAid"));
  const theatre = evaluateMarket(clonePreset("theatreWardrobe"));
  const choir = evaluateMarket(clonePreset("choirFolders"));
  const scout = evaluateMarket(clonePreset("scoutCamp"));
  const lunch = evaluateMarket(clonePreset("schoolExcursionLunch"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(canteen.winner);
  assert.equal(canteen.scenario.title, "Netball canteen lunch");
  assert.equal(canteen.scenario.buyers[0].category, "Canteen lunch pack");
  assert.notEqual(canteen.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, paper.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, sports.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, surf.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, theatre.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, choir.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, scout.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.buyers[0].category, lunch.scenario.buyers[0].category);
  assert.notEqual(canteen.scenario.title, ladder.scenario.title);
  assert.notEqual(canteen.scenario.title, lunch.scenario.title);
  assert.notEqual(canteen.scenario.title, fete.scenario.title);
  assert.ok(canteen.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Meat pie")));
  assert.ok(canteen.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Garden salad")));
  assert.ok(canteen.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Still water")));
  assert.ok(canteen.results.some((result) => result.offer.merchant === "Gate Canteen Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(canteen.results.some((result) => result.offer.merchant === "Hall Canteen Pickup" && result.offer.fulfillment === "pickup"));
  const quantities = canteen.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("netballCanteen"));
  const second = evaluateMarket(validateScenario(clonePreset("netballCanteen")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the netball canteen lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="netballCanteen"/u);
  assert.match(html, /Netball canteen/u);
});

test("swimming carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("swimmingCarnivalLunch"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const sports = evaluateMarket(clonePreset("sportsKit"));
  const surf = evaluateMarket(clonePreset("surfFirstAid"));
  const theatre = evaluateMarket(clonePreset("theatreWardrobe"));
  const choir = evaluateMarket(clonePreset("choirFolders"));
  const scout = evaluateMarket(clonePreset("scoutCamp"));
  const lunch = evaluateMarket(clonePreset("schoolExcursionLunch"));
  const canteen = evaluateMarket(clonePreset("netballCanteen"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Swimming carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Carnival lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, paper.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, sports.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, surf.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, theatre.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, choir.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, scout.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, lunch.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, canteen.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.title, ladder.scenario.title);
  assert.notEqual(carnival.scenario.title, lunch.scenario.title);
  assert.notEqual(carnival.scenario.title, canteen.scenario.title);
  assert.notEqual(carnival.scenario.title, fete.scenario.title);
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Carnival pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Lane salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pool water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Meat pie")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Garden salad")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Still water")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Mixed sandwich")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Pool-deck Carnival Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Carnival Pickup" && result.offer.fulfillment === "pickup"));
  const quantities = carnival.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("swimmingCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("swimmingCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the swimming carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="swimmingCarnivalLunch"/u);
  assert.match(html, /Swimming carnival/u);
});

test("athletics carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("athleticsCarnivalLunch"));
  const swimming = evaluateMarket(clonePreset("swimmingCarnivalLunch"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const sports = evaluateMarket(clonePreset("sportsKit"));
  const surf = evaluateMarket(clonePreset("surfFirstAid"));
  const theatre = evaluateMarket(clonePreset("theatreWardrobe"));
  const choir = evaluateMarket(clonePreset("choirFolders"));
  const scout = evaluateMarket(clonePreset("scoutCamp"));
  const lunch = evaluateMarket(clonePreset("schoolExcursionLunch"));
  const canteen = evaluateMarket(clonePreset("netballCanteen"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Athletics carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Athletics lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, swimming.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, paper.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, sports.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, surf.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, theatre.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, choir.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, scout.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, lunch.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, canteen.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.title, swimming.scenario.title);
  assert.notEqual(carnival.scenario.title, ladder.scenario.title);
  assert.notEqual(carnival.scenario.title, lunch.scenario.title);
  assert.notEqual(carnival.scenario.title, canteen.scenario.title);
  assert.notEqual(carnival.scenario.title, fete.scenario.title);
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Athletics pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Track salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Track water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Carnival pie")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Lane salad")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pool water")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Meat pie")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Garden salad")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Still water")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Mixed sandwich")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Track-side Athletics Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Athletics Pickup" && result.offer.fulfillment === "pickup"));
  const quantities = carnival.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("athleticsCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("athleticsCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the athletics carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="athleticsCarnivalLunch"/u);
  assert.match(html, /Athletics carnival/u);
});

test("cricket carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("cricketCarnivalLunch"));
  const athletics = evaluateMarket(clonePreset("athleticsCarnivalLunch"));
  const swimming = evaluateMarket(clonePreset("swimmingCarnivalLunch"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const studio = evaluateMarket(clonePreset("studio"));
  const pantry = evaluateMarket(clonePreset("pantry"));
  const office = evaluateMarket(clonePreset("officePantry"));
  const hardware = evaluateMarket(clonePreset("hardware"));
  const garden = evaluateMarket(clonePreset("garden"));
  const fete = evaluateMarket(clonePreset("schoolFete"));
  const fruit = evaluateMarket(clonePreset("officeFruit"));
  const paper = evaluateMarket(clonePreset("libraryPaper"));
  const sports = evaluateMarket(clonePreset("sportsKit"));
  const surf = evaluateMarket(clonePreset("surfFirstAid"));
  const theatre = evaluateMarket(clonePreset("theatreWardrobe"));
  const choir = evaluateMarket(clonePreset("choirFolders"));
  const scout = evaluateMarket(clonePreset("scoutCamp"));
  const lunch = evaluateMarket(clonePreset("schoolExcursionLunch"));
  const canteen = evaluateMarket(clonePreset("netballCanteen"));
  const ladder = evaluateMarket(clonePreset("tiers"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Cricket carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Cricket lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, athletics.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, swimming.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, studio.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, pantry.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, office.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, hardware.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, garden.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, fete.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, fruit.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, paper.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, sports.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, surf.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, theatre.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, choir.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, scout.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, lunch.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, canteen.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.title, athletics.scenario.title);
  assert.notEqual(carnival.scenario.title, swimming.scenario.title);
  assert.notEqual(carnival.scenario.title, ladder.scenario.title);
  assert.notEqual(carnival.scenario.title, lunch.scenario.title);
  assert.notEqual(carnival.scenario.title, canteen.scenario.title);
  assert.notEqual(carnival.scenario.title, fete.scenario.title);
  assert.notDeepEqual(clonePreset("cricketCarnivalLunch"), clonePreset("athleticsCarnivalLunch"));
  assert.notDeepEqual(clonePreset("cricketCarnivalLunch"), clonePreset("tennisCarnivalLunch"));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cricket pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pitch salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pitch water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Athletics pie")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Track salad")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Track water")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Carnival pie")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Lane salad")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pool water")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Meat pie")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Garden salad")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Still water")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Mixed sandwich")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Pitch-side Cricket Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Cricket Pickup" && result.offer.fulfillment === "pickup"));
  const leftoverFill = computeResidualCoverage(carnival.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Cricket Pickup");
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).fulfillment, "pickup");
  const quantities = carnival.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("cricketCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("cricketCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the cricket carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="cricketCarnivalLunch"/u);
  assert.match(html, /Cricket carnival/u);
});

test("tennis carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("tennisCarnivalLunch"));
  const cricket = evaluateMarket(clonePreset("cricketCarnivalLunch"));
  const athletics = evaluateMarket(clonePreset("athleticsCarnivalLunch"));
  const swimming = evaluateMarket(clonePreset("swimmingCarnivalLunch"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const canteen = evaluateMarket(clonePreset("netballCanteen"));
  const lunch = evaluateMarket(clonePreset("schoolExcursionLunch"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Tennis carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Tennis lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, cricket.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, athletics.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, swimming.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, canteen.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.title, cricket.scenario.title);
  assert.notDeepEqual(clonePreset("tennisCarnivalLunch"), clonePreset("cricketCarnivalLunch"));
  assert.notDeepEqual(clonePreset("tennisCarnivalLunch"), clonePreset("basketballCarnivalLunch"));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tennis pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Court salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Court water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cricket pie")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pitch salad")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Athletics pie")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Court-side Tennis Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Tennis Pickup" && result.offer.fulfillment === "pickup"));
  const leftoverFill = computeResidualCoverage(carnival.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Tennis Pickup");
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).fulfillment, "pickup");
  const quantities = carnival.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("tennisCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("tennisCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the tennis carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="tennisCarnivalLunch"/u);
  assert.match(html, /Tennis carnival/u);
});

test("basketball carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("basketballCarnivalLunch"));
  const tennis = evaluateMarket(clonePreset("tennisCarnivalLunch"));
  const cricket = evaluateMarket(clonePreset("cricketCarnivalLunch"));
  const athletics = evaluateMarket(clonePreset("athleticsCarnivalLunch"));
  const swimming = evaluateMarket(clonePreset("swimmingCarnivalLunch"));
  const coffee = evaluateMarket(clonePreset("neighbourhood"));
  const canteen = evaluateMarket(clonePreset("netballCanteen"));
  const lunch = evaluateMarket(clonePreset("schoolExcursionLunch"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Basketball carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Basketball lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, tennis.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, cricket.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, athletics.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, swimming.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, coffee.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.buyers[0].category, canteen.scenario.buyers[0].category);
  assert.notEqual(carnival.scenario.title, tennis.scenario.title);
  assert.notDeepEqual(clonePreset("basketballCarnivalLunch"), clonePreset("tennisCarnivalLunch"));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Basketball pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Bench salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Bench water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tennis pie")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Court salad")), false);
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cricket pie")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Court-side Basketball Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Basketball Pickup" && result.offer.fulfillment === "pickup"));
  const leftoverFill = computeResidualCoverage(carnival.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Basketball Pickup");
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).fulfillment, "pickup");
  const quantities = carnival.scenario.buyers.map((buyer) => buyer.quantity);
  assert.equal(new Set(quantities).size > 1, true);
  const first = evaluateMarket(clonePreset("basketballCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("basketballCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the basketball carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="basketballCarnivalLunch"/u);
  assert.match(html, /Basketball carnival/u);
});

test("volleyball carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("volleyballCarnivalLunch"));
  const basketball = evaluateMarket(clonePreset("basketballCarnivalLunch"));
  const tennis = evaluateMarket(clonePreset("tennisCarnivalLunch"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Volleyball carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Volleyball lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, basketball.scenario.buyers[0].category);
  assert.notDeepEqual(clonePreset("volleyballCarnivalLunch"), clonePreset("basketballCarnivalLunch"));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Volleyball pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Sideline salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Sideline water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Basketball pie")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Court-side Volleyball Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Volleyball Pickup" && result.offer.fulfillment === "pickup"));
  const leftoverFill = computeResidualCoverage(carnival.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Volleyball Pickup");
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).minimumUnits, 10);
  assert.notEqual(tennis.scenario.title, carnival.scenario.title);
  const first = evaluateMarket(clonePreset("volleyballCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("volleyballCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the volleyball carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="volleyballCarnivalLunch"/u);
  assert.match(html, /Volleyball carnival/u);
});

test("soccer carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  const volleyball = evaluateMarket(clonePreset("volleyballCarnivalLunch"));
  const basketball = evaluateMarket(clonePreset("basketballCarnivalLunch"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Soccer carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Soccer lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, volleyball.scenario.buyers[0].category);
  assert.notDeepEqual(clonePreset("soccerCarnivalLunch"), clonePreset("volleyballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("soccerCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Soccer pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pitch salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pitch water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Volleyball pie")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Court-side Soccer Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Soccer Pickup" && result.offer.fulfillment === "pickup"));
  const leftoverFill = computeResidualCoverage(carnival.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Soccer Pickup");
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).minimumUnits, 11);
  assert.notEqual(volleyball.scenario.title, carnival.scenario.title);
  assert.notEqual(basketball.scenario.title, carnival.scenario.title);
  const first = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("soccerCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the soccer carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="soccerCarnivalLunch"/u);
  assert.match(html, /Soccer carnival/u);
});

test("rugby carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  const volleyball = evaluateMarket(clonePreset("volleyballCarnivalLunch"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Rugby carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Rugby lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, soccer.scenario.buyers[0].category);
  assert.notDeepEqual(clonePreset("rugbyCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Rugby pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tryline salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tryline water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Soccer pie")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Court-side Rugby Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Rugby Pickup" && result.offer.fulfillment === "pickup"));
  const leftoverFill = computeResidualCoverage(carnival.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Rugby Pickup");
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).minimumUnits, 12);
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.notEqual(volleyball.scenario.title, carnival.scenario.title);
  assert.notEqual(soccer.scenario.title, carnival.scenario.title);
  const first = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("rugbyCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the rugby carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="rugbyCarnivalLunch"/u);
  assert.match(html, /Rugby carnival/u);
});

test("hockey carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Hockey carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Hockey lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, rugby.scenario.buyers[0].category);
  assert.notDeepEqual(clonePreset("hockeyCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("hockeyCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hockey pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Boards salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Boards water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Rugby pie")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Court-side Hockey Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Hockey Pickup" && result.offer.fulfillment === "pickup"));
  const leftoverFill = computeResidualCoverage(carnival.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Hockey Pickup");
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).minimumUnits, 13);
  assert.equal(rugby.winner.offer.merchant, "Court-side Rugby Delivery");
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.notEqual(rugby.scenario.title, carnival.scenario.title);
  assert.notEqual(soccer.scenario.title, carnival.scenario.title);
  const first = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("hockeyCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the hockey carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="hockeyCarnivalLunch"/u);
  assert.match(html, /Hockey carnival/u);
});

test("baseball carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Baseball carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Baseball lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, hockey.scenario.buyers[0].category);
  assert.notDeepEqual(clonePreset("baseballCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("baseballCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("baseballCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Baseball pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Boards salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Boards water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hockey pie")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Court-side Baseball Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Baseball Pickup" && result.offer.fulfillment === "pickup"));
  const leftoverFill = computeResidualCoverage(carnival.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Baseball Pickup");
  assert.equal(carnival.winner.fulfilledUnits, 50);
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).minimumUnits, 14);
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).capacity, 44);
  assert.equal(leftoverFill.fulfilledUnits, 23);
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).capacity - leftoverFill.fulfilledUnits, 21);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.deepEqual(computeResidualCoverage(carnival.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.equal(hockey.winner.offer.merchant, "Court-side Hockey Delivery");
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(rugby.winner.offer.merchant, "Court-side Rugby Delivery");
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.notEqual(hockey.scenario.title, carnival.scenario.title);
  assert.notEqual(rugby.scenario.title, carnival.scenario.title);
  assert.notEqual(soccer.scenario.title, carnival.scenario.title);
  const first = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("baseballCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the baseball carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="baseballCarnivalLunch"/u);
  assert.match(html, /Baseball carnival/u);
});

test("softball carnival lunch is distinct synthetic mixed carnival lunch", () => {
  const carnival = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(carnival.winner);
  assert.equal(carnival.scenario.title, "Softball carnival lunch");
  assert.equal(carnival.scenario.buyers[0].category, "Softball lunch pack");
  assert.notEqual(carnival.scenario.buyers[0].category, baseball.scenario.buyers[0].category);
  assert.notDeepEqual(clonePreset("softballCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("softballCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("softballCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("softballCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Softball pie")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Boards salad")));
  assert.ok(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Boards water")));
  assert.equal(carnival.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Baseball pie")), false);
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Court-side Softball Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(carnival.results.some((result) => result.offer.merchant === "Hall Softball Pickup" && result.offer.fulfillment === "pickup"));
  const leftoverFill = computeResidualCoverage(carnival.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Softball Pickup");
  assert.equal(carnival.winner.fulfilledUnits, 50);
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).minimumUnits, 15);
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).capacity, 44);
  assert.equal(leftoverFill.fulfilledUnits, 23);
  assert.equal(carnival.scenario.offers.find((offer) => offer.id === leftoverFill.offerId).capacity - leftoverFill.fulfilledUnits, 21);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.deepEqual(computeResidualCoverage(carnival.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.equal(baseball.winner.offer.merchant, "Court-side Baseball Delivery");
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(hockey.winner.offer.merchant, "Court-side Hockey Delivery");
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(rugby.winner.offer.merchant, "Court-side Rugby Delivery");
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.notEqual(baseball.scenario.title, carnival.scenario.title);
  assert.notEqual(hockey.scenario.title, carnival.scenario.title);
  assert.notEqual(rugby.scenario.title, carnival.scenario.title);
  assert.notEqual(soccer.scenario.title, carnival.scenario.title);
  const first = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("softballCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
});

test("the example bar includes the softball carnival lunch preset", async () => {
  const { readFile } = await import("node:fs/promises");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="softballCarnivalLunch"/u);
  assert.match(html, /Softball carnival/u);
});
