import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("road cycling carnival lunch leftover fill is hall pickup and stays distinct from gravel cycling carnival lunch", () => {
  const roadCycling = evaluateMarket(clonePreset("roadCyclingCarnivalLunch"));
  const gravelCycling = evaluateMarket(clonePreset("gravelCyclingCarnivalLunch"));
  const trackCycling = evaluateMarket(clonePreset("trackCyclingCarnivalLunch"));
  const cycloCross = evaluateMarket(clonePreset("cycloCrossCarnivalLunch"));
  const bmx = evaluateMarket(clonePreset("bmxCarnivalLunch"));
  const mountainBike = evaluateMarket(clonePreset("mountainBikeCarnivalLunch"));
  const cycling = evaluateMarket(clonePreset("cyclingCarnivalLunch"));
  const triathlon = evaluateMarket(clonePreset("triathlonCarnivalLunch"));
  const surf = evaluateMarket(clonePreset("surfCarnivalLunch"));
  const dragonBoat = evaluateMarket(clonePreset("dragonBoatCarnivalLunch"));
  const kayaking = evaluateMarket(clonePreset("kayakingCarnivalLunch"));
  const canoeing = evaluateMarket(clonePreset("canoeingCarnivalLunch"));
  const sailing = evaluateMarket(clonePreset("sailingCarnivalLunch"));
  const rowing = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(roadCycling.winner);
  assert.equal(roadCycling.winner.offer.merchant, "Court-side Road Cycling Delivery");
  assert.equal(roadCycling.winner.offer.fulfillment, "shipping");
  assert.equal(roadCycling.winner.fulfilledUnits, 50);
  assert.deepEqual(roadCycling.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(roadCycling.scenario.title, "Road cycling carnival lunch");
  assert.notEqual(roadCycling.scenario.title, gravelCycling.scenario.title);
  assert.notEqual(roadCycling.scenario.title, trackCycling.scenario.title);
  assert.notEqual(roadCycling.scenario.title, cycloCross.scenario.title);
  assert.notEqual(roadCycling.scenario.title, bmx.scenario.title);
  assert.notEqual(roadCycling.scenario.title, mountainBike.scenario.title);
  assert.notEqual(roadCycling.scenario.title, cycling.scenario.title);
  assert.notEqual(roadCycling.scenario.title, triathlon.scenario.title);
  assert.notEqual(roadCycling.scenario.title, surf.scenario.title);
  assert.notEqual(roadCycling.scenario.title, dragonBoat.scenario.title);
  assert.notEqual(roadCycling.scenario.title, kayaking.scenario.title);
  assert.notEqual(roadCycling.scenario.title, canoeing.scenario.title);
  assert.notEqual(roadCycling.scenario.title, sailing.scenario.title);
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("criteriumCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("gravelCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("trackCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("cycloCrossCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("bmxCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("mountainBikeCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("cyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("triathlonCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("surfCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("dragonBoatCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("kayakingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("canoeingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("sailingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("rowingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("waterPoloCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("roadCyclingCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(roadCycling.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Road Cycling Pickup");
  const leftoverOffer = roadCycling.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 30);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.minimumUnits);
  assert.equal(leftoverOffer.unitPrice, 25);
  assert.equal(roadCycling.scenario.buyers.find((buyer) => buyer.id === "B04").maxUnitPrice, 25);
  assert.equal(roadCycling.scenario.buyers.find((buyer) => buyer.id === "B04").quantity, 16);
  assert.equal(gravelCycling.scenario.offers.find((offer) => offer.merchant === "Hall Gravel Cycling Pickup").minimumUnits, 29);
  assert.equal(trackCycling.scenario.offers.find((offer) => offer.merchant === "Hall Track Cycling Pickup").minimumUnits, 28);
  assert.equal(cycloCross.scenario.offers.find((offer) => offer.merchant === "Hall Cyclo-cross Pickup").minimumUnits, 27);
  assert.equal(bmx.scenario.offers.find((offer) => offer.merchant === "Hall BMX Pickup").minimumUnits, 26);
  assert.equal(mountainBike.scenario.offers.find((offer) => offer.merchant === "Hall Mountain Bike Pickup").minimumUnits, 25);
  assert.equal(cycling.scenario.offers.find((offer) => offer.merchant === "Hall Cycling Pickup").minimumUnits, 24);
  assert.equal(triathlon.scenario.offers.find((offer) => offer.merchant === "Hall Triathlon Pickup").minimumUnits, 23);
  assert.equal(surf.scenario.offers.find((offer) => offer.merchant === "Hall Surf Pickup").minimumUnits, 22);
  assert.equal(dragonBoat.scenario.offers.find((offer) => offer.merchant === "Hall Dragon Boat Pickup").minimumUnits, 21);
  assert.equal(kayaking.scenario.offers.find((offer) => offer.merchant === "Hall Kayaking Pickup").minimumUnits, 20);
  assert.equal(canoeing.scenario.offers.find((offer) => offer.merchant === "Hall Canoeing Pickup").minimumUnits, 19);
  assert.equal(sailing.scenario.offers.find((offer) => offer.merchant === "Hall Sailing Pickup").minimumUnits, 18);
  assert.equal(rowing.scenario.offers.find((offer) => offer.merchant === "Hall Rowing Pickup").minimumUnits, 17);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(waterPolo.scenario.offers.find((offer) => offer.merchant === "Hall Water Polo Pickup").minimumUnits, 16);
  assert.equal(gravelCycling.winner.offer.merchant, "Court-side Gravel Cycling Delivery");
  assert.equal(trackCycling.winner.offer.merchant, "Court-side Track Cycling Delivery");
  assert.equal(cycloCross.winner.offer.merchant, "Court-side Cyclo-cross Delivery");
  assert.equal(bmx.winner.offer.merchant, "Court-side BMX Delivery");
  assert.equal(mountainBike.winner.offer.merchant, "Court-side Mountain Bike Delivery");
  assert.equal(cycling.winner.offer.merchant, "Court-side Cycling Delivery");
  assert.equal(triathlon.winner.offer.merchant, "Court-side Triathlon Delivery");
  assert.equal(surf.winner.offer.merchant, "Court-side Surf Delivery");
  assert.equal(dragonBoat.winner.offer.merchant, "Court-side Dragon Boat Delivery");
  assert.equal(kayaking.winner.offer.merchant, "Court-side Kayaking Delivery");
  assert.equal(sailing.winner.offer.merchant, "Court-side Sailing Delivery");
  assert.equal(canoeing.winner.offer.merchant, "Court-side Canoeing Delivery");
  assert.equal(rowing.winner.offer.merchant, "Court-side Rowing Delivery");
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(leftoverOffer.capacity, 60);
  assert.equal(leftoverFill.fulfilledUnits, 31);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 29);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.unitPrice);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.minimumUnits);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(roadCycling.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(roadCycling.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(roadCycling.results.some((result) => result.offer.merchant === "Court-side Road Cycling Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Road pie")));
  assert.ok(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Peloton salad")));
  assert.ok(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Bottle water")));
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Gravel pie")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Feed-zone salad")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Neutral water")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Keirin pie")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Sprint salad")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Keirin water")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cyclo-cross pie")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Barrier salad")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pit water")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("BMX pie")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pump salad")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pump water")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail pie")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail salad")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Trail water")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Cycle pie")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Velodrome salad")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Velodrome water")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tri pie")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Surf pie")), false);
  assert.equal(roadCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Dragon boat pie")), false);
  const first = evaluateMarket(clonePreset("roadCyclingCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("roadCyclingCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes road cycling carnival lunch next to gravel cycling carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="roadCyclingCarnivalLunch"/u);
  assert.match(html, /Road cycling carnival/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="gravelCyclingCarnivalLunch"') < html.indexOf('data-preset="roadCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="roadCyclingCarnivalLunch"') < html.indexOf('data-preset="criteriumCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="criteriumCyclingCarnivalLunch"') < html.indexOf('data-preset="timeTrialCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="timeTrialCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
});
