import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("rowing carnival lunch leftover fill is hall pickup and stays distinct from water polo carnival lunch", () => {
  const rowing = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(rowing.winner);
  assert.equal(rowing.winner.offer.merchant, "Court-side Rowing Delivery");
  assert.equal(rowing.winner.offer.fulfillment, "shipping");
  assert.equal(rowing.winner.fulfilledUnits, 50);
  assert.deepEqual(rowing.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(rowing.scenario.title, "Rowing carnival lunch");
  assert.notEqual(rowing.scenario.title, waterPolo.scenario.title);
  assert.notDeepEqual(clonePreset("rowingCarnivalLunch"), clonePreset("waterPoloCarnivalLunch"));
  assert.notDeepEqual(clonePreset("rowingCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("rowingCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("rowingCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("rowingCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("rowingCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(rowing.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Rowing Pickup");
  const leftoverOffer = rowing.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 17);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(waterPolo.scenario.offers.find((offer) => offer.merchant === "Hall Water Polo Pickup").minimumUnits, 16);
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(rugby.winner.offer.merchant, "Court-side Rugby Delivery");
  assert.equal(hockey.winner.offer.merchant, "Court-side Hockey Delivery");
  assert.equal(baseball.winner.offer.merchant, "Court-side Baseball Delivery");
  assert.equal(softball.winner.offer.merchant, "Court-side Softball Delivery");
  assert.equal(waterPolo.winner.offer.merchant, "Court-side Water Polo Delivery");
  assert.equal(leftoverOffer.capacity, 44);
  assert.equal(leftoverFill.fulfilledUnits, 23);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 21);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(rowing.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(rowing.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(rowing.results.some((result) => result.offer.merchant === "Court-side Rowing Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(rowing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Rowing pie")));
  assert.ok(rowing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pontoon salad")));
  assert.ok(rowing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pontoon water")));
  assert.equal(rowing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Water polo pie")), false);
  assert.equal(rowing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pool water")), false);
  assert.equal(rowing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pool salad")), false);
  const first = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("rowingCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes rowing carnival lunch next to water polo carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="rowingCarnivalLunch"/u);
  assert.match(html, /Rowing carnival/u);
  assert.match(html, /data-preset="waterPoloCarnivalLunch"/u);
});
