import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("sailing carnival lunch leftover fill is hall pickup and stays distinct from rowing carnival lunch", () => {
  const sailing = evaluateMarket(clonePreset("sailingCarnivalLunch"));
  const rowing = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(sailing.winner);
  assert.equal(sailing.winner.offer.merchant, "Court-side Sailing Delivery");
  assert.equal(sailing.winner.offer.fulfillment, "shipping");
  assert.equal(sailing.winner.fulfilledUnits, 50);
  assert.deepEqual(sailing.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(sailing.scenario.title, "Sailing carnival lunch");
  assert.notEqual(sailing.scenario.title, rowing.scenario.title);
  assert.notDeepEqual(clonePreset("sailingCarnivalLunch"), clonePreset("rowingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("sailingCarnivalLunch"), clonePreset("waterPoloCarnivalLunch"));
  assert.notDeepEqual(clonePreset("sailingCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("sailingCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("sailingCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("sailingCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("sailingCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(sailing.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Sailing Pickup");
  const leftoverOffer = sailing.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 18);
  assert.equal(rowing.scenario.offers.find((offer) => offer.merchant === "Hall Rowing Pickup").minimumUnits, 17);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(waterPolo.scenario.offers.find((offer) => offer.merchant === "Hall Water Polo Pickup").minimumUnits, 16);
  assert.equal(rowing.winner.offer.merchant, "Court-side Rowing Delivery");
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(rugby.winner.offer.merchant, "Court-side Rugby Delivery");
  assert.equal(hockey.winner.offer.merchant, "Court-side Hockey Delivery");
  assert.equal(baseball.winner.offer.merchant, "Court-side Baseball Delivery");
  assert.equal(softball.winner.offer.merchant, "Court-side Softball Delivery");
  assert.equal(waterPolo.winner.offer.merchant, "Court-side Water Polo Delivery");
  assert.equal(leftoverOffer.capacity, 44);
  assert.equal(leftoverFill.fulfilledUnits, 23);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 21);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(sailing.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(sailing.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(sailing.results.some((result) => result.offer.merchant === "Court-side Sailing Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(sailing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Sailing pie")));
  assert.ok(sailing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Marina salad")));
  assert.ok(sailing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Marina water")));
  assert.equal(sailing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Rowing pie")), false);
  assert.equal(sailing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pontoon water")), false);
  assert.equal(sailing.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pontoon salad")), false);
  const first = evaluateMarket(clonePreset("sailingCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("sailingCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes sailing carnival lunch next to rowing carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="sailingCarnivalLunch"/u);
  assert.match(html, /Sailing carnival/u);
  assert.match(html, /data-preset="rowingCarnivalLunch"/u);
});
