import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("softball carnival lunch leftover fill is hall pickup and stays distinct from baseball carnival lunch", () => {
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(softball.winner);
  assert.equal(softball.winner.offer.merchant, "Court-side Softball Delivery");
  assert.equal(softball.winner.offer.fulfillment, "shipping");
  assert.equal(softball.winner.fulfilledUnits, 50);
  assert.deepEqual(softball.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(softball.scenario.title, "Softball carnival lunch");
  assert.notEqual(softball.scenario.title, baseball.scenario.title);
  assert.notDeepEqual(clonePreset("softballCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("softballCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("softballCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("softballCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(softball.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Softball Pickup");
  const leftoverOffer = softball.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 15);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(rugby.winner.offer.merchant, "Court-side Rugby Delivery");
  assert.equal(hockey.winner.offer.merchant, "Court-side Hockey Delivery");
  assert.equal(baseball.winner.offer.merchant, "Court-side Baseball Delivery");
  assert.equal(leftoverOffer.capacity, 44);
  assert.equal(leftoverFill.fulfilledUnits, 23);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 21);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(softball.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(softball.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(softball.results.some((result) => result.offer.merchant === "Court-side Softball Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(softball.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Softball pie")));
  assert.ok(softball.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Boards salad")));
  assert.ok(softball.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Boards water")));
  const first = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("softballCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes softball carnival lunch next to baseball carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="softballCarnivalLunch"/u);
  assert.match(html, /Softball carnival/u);
  assert.match(html, /data-preset="baseballCarnivalLunch"/u);
});
