import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { buildStandalone } from "../scripts/build-standalone.mjs";

test("generated standalone parses as a module without duplicate declarations", async () => {
  const html = await buildStandalone();
  const source = html.match(/<script type="module">([\s\S]*?)<\/script>/u)?.[1];
  assert.ok(source);
  const result = spawnSync(process.execPath, ["--check", "--input-type=module"], { input: source, encoding: "utf8" });
  assert.equal(result.status, 0, result.stderr || result.error?.message);
});

test("standalone GUI is deterministic and current", async () => {
  const expected = await buildStandalone();
  const current = (await readFile(new URL("../standalone.html", import.meta.url), "utf8")).replace(/\r\n?/gu, "\n");
  assert.equal(current, expected);
});

test("standalone GUI has no external resource dependency", async () => {
  const html = await buildStandalone();
  assert.match(html, /Content-Security-Policy/u);
  assert.match(html, /default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'/u);
  assert.match(html, /<style>[\s\S]+<\/style>/u);
  assert.match(html, /<script type="module">[\s\S]+<\/script>/u);
  assert.doesNotMatch(html, /<script[^>]+src=/iu);
  assert.doesNotMatch(html, /<link[^>]+stylesheet/iu);
  assert.doesNotMatch(html, /(?:src|href)=["'](?:\.\/|https?:|\/\/)/iu);
  assert.match(html, /window\.location\.protocol === "file:"/u);
  assert.match(html, /Use Export JSON to share a standalone scenario\./u);
  assert.match(html, /Included locally/u);
  assert.match(html, /No complete buyer set/u);
  assert.match(html, /Three ASCII letters, e\.g\. AUD/u);
  assert.match(html, /Accepted variants are a comma-separated list/u);
  assert.match(html, /cannot be empty/u);
  assert.match(html, /"Room name"/u);
  assert.match(html, /Share link could not be opened/u);
  assert.match(html, /Saved room could not be restored/u);
  assert.match(html, /not valid JSON/u);
});

test("standalone retains 1.4.18 tertiary remaining tools and 1.4.19 tertiary maximum controls", async () => {
  const html = await buildStandalone();
  assert.match(html, /id="copy-leftover-fill-label"/u);
  assert.match(html, /id="copy-leftover-fill-label"[^>]*aria-keyshortcuts="\$"/u);
  assert.match(html, /id="hide-first-buyer-filled-by-leftover-fill"/u);
  assert.match(html, /id="hide-last-buyer-filled-by-leftover-fill"/u);
  assert.match(html, /data-preset="tennisCarnivalLunch"/u);
  assert.match(html, /id="copy-leftover-fill-minimum"/u);
  assert.match(html, /id="copy-leftover-fill-minimum"[^>]*aria-keyshortcuts="5"/u);
  assert.match(html, /id="hide-first-buyer-filled-by-tertiary-fill"/u);
  assert.match(html, /id="leftover-print-fill-minimum"/u);
  assert.match(html, /Leftover fill minimum: none/u);
  assert.match(html, /data-preset="basketballCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverFillMinimum\(/u);
  assert.match(html, /function focusLeftoverFillMinimumCopy\(/u);
  assert.match(html, /function focusHideFirstBuyerFilledByTertiaryFill\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstBuyerFilledByTertiaryFill\(/u);
  assert.match(html, /hideFirstBuyerFilledByTertiaryFill/u);
  assert.match(html, /if \(key === "5"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverFillMinimum\(\);/u);
  assert.match(html, /if \(key === "6"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverFillMinimumCopy\(\);/u);
  assert.match(html, /if \(key === "7"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstBuyerFilledByTertiaryFill\(\);/u);
  assert.match(html, /id="copy-leftover-fill-maximum"/u);
  assert.match(html, /id="copy-leftover-fill-maximum"[^>]*aria-keyshortcuts="8"/u);
  assert.match(html, /id="hide-last-buyer-filled-by-tertiary-fill"/u);
  assert.match(html, /id="leftover-print-fill-maximum"/u);
  assert.match(html, /Leftover fill maximum: none/u);
  assert.match(html, /data-preset="volleyballCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverFillMaximum\(/u);
  assert.match(html, /function focusLeftoverFillMaximumCopy\(/u);
  assert.match(html, /function focusHideLastBuyerFilledByTertiaryFill\(/u);
  assert.match(html, /filterBuyerIdsHidingLastBuyerFilledByTertiaryFill\(/u);
  assert.match(html, /hideLastBuyerFilledByTertiaryFill/u);
  assert.match(html, /if \(key === "8"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverFillMaximum\(\);/u);
  assert.match(html, /if \(key === "9"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverFillMaximumCopy\(\);/u);
  assert.match(html, /if \(key === "0"\) \{\s*event\.preventDefault\(\);\s*focusHideLastBuyerFilledByTertiaryFill\(\);/u);
  assert.match(html, /id="copy-tertiary-fill-remaining"/u);
  assert.match(html, /id="copy-tertiary-fill-remaining"[^>]*aria-keyshortcuts="1"/u);
  assert.match(html, /id="hide-last-unserved-buyer"/u);
  assert.match(html, /id="leftover-print-tertiary-remaining"/u);
  assert.match(html, /Tertiary fill remaining capacity: none/u);
  assert.match(html, /data-preset="soccerCarnivalLunch"/u);
  assert.match(html, /function copyTertiaryFillRemainingCapacity\(/u);
  assert.match(html, /function focusTertiaryFillRemainingCopy\(/u);
  assert.match(html, /function focusHideLastUnservedBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingLastUnservedBuyer\(/u);
  assert.match(html, /hideLastUnservedBuyer/u);
  assert.match(html, /if \(key === "1"\) \{\s*event\.preventDefault\(\);\s*copyTertiaryFillRemainingCapacity\(\);/u);
  assert.match(html, /if \(key === "2"\) \{\s*event\.preventDefault\(\);\s*focusTertiaryFillRemainingCopy\(\);/u);
  assert.match(html, /if \(key === "3"\) \{\s*event\.preventDefault\(\);\s*focusHideLastUnservedBuyer\(\);/u);
  assert.match(html, /id="copy-tertiary-fill-maximum"/u);
  assert.match(html, /id="copy-tertiary-fill-maximum"[^>]*aria-keyshortcuts="4"/u);
  assert.match(html, /id="hide-first-unserved-buyer"/u);
  assert.match(html, /id="leftover-print-tertiary-maximum"/u);
  assert.match(html, /Tertiary fill maximum: none/u);
  assert.match(html, /data-preset="rugbyCarnivalLunch"/u);
  assert.match(html, /function copyTertiaryFillMaximum\(/u);
  assert.match(html, /function focusTertiaryFillMaximumCopy\(/u);
  assert.match(html, /function focusHideFirstUnservedBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstUnservedBuyer\(/u);
  assert.match(html, /hideFirstUnservedBuyer/u);
  assert.match(html, /if \(key === "4"\) \{\s*event\.preventDefault\(\);\s*copyTertiaryFillMaximum\(\);/u);
  assert.match(html, /if \(key === "Home"\) \{\s*event\.preventDefault\(\);\s*focusTertiaryFillMaximumCopy\(\);/u);
  assert.match(html, /if \(key === "End"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUnservedBuyer\(\);/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-fill-minimum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-buyer-filled-by-tertiary-fill/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-fill-maximum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-buyer-filled-by-tertiary-fill/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-tertiary-fill-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-unserved-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-tertiary-fill-maximum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-unserved-buyer/u);
  assert.match(html, /id="copy-leftover-uncovered-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-remaining"[^>]*aria-keyshortcuts="PageUp"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /id="leftover-print-uncovered-remaining"/u);
  assert.match(html, /Leftover uncovered remaining: none/u);
  assert.match(html, /data-preset="hockeyCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredRemaining\(/u);
  assert.match(html, /function focusLeftoverUncoveredRemainingCopy\(/u);
  assert.match(html, /function focusHideLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /hideLastLeftoverOnlyBuyer/u);
  assert.match(html, /createLeftoverUncoveredRemainingMarkdown\(/u);
  assert.match(html, /if \(key === "PageUp"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredRemaining\(\);/u);
  assert.match(html, /if \(key === "PageDown"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredRemainingCopy\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-leftover-only-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideLastLeftoverOnlyBuyer/u);
  assert.match(html, /id="copy-leftover-uncovered-maximum"/u);
  assert.match(html, /id="copy-leftover-uncovered-maximum"[^>]*aria-keyshortcuts="Insert"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="leftover-print-uncovered-maximum"/u);
  assert.match(html, /Leftover uncovered maximum: none/u);
  assert.match(html, /data-preset="baseballCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredMaximum\(/u);
  assert.match(html, /function focusLeftoverUncoveredMaximumCopy\(/u);
  assert.match(html, /function focusHideFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /hideFirstLeftoverOnlyBuyer/u);
  assert.match(html, /createLeftoverUncoveredMaximumMarkdown\(/u);
  assert.match(html, /if \(key === "Insert"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredMaximum\(\);/u);
  assert.match(html, /if \(key === "ArrowDown"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredMaximumCopy\(\);/u);
  assert.match(html, /if \(key === "ArrowLeft"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-maximum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-leftover-only-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-maximum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideFirstLeftoverOnlyBuyer/u);
  assert.match(html, /id="copy-leftover-uncovered-minimum"/u);
  assert.match(html, /id="copy-leftover-uncovered-minimum"[^>]*aria-keyshortcuts="Delete"/u);
  assert.match(html, /id="hide-last-winner-allocated-buyer"/u);
  assert.match(html, /id="leftover-print-uncovered-minimum"/u);
  assert.match(html, /Leftover uncovered minimum: none/u);
  assert.match(html, /data-preset="softballCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredMinimum\(/u);
  assert.match(html, /function focusLeftoverUncoveredMinimumCopy\(/u);
  assert.match(html, /function focusHideLastWinnerAllocatedBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingLastWinnerAllocatedBuyer\(/u);
  assert.match(html, /hideLastWinnerAllocatedBuyer/u);
  assert.match(html, /createLeftoverUncoveredMinimumMarkdown\(/u);
  assert.match(html, /if \(key === "Delete"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredMinimum\(\);/u);
  assert.match(html, /if \(key === "F2"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredMinimumCopy\(\);/u);
  assert.match(html, /if \(key === "ArrowRight"\) \{\s*event\.preventDefault\(\);\s*focusHideLastWinnerAllocatedBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-minimum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-winner-allocated-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-minimum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideLastWinnerAllocatedBuyer/u);
});

test("release 1.4.23 ships water polo carnival lunch, leftover uncovered count copy and first winner-allocated hide", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-count"/u);
  assert.match(html, /id="copy-leftover-uncovered-count"[^>]*aria-keyshortcuts="F3"/u);
  assert.match(html, /id="hide-first-winner-allocated-buyer"/u);
  assert.match(html, /id="leftover-print-uncovered-count"/u);
  assert.match(html, /Leftover uncovered count: none/u);
  assert.match(html, /data-preset="waterPoloCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredCount\(/u);
  assert.match(html, /function focusLeftoverUncoveredCountCopy\(/u);
  assert.match(html, /function focusHideFirstWinnerAllocatedBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstWinnerAllocatedBuyer\(/u);
  assert.match(html, /hideFirstWinnerAllocatedBuyer/u);
  assert.match(html, /createLeftoverUncoveredCountMarkdown\(/u);
  assert.match(html, /if \(key === "F3"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredCount\(\);/u);
  assert.match(html, /if \(key === "F4"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredCountCopy\(\);/u);
  assert.match(html, /if \(key === "Backspace"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstWinnerAllocatedBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-count/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-winner-allocated-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-count/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideFirstWinnerAllocatedBuyer/u);
});

test("release 1.4.24 ships rowing carnival lunch, leftover uncovered leftover-only count copy and first uncovered leftover hide", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-count"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-count"[^>]*aria-keyshortcuts="F7"/u);
  assert.match(html, /id="hide-first-uncovered-leftover-buyer"/u);
  assert.match(html, /data-preset="rowingCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyCount\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyCountCopy\(/u);
  assert.match(html, /function focusHideFirstUncoveredLeftoverBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstUncoveredLeftoverBuyer\(/u);
  assert.match(html, /hideFirstUncoveredLeftoverBuyer/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyCountMarkdown\(/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyCountCopy\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-count/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-uncovered-leftover-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideFirstUncoveredLeftoverBuyer/u);
});

test("release 1.4.25 ships sailing carnival lunch, leftover uncovered leftover-only remaining copy and last uncovered leftover hide", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"[^>]*aria-keyshortcuts="F10"/u);
  assert.match(html, /id="hide-last-uncovered-leftover-buyer"/u);
  assert.match(html, /data-preset="sailingCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyRemaining\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(/u);
  assert.match(html, /function focusHideLastUncoveredLeftoverBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingLastUncoveredLeftoverBuyer\(/u);
  assert.match(html, /hideLastUncoveredLeftoverBuyer/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyRemainingMarkdown\(/u);
  assert.match(html, /if \(key === "F10"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /if \(key === "F11"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(\);/u);
  assert.match(html, /if \(key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideLastUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-uncovered-leftover-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideLastUncoveredLeftoverBuyer/u);
});

