import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { buildStandalone } from "../scripts/build-standalone.mjs";

test("generated standalone parses as a module without duplicate declarations", async () => {
  const html = await buildStandalone();
  const source = html.match(/<script type="module">([\s\S]*?)<\/script>/u)?.[1];
  assert.ok(source);
  const result = spawnSync(process.execPath, ["--check", "--input-type=module"], { input: source, encoding: "utf8" });
  assert.equal(result.status, 0, result.stderr || result.error?.message);
});

test("standalone GUI is deterministic and current", async () => {
  const expected = await buildStandalone();
  const current = (await readFile(new URL("../standalone.html", import.meta.url), "utf8")).replace(/\r\n?/gu, "\n");
  assert.equal(current, expected);
});

test("standalone GUI has no external resource dependency", async () => {
  const html = await buildStandalone();
  assert.match(html, /Content-Security-Policy/u);
  assert.match(html, /default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'/u);
  assert.match(html, /<style>[\s\S]+<\/style>/u);
  assert.match(html, /<script type="module">[\s\S]+<\/script>/u);
  assert.doesNotMatch(html, /<script[^>]+src=/iu);
  assert.doesNotMatch(html, /<link[^>]+stylesheet/iu);
  assert.doesNotMatch(html, /(?:src|href)=["'](?:\.\/|https?:|\/\/)/iu);
  assert.match(html, /window\.location\.protocol === "file:"/u);
  assert.match(html, /Use Export JSON to share a standalone scenario\./u);
  assert.match(html, /Included locally/u);
  assert.match(html, /No complete buyer set/u);
  assert.match(html, /Three ASCII letters, e\.g\. AUD/u);
  assert.match(html, /Accepted variants are a comma-separated list/u);
  assert.match(html, /cannot be empty/u);
  assert.match(html, /"Room name"/u);
  assert.match(html, /Share link could not be opened/u);
  assert.match(html, /Saved room could not be restored/u);
  assert.match(html, /not valid JSON/u);
});

test("standalone retains 1.4.18 tertiary remaining tools and 1.4.19 tertiary maximum controls", async () => {
  const html = await buildStandalone();
  assert.match(html, /id="copy-leftover-fill-label"/u);
  assert.match(html, /id="copy-leftover-fill-label"[^>]*aria-keyshortcuts="\$"/u);
  assert.match(html, /id="hide-first-buyer-filled-by-leftover-fill"/u);
  assert.match(html, /id="hide-last-buyer-filled-by-leftover-fill"/u);
  assert.match(html, /data-preset="tennisCarnivalLunch"/u);
  assert.match(html, /id="copy-leftover-fill-minimum"/u);
  assert.match(html, /id="copy-leftover-fill-minimum"[^>]*aria-keyshortcuts="5"/u);
  assert.match(html, /id="hide-first-buyer-filled-by-tertiary-fill"/u);
  assert.match(html, /id="leftover-print-fill-minimum"/u);
  assert.match(html, /Leftover fill minimum: none/u);
  assert.match(html, /data-preset="basketballCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverFillMinimum\(/u);
  assert.match(html, /function focusLeftoverFillMinimumCopy\(/u);
  assert.match(html, /function focusHideFirstBuyerFilledByTertiaryFill\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstBuyerFilledByTertiaryFill\(/u);
  assert.match(html, /hideFirstBuyerFilledByTertiaryFill/u);
  assert.match(html, /if \(key === "5"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverFillMinimum\(\);/u);
  assert.match(html, /if \(key === "6"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverFillMinimumCopy\(\);/u);
  assert.match(html, /if \(key === "7"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstBuyerFilledByTertiaryFill\(\);/u);
  assert.match(html, /id="copy-leftover-fill-maximum"/u);
  assert.match(html, /id="copy-leftover-fill-maximum"[^>]*aria-keyshortcuts="8"/u);
  assert.match(html, /id="hide-last-buyer-filled-by-tertiary-fill"/u);
  assert.match(html, /id="leftover-print-fill-maximum"/u);
  assert.match(html, /Leftover fill maximum: none/u);
  assert.match(html, /data-preset="volleyballCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverFillMaximum\(/u);
  assert.match(html, /function focusLeftoverFillMaximumCopy\(/u);
  assert.match(html, /function focusHideLastBuyerFilledByTertiaryFill\(/u);
  assert.match(html, /filterBuyerIdsHidingLastBuyerFilledByTertiaryFill\(/u);
  assert.match(html, /hideLastBuyerFilledByTertiaryFill/u);
  assert.match(html, /if \(key === "8"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverFillMaximum\(\);/u);
  assert.match(html, /if \(key === "9"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverFillMaximumCopy\(\);/u);
  assert.match(html, /if \(key === "0"\) \{\s*event\.preventDefault\(\);\s*focusHideLastBuyerFilledByTertiaryFill\(\);/u);
  assert.match(html, /id="copy-tertiary-fill-remaining"/u);
  assert.match(html, /id="copy-tertiary-fill-remaining"[^>]*aria-keyshortcuts="1"/u);
  assert.match(html, /id="hide-last-unserved-buyer"/u);
  assert.match(html, /id="leftover-print-tertiary-remaining"/u);
  assert.match(html, /Tertiary fill remaining capacity: none/u);
  assert.match(html, /data-preset="soccerCarnivalLunch"/u);
  assert.match(html, /function copyTertiaryFillRemainingCapacity\(/u);
  assert.match(html, /function focusTertiaryFillRemainingCopy\(/u);
  assert.match(html, /function focusHideLastUnservedBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingLastUnservedBuyer\(/u);
  assert.match(html, /hideLastUnservedBuyer/u);
  assert.match(html, /if \(key === "1"\) \{\s*event\.preventDefault\(\);\s*copyTertiaryFillRemainingCapacity\(\);/u);
  assert.match(html, /if \(key === "2"\) \{\s*event\.preventDefault\(\);\s*focusTertiaryFillRemainingCopy\(\);/u);
  assert.match(html, /if \(key === "3"\) \{\s*event\.preventDefault\(\);\s*focusHideLastUnservedBuyer\(\);/u);
  assert.match(html, /id="copy-tertiary-fill-maximum"/u);
  assert.match(html, /id="copy-tertiary-fill-maximum"[^>]*aria-keyshortcuts="4"/u);
  assert.match(html, /id="hide-first-unserved-buyer"/u);
  assert.match(html, /id="leftover-print-tertiary-maximum"/u);
  assert.match(html, /Tertiary fill maximum: none/u);
  assert.match(html, /data-preset="rugbyCarnivalLunch"/u);
  assert.match(html, /function copyTertiaryFillMaximum\(/u);
  assert.match(html, /function focusTertiaryFillMaximumCopy\(/u);
  assert.match(html, /function focusHideFirstUnservedBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstUnservedBuyer\(/u);
  assert.match(html, /hideFirstUnservedBuyer/u);
  assert.match(html, /if \(key === "4"\) \{\s*event\.preventDefault\(\);\s*copyTertiaryFillMaximum\(\);/u);
  assert.match(html, /if \(key === "Home"\) \{\s*event\.preventDefault\(\);\s*focusTertiaryFillMaximumCopy\(\);/u);
  assert.match(html, /if \(key === "End"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUnservedBuyer\(\);/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-fill-minimum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-buyer-filled-by-tertiary-fill/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-fill-maximum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-buyer-filled-by-tertiary-fill/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-tertiary-fill-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-unserved-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-tertiary-fill-maximum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-unserved-buyer/u);
  assert.match(html, /id="copy-leftover-uncovered-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-remaining"[^>]*aria-keyshortcuts="PageUp"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /id="leftover-print-uncovered-remaining"/u);
  assert.match(html, /Leftover uncovered remaining: none/u);
  assert.match(html, /data-preset="hockeyCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredRemaining\(/u);
  assert.match(html, /function focusLeftoverUncoveredRemainingCopy\(/u);
  assert.match(html, /function focusHideLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /hideLastLeftoverOnlyBuyer/u);
  assert.match(html, /createLeftoverUncoveredRemainingMarkdown\(/u);
  assert.match(html, /if \(key === "PageUp"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredRemaining\(\);/u);
  assert.match(html, /if \(key === "PageDown"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredRemainingCopy\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-leftover-only-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideLastLeftoverOnlyBuyer/u);
  assert.match(html, /id="copy-leftover-uncovered-maximum"/u);
  assert.match(html, /id="copy-leftover-uncovered-maximum"[^>]*aria-keyshortcuts="Insert"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="leftover-print-uncovered-maximum"/u);
  assert.match(html, /Leftover uncovered maximum: none/u);
  assert.match(html, /data-preset="baseballCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredMaximum\(/u);
  assert.match(html, /function focusLeftoverUncoveredMaximumCopy\(/u);
  assert.match(html, /function focusHideFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /hideFirstLeftoverOnlyBuyer/u);
  assert.match(html, /createLeftoverUncoveredMaximumMarkdown\(/u);
  assert.match(html, /if \(key === "Insert"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredMaximum\(\);/u);
  assert.match(html, /if \(key === "ArrowDown"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredMaximumCopy\(\);/u);
  assert.match(html, /if \(key === "ArrowLeft"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-maximum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-leftover-only-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-maximum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideFirstLeftoverOnlyBuyer/u);
  assert.match(html, /id="copy-leftover-uncovered-minimum"/u);
  assert.match(html, /id="copy-leftover-uncovered-minimum"[^>]*aria-keyshortcuts="Delete"/u);
  assert.match(html, /id="hide-last-winner-allocated-buyer"/u);
  assert.match(html, /id="leftover-print-uncovered-minimum"/u);
  assert.match(html, /Leftover uncovered minimum: none/u);
  assert.match(html, /data-preset="softballCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredMinimum\(/u);
  assert.match(html, /function focusLeftoverUncoveredMinimumCopy\(/u);
  assert.match(html, /function focusHideLastWinnerAllocatedBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingLastWinnerAllocatedBuyer\(/u);
  assert.match(html, /hideLastWinnerAllocatedBuyer/u);
  assert.match(html, /createLeftoverUncoveredMinimumMarkdown\(/u);
  assert.match(html, /if \(key === "Delete"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredMinimum\(\);/u);
  assert.match(html, /if \(key === "F2"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredMinimumCopy\(\);/u);
  assert.match(html, /if \(key === "ArrowRight"\) \{\s*event\.preventDefault\(\);\s*focusHideLastWinnerAllocatedBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-minimum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-winner-allocated-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-minimum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideLastWinnerAllocatedBuyer/u);
});

test("release 1.4.23 ships water polo carnival lunch, leftover uncovered count copy and first winner-allocated hide", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-count"/u);
  assert.match(html, /id="copy-leftover-uncovered-count"[^>]*aria-keyshortcuts="F3"/u);
  assert.match(html, /id="hide-first-winner-allocated-buyer"/u);
  assert.match(html, /id="leftover-print-uncovered-count"/u);
  assert.match(html, /Leftover uncovered count: none/u);
  assert.match(html, /data-preset="waterPoloCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredCount\(/u);
  assert.match(html, /function focusLeftoverUncoveredCountCopy\(/u);
  assert.match(html, /function focusHideFirstWinnerAllocatedBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstWinnerAllocatedBuyer\(/u);
  assert.match(html, /hideFirstWinnerAllocatedBuyer/u);
  assert.match(html, /createLeftoverUncoveredCountMarkdown\(/u);
  assert.match(html, /if \(key === "F3"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredCount\(\);/u);
  assert.match(html, /if \(key === "F4"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredCountCopy\(\);/u);
  assert.match(html, /if \(key === "Backspace"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstWinnerAllocatedBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-count/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-winner-allocated-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-count/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideFirstWinnerAllocatedBuyer/u);
});

test("release 1.4.24 ships rowing carnival lunch, leftover uncovered leftover-only count copy and first uncovered leftover hide", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-count"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-count"[^>]*aria-keyshortcuts="F7"/u);
  assert.match(html, /id="hide-first-uncovered-leftover-buyer"/u);
  assert.match(html, /data-preset="rowingCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyCount\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyCountCopy\(/u);
  assert.match(html, /function focusHideFirstUncoveredLeftoverBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstUncoveredLeftoverBuyer\(/u);
  assert.match(html, /hideFirstUncoveredLeftoverBuyer/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyCountMarkdown\(/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyCountCopy\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-count/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-uncovered-leftover-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideFirstUncoveredLeftoverBuyer/u);
});

test("release 1.4.25 ships sailing carnival lunch, leftover uncovered leftover-only remaining copy and last uncovered leftover hide", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"[^>]*aria-keyshortcuts="Shift\+F7 F10"/u);
  assert.match(html, /id="hide-last-uncovered-leftover-buyer"/u);
  assert.match(html, /data-preset="sailingCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyRemaining\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(/u);
  assert.match(html, /function focusHideLastUncoveredLeftoverBuyer\(/u);
  assert.match(html, /filterBuyerIdsHidingLastUncoveredLeftoverBuyer\(/u);
  assert.match(html, /hideLastUncoveredLeftoverBuyer/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyRemainingMarkdown\(/u);
  assert.match(html, /if \(key === "F10"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /if \(key === "F11"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(\);/u);
  assert.match(html, /if \(key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideLastUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-uncovered-leftover-buyer/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hideLastUncoveredLeftoverBuyer/u);
});

test("release 1.4.26 ships canoeing carnival lunch, leftover uncovered leftover-only maximum copy and first uncovered leftover hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-maximum"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-maximum"[^>]*aria-keyshortcuts="Shift\+F10"/u);
  assert.match(html, /id="hide-first-uncovered-leftover-buyer"/u);
  assert.match(html, /data-preset="canoeingCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyMaximum\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyMaximumCopy\(/u);
  assert.match(html, /function focusHideFirstUncoveredLeftoverBuyer\(/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyMaximumMarkdown\(/u);
  assert.match(html, /if \(event\.shiftKey && key === "F10"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyMaximum\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F11"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyMaximumCopy\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "F10"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-maximum/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-uncovered-leftover-buyer/u);
});

test("release 1.4.28 ships dragon boat carnival lunch, leftover uncovered leftover-only headroom copy and last uncovered leftover hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-headroom"/u);
  assert.match(html, /id="hide-last-uncovered-leftover-buyer"/u);
  assert.match(html, /data-preset="dragonBoatCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyHeadroom\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyHeadroomCopy\(/u);
  assert.match(html, /function focusHideLastUncoveredLeftoverBuyer\(/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyHeadroomMarkdown\(/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F10"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyMaximum\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-headroom/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-uncovered-leftover-buyer/u);
});

test("release 1.4.29 ships surf carnival lunch, leftover uncovered leftover-only allocated copy and first uncovered leftover hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-allocated"/u);
  assert.match(html, /id="hide-first-uncovered-leftover-buyer"/u);
  assert.match(html, /data-preset="surfCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyAllocated\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyAllocatedCopy\(/u);
  assert.match(html, /function focusHideFirstUncoveredLeftoverBuyer\(/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyAllocatedMarkdown\(/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideLastUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-allocated/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-uncovered-leftover-buyer/u);
});

test("release 1.4.30 ships triathlon carnival lunch, leftover uncovered leftover-only capacity copy and last leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-capacity"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-allocated"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-capacity"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="triathlonCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyCapacity\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyCapacityCopy\(/u);
  assert.match(html, /function focusHideLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyCapacityMarkdown\(/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyCountCopy\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-capacity/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-leftover-only-buyer/u);
});

test("release 1.4.33 ships bmx carnival lunch, leftover uncovered leftover-only headroom copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-headroom"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-headroom"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-minimum"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-minimum"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-unit-price"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-unit-price"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-capacity"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-capacity"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="bmxCarnivalLunch"/u);
  assert.match(html, /data-preset="mountainBikeCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyHeadroom\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyHeadroomCopy\(/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyMinimum\(/u);
  assert.match(html, /function focusHideFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /function focusHideLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyHeadroomMarkdown\(/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyCountCopy\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowLeft"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-headroom/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-leftover-only-buyer/u);
});

test("release 1.4.34 ships cyclo-cross carnival lunch, leftover uncovered leftover-only allocated copy and last leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-allocated"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-allocated"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-headroom"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-headroom"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-minimum"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-minimum"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-unit-price"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-unit-price"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-capacity"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-capacity"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="cycloCrossCarnivalLunch"/u);
  assert.match(html, /data-preset="bmxCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyAllocated\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyAllocatedCopy\(/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyHeadroom\(/u);
  assert.match(html, /function focusHideFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /function focusHideLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyAllocatedMarkdown\(/u);
  assert.doesNotMatch(html, /if \(event\.shiftKey && key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyAllocated\(\);/u);
  assert.doesNotMatch(html, /if \(event\.shiftKey && key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyAllocatedCopy\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyCountCopy\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowLeft"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-allocated/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-leftover-only-buyer/u);
});

test("release 1.4.36 ships gravel cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"[^>]*aria-keyshortcuts="Shift\+F7 F10"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-allocated"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-allocated"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-headroom"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-headroom"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-minimum"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-minimum"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-unit-price"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-unit-price"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-capacity"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-capacity"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="cycloCrossCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="cycloCrossCarnivalLunch"') < html.indexOf('data-preset="trackCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyRemaining\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyAllocated\(/u);
  assert.match(html, /function focusHideFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /function focusHideLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyRemainingMarkdown\(/u);
  assert.match(html, /if \(event\.shiftKey && key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyCountCopy\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "F10"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /if \(key === "F11"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowLeft"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.match(html, /Court-side Gravel Cycling Delivery/u);
  assert.match(html, /Hall Gravel Cycling Pickup/u);
  assert.match(html, /Court-side Track Cycling Delivery/u);
  assert.match(html, /Hall Track Cycling Pickup/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-leftover-only-buyer/u);
});



test("release 1.4.43 ships omnium cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.4.43");
  const firstHeading = changelog.match(/^## .+$/m)?.[0];
  assert.equal(firstHeading, "## 1.4.43");
  assert.match(changelog, /Omnium cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.43/);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"[^>]*aria-keyshortcuts="Shift\+F7 F10"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="omniumCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="madisonCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="madisonCyclingCarnivalLunch"') < html.indexOf('data-preset="omniumCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="omniumCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Omnium Delivery/u);
  assert.match(html, /Hall Omnium Pickup/u);
  assert.match(html, /Omnium-board crate/u);
  assert.match(html, /Flying-200 bench/u);
  assert.match(html, /Elimination hamper/u);
  assert.match(html, /if \(event\.shiftKey && key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
});

test("release 1.4.42 ships madison cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.4.43");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"[^>]*aria-keyshortcuts="Shift\+F7 F10"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="madisonCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="keirinCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="keirinCyclingCarnivalLunch"') < html.indexOf('data-preset="madisonCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="madisonCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Madison Delivery/u);
  assert.match(html, /Hall Madison Pickup/u);
  assert.match(html, /Madison-pair crate/u);
  assert.match(html, /Handsling bench/u);
  assert.match(html, /Pairing hamper/u);
  assert.match(html, /if \(event\.shiftKey && key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
});

test("release 1.4.41 ships keirin cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"[^>]*aria-keyshortcuts="Shift\+F7 F10"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="keirinCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="hillClimbCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"') < html.indexOf('data-preset="keirinCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="keirinCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Keirin Delivery/u);
  assert.match(html, /Hall Keirin Pickup/u);
  assert.match(html, /Derny crate/u);
  assert.match(html, /Keirin-gate bench/u);
  assert.match(html, /Pacer hamper/u);
  assert.match(html, /if \(event\.shiftKey && key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
});

test("release 1.4.40 ships hill-climb cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"[^>]*aria-keyshortcuts="Shift\+F7 F10"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="hillClimbCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="timeTrialCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="timeTrialCyclingCarnivalLunch"') < html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Hill Climb Delivery/u);
  assert.match(html, /Hall Hill Climb Pickup/u);
  assert.match(html, /Hairpin crate/u);
  assert.match(html, /Summit-marshal bench/u);
  assert.match(html, /Hairpin hamper/u);
  assert.match(html, /if \(event\.shiftKey && key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
});

test("release 1.4.39 ships time-trial cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"[^>]*aria-keyshortcuts="Shift\+F7 F10"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-allocated"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-allocated"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-headroom"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-headroom"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-minimum"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-minimum"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-unit-price"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-unit-price"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-capacity"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-capacity"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="timeTrialCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="criteriumCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="roadCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="gravelCyclingCarnivalLunch"') < html.indexOf('data-preset="roadCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="roadCyclingCarnivalLunch"') < html.indexOf('data-preset="criteriumCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="criteriumCyclingCarnivalLunch"') < html.indexOf('data-preset="timeTrialCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="timeTrialCyclingCarnivalLunch"') < html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"'));
  assert.match(html, /data-preset="hillClimbCyclingCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyRemaining\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyAllocated\(/u);
  assert.match(html, /function focusHideFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /function focusHideLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyRemainingMarkdown\(/u);
  assert.match(html, /if \(event\.shiftKey && key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyCountCopy\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "F10"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /if \(key === "F11"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowLeft"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.match(html, /Court-side Time Trial Delivery/u);
  assert.match(html, /Hall Time Trial Pickup/u);
  assert.match(html, /Court-side Criterium Delivery/u);
  assert.match(html, /Hall Criterium Pickup/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-leftover-only-buyer/u);
});

test("release 1.4.38 ships criterium cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"[^>]*aria-keyshortcuts="Shift\+F7 F10"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-allocated"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-allocated"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-headroom"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-headroom"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-minimum"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-minimum"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-unit-price"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-unit-price"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-capacity"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-capacity"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="criteriumCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="roadCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="gravelCyclingCarnivalLunch"') < html.indexOf('data-preset="roadCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="roadCyclingCarnivalLunch"') < html.indexOf('data-preset="criteriumCyclingCarnivalLunch"'));
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyRemaining\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyAllocated\(/u);
  assert.match(html, /function focusHideFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /function focusHideLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyRemainingMarkdown\(/u);
  assert.match(html, /if \(event\.shiftKey && key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyCountCopy\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "F10"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /if \(key === "F11"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowLeft"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.match(html, /Court-side Criterium Delivery/u);
  assert.match(html, /Hall Criterium Pickup/u);
  assert.match(html, /Court-side Road Cycling Delivery/u);
  assert.match(html, /Hall Road Cycling Pickup/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-first-leftover-only-buyer/u);
});

test("release 1.4.37 ships road cycling carnival lunch, leftover uncovered leftover-only remaining copy and last leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-remaining"[^>]*aria-keyshortcuts="Shift\+F7 F10"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-allocated"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-allocated"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-headroom"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-headroom"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-minimum"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-minimum"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-unit-price"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-unit-price"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="copy-leftover-uncovered-leftover-only-capacity"/u);
  assert.doesNotMatch(html, /id="copy-leftover-uncovered-leftover-only-capacity"[^>]*aria-keyshortcuts="Shift\+F7"/u);
  assert.match(html, /id="hide-first-leftover-only-buyer"/u);
  assert.match(html, /id="hide-last-leftover-only-buyer"/u);
  assert.match(html, /data-preset="roadCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="gravelCyclingCarnivalLunch"') < html.indexOf('data-preset="roadCyclingCarnivalLunch"'));
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyRemaining\(/u);
  assert.match(html, /function focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(/u);
  assert.match(html, /function copyLeftoverUncoveredLeftoverOnlyAllocated\(/u);
  assert.match(html, /function focusHideFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /function focusHideLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /createLeftoverUncoveredLeftoverOnlyRemainingMarkdown\(/u);
  assert.match(html, /if \(event\.shiftKey && key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "F7"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyCount\(\);/u);
  assert.match(html, /if \(key === "F8"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyCountCopy\(\);/u);
  assert.match(html, /if \(key === "F9"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "F10"\) \{\s*event\.preventDefault\(\);\s*copyLeftoverUncoveredLeftoverOnlyRemaining\(\);/u);
  assert.match(html, /if \(key === "F11"\) \{\s*event\.preventDefault\(\);\s*focusLeftoverUncoveredLeftoverOnlyRemainingCopy\(\);/u);
  assert.match(html, /if \(event\.shiftKey && key === "F12"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstUncoveredLeftoverBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowUp"\) \{\s*event\.preventDefault\(\);\s*focusHideLastLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /if \(key === "ArrowLeft"\) \{\s*event\.preventDefault\(\);\s*focusHideFirstLeftoverOnlyBuyer\(\);/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.match(html, /Court-side Road Cycling Delivery/u);
  assert.match(html, /Hall Road Cycling Pickup/u);
  assert.match(html, /Court-side Gravel Cycling Delivery/u);
  assert.match(html, /Hall Gravel Cycling Pickup/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-uncovered-leftover-only-remaining/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /hide-last-leftover-only-buyer/u);
});



