import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { buildStandalone } from "../scripts/build-standalone.mjs";

test("generated standalone parses as a module without duplicate declarations", async () => {
  const html = await buildStandalone();
  const source = html.match(/<script type="module">([\s\S]*?)<\/script>/u)?.[1];
  assert.ok(source);
  const result = spawnSync(process.execPath, ["--check", "--input-type=module"], { input: source, encoding: "utf8" });
  assert.equal(result.status, 0, result.stderr || result.error?.message);
});

test("standalone GUI is deterministic and current", async () => {
  const expected = await buildStandalone();
  const current = (await readFile(new URL("../standalone.html", import.meta.url), "utf8")).replace(/\r\n?/gu, "\n");
  assert.equal(current, expected);
});

test("standalone GUI has no external resource dependency", async () => {
  const html = await buildStandalone();
  assert.match(html, /Content-Security-Policy/u);
  assert.match(html, /default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'/u);
  assert.match(html, /<style>[\s\S]+<\/style>/u);
  assert.match(html, /<script type="module">[\s\S]+<\/script>/u);
  assert.doesNotMatch(html, /<script[^>]+src=/iu);
  assert.doesNotMatch(html, /<link[^>]+stylesheet/iu);
  assert.doesNotMatch(html, /(?:src|href)=["'](?:\.\/|https?:|\/\/)/iu);
  assert.match(html, /window\.location\.protocol === "file:"/u);
  assert.match(html, /Use Export JSON to share a standalone scenario\./u);
  assert.match(html, /Included locally/u);
  assert.match(html, /No complete buyer set/u);
  assert.match(html, /Three ASCII letters, e\.g\. AUD/u);
  assert.match(html, /Accepted variants are a comma-separated list/u);
  assert.match(html, /cannot be empty/u);
  assert.match(html, /"Room name"/u);
  assert.match(html, /Share link could not be opened/u);
  assert.match(html, /Saved room could not be restored/u);
  assert.match(html, /not valid JSON/u);
});

test("standalone retains 1.4.18 tertiary remaining tools and 1.4.19 tertiary maximum controls", async () => {
  const html = await buildStandalone();
  assert.match(html, /id="copy-leftover-fill-evidence"/u);
  assert.match(html, /id="edge-leftover-fill"/u);
  assert.match(html, /id="edge-leftover-fill"/u);
  assert.match(html, /data-preset="tennisCarnivalLunch"/u);
  assert.match(html, /id="copy-leftover-fill-evidence"/u);
  assert.match(html, /id="edge-tertiary-fill"/u);
  assert.match(html, /id="leftover-print-fill-evidence"/u);
  assert.match(html, /Leftover fill evidence: none/u);
  assert.match(html, /data-preset="basketballCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverFillEvidence\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstBuyerFilledByTertiaryFill\(/u);
  assert.match(html, /edgeTertiaryFill/u);
  assert.match(html, /id="copy-leftover-fill-evidence"/u);
  assert.match(html, /id="edge-tertiary-fill"/u);
  assert.match(html, /id="leftover-print-fill-evidence"/u);
  assert.match(html, /Leftover fill evidence: none/u);
  assert.match(html, /data-preset="volleyballCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverFillEvidence\(/u);
  assert.match(html, /filterBuyerIdsHidingLastBuyerFilledByTertiaryFill\(/u);
  assert.match(html, /edgeTertiaryFill/u);
  assert.match(html, /id="copy-tertiary-fill-evidence"/u);
  assert.match(html, /id="edge-unserved"/u);
  assert.match(html, /id="leftover-print-tertiary-evidence"/u);
  assert.match(html, /Tertiary fill evidence: none/u);
  assert.match(html, /data-preset="soccerCarnivalLunch"/u);
  assert.match(html, /function copyTertiaryFillEvidence\(/u);
  assert.match(html, /filterBuyerIdsHidingLastUnservedBuyer\(/u);
  assert.match(html, /edgeUnserved/u);
  assert.match(html, /id="copy-tertiary-fill-evidence"/u);
  assert.match(html, /id="edge-unserved"/u);
  assert.match(html, /id="leftover-print-tertiary-evidence"/u);
  assert.match(html, /Tertiary fill evidence: none/u);
  assert.match(html, /data-preset="rugbyCarnivalLunch"/u);
  assert.match(html, /function copyTertiaryFillEvidence\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstUnservedBuyer\(/u);
  assert.match(html, /edgeUnserved/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-fill-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-tertiary-fill/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-fill-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-tertiary-fill/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-tertiary-fill-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-unserved/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-tertiary-fill-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-unserved/u);
  assert.match(html, /id="copy-uncovered-leftover-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="leftover-print-uncovered-evidence"/u);
  assert.match(html, /Uncovered leftover evidence: none/u);
  assert.match(html, /data-preset="hockeyCarnivalLunch"/u);
  assert.match(html, /function copyUncoveredLeftoverEvidence\(/u);
  assert.match(html, /filterBuyerIdsHidingLastLeftoverOnlyBuyer\(/u);
  assert.match(html, /edgeLeftoverOnly/u);
  assert.match(html, /uncoveredLeftoverEvidenceToMarkdown\(/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-uncovered-leftover-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-leftover-only/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edgeLeftoverOnly/u);
  assert.match(html, /id="copy-uncovered-leftover-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="leftover-print-uncovered-evidence"/u);
  assert.match(html, /Uncovered leftover evidence: none/u);
  assert.match(html, /data-preset="baseballCarnivalLunch"/u);
  assert.match(html, /function copyUncoveredLeftoverEvidence\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstLeftoverOnlyBuyer\(/u);
  assert.match(html, /edgeLeftoverOnly/u);
  assert.match(html, /uncoveredLeftoverEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-uncovered-leftover-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-leftover-only/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edgeLeftoverOnly/u);
  assert.match(html, /id="copy-uncovered-leftover-evidence"/u);
  assert.match(html, /id="edge-winner-allocated"/u);
  assert.match(html, /id="leftover-print-uncovered-evidence"/u);
  assert.match(html, /Uncovered leftover evidence: none/u);
  assert.match(html, /data-preset="softballCarnivalLunch"/u);
  assert.match(html, /function copyUncoveredLeftoverEvidence\(/u);
  assert.match(html, /filterBuyerIdsHidingLastWinnerAllocatedBuyer\(/u);
  assert.match(html, /edgeWinnerAllocated/u);
  assert.match(html, /uncoveredLeftoverEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-uncovered-leftover-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-winner-allocated/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edgeWinnerAllocated/u);
});

test("release 1.4.23 ships water polo carnival lunch, leftover uncovered count copy and first winner-allocated hide", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-uncovered-leftover-evidence"/u);
  assert.match(html, /id="edge-winner-allocated"/u);
  assert.match(html, /id="leftover-print-uncovered-evidence"/u);
  assert.match(html, /Uncovered leftover evidence: none/u);
  assert.match(html, /data-preset="waterPoloCarnivalLunch"/u);
  assert.match(html, /function copyUncoveredLeftoverEvidence\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstWinnerAllocatedBuyer\(/u);
  assert.match(html, /edgeWinnerAllocated/u);
  assert.match(html, /uncoveredLeftoverEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-uncovered-leftover-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-winner-allocated/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /leftover-print-uncovered-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edgeWinnerAllocated/u);
});

test("release 1.4.24 ships rowing carnival lunch, leftover uncovered leftover-only count copy and first uncovered leftover hide", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-uncovered-leftover"/u);
  assert.match(html, /data-preset="rowingCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /filterBuyerIdsHidingFirstUncoveredLeftoverBuyer\(/u);
  assert.match(html, /edgeUncoveredLeftover/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-uncovered-leftover/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edgeUncoveredLeftover/u);
});

test("release 1.4.25 ships sailing carnival lunch, leftover uncovered leftover-only remaining copy and last uncovered leftover hide", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-uncovered-leftover"/u);
  assert.match(html, /data-preset="sailingCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /filterBuyerIdsHidingLastUncoveredLeftoverBuyer\(/u);
  assert.match(html, /edgeUncoveredLeftover/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-uncovered-leftover/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edgeUncoveredLeftover/u);
});

test("release 1.4.26 ships canoeing carnival lunch, leftover uncovered leftover-only maximum copy and first uncovered leftover hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-uncovered-leftover"/u);
  assert.match(html, /data-preset="canoeingCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-uncovered-leftover/u);
});

test("release 1.4.28 ships dragon boat carnival lunch, leftover uncovered leftover-only headroom copy and last uncovered leftover hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-uncovered-leftover"/u);
  assert.match(html, /data-preset="dragonBoatCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-uncovered-leftover/u);
});

test("release 1.4.29 ships surf carnival lunch, leftover uncovered leftover-only allocated copy and first uncovered leftover hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-uncovered-leftover"/u);
  assert.match(html, /data-preset="surfCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-uncovered-leftover/u);
});

test("release 1.4.30 ships triathlon carnival lunch, leftover uncovered leftover-only capacity copy and last leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="triathlonCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-leftover-only/u);
});

test("release 1.4.33 ships bmx carnival lunch, leftover uncovered leftover-only headroom copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="bmxCarnivalLunch"/u);
  assert.match(html, /data-preset="mountainBikeCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-leftover-only/u);
});

test("release 1.4.34 ships cyclo-cross carnival lunch, leftover uncovered leftover-only allocated copy and last leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="cycloCrossCarnivalLunch"/u);
  assert.match(html, /data-preset="bmxCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-leftover-only/u);
});

test("release 1.4.36 ships gravel cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="cycloCrossCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="cycloCrossCarnivalLunch"') < html.indexOf('data-preset="trackCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.match(html, /Court-side Gravel Cycling Delivery/u);
  assert.match(html, /Hall Gravel Cycling Pickup/u);
  assert.match(html, /Court-side Track Cycling Delivery/u);
  assert.match(html, /Hall Track Cycling Pickup/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-leftover-only/u);
});



test("release 1.4.54 ships bottle-hand cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  const firstHeading = changelog.match(/^## .+$/m)?.[0];
  assert.equal(firstHeading, "## 1.7.0 - 2026-09-19");
  assert.match(changelog, /Bottle-hand cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.54/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="bottleHandCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="domestiqueCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="domestiqueCyclingCarnivalLunch"') < html.indexOf('data-preset="bottleHandCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="bottleHandCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Bottle-hand Delivery/u);
  assert.match(html, /Hall Bottle-hand Pickup/u);
  assert.match(html, /Bidon-pass crate/u);
  assert.match(html, /Car-window bench/u);
  assert.match(html, /Crate-lock hamper/u);
});

test("release 1.4.53 ships domestique cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /Domestique cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.53/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="domestiqueCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="soigneurCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="soigneurCyclingCarnivalLunch"') < html.indexOf('data-preset="domestiqueCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="domestiqueCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Domestique Delivery/u);
  assert.match(html, /Hall Domestique Pickup/u);
  assert.match(html, /Wheel-change crate/u);
  assert.match(html, /Neutral-service bench/u);
  assert.match(html, /Team-car hamper/u);
});

test("release 1.4.52 ships soigneur cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /## 1\.4\.52 - 2026-09-13/);
  assert.match(changelog, /Soigneur cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.52/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="soigneurCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="leadOutCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="leadOutCyclingCarnivalLunch"') < html.indexOf('data-preset="soigneurCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="soigneurCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Soigneur Delivery/u);
  assert.match(html, /Hall Soigneur Pickup/u);
  assert.match(html, /Soigneur-station crate/u);
  assert.match(html, /Cape-bag bench/u);
  assert.match(html, /Rice-cake hamper/u);
});

test("release 1.4.51 ships lead-out cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /## 1\.4\.51 - 2026-09-13/);
  assert.match(changelog, /Lead-out cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.51/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="leadOutCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="feedZoneCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="feedZoneCyclingCarnivalLunch"') < html.indexOf('data-preset="leadOutCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="leadOutCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Lead-out Delivery/u);
  assert.match(html, /Hall Lead-out Pickup/u);
  assert.match(html, /Train-line crate/u);
  assert.match(html, /Last-rider bench/u);
  assert.match(html, /Sprinter-launch hamper/u);
});

test("release 1.4.50 ships feed-zone cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /## 1\.4\.50 - 2026-09-13/);
  assert.match(changelog, /Feed-zone cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.50/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="feedZoneCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="firstAidCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="firstAidCyclingCarnivalLunch"') < html.indexOf('data-preset="feedZoneCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="feedZoneCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Feed-zone Delivery/u);
  assert.match(html, /Hall Feed-zone Pickup/u);
  assert.match(html, /Musette-line crate/u);
  assert.match(html, /Sticky-bottle bench/u);
  assert.match(html, /Bottle-hand-up hamper/u);
});

test("release 1.4.49 ships first-aid cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /## 1\.4\.49 - 2026-09-13/);
  assert.match(changelog, /First-aid cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.49/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="firstAidCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="teamSprintCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="teamSprintCyclingCarnivalLunch"') < html.indexOf('data-preset="firstAidCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="firstAidCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side First-aid Delivery/u);
  assert.match(html, /Hall First-aid Pickup/u);
  assert.match(html, /Treatment-tent crate/u);
  assert.match(html, /Ice-pack-rota bench/u);
  assert.match(html, /Triage-board hamper/u);
});

test("release 1.4.48 ships team-sprint cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /## 1\.4\.48 - 2026-09-13/);
  assert.match(changelog, /Team-sprint cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.48/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="teamSprintCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="teamPursuitCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="teamPursuitCyclingCarnivalLunch"') < html.indexOf('data-preset="teamSprintCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="teamSprintCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Team-sprint Delivery/u);
  assert.match(html, /Hall Team-sprint Pickup/u);
  assert.match(html, /Start-gate crate/u);
  assert.match(html, /Flying-relay bench/u);
  assert.match(html, /Trio-board hamper/u);
});

test("release 1.4.47 ships team-pursuit cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /## 1\.4\.47 - 2026-09-13/);
  assert.match(changelog, /Team-pursuit cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.47/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="teamPursuitCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="individualPursuitCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="individualPursuitCyclingCarnivalLunch"') < html.indexOf('data-preset="teamPursuitCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="teamPursuitCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Team-pursuit Delivery/u);
  assert.match(html, /Hall Team-pursuit Pickup/u);
  assert.match(html, /Changeover-bell crate/u);
  assert.match(html, /Quartet-board bench/u);
  assert.match(html, /Team-pursuit-rota hamper/u);
});

test("release 1.4.46 ships individual-pursuit cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /## 1\.4\.46 - 2026-09-13/);
  assert.match(changelog, /Individual-pursuit cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.46/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="individualPursuitCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="scratchCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="scratchCyclingCarnivalLunch"') < html.indexOf('data-preset="individualPursuitCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="individualPursuitCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Individual-pursuit Delivery/u);
  assert.match(html, /Hall Individual-pursuit Pickup/u);
  assert.match(html, /Pursuit-line crate/u);
  assert.match(html, /Catch-bell bench/u);
  assert.match(html, /Pursuit-chip hamper/u);
});

test("release 1.4.45 ships scratch cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /## 1\.4\.45 - 2026-09-13/);
  assert.match(changelog, /Scratch cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.45/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="scratchCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="pointsRaceCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="pointsRaceCyclingCarnivalLunch"') < html.indexOf('data-preset="scratchCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="scratchCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Scratch Delivery/u);
  assert.match(html, /Hall Scratch Pickup/u);
  assert.match(html, /Scratch-bunch crate/u);
  assert.match(html, /Bunch-finish bench/u);
  assert.match(html, /Scratch-chip hamper/u);
});

test("release 1.4.44 ships points-race cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /## 1\.4\.44 - 2026-09-12/);
  assert.match(changelog, /Points-race cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.44/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="pointsRaceCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="omniumCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="omniumCyclingCarnivalLunch"') < html.indexOf('data-preset="pointsRaceCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="pointsRaceCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Points-race Delivery/u);
  assert.match(html, /Hall Points-race Pickup/u);
  assert.match(html, /Points-sprint crate/u);
  assert.match(html, /Bell-lap bench/u);
  assert.match(html, /Prime-board hamper/u);
});

test("release 1.4.43 ships omnium cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const changelog = await readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8");
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(changelog, /## 1\.4\.43 - 2026-09-12/);
  assert.match(changelog, /Omnium cycling carnival lunch, leftover-uncovered leftover-only remaining copy, and first leftover-only hide jump in Common Cart 1\.4\.43/);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="omniumCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="madisonCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="madisonCyclingCarnivalLunch"') < html.indexOf('data-preset="omniumCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="omniumCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Omnium Delivery/u);
  assert.match(html, /Hall Omnium Pickup/u);
  assert.match(html, /Omnium-board crate/u);
  assert.match(html, /Flying-200 bench/u);
  assert.match(html, /Elimination hamper/u);
});

test("release 1.4.42 ships madison cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="madisonCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="keirinCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="keirinCyclingCarnivalLunch"') < html.indexOf('data-preset="madisonCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="madisonCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Madison Delivery/u);
  assert.match(html, /Hall Madison Pickup/u);
  assert.match(html, /Madison-pair crate/u);
  assert.match(html, /Handsling bench/u);
  assert.match(html, /Pairing hamper/u);
});

test("release 1.4.41 ships keirin cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.equal(pkg.version, "1.7.0");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="keirinCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="hillClimbCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"') < html.indexOf('data-preset="keirinCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="keirinCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Keirin Delivery/u);
  assert.match(html, /Hall Keirin Pickup/u);
  assert.match(html, /Derny crate/u);
  assert.match(html, /Keirin-gate bench/u);
  assert.match(html, /Pacer hamper/u);
});

test("release 1.4.40 ships hill-climb cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="hillClimbCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="timeTrialCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="timeTrialCyclingCarnivalLunch"') < html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
  assert.match(html, /Court-side Hill Climb Delivery/u);
  assert.match(html, /Hall Hill Climb Pickup/u);
  assert.match(html, /Hairpin crate/u);
  assert.match(html, /Summit-marshal bench/u);
  assert.match(html, /Hairpin hamper/u);
});

test("release 1.4.39 ships time-trial cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="timeTrialCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="criteriumCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="roadCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="gravelCyclingCarnivalLunch"') < html.indexOf('data-preset="roadCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="roadCyclingCarnivalLunch"') < html.indexOf('data-preset="criteriumCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="criteriumCyclingCarnivalLunch"') < html.indexOf('data-preset="timeTrialCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="timeTrialCyclingCarnivalLunch"') < html.indexOf('data-preset="hillClimbCyclingCarnivalLunch"'));
  assert.match(html, /data-preset="hillClimbCyclingCarnivalLunch"/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.match(html, /Court-side Time Trial Delivery/u);
  assert.match(html, /Hall Time Trial Pickup/u);
  assert.match(html, /Court-side Criterium Delivery/u);
  assert.match(html, /Hall Criterium Pickup/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-leftover-only/u);
});

test("release 1.4.38 ships criterium cycling carnival lunch, leftover uncovered leftover-only remaining copy and first leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="criteriumCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="roadCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="gravelCyclingCarnivalLunch"') < html.indexOf('data-preset="roadCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="roadCyclingCarnivalLunch"') < html.indexOf('data-preset="criteriumCyclingCarnivalLunch"'));
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.match(html, /Court-side Criterium Delivery/u);
  assert.match(html, /Hall Criterium Pickup/u);
  assert.match(html, /Court-side Road Cycling Delivery/u);
  assert.match(html, /Hall Road Cycling Pickup/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-leftover-only/u);
});

test("release 1.4.37 ships road cycling carnival lunch, leftover uncovered leftover-only remaining copy and last leftover-only hide jump", async () => {
  const html = await readFile(new URL("../standalone.html", import.meta.url), "utf8");
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="copy-leftover-only-evidence"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /id="edge-leftover-only"/u);
  assert.match(html, /data-preset="roadCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="gravelCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="trackCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="trackCyclingCarnivalLunch"') < html.indexOf('data-preset="gravelCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="gravelCyclingCarnivalLunch"') < html.indexOf('data-preset="roadCyclingCarnivalLunch"'));
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /function copyLeftoverOnlyEvidence\(/u);
  assert.match(html, /leftoverOnlyEvidenceToMarkdown\(/u);
  assert.match(html, /function handleShortcut\(event\) \{\s*if \(event\.defaultPrevented \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey\) return;/u);
  assert.match(html, /const key = event\.key\.length === 1 \? event\.key\.toLowerCase\(\) : event\.key;/u);
  assert.match(html, /Court-side Road Cycling Delivery/u);
  assert.match(html, /Hall Road Cycling Pickup/u);
  assert.match(html, /Court-side Gravel Cycling Delivery/u);
  assert.match(html, /Hall Gravel Cycling Pickup/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /copy-leftover-only-evidence/u);
  assert.doesNotMatch(html.slice(html.indexOf('id="merchant-panel"'), html.indexOf('id="method-panel"')), /edge-leftover-only/u);
});


