import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("surf carnival lunch leftover fill is hall pickup and stays distinct from dragon boat carnival lunch", () => {
  const surf = evaluateMarket(clonePreset("surfCarnivalLunch"));
  const dragonBoat = evaluateMarket(clonePreset("dragonBoatCarnivalLunch"));
  const kayaking = evaluateMarket(clonePreset("kayakingCarnivalLunch"));
  const canoeing = evaluateMarket(clonePreset("canoeingCarnivalLunch"));
  const sailing = evaluateMarket(clonePreset("sailingCarnivalLunch"));
  const rowing = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(surf.winner);
  assert.equal(surf.winner.offer.merchant, "Court-side Surf Delivery");
  assert.equal(surf.winner.offer.fulfillment, "shipping");
  assert.equal(surf.winner.fulfilledUnits, 50);
  assert.deepEqual(surf.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(surf.scenario.title, "Surf carnival lunch");
  assert.notEqual(surf.scenario.title, dragonBoat.scenario.title);
  assert.notEqual(surf.scenario.title, kayaking.scenario.title);
  assert.notEqual(surf.scenario.title, canoeing.scenario.title);
  assert.notEqual(surf.scenario.title, sailing.scenario.title);
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("dragonBoatCarnivalLunch"));
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("kayakingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("canoeingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("sailingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("rowingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("waterPoloCarnivalLunch"));
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("surfCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(surf.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Surf Pickup");
  const leftoverOffer = surf.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 22);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.minimumUnits);
  assert.equal(leftoverOffer.unitPrice, 17);
  assert.equal(surf.scenario.buyers.find((buyer) => buyer.id === "B04").maxUnitPrice, 17);
  assert.equal(dragonBoat.scenario.offers.find((offer) => offer.merchant === "Hall Dragon Boat Pickup").minimumUnits, 21);
  assert.equal(kayaking.scenario.offers.find((offer) => offer.merchant === "Hall Kayaking Pickup").minimumUnits, 20);
  assert.equal(canoeing.scenario.offers.find((offer) => offer.merchant === "Hall Canoeing Pickup").minimumUnits, 19);
  assert.equal(sailing.scenario.offers.find((offer) => offer.merchant === "Hall Sailing Pickup").minimumUnits, 18);
  assert.equal(rowing.scenario.offers.find((offer) => offer.merchant === "Hall Rowing Pickup").minimumUnits, 17);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(waterPolo.scenario.offers.find((offer) => offer.merchant === "Hall Water Polo Pickup").minimumUnits, 16);
  assert.equal(dragonBoat.winner.offer.merchant, "Court-side Dragon Boat Delivery");
  assert.equal(kayaking.winner.offer.merchant, "Court-side Kayaking Delivery");
  assert.equal(sailing.winner.offer.merchant, "Court-side Sailing Delivery");
  assert.equal(canoeing.winner.offer.merchant, "Court-side Canoeing Delivery");
  assert.equal(rowing.winner.offer.merchant, "Court-side Rowing Delivery");
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(leftoverOffer.capacity, 44);
  assert.equal(leftoverFill.fulfilledUnits, 23);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 21);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.unitPrice);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.minimumUnits);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(surf.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(surf.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(surf.results.some((result) => result.offer.merchant === "Court-side Surf Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(surf.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Surf pie")));
  assert.ok(surf.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Beach salad")));
  assert.ok(surf.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Beach water")));
  assert.equal(surf.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Dragon boat pie")), false);
  assert.equal(surf.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Drum salad")), false);
  assert.equal(surf.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Drum water")), false);
  assert.equal(surf.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Kayaking pie")), false);
  const first = evaluateMarket(clonePreset("surfCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("surfCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes surf carnival lunch next to dragon boat carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="surfCarnivalLunch"/u);
  assert.match(html, /Surf carnival/u);
  assert.match(html, /data-preset="dragonBoatCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="dragonBoatCarnivalLunch"') < html.indexOf('data-preset="surfCarnivalLunch"'));
});
