import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("team-pursuit cycling carnival lunch leftover fill is hall pickup and stays distinct from scratch cycling carnival lunch", () => {
  const teamPursuitCycling = evaluateMarket(clonePreset("teamPursuitCyclingCarnivalLunch"));
  const pursuitCycling = evaluateMarket(clonePreset("individualPursuitCyclingCarnivalLunch"));
  const scratchCycling = evaluateMarket(clonePreset("scratchCyclingCarnivalLunch"));
  const pointsRaceCycling = evaluateMarket(clonePreset("pointsRaceCyclingCarnivalLunch"));
  const madisonCycling = evaluateMarket(clonePreset("madisonCyclingCarnivalLunch"));
  const keirinCycling = evaluateMarket(clonePreset("keirinCyclingCarnivalLunch"));
  const hillClimbCycling = evaluateMarket(clonePreset("hillClimbCyclingCarnivalLunch"));
  const timeTrialCycling = evaluateMarket(clonePreset("timeTrialCyclingCarnivalLunch"));
  const criteriumCycling = evaluateMarket(clonePreset("criteriumCyclingCarnivalLunch"));
  const roadCycling = evaluateMarket(clonePreset("roadCyclingCarnivalLunch"));
  const gravelCycling = evaluateMarket(clonePreset("gravelCyclingCarnivalLunch"));
  const trackCycling = evaluateMarket(clonePreset("trackCyclingCarnivalLunch"));
  const cycloCross = evaluateMarket(clonePreset("cycloCrossCarnivalLunch"));
  const bmx = evaluateMarket(clonePreset("bmxCarnivalLunch"));
  const mountainBike = evaluateMarket(clonePreset("mountainBikeCarnivalLunch"));
  const cycling = evaluateMarket(clonePreset("cyclingCarnivalLunch"));
  const triathlon = evaluateMarket(clonePreset("triathlonCarnivalLunch"));
  const surf = evaluateMarket(clonePreset("surfCarnivalLunch"));
  const dragonBoat = evaluateMarket(clonePreset("dragonBoatCarnivalLunch"));
  const kayaking = evaluateMarket(clonePreset("kayakingCarnivalLunch"));
  const canoeing = evaluateMarket(clonePreset("canoeingCarnivalLunch"));
  const sailing = evaluateMarket(clonePreset("sailingCarnivalLunch"));
  const rowing = evaluateMarket(clonePreset("rowingCarnivalLunch"));
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(teamPursuitCycling.winner);
  assert.equal(teamPursuitCycling.winner.offer.merchant, "Court-side Team-pursuit Delivery");
  assert.equal(teamPursuitCycling.winner.offer.fulfillment, "shipping");
  assert.equal(teamPursuitCycling.winner.fulfilledUnits, 50);
  assert.deepEqual(teamPursuitCycling.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(teamPursuitCycling.scenario.title, "Team-pursuit cycling carnival lunch");
  assert.notEqual(teamPursuitCycling.scenario.title, clonePreset("individualPursuitCyclingCarnivalLunch").title);
  assert.notEqual(teamPursuitCycling.scenario.title, clonePreset("scratchCyclingCarnivalLunch").title);
  assert.notEqual(teamPursuitCycling.scenario.title, clonePreset("pointsRaceCyclingCarnivalLunch").title);
  assert.notEqual(teamPursuitCycling.scenario.title, clonePreset("omniumCyclingCarnivalLunch").title);
  assert.notEqual(teamPursuitCycling.scenario.title, clonePreset("madisonCyclingCarnivalLunch").title);
  assert.notEqual(teamPursuitCycling.scenario.title, keirinCycling.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, hillClimbCycling.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, timeTrialCycling.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, criteriumCycling.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, roadCycling.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, gravelCycling.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, trackCycling.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, cycloCross.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, bmx.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, mountainBike.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, cycling.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, triathlon.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, surf.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, dragonBoat.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, kayaking.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, canoeing.scenario.title);
  assert.notEqual(teamPursuitCycling.scenario.title, sailing.scenario.title);
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("individualPursuitCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("scratchCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("madisonCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("keirinCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("hillClimbCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("timeTrialCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("criteriumCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("roadCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("gravelCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("trackCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("cycloCrossCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("bmxCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("mountainBikeCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("cyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("triathlonCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("surfCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("dragonBoatCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("kayakingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("canoeingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("sailingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("rowingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("waterPoloCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("pointsRaceCyclingCarnivalLunch"));
  assert.notDeepEqual(clonePreset("teamPursuitCyclingCarnivalLunch"), clonePreset("omniumCyclingCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(teamPursuitCycling.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Team-pursuit Pickup");
  const leftoverOffer = teamPursuitCycling.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 42);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.minimumUnits);
  assert.equal(leftoverOffer.unitPrice, 38);
  assert.equal(teamPursuitCycling.scenario.buyers.find((buyer) => buyer.id === "B03").quantity, 15);
  assert.equal(teamPursuitCycling.scenario.buyers.find((buyer) => buyer.id === "B03").maxUnitPrice, 38);
  assert.equal(teamPursuitCycling.scenario.buyers.find((buyer) => buyer.id === "B04").maxUnitPrice, 38);
  assert.equal(teamPursuitCycling.scenario.buyers.find((buyer) => buyer.id === "B04").quantity, 28);
  assert.equal(evaluateMarket(clonePreset("scratchCyclingCarnivalLunch")).scenario.offers.find((offer) => offer.merchant === "Hall Scratch Pickup").minimumUnits, 38);
  assert.equal(evaluateMarket(clonePreset("pointsRaceCyclingCarnivalLunch")).scenario.offers.find((offer) => offer.merchant === "Hall Points-race Pickup").minimumUnits, 37);
  assert.equal(evaluateMarket(clonePreset("omniumCyclingCarnivalLunch")).scenario.offers.find((offer) => offer.merchant === "Hall Omnium Pickup").minimumUnits, 36);
  assert.equal(madisonCycling.scenario.offers.find((offer) => offer.merchant === "Hall Madison Pickup").minimumUnits, 35);
  assert.equal(keirinCycling.scenario.offers.find((offer) => offer.merchant === "Hall Keirin Pickup").minimumUnits, 34);
  assert.equal(hillClimbCycling.scenario.offers.find((offer) => offer.merchant === "Hall Hill Climb Pickup").minimumUnits, 33);
  assert.equal(timeTrialCycling.scenario.offers.find((offer) => offer.merchant === "Hall Time Trial Pickup").minimumUnits, 32);
  assert.equal(criteriumCycling.scenario.offers.find((offer) => offer.merchant === "Hall Criterium Pickup").minimumUnits, 31);
  assert.equal(roadCycling.scenario.offers.find((offer) => offer.merchant === "Hall Road Cycling Pickup").minimumUnits, 30);
  assert.equal(gravelCycling.scenario.offers.find((offer) => offer.merchant === "Hall Gravel Cycling Pickup").minimumUnits, 29);
  assert.equal(trackCycling.scenario.offers.find((offer) => offer.merchant === "Hall Track Cycling Pickup").minimumUnits, 28);
  assert.equal(cycloCross.scenario.offers.find((offer) => offer.merchant === "Hall Cyclo-cross Pickup").minimumUnits, 27);
  assert.equal(bmx.scenario.offers.find((offer) => offer.merchant === "Hall BMX Pickup").minimumUnits, 26);
  assert.equal(mountainBike.scenario.offers.find((offer) => offer.merchant === "Hall Mountain Bike Pickup").minimumUnits, 25);
  assert.equal(cycling.scenario.offers.find((offer) => offer.merchant === "Hall Cycling Pickup").minimumUnits, 24);
  assert.equal(triathlon.scenario.offers.find((offer) => offer.merchant === "Hall Triathlon Pickup").minimumUnits, 23);
  assert.equal(surf.scenario.offers.find((offer) => offer.merchant === "Hall Surf Pickup").minimumUnits, 22);
  assert.equal(dragonBoat.scenario.offers.find((offer) => offer.merchant === "Hall Dragon Boat Pickup").minimumUnits, 21);
  assert.equal(kayaking.scenario.offers.find((offer) => offer.merchant === "Hall Kayaking Pickup").minimumUnits, 20);
  assert.equal(canoeing.scenario.offers.find((offer) => offer.merchant === "Hall Canoeing Pickup").minimumUnits, 19);
  assert.equal(sailing.scenario.offers.find((offer) => offer.merchant === "Hall Sailing Pickup").minimumUnits, 18);
  assert.equal(rowing.scenario.offers.find((offer) => offer.merchant === "Hall Rowing Pickup").minimumUnits, 17);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(waterPolo.scenario.offers.find((offer) => offer.merchant === "Hall Water Polo Pickup").minimumUnits, 16);
  assert.equal(criteriumCycling.winner.offer.merchant, "Court-side Criterium Delivery");
  assert.equal(evaluateMarket(clonePreset("omniumCyclingCarnivalLunch")).winner.offer.merchant, "Court-side Omnium Delivery");
  assert.equal(madisonCycling.winner.offer.merchant, "Court-side Madison Delivery");
  assert.equal(keirinCycling.winner.offer.merchant, "Court-side Keirin Delivery");
  assert.equal(scratchCycling.winner.offer.merchant, "Court-side Scratch Delivery");
  assert.equal(leftoverOffer.capacity, 64);
  assert.equal(leftoverFill.fulfilledUnits, 43);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 21);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.unitPrice);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.minimumUnits);
  assert.notEqual(leftoverFill.fulfilledUnits, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.capacity, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.unitPrice, leftoverOffer.capacity - leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverOffer.unitPrice, leftoverFill.fulfilledUnits);
  assert.notEqual(leftoverFill.fulfilledUnits, 41);
  assert.notEqual(leftoverFill.fulfilledUnits, 39);
  assert.notEqual(leftoverFill.fulfilledUnits, 38);
  assert.notEqual(leftoverFill.fulfilledUnits, 37);
  assert.notEqual(leftoverFill.fulfilledUnits, 36);
  assert.notEqual(leftoverFill.fulfilledUnits, 35);
  assert.notEqual(leftoverFill.fulfilledUnits, 34);
  assert.notEqual(leftoverFill.fulfilledUnits, 33);
  assert.notEqual(leftoverFill.fulfilledUnits, 32);
  assert.notEqual(leftoverFill.fulfilledUnits, 31);
  assert.notEqual(leftoverFill.fulfilledUnits, 30);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(teamPursuitCycling.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(teamPursuitCycling.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(teamPursuitCycling.results.some((result) => result.offer.merchant === "Court-side Team-pursuit Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Team-pursuit pie")));
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Scratch pie")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Points-race pie")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Omnium pie")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Bell salad")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Prime water")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tempo salad")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Tempo water")), false);
  assert.ok(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Changeover salad")));
  assert.ok(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Quartet water")));
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Catch salad")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pursuit water")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Individual-pursuit pie")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Bunch salad")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Chip water")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Madison pie")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Handsling salad")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Handsling water")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Keirin pie")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Derny salad")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Derny water")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hill-climb pie")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hairpin salad")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Hairpin water")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Criterium pie")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Circuit salad")), false);
  assert.equal(teamPursuitCycling.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Circuit water")), false);
  const payload = JSON.stringify(clonePreset("teamPursuitCyclingCarnivalLunch"));
  assert.equal(payload.includes("start-ramp"), false);
  assert.equal(payload.includes("timing-hut"), false);
  assert.equal(payload.includes("time-check"), false);
  assert.equal(payload.includes("pit-lane"), false);
  assert.equal(payload.includes("circuit"), false);
  assert.equal(payload.includes("sealed-road"), false);
  assert.equal(payload.includes("feed-zone"), false);
  assert.equal(payload.includes("banked-boards"), false);
  assert.equal(payload.includes("summit-marshal"), false);
  assert.equal(payload.includes("hairpin"), false);
  assert.equal(payload.includes("climb-chip"), false);
  assert.equal(payload.includes("derny-pacer"), false);
  assert.equal(payload.includes("keirin-chip"), false);
  assert.equal(payload.includes("keirin-gate"), false);
  assert.equal(payload.includes("madison-pair"), false);
  assert.equal(payload.includes("handsling"), false);
  assert.equal(payload.includes("omnium-board"), false);
  assert.equal(payload.includes("flying-200"), false);
  assert.equal(payload.includes("elimination-heat"), false);
  assert.equal(payload.includes("tempo-lap"), false);
  assert.equal(payload.includes("points-race"), false);
  assert.equal(payload.includes("points-sprint"), false);
  assert.equal(payload.includes("bell-lap"), false);
  assert.equal(payload.includes("prime-board"), false);
  assert.equal(payload.includes("scratch-bunch"), false);
  assert.equal(payload.includes("bunch-finish"), false);
  assert.equal(payload.includes("scratch-chip"), false);
  assert.equal(payload.includes("pursuit-line"), false);
  assert.equal(payload.includes("catch-bell"), false);
  assert.equal(payload.includes("pursuit-chip"), false);
  assert.match(payload, /Changeover-bell crate/);
  assert.match(payload, /Quartet-board bench/);
  assert.match(payload, /Team-pursuit-rota hamper/);
  const first = evaluateMarket(clonePreset("teamPursuitCyclingCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("teamPursuitCyclingCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes team-pursuit cycling carnival lunch next to individual-pursuit cycling carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="teamPursuitCyclingCarnivalLunch"/u);
  assert.match(html, /Team-pursuit cycling carnival/u);
  assert.match(html, /data-preset="scratchCyclingCarnivalLunch"/u);
  assert.match(html, /data-preset="pointsRaceCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="pointsRaceCyclingCarnivalLunch"') < html.indexOf('data-preset="scratchCyclingCarnivalLunch"'));
  assert.match(html, /data-preset="individualPursuitCyclingCarnivalLunch"/u);
  assert.ok(html.indexOf('data-preset="scratchCyclingCarnivalLunch"') < html.indexOf('data-preset="individualPursuitCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="individualPursuitCyclingCarnivalLunch"') < html.indexOf('data-preset="teamPursuitCyclingCarnivalLunch"'));
  assert.ok(html.indexOf('data-preset="teamPursuitCyclingCarnivalLunch"') < html.indexOf('data-preset="tiers"'));
});
