import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { clonePreset, computeResidualCoverage, evaluateMarket, validateScenario } from "../src/model.js";

test("water polo carnival lunch leftover fill is hall pickup and stays distinct from softball carnival lunch", () => {
  const waterPolo = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const softball = evaluateMarket(clonePreset("softballCarnivalLunch"));
  const baseball = evaluateMarket(clonePreset("baseballCarnivalLunch"));
  const hockey = evaluateMarket(clonePreset("hockeyCarnivalLunch"));
  const rugby = evaluateMarket(clonePreset("rugbyCarnivalLunch"));
  const soccer = evaluateMarket(clonePreset("soccerCarnivalLunch"));
  assert.ok(waterPolo.winner);
  assert.equal(waterPolo.winner.offer.merchant, "Court-side Water Polo Delivery");
  assert.equal(waterPolo.winner.offer.fulfillment, "shipping");
  assert.equal(waterPolo.winner.fulfilledUnits, 50);
  assert.deepEqual(waterPolo.winner.selectedBuyerIds, ["B01", "B02", "B05"]);
  assert.equal(waterPolo.scenario.title, "Water polo carnival lunch");
  assert.notEqual(waterPolo.scenario.title, softball.scenario.title);
  assert.notDeepEqual(clonePreset("waterPoloCarnivalLunch"), clonePreset("softballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("waterPoloCarnivalLunch"), clonePreset("baseballCarnivalLunch"));
  assert.notDeepEqual(clonePreset("waterPoloCarnivalLunch"), clonePreset("hockeyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("waterPoloCarnivalLunch"), clonePreset("rugbyCarnivalLunch"));
  assert.notDeepEqual(clonePreset("waterPoloCarnivalLunch"), clonePreset("soccerCarnivalLunch"));
  const leftoverFill = computeResidualCoverage(waterPolo.scenario).secondary;
  assert.ok(leftoverFill);
  assert.equal(leftoverFill.merchant, "Hall Water Polo Pickup");
  const leftoverOffer = waterPolo.scenario.offers.find((offer) => offer.id === leftoverFill.offerId);
  assert.equal(leftoverOffer.fulfillment, "pickup");
  assert.equal(leftoverOffer.minimumUnits, 16);
  assert.equal(soccer.scenario.offers.find((offer) => offer.merchant === "Hall Soccer Pickup").minimumUnits, 11);
  assert.equal(rugby.scenario.offers.find((offer) => offer.merchant === "Hall Rugby Pickup").minimumUnits, 12);
  assert.equal(hockey.scenario.offers.find((offer) => offer.merchant === "Hall Hockey Pickup").minimumUnits, 13);
  assert.equal(baseball.scenario.offers.find((offer) => offer.merchant === "Hall Baseball Pickup").minimumUnits, 14);
  assert.equal(softball.scenario.offers.find((offer) => offer.merchant === "Hall Softball Pickup").minimumUnits, 15);
  assert.equal(soccer.winner.offer.merchant, "Court-side Soccer Delivery");
  assert.equal(rugby.winner.offer.merchant, "Court-side Rugby Delivery");
  assert.equal(hockey.winner.offer.merchant, "Court-side Hockey Delivery");
  assert.equal(baseball.winner.offer.merchant, "Court-side Baseball Delivery");
  assert.equal(softball.winner.offer.merchant, "Court-side Softball Delivery");
  assert.equal(leftoverOffer.capacity, 44);
  assert.equal(leftoverFill.fulfilledUnits, 23);
  assert.equal(leftoverOffer.capacity - leftoverFill.fulfilledUnits, 21);
  assert.deepEqual(leftoverFill.selectedBuyerIds, ["B03", "B04"]);
  assert.equal(computeResidualCoverage(waterPolo.scenario).tertiary, null);
  assert.deepEqual(computeResidualCoverage(waterPolo.scenario).leftoverBuyerIds.filter((id) => !(leftoverFill.selectedBuyerIds ?? []).includes(id)), ["B06"]);
  assert.ok(waterPolo.results.some((result) => result.offer.merchant === "Court-side Water Polo Delivery" && result.offer.fulfillment === "shipping"));
  assert.ok(waterPolo.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Water polo pie")));
  assert.ok(waterPolo.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pool salad")));
  assert.ok(waterPolo.scenario.buyers.some((buyer) => buyer.allowedVariants.includes("Pool water")));
  const first = evaluateMarket(clonePreset("waterPoloCarnivalLunch"));
  const second = evaluateMarket(validateScenario(clonePreset("waterPoloCarnivalLunch")));
  assert.equal(first.winner.offer.id, second.winner.offer.id);
  assert.equal(first.winner.fulfilledUnits, second.winner.fulfilledUnits);
  assert.equal(first.winner.fulfilledUnits, 50);
});

test("the example bar includes water polo carnival lunch next to softball carnival lunch", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  assert.match(html, /data-preset="waterPoloCarnivalLunch"/u);
  assert.match(html, /Water polo carnival/u);
  assert.match(html, /data-preset="softballCarnivalLunch"/u);
});
